// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.
// See LICENSE file for details.

/**
 * =============================================================================
 * SUPPLY CHAIN & LOGISTICS CONNECTORS
 * =============================================================================
 * Customs, Shipping, Ports, Trade Compliance
 */

import { ConnectorMetadata } from '../BaseConnector.js';

export const SUPPLY_CHAIN_CONNECTORS: ConnectorMetadata[] = [
  // US Customs
  {
    id: 'cbp-ace',
    name: 'CBP ACE',
    description: 'Automated Commercial Environment - US customs',
    vertical: 'supply-chain',
    category: 'customs',
    provider: 'US CBP',
    region: 'US',
    dataTypes: ['entries', 'manifests', 'holds', 'releases'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.cbp.gov/trade/automated',
    requiredCredentials: ['filer_code', 'certificate'],
    complianceFrameworks: ['C-TPAT', 'AEO'],
    compatibilityLabel: 'client_gateway',
    integrationNotes: 'Requires customs broker filer code; File export ingestion',
  },
  {
    id: 'cbp-itds',
    name: 'CBP ITDS',
    description: 'International Trade Data System',
    vertical: 'supply-chain',
    category: 'customs',
    provider: 'US CBP',
    region: 'US',
    dataTypes: ['pga-filings', 'licenses', 'permits'],
    updateFrequency: 'real-time',
    requiredCredentials: ['filer_code', 'certificate'],
    complianceFrameworks: ['C-TPAT'],
    compatibilityLabel: 'client_gateway',
    integrationNotes: 'Requires customs broker filer code; File export ingestion',
  },

  // International Customs
  {
    id: 'eu-customs',
    name: 'EU Customs Data Hub',
    description: 'European Union customs declarations',
    vertical: 'supply-chain',
    category: 'customs',
    provider: 'EU Commission',
    region: 'EU',
    dataTypes: ['declarations', 'tariffs', 'origin'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://ec.europa.eu/taxation_customs/',
    requiredCredentials: ['eori', 'certificate'],
    complianceFrameworks: ['AEO', 'UCC'],
    compatibilityLabel: 'client_gateway',
    integrationNotes: 'Requires EORI registration; File export ingestion',
  },
  {
    id: 'uk-cds',
    name: 'UK Customs Declaration Service',
    description: 'UK customs post-Brexit',
    vertical: 'supply-chain',
    category: 'customs',
    provider: 'HMRC',
    region: 'UK',
    dataTypes: ['declarations', 'clearances', 'duty'],
    updateFrequency: 'real-time',
    requiredCredentials: ['eori', 'government_gateway'],
    complianceFrameworks: ['AEO'],
    compatibilityLabel: 'client_gateway',
    integrationNotes: 'Requires UK EORI and Government Gateway; File export ingestion',
  },
  {
    id: 'china-customs',
    name: 'China Customs (GACC)',
    description: 'General Administration of Customs of China',
    vertical: 'supply-chain',
    category: 'customs',
    provider: 'GACC',
    region: 'China',
    dataTypes: ['declarations', 'inspections', 'clearances'],
    updateFrequency: 'real-time',
    requiredCredentials: ['enterprise_code', 'certificate'],
    complianceFrameworks: ['AEO'],
    compatibilityLabel: 'client_gateway',
    integrationNotes: 'Requires China enterprise registration; File export ingestion',
  },

  // Shipping & Carriers
  {
    id: 'maersk-api',
    name: 'Maersk Shipping API',
    description: 'Container tracking, bookings, schedules',
    vertical: 'supply-chain',
    category: 'shipping',
    provider: 'Maersk',
    region: 'Global',
    dataTypes: ['tracking', 'bookings', 'schedules', 'rates'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://developer.maersk.com/',
    requiredCredentials: ['api_key', 'consumer_key'],
    complianceFrameworks: ['ISO28000'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Maersk customer account; Webhook Adapter',
  },
  {
    id: 'msc-api',
    name: 'MSC Shipping API',
    description: 'Mediterranean Shipping Company tracking',
    vertical: 'supply-chain',
    category: 'shipping',
    provider: 'MSC',
    region: 'Global',
    dataTypes: ['tracking', 'bookings', 'schedules'],
    updateFrequency: 'real-time',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['ISO28000'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO MSC customer account; Webhook Adapter',
  },
  {
    id: 'cma-cgm',
    name: 'CMA CGM API',
    description: 'CMA CGM container shipping',
    vertical: 'supply-chain',
    category: 'shipping',
    provider: 'CMA CGM',
    region: 'Global',
    dataTypes: ['tracking', 'bookings', 'schedules'],
    updateFrequency: 'real-time',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['ISO28000'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO CMA CGM customer account; Webhook Adapter',
  },

  // Ports
  {
    id: 'port-la',
    name: 'Port of Los Angeles',
    description: 'LA port operations and vessel tracking',
    vertical: 'supply-chain',
    category: 'ports',
    provider: 'Port of LA',
    region: 'US',
    dataTypes: ['vessel-arrivals', 'container-dwell', 'appointments'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.portoflosangeles.org/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['C-TPAT'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'port-rotterdam',
    name: 'Port of Rotterdam',
    description: "Europe's largest port operations",
    vertical: 'supply-chain',
    category: 'ports',
    provider: 'Port of Rotterdam',
    region: 'EU',
    dataTypes: ['vessel-arrivals', 'berth-planning', 'cargo'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.portofrotterdam.com/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['AEO'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'port-singapore',
    name: 'Port of Singapore (PSA)',
    description: 'Singapore port authority data',
    vertical: 'supply-chain',
    category: 'ports',
    provider: 'PSA Singapore',
    region: 'Asia',
    dataTypes: ['vessel-arrivals', 'container-tracking', 'schedules'],
    updateFrequency: 'real-time',
    requiredCredentials: ['api_key', 'company_id'],
    complianceFrameworks: ['AEO'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO PSA customer account; Webhook Adapter',
  },

  // Trade Data
  {
    id: 'unctad-comtrade',
    name: 'UN Comtrade',
    description: 'United Nations international trade statistics',
    vertical: 'supply-chain',
    category: 'trade-data',
    provider: 'UNCTAD',
    region: 'Global',
    dataTypes: ['imports', 'exports', 'trade-flows', 'tariffs'],
    updateFrequency: 'monthly',
    documentationUrl: 'https://comtrade.un.org/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: [],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'wto-data',
    name: 'WTO Trade Data',
    description: 'World Trade Organization statistics',
    vertical: 'supply-chain',
    category: 'trade-data',
    provider: 'WTO',
    region: 'Global',
    dataTypes: ['trade-statistics', 'tariff-profiles', 'trade-agreements'],
    updateFrequency: 'quarterly',
    documentationUrl: 'https://www.wto.org/english/res_e/statis_e/statis_e.htm',
    requiredCredentials: [],
    complianceFrameworks: [],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },
];

export class SupplyChainConnectorFactory {
  static getAvailableConnectors(): ConnectorMetadata[] {
    return SUPPLY_CHAIN_CONNECTORS;
  }
}
