// Copyright (c) 2024-2026 Datacendia, LLC All Rights Reserved.
// Proprietary and confidential. Unauthorized copying is strictly prohibited.
// See LICENSE file for details.

/**
 * =============================================================================
 * TRANSPORTATION CONNECTORS
 * =============================================================================
 * Aviation, Maritime, Rail, Road, Space
 */

import { ConnectorMetadata } from '../BaseConnector.js';

export const TRANSPORTATION_CONNECTORS: ConnectorMetadata[] = [
  // Aviation
  {
    id: 'eurocontrol',
    name: 'EUROCONTROL',
    description: 'European air traffic management data',
    vertical: 'transportation',
    category: 'aviation',
    provider: 'EUROCONTROL',
    region: 'EU',
    dataTypes: ['flight-data', 'delays', 'airspace', 'safety'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.eurocontrol.int/',
    requiredCredentials: ['api_key', 'certificate'],
    complianceFrameworks: ['GDPR'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO EUROCONTROL B2B subscription; Webhook Adapter',
  },
  {
    id: 'icao-wacaf',
    name: 'ICAO API',
    description: 'International Civil Aviation Organization',
    vertical: 'transportation',
    category: 'aviation',
    provider: 'ICAO',
    region: 'Global',
    dataTypes: ['airports', 'airlines', 'aircraft', 'safety-data'],
    updateFrequency: 'daily',
    documentationUrl: 'https://www.icao.int/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: [],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO ICAO subscription; Webhook Adapter',
  },
  {
    id: 'flightradar24',
    name: 'Flightradar24',
    description: 'Global flight tracking',
    vertical: 'transportation',
    category: 'aviation',
    provider: 'Flightradar24',
    region: 'Global',
    dataTypes: ['live-flights', 'historical', 'airports'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.flightradar24.com/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: [],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Flightradar24 subscription; Webhook Adapter',
  },

  // Maritime
  {
    id: 'imo-gisis',
    name: 'IMO GISIS',
    description: 'International Maritime Organization database',
    vertical: 'transportation',
    category: 'maritime',
    provider: 'IMO',
    region: 'Global',
    dataTypes: ['ships', 'companies', 'flags', 'safety'],
    updateFrequency: 'daily',
    documentationUrl: 'https://gisis.imo.org/',
    requiredCredentials: ['username', 'password'],
    complianceFrameworks: [],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'ais-marine-traffic',
    name: 'MarineTraffic AIS',
    description: 'Automatic Identification System vessel tracking',
    vertical: 'transportation',
    category: 'maritime',
    provider: 'MarineTraffic',
    region: 'Global',
    dataTypes: ['vessel-positions', 'port-calls', 'voyages'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.marinetraffic.com/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: [],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO MarineTraffic subscription; Webhook Adapter',
  },
  {
    id: 'lloyd-list',
    name: "Lloyd's List Intelligence",
    description: 'Maritime intelligence and vessel data',
    vertical: 'transportation',
    category: 'maritime',
    provider: "Lloyd's",
    region: 'Global',
    dataTypes: ['vessels', 'ownership', 'sanctions', 'casualties'],
    updateFrequency: 'daily',
    requiredCredentials: ['api_key', 'subscription'],
    complianceFrameworks: ['SOC2'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Lloyd\'s List subscription; Webhook Adapter',
  },

  // Rail
  {
    id: 'amtrak-api',
    name: 'Amtrak API',
    description: 'US passenger rail data',
    vertical: 'transportation',
    category: 'rail',
    provider: 'Amtrak',
    region: 'US',
    dataTypes: ['schedules', 'delays', 'stations'],
    updateFrequency: 'real-time',
    requiredCredentials: ['api_key'],
    complianceFrameworks: [],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'era-europe',
    name: 'ERA Railway Data',
    description: 'European Union Agency for Railways',
    vertical: 'transportation',
    category: 'rail',
    provider: 'ERA',
    region: 'EU',
    dataTypes: ['infrastructure', 'rolling-stock', 'safety'],
    updateFrequency: 'monthly',
    documentationUrl: 'https://www.era.europa.eu/',
    requiredCredentials: [],
    complianceFrameworks: ['GDPR'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },

  // Road
  {
    id: 'here-traffic',
    name: 'HERE Traffic',
    description: 'Real-time traffic and routing',
    vertical: 'transportation',
    category: 'road',
    provider: 'HERE Technologies',
    region: 'Global',
    dataTypes: ['traffic-flow', 'incidents', 'routing', 'ev-charging'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://developer.here.com/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['SOC2', 'ISO27001'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO HERE subscription; Webhook Adapter',
  },
  {
    id: 'tomtom-traffic',
    name: 'TomTom Traffic',
    description: 'Traffic data and navigation',
    vertical: 'transportation',
    category: 'road',
    provider: 'TomTom',
    region: 'Global',
    dataTypes: ['traffic', 'routing', 'maps', 'ev-charging'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://developer.tomtom.com/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['SOC2'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO TomTom subscription; Webhook Adapter',
  },

  // Space
  {
    id: 'nasa-space-weather',
    name: 'NASA Space Weather',
    description: 'Solar activity and space weather',
    vertical: 'transportation',
    category: 'space',
    provider: 'NASA',
    region: 'Global',
    dataTypes: ['solar-flares', 'geomagnetic-storms', 'radiation'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://api.nasa.gov/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'space-track',
    name: 'Space-Track',
    description: 'US Space Command satellite catalog',
    vertical: 'transportation',
    category: 'space',
    provider: 'US Space Command',
    region: 'Global',
    dataTypes: ['tle', 'conjunction-data', 'decay-predictions'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.space-track.org/',
    requiredCredentials: ['username', 'password'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
];

export class TransportationConnectorFactory {
  static getAvailableConnectors(): ConnectorMetadata[] {
    return TRANSPORTATION_CONNECTORS;
  }
}
