// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.
// See LICENSE file for details.

/**
 * =============================================================================
 * ENERGY & UTILITIES CONNECTORS
 * =============================================================================
 * Grid Operators, Power Markets, Oil & Gas, Renewables
 */

import { ConnectorMetadata } from '../BaseConnector.js';

export const ENERGY_CONNECTORS: ConnectorMetadata[] = [
  // US Grid Operators (ISOs/RTOs)
  {
    id: 'caiso',
    name: 'CAISO',
    description: 'California Independent System Operator',
    vertical: 'energy',
    category: 'grid-operator',
    provider: 'CAISO',
    region: 'US-West',
    dataTypes: ['lmp', 'load', 'generation', 'congestion', 'reserves'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.caiso.com/market/Pages/OASISMethodology/',
    requiredCredentials: ['username', 'password'],
    complianceFrameworks: ['NERC-CIP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public OASIS API with free registration',
  },
  {
    id: 'pjm',
    name: 'PJM Interconnection',
    description: 'PJM regional transmission organization',
    vertical: 'energy',
    category: 'grid-operator',
    provider: 'PJM',
    region: 'US-East',
    dataTypes: ['lmp', 'load', 'generation', 'capacity', 'ancillary'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://dataminer2.pjm.com/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['NERC-CIP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'ercot',
    name: 'ERCOT',
    description: 'Electric Reliability Council of Texas',
    vertical: 'energy',
    category: 'grid-operator',
    provider: 'ERCOT',
    region: 'US-Texas',
    dataTypes: ['spp', 'load', 'generation', 'wind', 'solar'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.ercot.com/mktinfo/data_agg',
    requiredCredentials: ['certificate'],
    complianceFrameworks: ['NERC-CIP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with certificate registration',
  },
  {
    id: 'nyiso',
    name: 'NYISO',
    description: 'New York Independent System Operator',
    vertical: 'energy',
    category: 'grid-operator',
    provider: 'NYISO',
    region: 'US-Northeast',
    dataTypes: ['lbmp', 'load', 'generation', 'capacity'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.nyiso.com/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['NERC-CIP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'miso',
    name: 'MISO',
    description: 'Midcontinent Independent System Operator',
    vertical: 'energy',
    category: 'grid-operator',
    provider: 'MISO',
    region: 'US-Midwest',
    dataTypes: ['lmp', 'load', 'generation', 'wind'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.misoenergy.org/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['NERC-CIP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },

  // European Grid
  {
    id: 'entso-e',
    name: 'ENTSO-E Transparency',
    description: 'European Network of Transmission System Operators',
    vertical: 'energy',
    category: 'grid-operator',
    provider: 'ENTSO-E',
    region: 'EU',
    dataTypes: ['generation', 'load', 'cross-border-flows', 'prices'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://transparency.entsoe.eu/',
    requiredCredentials: ['security_token'],
    complianceFrameworks: ['GDPR'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'nordpool',
    name: 'Nord Pool',
    description: 'Nordic/Baltic power exchange',
    vertical: 'energy',
    category: 'power-market',
    provider: 'Nord Pool',
    region: 'EU-Nordic',
    dataTypes: ['day-ahead', 'intraday', 'system-prices'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.nordpoolgroup.com/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: [],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Nord Pool membership; Webhook Adapter',
  },
  {
    id: 'epex-spot',
    name: 'EPEX SPOT',
    description: 'European Power Exchange',
    vertical: 'energy',
    category: 'power-market',
    provider: 'EPEX SPOT',
    region: 'EU',
    dataTypes: ['day-ahead', 'intraday', 'auction-results'],
    updateFrequency: 'real-time',
    requiredCredentials: ['api_key', 'certificate'],
    complianceFrameworks: ['REMIT'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO EPEX SPOT membership; Webhook Adapter',
  },

  // Oil & Gas
  {
    id: 'platts',
    name: 'S&P Global Platts',
    description: 'Energy commodity prices and analytics',
    vertical: 'energy',
    category: 'commodities',
    provider: 'S&P Global',
    region: 'Global',
    dataTypes: ['oil-prices', 'gas-prices', 'petrochemicals', 'metals'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.spglobal.com/platts/',
    requiredCredentials: ['api_key', 'username'],
    complianceFrameworks: ['SOC2'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO S&P Platts subscription; Webhook Adapter',
  },
  {
    id: 'argus-media',
    name: 'Argus Media',
    description: 'Energy and commodity price reporting',
    vertical: 'energy',
    category: 'commodities',
    provider: 'Argus Media',
    region: 'Global',
    dataTypes: ['oil-prices', 'lng', 'biofuels', 'fertilizers'],
    updateFrequency: 'daily',
    requiredCredentials: ['api_key'],
    complianceFrameworks: [],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Argus subscription; Webhook Adapter',
  },

  // Renewables
  {
    id: 'solcast',
    name: 'Solcast',
    description: 'Solar irradiance and PV power forecasting',
    vertical: 'energy',
    category: 'renewables',
    provider: 'Solcast',
    region: 'Global',
    dataTypes: ['irradiance', 'pv-power', 'forecasts'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://solcast.com/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: [],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Solcast subscription; Webhook Adapter',
  },
  {
    id: 'meteomatics',
    name: 'Meteomatics Weather API',
    description: 'High-resolution weather for energy forecasting',
    vertical: 'energy',
    category: 'weather',
    provider: 'Meteomatics',
    region: 'Global',
    dataTypes: ['wind-speed', 'solar-radiation', 'temperature', 'precipitation'],
    updateFrequency: 'hourly',
    documentationUrl: 'https://www.meteomatics.com/',
    requiredCredentials: ['username', 'password'],
    complianceFrameworks: [],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Meteomatics subscription; Webhook Adapter',
  },
];

export class EnergyConnectorFactory {
  static getAvailableConnectors(): ConnectorMetadata[] {
    return ENERGY_CONNECTORS;
  }
}
