// Copyright (c) 2024-2026 Datacendia, LLC All Rights Reserved.
// Proprietary and confidential. Unauthorized copying is strictly prohibited.
// See LICENSE file for details.

/**
 * =============================================================================
 * GOVERNMENT & PUBLIC SECTOR CONNECTORS
 * =============================================================================
 * US Federal, State, and International Government Data Sources
 */

import { BaseConnector, ConnectorConfig, ConnectorMetadata } from '../BaseConnector.js';

// =============================================================================
// US FEDERAL AGENCIES
// =============================================================================

export const GOVERNMENT_CONNECTORS: ConnectorMetadata[] = [
  // Weather & Climate
  {
    id: 'noaa-weather',
    name: 'NOAA Weather Service',
    description: 'National Oceanic and Atmospheric Administration - Weather forecasts, alerts, observations',
    vertical: 'government',
    category: 'weather',
    provider: 'NOAA',
    region: 'US',
    dataTypes: ['forecasts', 'alerts', 'observations', 'radar', 'satellite'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.weather.gov/documentation/services-web-api',
    apiVersion: 'v3',
    requiredCredentials: [],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },
  {
    id: 'noaa-climate',
    name: 'NOAA Climate Data',
    description: 'Historical climate data, trends, and projections',
    vertical: 'government',
    category: 'climate',
    provider: 'NOAA NCEI',
    region: 'US',
    dataTypes: ['temperature', 'precipitation', 'sea-level', 'ice-coverage'],
    updateFrequency: 'daily',
    documentationUrl: 'https://www.ncei.noaa.gov/access',
    requiredCredentials: ['api_token'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free token registration',
  },
  {
    id: 'noaa-marine',
    name: 'NOAA Marine Data',
    description: 'Ocean buoy data, tides, currents, water temperature',
    vertical: 'government',
    category: 'marine',
    provider: 'NOAA NDBC',
    region: 'US',
    dataTypes: ['buoy-observations', 'tides', 'currents', 'water-temp'],
    updateFrequency: 'hourly',
    documentationUrl: 'https://www.ndbc.noaa.gov/',
    requiredCredentials: [],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },

  // Aviation
  {
    id: 'faa-notams',
    name: 'FAA NOTAMs',
    description: 'Notices to Air Missions - airspace restrictions, hazards',
    vertical: 'government',
    category: 'aviation',
    provider: 'FAA',
    region: 'US',
    dataTypes: ['notams', 'tfrs', 'airspace-status'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.faa.gov/air_traffic/flight_info/aeronav/notams/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['FedRAMP', 'FISMA'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'faa-swim',
    name: 'FAA SWIM',
    description: 'System Wide Information Management - comprehensive flight data',
    vertical: 'government',
    category: 'aviation',
    provider: 'FAA',
    region: 'US',
    dataTypes: ['flight-tracks', 'airport-status', 'weather', 'flow-control'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.faa.gov/air_traffic/technology/swim/',
    requiredCredentials: ['certificate', 'subscriber_id'],
    complianceFrameworks: ['FedRAMP', 'FISMA'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'FAA SWIM subscription agreement required',
  },
  {
    id: 'faa-asdi',
    name: 'FAA ASDI',
    description: 'Aircraft Situation Display to Industry - real-time flight tracking',
    vertical: 'government',
    category: 'aviation',
    provider: 'FAA',
    region: 'US',
    dataTypes: ['flight-positions', 'flight-plans', 'delays'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.fly.faa.gov/',
    requiredCredentials: ['api_key', 'subscription'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'FAA ASDI subscription agreement required',
  },

  // Emergency Management
  {
    id: 'fema-alerts',
    name: 'FEMA IPAWS',
    description: 'Integrated Public Alert and Warning System',
    vertical: 'government',
    category: 'emergency',
    provider: 'FEMA',
    region: 'US',
    dataTypes: ['emergency-alerts', 'weather-warnings', 'amber-alerts'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.fema.gov/emergency-managers/practitioners/integrated-public-alert-warning-system',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['FedRAMP', 'FISMA'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'fema-disasters',
    name: 'FEMA Disaster Declarations',
    description: 'Federal disaster declarations and assistance data',
    vertical: 'government',
    category: 'emergency',
    provider: 'FEMA',
    region: 'US',
    dataTypes: ['disaster-declarations', 'assistance-programs', 'damage-assessments'],
    updateFrequency: 'daily',
    documentationUrl: 'https://www.fema.gov/openfema-data-page/disaster-declarations-summaries-v2',
    requiredCredentials: [],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },
  {
    id: 'fema-nfip',
    name: 'FEMA Flood Insurance',
    description: 'National Flood Insurance Program data and flood maps',
    vertical: 'government',
    category: 'emergency',
    provider: 'FEMA',
    region: 'US',
    dataTypes: ['flood-zones', 'flood-claims', 'insurance-policies'],
    updateFrequency: 'monthly',
    documentationUrl: 'https://www.fema.gov/flood-maps',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },

  // Census & Demographics
  {
    id: 'census-acs',
    name: 'US Census ACS',
    description: 'American Community Survey - demographics, economics, housing',
    vertical: 'government',
    category: 'demographics',
    provider: 'US Census Bureau',
    region: 'US',
    dataTypes: ['demographics', 'economics', 'housing', 'education'],
    updateFrequency: 'annual',
    documentationUrl: 'https://www.census.gov/data/developers/data-sets/acs-5year.html',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'census-economic',
    name: 'US Census Economic Indicators',
    description: 'Business patterns, retail sales, construction spending',
    vertical: 'government',
    category: 'economics',
    provider: 'US Census Bureau',
    region: 'US',
    dataTypes: ['business-patterns', 'retail-sales', 'construction', 'trade'],
    updateFrequency: 'monthly',
    documentationUrl: 'https://www.census.gov/econ/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },

  // Labor & Employment
  {
    id: 'bls-employment',
    name: 'Bureau of Labor Statistics',
    description: 'Employment, wages, inflation, productivity data',
    vertical: 'government',
    category: 'labor',
    provider: 'BLS',
    region: 'US',
    dataTypes: ['employment', 'wages', 'cpi', 'ppi', 'productivity'],
    updateFrequency: 'monthly',
    documentationUrl: 'https://www.bls.gov/developers/',
    requiredCredentials: ['registration_key'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },

  // Financial Regulators
  {
    id: 'sec-edgar',
    name: 'SEC EDGAR',
    description: 'Corporate filings, financial statements, insider trading',
    vertical: 'government',
    category: 'financial-regulatory',
    provider: 'SEC',
    region: 'US',
    dataTypes: ['10-K', '10-Q', '8-K', 'insider-transactions', 'proxy-statements'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.sec.gov/developer',
    requiredCredentials: ['user_agent'],
    complianceFrameworks: ['FedRAMP', 'SOX'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, user agent identification required',
  },
  {
    id: 'treasury-yields',
    name: 'US Treasury Yields',
    description: 'Treasury securities rates and auction data',
    vertical: 'government',
    category: 'financial-regulatory',
    provider: 'US Treasury',
    region: 'US',
    dataTypes: ['yield-curves', 'auction-results', 'debt-outstanding'],
    updateFrequency: 'daily',
    documentationUrl: 'https://home.treasury.gov/policy-issues/financing-the-government/interest-rate-statistics',
    requiredCredentials: [],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },
  {
    id: 'fred-economic',
    name: 'Federal Reserve FRED',
    description: 'Federal Reserve Economic Data - comprehensive economic indicators',
    vertical: 'government',
    category: 'economics',
    provider: 'Federal Reserve Bank of St. Louis',
    region: 'US',
    dataTypes: ['gdp', 'interest-rates', 'money-supply', 'employment', 'inflation'],
    updateFrequency: 'varies',
    documentationUrl: 'https://fred.stlouisfed.org/docs/api/fred/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },

  // Geospatial
  {
    id: 'usgs-earthquakes',
    name: 'USGS Earthquake Hazards',
    description: 'Real-time earthquake data and hazard assessments',
    vertical: 'government',
    category: 'geoscience',
    provider: 'USGS',
    region: 'US',
    dataTypes: ['earthquakes', 'faults', 'hazard-maps', 'shakemaps'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://earthquake.usgs.gov/fdsnws/event/1/',
    requiredCredentials: [],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },
  {
    id: 'usgs-water',
    name: 'USGS Water Services',
    description: 'Stream gauges, groundwater, water quality',
    vertical: 'government',
    category: 'water',
    provider: 'USGS',
    region: 'US',
    dataTypes: ['streamflow', 'groundwater', 'water-quality', 'precipitation'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://waterservices.usgs.gov/',
    requiredCredentials: [],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },

  // Energy
  {
    id: 'eia-petroleum',
    name: 'EIA Petroleum Data',
    description: 'Crude oil, gasoline, diesel prices and inventories',
    vertical: 'government',
    category: 'energy',
    provider: 'EIA',
    region: 'US',
    dataTypes: ['crude-prices', 'inventories', 'production', 'refinery-data'],
    updateFrequency: 'weekly',
    documentationUrl: 'https://www.eia.gov/opendata/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'eia-electricity',
    name: 'EIA Electricity Data',
    description: 'Power generation, consumption, grid operations',
    vertical: 'government',
    category: 'energy',
    provider: 'EIA',
    region: 'US',
    dataTypes: ['generation', 'consumption', 'prices', 'emissions'],
    updateFrequency: 'hourly',
    documentationUrl: 'https://www.eia.gov/opendata/',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },

  // Transportation
  {
    id: 'dot-highway',
    name: 'DOT Highway Statistics',
    description: 'Highway usage, vehicle miles traveled, infrastructure',
    vertical: 'government',
    category: 'transportation',
    provider: 'DOT FHWA',
    region: 'US',
    dataTypes: ['vmt', 'highway-conditions', 'bridge-data', 'traffic-counts'],
    updateFrequency: 'annual',
    documentationUrl: 'https://www.fhwa.dot.gov/policyinformation/statistics.cfm',
    requiredCredentials: [],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },
  {
    id: 'nhtsa-recalls',
    name: 'NHTSA Vehicle Safety',
    description: 'Vehicle recalls, complaints, crash data',
    vertical: 'government',
    category: 'transportation',
    provider: 'NHTSA',
    region: 'US',
    dataTypes: ['recalls', 'complaints', 'crash-data', 'investigations'],
    updateFrequency: 'daily',
    documentationUrl: 'https://www.nhtsa.gov/nhtsa-apis',
    requiredCredentials: [],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },

  // Agriculture
  {
    id: 'usda-nass',
    name: 'USDA NASS',
    description: 'National Agricultural Statistics Service - crop data',
    vertical: 'government',
    category: 'agriculture',
    provider: 'USDA',
    region: 'US',
    dataTypes: ['crop-production', 'livestock', 'prices', 'land-use'],
    updateFrequency: 'varies',
    documentationUrl: 'https://quickstats.nass.usda.gov/api',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'usda-ers',
    name: 'USDA Economic Research',
    description: 'Food prices, trade, farm income data',
    vertical: 'government',
    category: 'agriculture',
    provider: 'USDA ERS',
    region: 'US',
    dataTypes: ['food-prices', 'trade', 'farm-income', 'food-security'],
    updateFrequency: 'monthly',
    documentationUrl: 'https://www.ers.usda.gov/developer/',
    requiredCredentials: [],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },
];

export class GovernmentConnectorFactory {
  static getAvailableConnectors(): ConnectorMetadata[] {
    return GOVERNMENT_CONNECTORS;
  }

  static getByCategory(category: string): ConnectorMetadata[] {
    return GOVERNMENT_CONNECTORS.filter(c => c.category === category);
  }

  static getById(id: string): ConnectorMetadata | undefined {
    return GOVERNMENT_CONNECTORS.find(c => c.id === id);
  }
}
