// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.
// See LICENSE file for details.

// =============================================================================
// DELIBERATION SERVICE (Community Edition — In-Memory)
// Provides CRUD, summary generation, and report export for Council deliberations.
// Production: backed by Prisma/Postgres. Community: in-memory store.
// =============================================================================

import crypto from 'crypto';
import { BoundedMap } from '../utils/BoundedMap.js';
import { withFallback } from './_serviceProxy.js';

interface Deliberation {
  id: string;
  organizationId: string;
  userId: string;
  question: string;
  mode: string;
  councilMode: string;
  agentResponses: any[];
  crossExaminations: any[];
  synthesis: string;
  confidence: number;
  status: string;
  createdAt: string;
  updatedAt: string;
}

const store = new BoundedMap<string, Deliberation>({ maxSize: 10000 });

export const deliberationService: any = withFallback({
  async saveDeliberation(data: Partial<Deliberation>): Promise<Deliberation> {
    const id = crypto.randomUUID();
    const now = new Date().toISOString();
    const deliberation: Deliberation = {
      id,
      organizationId: data.organizationId || 'demo',
      userId: data.userId || 'demo-user',
      question: data.question || '',
      mode: data.mode || 'deliberation',
      councilMode: data.councilMode || 'war-room',
      agentResponses: data.agentResponses || [],
      crossExaminations: data.crossExaminations || [],
      synthesis: data.synthesis || '',
      confidence: data.confidence || 0,
      status: data.status || 'completed',
      createdAt: now,
      updatedAt: now,
    };
    store.set(id, deliberation);
    return deliberation;
  },

  async getDeliberations(
    _orgId?: string,
    opts?: { limit?: number; offset?: number; status?: string },
  ): Promise<Deliberation[]> {
    let items = [...store.values()];
    if (opts?.status) items = items.filter(d => d.status === opts.status);
    items.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
    const offset = opts?.offset || 0;
    const limit = opts?.limit || 50;
    return items.slice(offset, offset + limit);
  },

  async getDeliberation(id: string): Promise<Deliberation | null> {
    return store.get(id) || null;
  },

  async generateExecutiveSummary(id: string): Promise<any> {
    const d = store.get(id);
    if (!d) throw new Error(`Deliberation ${id} not found`);
    return {
      deliberationId: id,
      title: `Executive Summary: ${d.question.slice(0, 80)}`,
      keyFindings: d.agentResponses.map((r: any) => r.content?.slice(0, 200) || 'Analysis complete'),
      recommendation: d.synthesis,
      confidence: d.confidence,
      riskFactors: ['Implementation complexity', 'Timeline constraints'],
      generatedAt: new Date().toISOString(),
    };
  },

  async generateMinutes(id: string): Promise<any> {
    const d = store.get(id);
    if (!d) throw new Error(`Deliberation ${id} not found`);
    return {
      deliberationId: id,
      title: `Council Minutes — ${d.question.slice(0, 60)}`,
      date: d.createdAt,
      mode: d.councilMode,
      participants: d.agentResponses.map((r: any) => r.agentId || 'Agent'),
      agenda: d.question,
      discussion: d.agentResponses,
      resolution: d.synthesis,
      confidence: d.confidence,
      generatedAt: new Date().toISOString(),
    };
  },

  generatePDFReport(deliberation: Deliberation, summary: any): string {
    return `<!DOCTYPE html><html><head><title>Deliberation Report</title>
<style>body{font-family:system-ui;max-width:800px;margin:auto;padding:2rem}
h1{color:#059669}table{width:100%;border-collapse:collapse}td,th{padding:8px;border:1px solid #ddd}</style>
</head><body><h1>Council Deliberation Report</h1>
<p><strong>Question:</strong> ${deliberation.question}</p>
<p><strong>Mode:</strong> ${deliberation.councilMode}</p>
<p><strong>Confidence:</strong> ${deliberation.confidence}%</p>
<h2>Synthesis</h2><p>${deliberation.synthesis}</p>
<h2>Key Findings</h2><ul>${(summary.keyFindings || []).map((f: string) => `<li>${f}</li>`).join('')}</ul>
<p><em>Generated by Datacendia Council™</em></p></body></html>`;
  },
});

export const postDeliberationService: any = withFallback({
  async getRecommendations(deliberationId: string): Promise<any[]> {
    const d = store.get(deliberationId);
    if (!d) return [];
    return [
      { type: 'action', title: 'Implement recommended approach', priority: 'high', status: 'pending' },
      { type: 'review', title: 'Schedule follow-up review in 30 days', priority: 'medium', status: 'pending' },
      { type: 'monitor', title: 'Set up KPI tracking for decision outcomes', priority: 'medium', status: 'pending' },
    ];
  },

  async generateActionItems(_deliberationId: string): Promise<any[]> {
    return [
      { type: 'action', title: 'Implement recommended approach', priority: 'high', status: 'pending' },
      { type: 'review', title: 'Schedule follow-up review in 30 days', priority: 'medium', status: 'pending' },
    ];
  },
});
