// Copyright (c) 2024-2026 Datacendia, LLC All Rights Reserved.
// Proprietary and confidential. Unauthorized copying is strictly prohibited.
// See LICENSE file for details.

/**
 * Compliance Frameworks - The Five Rings of Sovereignty
 * Complete mapping of all compliance domains across 8 pillars
 */

export type ComplianceDomain = 
  | 'ethical_ai'
  | 'cybersecurity'
  | 'privacy'
  | 'governance'
  | 'industry';

export type PillarId = 
  | 'helm' | 'lineage' | 'predict' | 'flow' 
  | 'health' | 'guard' | 'ethics' | 'agents';

export interface ComplianceFramework {
  id: string;
  code: string;
  name: string;
  fullName: string;
  domain: ComplianceDomain;
  description: string;
  version: string;
  jurisdiction: string[];
  industries: string[];
  pillars: PillarId[];
  controlCount: number;
  lastUpdated: Date;
  status: 'active' | 'deprecated' | 'draft';
}

// ============================================================================
// RING 1: ETHICAL AI FRAMEWORKS
// ============================================================================
export const ETHICAL_AI_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'nist-ai-rmf',
    code: 'NIST-AI-RMF',
    name: 'NIST AI RMF',
    fullName: 'NIST Artificial Intelligence Risk Management Framework',
    domain: 'ethical_ai',
    description: 'Framework for managing AI risks throughout the AI lifecycle',
    version: '1.0',
    jurisdiction: ['US', 'Global'],
    industries: ['All'],
    pillars: ['helm', 'predict', 'ethics', 'agents'],
    controlCount: 72,
    lastUpdated: new Date('2023-01-26'),
    status: 'active',
  },
  {
    id: 'oecd-ai',
    code: 'OECD-AI',
    name: 'OECD AI Principles',
    fullName: 'OECD Principles on Artificial Intelligence',
    domain: 'ethical_ai',
    description: 'International standards for responsible stewardship of trustworthy AI',
    version: '2019',
    jurisdiction: ['OECD Countries', 'Global'],
    industries: ['All'],
    pillars: ['helm', 'predict', 'ethics', 'agents', 'lineage'],
    controlCount: 45,
    lastUpdated: new Date('2019-05-22'),
    status: 'active',
  },
  {
    id: 'unesco-ai',
    code: 'UNESCO-AI',
    name: 'UNESCO AI Ethics',
    fullName: 'UNESCO Recommendation on the Ethics of AI',
    domain: 'ethical_ai',
    description: 'Global standard for AI ethics covering all stages of the AI lifecycle',
    version: '2021',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['ethics', 'lineage', 'agents'],
    controlCount: 50,
    lastUpdated: new Date('2021-11-24'),
    status: 'active',
  },
  {
    id: 'iso-42001',
    code: 'ISO-42001',
    name: 'ISO 42001',
    fullName: 'ISO/IEC 42001 AI Management System',
    domain: 'ethical_ai',
    description: 'International standard for AI management systems',
    version: '2023',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['predict', 'ethics', 'agents', 'helm'],
    controlCount: 93,
    lastUpdated: new Date('2023-12-18'),
    status: 'active',
  },
  {
    id: 'eu-ai-act',
    code: 'EU-AI-ACT',
    name: 'EU AI Act',
    fullName: 'European Union Artificial Intelligence Act',
    domain: 'ethical_ai',
    description: 'Comprehensive AI regulation for the European Union',
    version: '2024',
    jurisdiction: ['EU'],
    industries: ['All'],
    pillars: ['ethics', 'agents', 'predict', 'guard'],
    controlCount: 85,
    lastUpdated: new Date('2024-03-13'),
    status: 'active',
  },
];

// ============================================================================
// RING 2: CYBERSECURITY FRAMEWORKS
// ============================================================================
export const CYBERSECURITY_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'nist-800-53',
    code: 'NIST-800-53',
    name: 'NIST 800-53',
    fullName: 'NIST Special Publication 800-53 Security Controls',
    domain: 'cybersecurity',
    description: 'Comprehensive security and privacy controls catalog',
    version: 'Rev 5',
    jurisdiction: ['US', 'Global'],
    industries: ['All', 'Government'],
    pillars: ['guard', 'health', 'lineage', 'flow'],
    controlCount: 1189,
    lastUpdated: new Date('2020-09-23'),
    status: 'active',
  },
  {
    id: 'soc2',
    code: 'SOC2',
    name: 'SOC 2',
    fullName: 'Service Organization Control 2',
    domain: 'cybersecurity',
    description: 'Trust services criteria for security, availability, processing integrity',
    version: '2017',
    jurisdiction: ['US', 'Global'],
    industries: ['All', 'SaaS'],
    pillars: ['guard', 'helm', 'health', 'lineage'],
    controlCount: 64,
    lastUpdated: new Date('2017-01-01'),
    status: 'active',
  },
  {
    id: 'iso-27001',
    code: 'ISO-27001',
    name: 'ISO 27001',
    fullName: 'ISO/IEC 27001 Information Security Management',
    domain: 'cybersecurity',
    description: 'International standard for information security management systems',
    version: '2022',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['guard', 'lineage', 'health', 'flow'],
    controlCount: 93,
    lastUpdated: new Date('2022-10-25'),
    status: 'active',
  },
  {
    id: 'mitre-attack',
    code: 'MITRE-ATT&CK',
    name: 'MITRE ATT&CK',
    fullName: 'MITRE ATT&CK Framework',
    domain: 'cybersecurity',
    description: 'Knowledge base of adversary tactics and techniques',
    version: '14.1',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['guard', 'health', 'lineage'],
    controlCount: 201,
    lastUpdated: new Date('2023-10-31'),
    status: 'active',
  },
  {
    id: 'zero-trust',
    code: 'ZERO-TRUST',
    name: 'Zero Trust Architecture',
    fullName: 'NIST SP 800-207 Zero Trust Architecture',
    domain: 'cybersecurity',
    description: 'Security model based on strict access controls and continuous verification',
    version: '2020',
    jurisdiction: ['US', 'Global'],
    industries: ['All'],
    pillars: ['guard', 'flow', 'helm', 'agents'],
    controlCount: 35,
    lastUpdated: new Date('2020-08-11'),
    status: 'active',
  },
  {
    id: 'cmmc',
    code: 'CMMC',
    name: 'CMMC 2.0',
    fullName: 'Cybersecurity Maturity Model Certification',
    domain: 'cybersecurity',
    description: 'DoD cybersecurity requirements for defense contractors',
    version: '2.0',
    jurisdiction: ['US'],
    industries: ['Defense'],
    pillars: ['guard', 'lineage', 'flow'],
    controlCount: 110,
    lastUpdated: new Date('2021-11-04'),
    status: 'active',
  },
  {
    id: 'nist-800-137',
    code: 'NIST-800-137',
    name: 'NIST 800-137',
    fullName: 'NIST SP 800-137 Continuous Monitoring',
    domain: 'cybersecurity',
    description: 'Information security continuous monitoring for federal systems',
    version: '2011',
    jurisdiction: ['US'],
    industries: ['Government'],
    pillars: ['health', 'guard'],
    controlCount: 42,
    lastUpdated: new Date('2011-09-30'),
    status: 'active',
  },
  {
    id: 'cis-benchmarks',
    code: 'CIS',
    name: 'CIS Benchmarks',
    fullName: 'Center for Internet Security Benchmarks',
    domain: 'cybersecurity',
    description: 'Best practice security configuration guidelines',
    version: '8.0',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['guard', 'health'],
    controlCount: 153,
    lastUpdated: new Date('2023-03-15'),
    status: 'active',
  },
];

// ============================================================================
// RING 3: PRIVACY & DATA PROTECTION
// ============================================================================
export const PRIVACY_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'gdpr',
    code: 'GDPR',
    name: 'GDPR',
    fullName: 'General Data Protection Regulation',
    domain: 'privacy',
    description: 'EU regulation on data protection and privacy',
    version: '2016/679',
    jurisdiction: ['EU', 'EEA'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'helm', 'ethics', 'flow'],
    controlCount: 99,
    lastUpdated: new Date('2018-05-25'),
    status: 'active',
  },
  {
    id: 'ccpa',
    code: 'CCPA/CPRA',
    name: 'CCPA/CPRA',
    fullName: 'California Consumer Privacy Act / California Privacy Rights Act',
    domain: 'privacy',
    description: 'California data privacy and protection law',
    version: '2023',
    jurisdiction: ['US-CA'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 55,
    lastUpdated: new Date('2023-01-01'),
    status: 'active',
  },
  {
    id: 'hipaa',
    code: 'HIPAA',
    name: 'HIPAA',
    fullName: 'Health Insurance Portability and Accountability Act',
    domain: 'privacy',
    description: 'US law protecting sensitive patient health information',
    version: '2013 Omnibus',
    jurisdiction: ['US'],
    industries: ['Healthcare'],
    pillars: ['guard', 'lineage', 'health', 'predict'],
    controlCount: 75,
    lastUpdated: new Date('2013-01-25'),
    status: 'active',
  },
  {
    id: 'iso-27701',
    code: 'ISO-27701',
    name: 'ISO 27701',
    fullName: 'ISO/IEC 27701 Privacy Information Management',
    domain: 'privacy',
    description: 'Extension to ISO 27001 for privacy information management',
    version: '2019',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['guard', 'lineage', 'helm', 'flow'],
    controlCount: 49,
    lastUpdated: new Date('2019-08-06'),
    status: 'active',
  },
  {
    id: 'pci-dss',
    code: 'PCI-DSS',
    name: 'PCI DSS',
    fullName: 'Payment Card Industry Data Security Standard',
    domain: 'privacy',
    description: 'Security standards for card payment data protection',
    version: '4.0',
    jurisdiction: ['Global'],
    industries: ['Finance', 'Retail'],
    pillars: ['guard', 'lineage', 'flow'],
    controlCount: 64,
    lastUpdated: new Date('2022-03-31'),
    status: 'active',
  },
];

// ============================================================================
// RING 4: GOVERNANCE & AUDIT
// ============================================================================
export const GOVERNANCE_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'coso-erm',
    code: 'COSO-ERM',
    name: 'COSO ERM',
    fullName: 'Committee of Sponsoring Organizations Enterprise Risk Management',
    domain: 'governance',
    description: 'Enterprise risk management framework',
    version: '2017',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['helm', 'predict', 'guard'],
    controlCount: 23,
    lastUpdated: new Date('2017-09-06'),
    status: 'active',
  },
  {
    id: 'cobit',
    code: 'COBIT',
    name: 'COBIT 2019',
    fullName: 'Control Objectives for Information Technologies',
    domain: 'governance',
    description: 'IT governance and management framework',
    version: '2019',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['helm', 'flow', 'guard', 'health'],
    controlCount: 40,
    lastUpdated: new Date('2018-11-18'),
    status: 'active',
  },
  {
    id: 'itil',
    code: 'ITIL',
    name: 'ITIL 4',
    fullName: 'Information Technology Infrastructure Library',
    domain: 'governance',
    description: 'IT service management best practices',
    version: '4.0',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['flow', 'health', 'helm'],
    controlCount: 34,
    lastUpdated: new Date('2019-02-18'),
    status: 'active',
  },
  {
    id: 'sox',
    code: 'SOX',
    name: 'SOX',
    fullName: 'Sarbanes-Oxley Act',
    domain: 'governance',
    description: 'US law for corporate financial accountability and auditing',
    version: '2002',
    jurisdiction: ['US'],
    industries: ['Public Companies', 'Finance'],
    pillars: ['helm', 'lineage', 'guard', 'flow'],
    controlCount: 66,
    lastUpdated: new Date('2002-07-30'),
    status: 'active',
  },
  {
    id: 'iso-9001',
    code: 'ISO-9001',
    name: 'ISO 9001',
    fullName: 'ISO 9001 Quality Management System',
    domain: 'governance',
    description: 'International standard for quality management systems',
    version: '2015',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['health', 'flow', 'helm'],
    controlCount: 51,
    lastUpdated: new Date('2015-09-23'),
    status: 'active',
  },
  {
    id: 'iso-20000',
    code: 'ISO-20000',
    name: 'ISO 20000',
    fullName: 'ISO/IEC 20000 IT Service Management',
    domain: 'governance',
    description: 'International standard for IT service management',
    version: '2018',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['health', 'flow'],
    controlCount: 48,
    lastUpdated: new Date('2018-09-15'),
    status: 'active',
  },
];

// ============================================================================
// RING 5: INDUSTRY REGULATIONS
// ============================================================================
export const INDUSTRY_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'basel-iii',
    code: 'BASEL-III',
    name: 'Basel III/IV',
    fullName: 'Basel III/IV Banking Supervision Framework',
    domain: 'industry',
    description: 'International regulatory framework for banks',
    version: 'III/IV',
    jurisdiction: ['Global'],
    industries: ['Banking', 'Finance'],
    pillars: ['helm', 'predict', 'guard'],
    controlCount: 87,
    lastUpdated: new Date('2023-01-01'),
    status: 'active',
  },
  {
    id: 'fedramp',
    code: 'FedRAMP',
    name: 'FedRAMP',
    fullName: 'Federal Risk and Authorization Management Program',
    domain: 'industry',
    description: 'US government cloud security authorization program',
    version: '2023',
    jurisdiction: ['US'],
    industries: ['Government'],
    pillars: ['guard', 'flow', 'health', 'lineage'],
    controlCount: 325,
    lastUpdated: new Date('2023-06-06'),
    status: 'active',
  },
  {
    id: 'gxp',
    code: 'GxP',
    name: 'GxP',
    fullName: 'Good Practice Guidelines (GLP, GMP, GCP, GDP)',
    domain: 'industry',
    description: 'Quality and safety guidelines for life sciences',
    version: 'Various',
    jurisdiction: ['Global'],
    industries: ['Pharma', 'Healthcare', 'Medical Devices'],
    pillars: ['flow', 'lineage', 'guard', 'ethics'],
    controlCount: 120,
    lastUpdated: new Date('2022-01-01'),
    status: 'active',
  },
  {
    id: 'nerc-cip',
    code: 'NERC-CIP',
    name: 'NERC CIP',
    fullName: 'North American Electric Reliability Corporation Critical Infrastructure Protection',
    domain: 'industry',
    description: 'Cybersecurity standards for bulk electric system',
    version: '2023',
    jurisdiction: ['US', 'Canada'],
    industries: ['Energy', 'Utilities'],
    pillars: ['guard', 'health', 'flow'],
    controlCount: 45,
    lastUpdated: new Date('2023-01-01'),
    status: 'active',
  },
  {
    id: 'cjis',
    code: 'CJIS',
    name: 'FBI CJIS',
    fullName: 'Criminal Justice Information Services Security Policy',
    domain: 'industry',
    description: 'Security policy for criminal justice information',
    version: '5.9.1',
    jurisdiction: ['US'],
    industries: ['Government', 'Law Enforcement'],
    pillars: ['guard', 'lineage', 'ethics'],
    controlCount: 52,
    lastUpdated: new Date('2022-06-01'),
    status: 'active',
  },
  {
    id: 'ifrs-9',
    code: 'IFRS-9',
    name: 'IFRS 9',
    fullName: 'International Financial Reporting Standard 9',
    domain: 'industry',
    description: 'Financial instruments accounting standard with ECL modeling',
    version: '2014',
    jurisdiction: ['Global'],
    industries: ['Finance', 'Banking'],
    pillars: ['predict', 'helm'],
    controlCount: 38,
    lastUpdated: new Date('2014-07-24'),
    status: 'active',
  },
  {
    id: 'sr-11-7',
    code: 'SR-11-7',
    name: 'SR 11-7',
    fullName: 'Federal Reserve Model Risk Management Guidance',
    domain: 'industry',
    description: 'Guidance on model risk management for banking',
    version: '2011',
    jurisdiction: ['US'],
    industries: ['Banking'],
    pillars: ['predict', 'ethics', 'guard'],
    controlCount: 28,
    lastUpdated: new Date('2011-04-04'),
    status: 'active',
  },
  // ========== AUTOMOTIVE ==========
  {
    id: 'tisax',
    code: 'TISAX',
    name: 'TISAX',
    fullName: 'Trusted Information Security Assessment Exchange',
    domain: 'industry',
    description: 'Automotive industry information security assessment standard',
    version: '5.1',
    jurisdiction: ['EU', 'Global'],
    industries: ['Automotive'],
    pillars: ['guard', 'lineage', 'flow'],
    controlCount: 68,
    lastUpdated: new Date('2023-04-01'),
    status: 'active',
  },
  {
    id: 'iso-sae-21434',
    code: 'ISO-21434',
    name: 'ISO/SAE 21434',
    fullName: 'Road Vehicles - Cybersecurity Engineering',
    domain: 'industry',
    description: 'Automotive cybersecurity engineering standard',
    version: '2021',
    jurisdiction: ['Global'],
    industries: ['Automotive'],
    pillars: ['guard', 'flow', 'health'],
    controlCount: 45,
    lastUpdated: new Date('2021-08-31'),
    status: 'active',
  },
  {
    id: 'unece-wp29',
    code: 'UNECE-WP29',
    name: 'UNECE WP.29',
    fullName: 'UN Regulation on Cybersecurity and Software Updates',
    domain: 'industry',
    description: 'UN regulations for vehicle cybersecurity management systems',
    version: '2021',
    jurisdiction: ['EU', 'Global'],
    industries: ['Automotive'],
    pillars: ['guard', 'flow'],
    controlCount: 32,
    lastUpdated: new Date('2021-01-22'),
    status: 'active',
  },
  // ========== FINANCIAL SERVICES (EXTENDED) ==========
  {
    id: 'dora',
    code: 'DORA',
    name: 'DORA',
    fullName: 'Digital Operational Resilience Act',
    domain: 'industry',
    description: 'EU regulation on digital operational resilience for financial sector',
    version: '2022',
    jurisdiction: ['EU'],
    industries: ['Finance', 'Banking', 'Insurance'],
    pillars: ['guard', 'health', 'flow', 'predict'],
    controlCount: 64,
    lastUpdated: new Date('2022-12-27'),
    status: 'active',
  },
  {
    id: 'nydfs-500',
    code: 'NYDFS-500',
    name: 'NY DFS 500',
    fullName: 'New York Department of Financial Services Cybersecurity Regulation',
    domain: 'industry',
    description: 'NY state cybersecurity requirements for financial services',
    version: '2023',
    jurisdiction: ['US-NY'],
    industries: ['Finance', 'Banking', 'Insurance'],
    pillars: ['guard', 'lineage', 'health'],
    controlCount: 23,
    lastUpdated: new Date('2023-11-01'),
    status: 'active',
  },
  {
    id: 'mifid-ii',
    code: 'MiFID-II',
    name: 'MiFID II',
    fullName: 'Markets in Financial Instruments Directive II',
    domain: 'industry',
    description: 'EU regulation for investment services and financial markets',
    version: '2018',
    jurisdiction: ['EU'],
    industries: ['Finance', 'Banking'],
    pillars: ['helm', 'lineage', 'guard'],
    controlCount: 97,
    lastUpdated: new Date('2018-01-03'),
    status: 'active',
  },
  {
    id: 'dodd-frank',
    code: 'DODD-FRANK',
    name: 'Dodd-Frank',
    fullName: 'Dodd-Frank Wall Street Reform and Consumer Protection Act',
    domain: 'industry',
    description: 'US financial regulatory reform legislation',
    version: '2010',
    jurisdiction: ['US'],
    industries: ['Finance', 'Banking'],
    pillars: ['helm', 'predict', 'guard', 'lineage'],
    controlCount: 125,
    lastUpdated: new Date('2010-07-21'),
    status: 'active',
  },
  {
    id: 'glba',
    code: 'GLBA',
    name: 'GLBA',
    fullName: 'Gramm-Leach-Bliley Act',
    domain: 'industry',
    description: 'US law requiring financial institutions to protect consumer data',
    version: '1999',
    jurisdiction: ['US'],
    industries: ['Finance', 'Banking'],
    pillars: ['guard', 'lineage'],
    controlCount: 42,
    lastUpdated: new Date('1999-11-12'),
    status: 'active',
  },
  {
    id: 'finra',
    code: 'FINRA',
    name: 'FINRA Rules',
    fullName: 'Financial Industry Regulatory Authority Rules',
    domain: 'industry',
    description: 'Self-regulatory organization rules for broker-dealers',
    version: '2024',
    jurisdiction: ['US'],
    industries: ['Finance', 'Securities'],
    pillars: ['helm', 'lineage', 'guard', 'ethics'],
    controlCount: 156,
    lastUpdated: new Date('2024-01-01'),
    status: 'active',
  },
  {
    id: 'apra-cps-234',
    code: 'APRA-CPS-234',
    name: 'APRA CPS 234',
    fullName: 'Australian Prudential Regulation Authority Information Security',
    domain: 'industry',
    description: 'Australian information security standard for financial institutions',
    version: '2019',
    jurisdiction: ['AU'],
    industries: ['Finance', 'Banking', 'Insurance'],
    pillars: ['guard', 'health', 'flow'],
    controlCount: 36,
    lastUpdated: new Date('2019-07-01'),
    status: 'active',
  },
  {
    id: 'mas-trm',
    code: 'MAS-TRM',
    name: 'MAS TRM',
    fullName: 'Monetary Authority of Singapore Technology Risk Management',
    domain: 'industry',
    description: 'Singapore technology risk management guidelines for financial institutions',
    version: '2021',
    jurisdiction: ['SG'],
    industries: ['Finance', 'Banking'],
    pillars: ['guard', 'health', 'flow', 'predict'],
    controlCount: 58,
    lastUpdated: new Date('2021-01-18'),
    status: 'active',
  },
  {
    id: 'psd2',
    code: 'PSD2',
    name: 'PSD2',
    fullName: 'Payment Services Directive 2',
    domain: 'industry',
    description: 'EU directive on payment services including open banking',
    version: '2018',
    jurisdiction: ['EU'],
    industries: ['Finance', 'Banking', 'Payments'],
    pillars: ['guard', 'flow', 'lineage'],
    controlCount: 48,
    lastUpdated: new Date('2018-01-13'),
    status: 'active',
  },
  // ========== HEALTHCARE (EXTENDED) ==========
  {
    id: 'fda-21-cfr-11',
    code: 'FDA-21-CFR-11',
    name: 'FDA 21 CFR Part 11',
    fullName: 'FDA Electronic Records and Electronic Signatures',
    domain: 'industry',
    description: 'FDA regulations for electronic records in pharmaceuticals',
    version: '2003',
    jurisdiction: ['US'],
    industries: ['Pharma', 'Healthcare', 'Medical Devices'],
    pillars: ['lineage', 'guard', 'flow'],
    controlCount: 38,
    lastUpdated: new Date('2003-08-20'),
    status: 'active',
  },
  {
    id: 'hitrust-csf',
    code: 'HITRUST-CSF',
    name: 'HITRUST CSF',
    fullName: 'HITRUST Common Security Framework',
    domain: 'industry',
    description: 'Healthcare-focused certifiable security framework',
    version: '11.0',
    jurisdiction: ['US', 'Global'],
    industries: ['Healthcare'],
    pillars: ['guard', 'health', 'lineage', 'flow'],
    controlCount: 156,
    lastUpdated: new Date('2023-01-01'),
    status: 'active',
  },
  {
    id: 'hl7-fhir',
    code: 'HL7-FHIR',
    name: 'HL7 FHIR',
    fullName: 'Health Level 7 Fast Healthcare Interoperability Resources',
    domain: 'industry',
    description: 'Standard for healthcare data exchange',
    version: 'R4',
    jurisdiction: ['Global'],
    industries: ['Healthcare'],
    pillars: ['flow', 'lineage'],
    controlCount: 85,
    lastUpdated: new Date('2019-10-30'),
    status: 'active',
  },
  {
    id: 'ich-e6-r2',
    code: 'ICH-E6-R2',
    name: 'ICH E6(R2)',
    fullName: 'ICH Guideline for Good Clinical Practice',
    domain: 'industry',
    description: 'International standard for clinical trial design and reporting',
    version: 'R2',
    jurisdiction: ['Global'],
    industries: ['Pharma', 'Healthcare'],
    pillars: ['ethics', 'lineage', 'flow'],
    controlCount: 64,
    lastUpdated: new Date('2016-11-09'),
    status: 'active',
  },
  {
    id: 'iso-13485',
    code: 'ISO-13485',
    name: 'ISO 13485',
    fullName: 'Medical Devices Quality Management Systems',
    domain: 'industry',
    description: 'Quality management system for medical device manufacturing',
    version: '2016',
    jurisdiction: ['Global'],
    industries: ['Medical Devices'],
    pillars: ['flow', 'health', 'guard'],
    controlCount: 52,
    lastUpdated: new Date('2016-03-01'),
    status: 'active',
  },
  {
    id: 'mdr-eu',
    code: 'MDR-EU',
    name: 'EU MDR',
    fullName: 'European Medical Device Regulation',
    domain: 'industry',
    description: 'EU regulation on medical devices',
    version: '2017/745',
    jurisdiction: ['EU'],
    industries: ['Medical Devices'],
    pillars: ['flow', 'guard', 'lineage', 'ethics'],
    controlCount: 78,
    lastUpdated: new Date('2021-05-26'),
    status: 'active',
  },
  // ========== GOVERNMENT & DEFENSE (EXTENDED) ==========
  {
    id: 'itar',
    code: 'ITAR',
    name: 'ITAR',
    fullName: 'International Traffic in Arms Regulations',
    domain: 'industry',
    description: 'US regulations governing defense articles and services',
    version: '2024',
    jurisdiction: ['US'],
    industries: ['Defense', 'Aerospace'],
    pillars: ['guard', 'lineage', 'ethics'],
    controlCount: 45,
    lastUpdated: new Date('2024-01-01'),
    status: 'active',
  },
  {
    id: 'ear',
    code: 'EAR',
    name: 'EAR',
    fullName: 'Export Administration Regulations',
    domain: 'industry',
    description: 'US regulations on dual-use item exports',
    version: '2024',
    jurisdiction: ['US'],
    industries: ['Defense', 'Technology'],
    pillars: ['guard', 'lineage'],
    controlCount: 38,
    lastUpdated: new Date('2024-01-01'),
    status: 'active',
  },
  {
    id: 'dfars',
    code: 'DFARS',
    name: 'DFARS',
    fullName: 'Defense Federal Acquisition Regulation Supplement',
    domain: 'industry',
    description: 'DoD-specific supplement to FAR for defense contracts',
    version: '2023',
    jurisdiction: ['US'],
    industries: ['Defense'],
    pillars: ['guard', 'lineage', 'flow'],
    controlCount: 82,
    lastUpdated: new Date('2023-12-01'),
    status: 'active',
  },
  {
    id: 'stateramp',
    code: 'StateRAMP',
    name: 'StateRAMP',
    fullName: 'State Risk and Authorization Management Program',
    domain: 'industry',
    description: 'Cloud security framework for US state and local governments',
    version: '2023',
    jurisdiction: ['US'],
    industries: ['Government'],
    pillars: ['guard', 'flow', 'health'],
    controlCount: 156,
    lastUpdated: new Date('2023-01-01'),
    status: 'active',
  },
  {
    id: 'fips-140-3',
    code: 'FIPS-140-3',
    name: 'FIPS 140-3',
    fullName: 'Federal Information Processing Standard 140-3',
    domain: 'industry',
    description: 'US government cryptographic module security requirements',
    version: '2019',
    jurisdiction: ['US'],
    industries: ['Government', 'Defense'],
    pillars: ['guard'],
    controlCount: 42,
    lastUpdated: new Date('2019-03-22'),
    status: 'active',
  },
  {
    id: 'fisma',
    code: 'FISMA',
    name: 'FISMA',
    fullName: 'Federal Information Security Modernization Act',
    domain: 'industry',
    description: 'US law requiring federal agencies to secure information systems',
    version: '2014',
    jurisdiction: ['US'],
    industries: ['Government'],
    pillars: ['guard', 'health', 'lineage'],
    controlCount: 64,
    lastUpdated: new Date('2014-12-18'),
    status: 'active',
  },
  // ========== ENERGY & UTILITIES (EXTENDED) ==========
  {
    id: 'iec-62443',
    code: 'IEC-62443',
    name: 'IEC 62443',
    fullName: 'Industrial Automation and Control Systems Security',
    domain: 'industry',
    description: 'Security standards for industrial automation and control systems',
    version: '2018',
    jurisdiction: ['Global'],
    industries: ['Energy', 'Manufacturing', 'Utilities'],
    pillars: ['guard', 'health', 'flow'],
    controlCount: 98,
    lastUpdated: new Date('2018-08-24'),
    status: 'active',
  },
  {
    id: 'tsa-pipeline',
    code: 'TSA-PIPELINE',
    name: 'TSA Pipeline Security',
    fullName: 'TSA Security Directives for Pipeline Operators',
    domain: 'industry',
    description: 'US cybersecurity requirements for pipeline operators',
    version: '2022',
    jurisdiction: ['US'],
    industries: ['Energy', 'Oil & Gas'],
    pillars: ['guard', 'health'],
    controlCount: 28,
    lastUpdated: new Date('2022-07-21'),
    status: 'active',
  },
  {
    id: 'api-1164',
    code: 'API-1164',
    name: 'API 1164',
    fullName: 'API Pipeline SCADA Security Standard',
    domain: 'industry',
    description: 'Security standard for pipeline SCADA systems',
    version: '2009',
    jurisdiction: ['US', 'Global'],
    industries: ['Energy', 'Oil & Gas'],
    pillars: ['guard', 'flow'],
    controlCount: 35,
    lastUpdated: new Date('2009-06-01'),
    status: 'active',
  },
  // ========== TELECOM ==========
  {
    id: 'gsma-nesas',
    code: 'GSMA-NESAS',
    name: 'GSMA NESAS',
    fullName: 'Network Equipment Security Assurance Scheme',
    domain: 'industry',
    description: 'Security assurance framework for mobile network equipment',
    version: '2.0',
    jurisdiction: ['Global'],
    industries: ['Telecom'],
    pillars: ['guard', 'flow'],
    controlCount: 45,
    lastUpdated: new Date('2021-10-01'),
    status: 'active',
  },
  {
    id: 'etsi-en-303-645',
    code: 'ETSI-EN-303-645',
    name: 'ETSI EN 303 645',
    fullName: 'Cyber Security for Consumer Internet of Things',
    domain: 'industry',
    description: 'European standard for IoT device cybersecurity',
    version: '2020',
    jurisdiction: ['EU'],
    industries: ['Telecom', 'IoT', 'Consumer Electronics'],
    pillars: ['guard', 'flow'],
    controlCount: 33,
    lastUpdated: new Date('2020-06-01'),
    status: 'active',
  },
  {
    id: 'fcc-tcpa',
    code: 'FCC-TCPA',
    name: 'FCC TCPA',
    fullName: 'Telephone Consumer Protection Act',
    domain: 'industry',
    description: 'US regulations on telemarketing and automated communications',
    version: '2024',
    jurisdiction: ['US'],
    industries: ['Telecom', 'Marketing'],
    pillars: ['ethics', 'lineage'],
    controlCount: 28,
    lastUpdated: new Date('2024-01-01'),
    status: 'active',
  },
  // ========== PRIVACY (REGIONAL EXTENDED) ==========
  {
    id: 'pdpa-thailand',
    code: 'PDPA-TH',
    name: 'Thailand PDPA',
    fullName: 'Thailand Personal Data Protection Act',
    domain: 'privacy',
    description: 'Thailand data protection law modeled on GDPR',
    version: '2022',
    jurisdiction: ['TH'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 45,
    lastUpdated: new Date('2022-06-01'),
    status: 'active',
  },
  {
    id: 'pdpa-singapore',
    code: 'PDPA-SG',
    name: 'Singapore PDPA',
    fullName: 'Singapore Personal Data Protection Act',
    domain: 'privacy',
    description: 'Singapore personal data protection law',
    version: '2020',
    jurisdiction: ['SG'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 52,
    lastUpdated: new Date('2020-11-01'),
    status: 'active',
  },
  {
    id: 'lgpd',
    code: 'LGPD',
    name: 'Brazil LGPD',
    fullName: 'Lei Geral de Proteção de Dados',
    domain: 'privacy',
    description: 'Brazil general data protection law',
    version: '2020',
    jurisdiction: ['BR'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 65,
    lastUpdated: new Date('2020-09-18'),
    status: 'active',
  },
  {
    id: 'pipl',
    code: 'PIPL',
    name: 'China PIPL',
    fullName: 'Personal Information Protection Law of China',
    domain: 'privacy',
    description: 'China comprehensive data privacy law',
    version: '2021',
    jurisdiction: ['CN'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 72,
    lastUpdated: new Date('2021-11-01'),
    status: 'active',
  },
  {
    id: 'popia',
    code: 'POPIA',
    name: 'South Africa POPIA',
    fullName: 'Protection of Personal Information Act',
    domain: 'privacy',
    description: 'South African data protection law',
    version: '2021',
    jurisdiction: ['ZA'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 48,
    lastUpdated: new Date('2021-07-01'),
    status: 'active',
  },
  {
    id: 'dpdp-india',
    code: 'DPDP',
    name: 'India DPDP',
    fullName: 'Digital Personal Data Protection Act',
    domain: 'privacy',
    description: 'India digital personal data protection law',
    version: '2023',
    jurisdiction: ['IN'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 38,
    lastUpdated: new Date('2023-08-11'),
    status: 'active',
  },
  {
    id: 'appi-japan',
    code: 'APPI',
    name: 'Japan APPI',
    fullName: 'Act on Protection of Personal Information',
    domain: 'privacy',
    description: 'Japan data protection law',
    version: '2022',
    jurisdiction: ['JP'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 56,
    lastUpdated: new Date('2022-04-01'),
    status: 'active',
  },
  {
    id: 'privacy-act-au',
    code: 'PRIVACY-AU',
    name: 'Australia Privacy Act',
    fullName: 'Australian Privacy Act and APPs',
    domain: 'privacy',
    description: 'Australian privacy principles and data protection',
    version: '2022',
    jurisdiction: ['AU'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 42,
    lastUpdated: new Date('2022-12-12'),
    status: 'active',
  },
  // ========== RETAIL & E-COMMERCE ==========
  {
    id: 'pci-p2pe',
    code: 'PCI-P2PE',
    name: 'PCI P2PE',
    fullName: 'PCI Point-to-Point Encryption Standard',
    domain: 'industry',
    description: 'Standard for payment terminal encryption',
    version: '3.0',
    jurisdiction: ['Global'],
    industries: ['Retail', 'Payments'],
    pillars: ['guard', 'flow'],
    controlCount: 42,
    lastUpdated: new Date('2019-06-01'),
    status: 'active',
  },
  {
    id: 'pci-3ds',
    code: 'PCI-3DS',
    name: 'PCI 3DS',
    fullName: 'PCI 3-D Secure Standard',
    domain: 'industry',
    description: 'Security standard for online card authentication',
    version: '2.0',
    jurisdiction: ['Global'],
    industries: ['Retail', 'Payments', 'E-commerce'],
    pillars: ['guard', 'flow'],
    controlCount: 38,
    lastUpdated: new Date('2020-10-01'),
    status: 'active',
  },
  // ========== MANUFACTURING ==========
  {
    id: 'iso-22301',
    code: 'ISO-22301',
    name: 'ISO 22301',
    fullName: 'Business Continuity Management Systems',
    domain: 'industry',
    description: 'Standard for business continuity management',
    version: '2019',
    jurisdiction: ['Global'],
    industries: ['All', 'Manufacturing'],
    pillars: ['health', 'flow', 'helm'],
    controlCount: 34,
    lastUpdated: new Date('2019-10-30'),
    status: 'active',
  },
  {
    id: 'iso-55001',
    code: 'ISO-55001',
    name: 'ISO 55001',
    fullName: 'Asset Management Systems',
    domain: 'industry',
    description: 'Standard for asset management',
    version: '2014',
    jurisdiction: ['Global'],
    industries: ['Manufacturing', 'Utilities', 'Transportation'],
    pillars: ['flow', 'health', 'helm'],
    controlCount: 28,
    lastUpdated: new Date('2014-01-15'),
    status: 'active',
  },
  // ========== AEROSPACE ==========
  {
    id: 'as9100',
    code: 'AS9100',
    name: 'AS9100D',
    fullName: 'Aerospace Quality Management System Standard',
    domain: 'industry',
    description: 'Quality management standard for aerospace industry',
    version: 'D',
    jurisdiction: ['Global'],
    industries: ['Aerospace'],
    pillars: ['flow', 'health', 'guard'],
    controlCount: 76,
    lastUpdated: new Date('2016-09-20'),
    status: 'active',
  },
  {
    id: 'do-326a',
    code: 'DO-326A',
    name: 'DO-326A',
    fullName: 'Airborne Systems Security',
    domain: 'industry',
    description: 'Airworthiness security process specification',
    version: '2014',
    jurisdiction: ['US', 'Global'],
    industries: ['Aerospace', 'Aviation'],
    pillars: ['guard', 'flow'],
    controlCount: 45,
    lastUpdated: new Date('2014-07-08'),
    status: 'active',
  },
  // ========== EDUCATION ==========
  {
    id: 'ferpa',
    code: 'FERPA',
    name: 'FERPA',
    fullName: 'Family Educational Rights and Privacy Act',
    domain: 'industry',
    description: 'US law protecting student education records',
    version: '1974',
    jurisdiction: ['US'],
    industries: ['Education'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 28,
    lastUpdated: new Date('2012-01-01'),
    status: 'active',
  },
  {
    id: 'coppa',
    code: 'COPPA',
    name: 'COPPA',
    fullName: 'Children\'s Online Privacy Protection Act',
    domain: 'industry',
    description: 'US law protecting children online privacy',
    version: '2013',
    jurisdiction: ['US'],
    industries: ['Education', 'Technology', 'Entertainment'],
    pillars: ['ethics', 'lineage', 'guard'],
    controlCount: 18,
    lastUpdated: new Date('2013-07-01'),
    status: 'active',
  },
  // ========== INSURANCE ==========
  {
    id: 'solvency-ii',
    code: 'SOLVENCY-II',
    name: 'Solvency II',
    fullName: 'EU Solvency II Directive',
    domain: 'industry',
    description: 'EU regulatory framework for insurance companies',
    version: '2016',
    jurisdiction: ['EU'],
    industries: ['Insurance'],
    pillars: ['helm', 'predict', 'guard'],
    controlCount: 86,
    lastUpdated: new Date('2016-01-01'),
    status: 'active',
  },
  {
    id: 'naic-model-laws',
    code: 'NAIC',
    name: 'NAIC Model Laws',
    fullName: 'National Association of Insurance Commissioners Model Laws',
    domain: 'industry',
    description: 'US insurance industry regulatory model laws',
    version: '2023',
    jurisdiction: ['US'],
    industries: ['Insurance'],
    pillars: ['helm', 'guard', 'lineage'],
    controlCount: 68,
    lastUpdated: new Date('2023-01-01'),
    status: 'active',
  },
  // ========== REAL ESTATE & CONSTRUCTION ==========
  {
    id: 'respa',
    code: 'RESPA',
    name: 'RESPA',
    fullName: 'Real Estate Settlement Procedures Act',
    domain: 'industry',
    description: 'US law governing real estate transactions',
    version: '2024',
    jurisdiction: ['US'],
    industries: ['Real Estate'],
    pillars: ['lineage', 'ethics'],
    controlCount: 24,
    lastUpdated: new Date('2024-01-01'),
    status: 'active',
  },
  {
    id: 'iso-19650',
    code: 'ISO-19650',
    name: 'ISO 19650',
    fullName: 'Organization and Digitization of Information about Buildings',
    domain: 'industry',
    description: 'BIM and construction information management standard',
    version: '2018',
    jurisdiction: ['Global'],
    industries: ['Construction'],
    pillars: ['flow', 'lineage'],
    controlCount: 32,
    lastUpdated: new Date('2018-12-01'),
    status: 'active',
  },
  // ========== FOOD & BEVERAGE ==========
  {
    id: 'fsma',
    code: 'FSMA',
    name: 'FDA FSMA',
    fullName: 'Food Safety Modernization Act',
    domain: 'industry',
    description: 'US law for preventing food safety problems',
    version: '2011',
    jurisdiction: ['US'],
    industries: ['Food & Beverage'],
    pillars: ['flow', 'lineage', 'health'],
    controlCount: 48,
    lastUpdated: new Date('2011-01-04'),
    status: 'active',
  },
  {
    id: 'iso-22000',
    code: 'ISO-22000',
    name: 'ISO 22000',
    fullName: 'Food Safety Management Systems',
    domain: 'industry',
    description: 'International food safety management standard',
    version: '2018',
    jurisdiction: ['Global'],
    industries: ['Food & Beverage'],
    pillars: ['flow', 'health'],
    controlCount: 42,
    lastUpdated: new Date('2018-06-19'),
    status: 'active',
  },
  // ========== ENVIRONMENTAL ==========
  {
    id: 'iso-14001',
    code: 'ISO-14001',
    name: 'ISO 14001',
    fullName: 'Environmental Management Systems',
    domain: 'industry',
    description: 'International environmental management standard',
    version: '2015',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['flow', 'health', 'ethics'],
    controlCount: 45,
    lastUpdated: new Date('2015-09-15'),
    status: 'active',
  },
  {
    id: 'tcfd',
    code: 'TCFD',
    name: 'TCFD',
    fullName: 'Task Force on Climate-Related Financial Disclosures',
    domain: 'industry',
    description: 'Climate risk disclosure framework',
    version: '2022',
    jurisdiction: ['Global'],
    industries: ['All', 'Finance'],
    pillars: ['predict', 'helm', 'lineage'],
    controlCount: 32,
    lastUpdated: new Date('2022-10-01'),
    status: 'active',
  },
  {
    id: 'csrd-eu',
    code: 'CSRD',
    name: 'EU CSRD',
    fullName: 'Corporate Sustainability Reporting Directive',
    domain: 'industry',
    description: 'EU sustainability reporting requirements',
    version: '2024',
    jurisdiction: ['EU'],
    industries: ['All'],
    pillars: ['lineage', 'helm', 'ethics'],
    controlCount: 58,
    lastUpdated: new Date('2024-01-01'),
    status: 'active',
  },
  // ========== LEGAL ==========
  {
    id: 'aba-model-rules',
    code: 'ABA-MRPC',
    name: 'ABA Model Rules',
    fullName: 'ABA Model Rules of Professional Conduct',
    domain: 'industry',
    description: 'Professional conduct rules for US attorneys',
    version: '2023',
    jurisdiction: ['US'],
    industries: ['Legal'],
    pillars: ['ethics', 'lineage', 'guard'],
    controlCount: 56,
    lastUpdated: new Date('2023-08-01'),
    status: 'active',
  },
  {
    id: 'sra-uk',
    code: 'SRA-UK',
    name: 'SRA Standards',
    fullName: 'Solicitors Regulation Authority Standards and Regulations',
    domain: 'industry',
    description: 'UK solicitor professional standards',
    version: '2023',
    jurisdiction: ['UK'],
    industries: ['Legal'],
    pillars: ['ethics', 'lineage'],
    controlCount: 42,
    lastUpdated: new Date('2023-04-01'),
    status: 'active',
  },
];

// ============================================================================
// ALL FRAMEWORKS COMBINED
// ============================================================================
export const ALL_FRAMEWORKS: ComplianceFramework[] = [
  ...ETHICAL_AI_FRAMEWORKS,
  ...CYBERSECURITY_FRAMEWORKS,
  ...PRIVACY_FRAMEWORKS,
  ...GOVERNANCE_FRAMEWORKS,
  ...INDUSTRY_FRAMEWORKS,
];

// ============================================================================
// PILLAR-TO-FRAMEWORK MAPPING
// ============================================================================
export const PILLAR_FRAMEWORK_MAPPING: Record<PillarId, Record<ComplianceDomain, string[]>> = {
  helm: {
    ethical_ai: ['NIST-AI-RMF', 'OECD-AI', 'ISO-42001'],
    cybersecurity: ['SOC2', 'ZERO-TRUST'],
    privacy: ['GDPR', 'ISO-27701'],
    governance: ['COSO-ERM', 'COBIT', 'SOX'],
    industry: ['BASEL-III', 'IFRS-9'],
  },
  lineage: {
    ethical_ai: ['UNESCO-AI', 'OECD-AI'],
    cybersecurity: ['NIST-800-53', 'MITRE-ATT&CK', 'ISO-27001'],
    privacy: ['GDPR', 'CCPA/CPRA', 'HIPAA', 'PCI-DSS'],
    governance: ['SOX', 'ISO-27001'],
    industry: ['HIPAA', 'PCI-DSS', 'FedRAMP'],
  },
  predict: {
    ethical_ai: ['OECD-AI', 'ISO-42001', 'EU-AI-ACT'],
    cybersecurity: ['NIST-AI-RMF'],
    privacy: ['GDPR', 'HIPAA'],
    governance: ['COSO-ERM', 'SR-11-7'],
    industry: ['BASEL-III', 'IFRS-9', 'SR-11-7'],
  },
  flow: {
    ethical_ai: ['ISO-42001'],
    cybersecurity: ['ZERO-TRUST', 'SOC2', 'NIST-800-53'],
    privacy: ['ISO-27701', 'GDPR'],
    governance: ['ITIL', 'COBIT'],
    industry: ['GxP', 'FedRAMP', 'NERC-CIP'],
  },
  health: {
    ethical_ai: ['ISO-42001'],
    cybersecurity: ['NIST-800-137', 'MITRE-ATT&CK', 'CIS'],
    privacy: ['HIPAA', 'GDPR'],
    governance: ['ISO-20000', 'ISO-9001', 'ITIL'],
    industry: ['NERC-CIP'],
  },
  guard: {
    ethical_ai: ['EU-AI-ACT'],
    cybersecurity: ['NIST-800-53', 'MITRE-ATT&CK', 'ZERO-TRUST', 'ISO-27001', 'SOC2', 'CMMC', 'CIS'],
    privacy: ['GDPR', 'ISO-27701', 'HIPAA', 'PCI-DSS'],
    governance: ['SOC2', 'COBIT'],
    industry: ['CJIS', 'CMMC', 'FedRAMP'],
  },
  ethics: {
    ethical_ai: ['NIST-AI-RMF', 'OECD-AI', 'UNESCO-AI', 'ISO-42001', 'EU-AI-ACT'],
    cybersecurity: ['NIST-800-53'],
    privacy: ['GDPR'],
    governance: ['COSO-ERM'],
    industry: ['GxP', 'CJIS'],
  },
  agents: {
    ethical_ai: ['OECD-AI', 'UNESCO-AI', 'ISO-42001', 'EU-AI-ACT', 'NIST-AI-RMF'],
    cybersecurity: ['NIST-AI-RMF', 'ZERO-TRUST'],
    privacy: ['GDPR'],
    governance: ['ISO-42001'],
    industry: ['SR-11-7'],
  },
};
