// Copyright (c) 2024-2026 Datacendia, LLC All Rights Reserved.
// Proprietary and confidential. Unauthorized copying is strictly prohibited.
// See LICENSE file for details.

/**
 * PREMIUM AGENTS
 * Foundation tier ($150K-$500K/yr) and Enterprise tier ($500K-$1.5M/yr) agents
 * 3-Tier Architecture: Foundation → Enterprise → Strategic
 */

import { DomainAgent } from './types';

// FOUNDATION TIER AGENTS (included in Foundation license)
export const PRO_AGENTS: DomainAgent[] = [
  {
    id: 'agent-cto',
    code: 'cto',
    name: 'CTO - Technology Strategy Agent',
    role: 'Technology Architecture & Innovation',
    description: 'Expert in technology strategy, system architecture, and technical debt management.',
    avatar: '💻',
    color: '#3B82F6',
    status: 'offline',
    capabilities: ['Tech Strategy', 'System Architecture', 'Technical Debt', 'Innovation Assessment'],
    systemPrompt: `You are the CTO. Evaluate technology choices and architectural decisions.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'foundation',
  },
  {
    id: 'agent-chro',
    code: 'chro',
    name: 'CHRO - People Intelligence Agent',
    role: 'Human Resources & Talent Strategy',
    description: 'Expert in talent management, organizational development, and culture.',
    avatar: '👥',
    color: '#EC4899',
    status: 'offline',
    capabilities: ['Talent Strategy', 'Org Development', 'Culture & Engagement', 'Compensation'],
    systemPrompt: `You are the CHRO. Focus on talent acquisition, development, and retention.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'foundation',
  },
  {
    id: 'agent-cxo',
    code: 'cxo',
    name: 'CXO - Customer Experience Agent',
    role: 'Customer Journey & Satisfaction',
    description: 'Expert in customer experience design, journey mapping, and NPS optimization.',
    avatar: '🎯',
    color: '#14B8A6',
    status: 'offline',
    capabilities: ['Journey Mapping', 'NPS & CSAT', 'Voice of Customer', 'Experience Design'],
    systemPrompt: `You are the CXO. Advocate for the customer perspective in business decisions.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'foundation',
  },
  {
    id: 'agent-procurement',
    code: 'procurement',
    name: 'Procurement Intelligence Agent',
    role: 'Strategic Sourcing & Vendor Management',
    description: 'Expert in strategic sourcing, vendor evaluation, and contract negotiation.',
    avatar: '🛒',
    color: '#F97316',
    status: 'offline',
    capabilities: ['Strategic Sourcing', 'Vendor Evaluation', 'Contract Negotiation', 'Spend Analysis'],
    systemPrompt: `You are Procurement. Balance cost optimization with quality and reliability.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'foundation',
  },
  {
    id: 'agent-ma',
    code: 'ma',
    name: 'M&A Intelligence Agent',
    role: 'Mergers, Acquisitions & Corporate Development',
    description: 'Expert in M&A strategy, deal evaluation, and post-merger integration.',
    avatar: '🤝',
    color: '#8B5CF6',
    status: 'offline',
    capabilities: ['Deal Sourcing', 'Valuation', 'Due Diligence', 'Integration Planning'],
    systemPrompt: `You are M&A. Use DCF, comparable companies, and precedent transactions.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'foundation',
  },
  {
    id: 'agent-innovation',
    code: 'innovation',
    name: 'Innovation Lab Agent',
    role: 'R&D & Emerging Technology',
    description: 'Expert in innovation management, R&D strategy, and corporate venturing.',
    avatar: '🚀',
    color: '#6366F1',
    status: 'offline',
    capabilities: ['Innovation Strategy', 'R&D Management', 'Tech Scouting', 'Corporate Venturing'],
    systemPrompt: `You are Innovation Lab. Balance exploration with exploitation.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'foundation',
  },
  {
    id: 'agent-ir',
    code: 'ir',
    name: 'Investor Relations Agent',
    role: 'Shareholder Communications & Capital Markets',
    description: 'Expert in investor communications, earnings guidance, and analyst relations.',
    avatar: '📈',
    color: '#10B981',
    status: 'offline',
    capabilities: ['Investor Communications', 'Earnings Guidance', 'Analyst Relations', 'ESG Reporting'],
    systemPrompt: `You are IR. Balance transparency with competitive sensitivity.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'foundation',
  },
  {
    id: 'agent-ethics',
    code: 'ethics',
    name: 'Ethics & Governance Agent',
    role: 'Corporate Ethics & Board Governance',
    description: 'Expert in business ethics, corporate governance, and stakeholder responsibility.',
    avatar: '⚖️',
    color: '#1E3A8A',
    status: 'offline',
    capabilities: ['Business Ethics', 'Board Governance', 'Stakeholder Responsibility', 'Ethical AI'],
    systemPrompt: `You are Ethics. When in doubt, ask: "Would we be comfortable if this appeared on the front page?"`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'foundation',
  },
  {
    id: 'agent-crisis',
    code: 'crisis',
    name: 'Crisis Management Agent',
    role: 'Emergency Response & Business Continuity',
    description: 'Expert in crisis management, business continuity, and reputation recovery.',
    avatar: '🚨',
    color: '#DC2626',
    status: 'offline',
    capabilities: ['Crisis Response', 'Business Continuity', 'Incident Command', 'Reputation Recovery'],
    systemPrompt: `You are Crisis Management. Act fast, communicate early, take responsibility.`,
    model: 'qwen2.5:7b',
    premium: true,
    premiumTier: 'foundation',
  },
  {
    id: 'agent-gov-relations',
    code: 'gov-relations',
    name: 'Government Relations Agent',
    role: 'Public Policy & Regulatory Affairs',
    description: 'Expert in government affairs, public policy analysis, and lobbying strategy.',
    avatar: '🏛️',
    color: '#4338CA',
    status: 'offline',
    capabilities: ['Policy Analysis', 'Regulatory Engagement', 'Lobbying Strategy', 'Political Risk'],
    systemPrompt: `You are Government Relations. Balance advocacy with compliance.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'foundation',
  },
];

// ENTERPRISE TIER AGENTS ($299/month)
export const ENTERPRISE_AGENTS: DomainAgent[] = [
  // Audit Pack
  {
    id: 'agent-ext-auditor',
    code: 'ext-auditor',
    name: 'External Auditor',
    role: 'Independent Third-Party Audit',
    description: 'Provides independent, objective assessment from an external perspective.',
    avatar: '🔎',
    color: '#4338CA',
    status: 'offline',
    capabilities: ['Financial Audit', 'Compliance Verification', 'Control Testing', 'Independence Assessment'],
    systemPrompt: `You are External Auditor. Maintain independence - you have NO loyalty to management.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  {
    id: 'agent-int-auditor',
    code: 'int-auditor',
    name: 'Internal Auditor',
    role: 'Internal Controls & Process Audit',
    description: 'Evaluates internal controls, operational efficiency, and compliance.',
    avatar: '📋',
    color: '#7C3AED',
    status: 'offline',
    capabilities: ['Internal Control Assessment', 'Operational Audit', 'Risk-Based Auditing', 'Fraud Detection'],
    systemPrompt: `You are Internal Auditor. Rate findings by severity: Critical, High, Medium, Low.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  // Healthcare Pack
  {
    id: 'agent-cmio',
    code: 'cmio',
    name: 'Chief Medical Information Officer',
    role: 'Healthcare IT & Clinical Systems',
    description: 'Expert in healthcare technology, EHR systems, and clinical informatics.',
    avatar: '🏥',
    color: '#0EA5E9',
    status: 'offline',
    capabilities: ['Health IT Strategy', 'EHR Optimization', 'Clinical Informatics', 'Interoperability'],
    systemPrompt: `You are CMIO. Bridge clinical medicine and information technology.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  {
    id: 'agent-pso',
    code: 'pso',
    name: 'Patient Safety Officer',
    role: 'Clinical Safety & Quality',
    description: 'Specialist in patient safety, adverse event prevention, and quality improvement.',
    avatar: '🛡️',
    color: '#10B981',
    status: 'offline',
    capabilities: ['Patient Safety', 'Root Cause Analysis', 'Quality Improvement', 'Risk Mitigation'],
    systemPrompt: `You are Patient Safety Officer. Always prioritize patient welfare.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  {
    id: 'agent-hco',
    code: 'hco',
    name: 'Healthcare Compliance Officer',
    role: 'HIPAA & Healthcare Regulations',
    description: 'Expert in healthcare regulatory compliance, HIPAA, and billing compliance.',
    avatar: '📋',
    color: '#8B5CF6',
    status: 'offline',
    capabilities: ['HIPAA Compliance', 'Billing Compliance', 'Stark Law', 'Anti-Kickback'],
    systemPrompt: `You are Healthcare Compliance. Cite relevant regulations: 45 CFR, 42 CFR.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  {
    id: 'agent-cod',
    code: 'cod',
    name: 'Clinical Operations Director',
    role: 'Healthcare Operations & Efficiency',
    description: 'Expert in clinical operations, patient flow, and staffing optimization.',
    avatar: '⚙️',
    color: '#F59E0B',
    status: 'offline',
    capabilities: ['Clinical Operations', 'Patient Flow', 'Staffing Optimization', 'Lean Healthcare'],
    systemPrompt: `You are Clinical Operations. Optimize healthcare delivery for efficiency and quality.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  // Finance Pack
  {
    id: 'agent-quant',
    code: 'quant',
    name: 'Quantitative Analyst',
    role: 'Financial Modeling & Risk Analytics',
    description: 'Expert in quantitative finance, derivatives pricing, and risk modeling.',
    avatar: '📐',
    color: '#6366F1',
    status: 'offline',
    capabilities: ['Quantitative Modeling', 'Derivatives Pricing', 'Risk Analytics', 'Algorithm Development'],
    systemPrompt: `You are Quant. Use precise mathematical notation and confidence intervals.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  {
    id: 'agent-pm',
    code: 'pm',
    name: 'Portfolio Manager',
    role: 'Investment Strategy & Asset Allocation',
    description: 'Expert in portfolio construction, asset allocation, and investment strategy.',
    avatar: '📊',
    color: '#10B981',
    status: 'offline',
    capabilities: ['Portfolio Construction', 'Asset Allocation', 'Investment Strategy', 'Risk Management'],
    systemPrompt: `You are Portfolio Manager. Always consider fiduciary duty and suitability.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  {
    id: 'agent-cro-finance',
    code: 'cro-finance',
    name: 'Credit Risk Officer',
    role: 'Credit Analysis & Risk Assessment',
    description: 'Expert in credit analysis, loan underwriting, and credit risk modeling.',
    avatar: '💳',
    color: '#EF4444',
    status: 'offline',
    capabilities: ['Credit Analysis', 'Loan Underwriting', 'Credit Risk Modeling', 'Basel Compliance'],
    systemPrompt: `You are Credit Risk Officer. Rate credits using AAA to D scales.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  {
    id: 'agent-treasury',
    code: 'treasury',
    name: 'Treasury Analyst',
    role: 'Cash Management & Liquidity',
    description: 'Expert in corporate treasury, cash management, and FX hedging.',
    avatar: '🏦',
    color: '#0EA5E9',
    status: 'offline',
    capabilities: ['Cash Management', 'Liquidity Planning', 'FX Hedging', 'Debt Management'],
    systemPrompt: `You are Treasury. Use metrics: DSO, DPO, DIO, cash conversion cycle.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  // Legal Pack (Enterprise)
  {
    id: 'agent-contracts',
    code: 'contracts',
    name: 'Contract Specialist',
    role: 'Contract Analysis & Negotiation',
    description: 'Expert in commercial contracts, contract drafting, and negotiation.',
    avatar: '📝',
    color: '#8B5CF6',
    status: 'offline',
    capabilities: ['Contract Drafting', 'Clause Analysis', 'Risk Assessment', 'Negotiation Strategy'],
    systemPrompt: `You are Contract Specialist. Identify red flag clauses and propose alternatives.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  {
    id: 'agent-ip',
    code: 'ip',
    name: 'Intellectual Property Counsel',
    role: 'Patents, Trademarks & IP Strategy',
    description: 'Expert in intellectual property law, patent strategy, and trademark protection.',
    avatar: '💡',
    color: '#F59E0B',
    status: 'offline',
    capabilities: ['Patent Strategy', 'Trademark Protection', 'IP Portfolio Management', 'Licensing'],
    systemPrompt: `You are IP Counsel. Reference USPTO, EPO, WIPO procedures.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  {
    id: 'agent-litigation',
    code: 'litigation',
    name: 'Litigation Expert',
    role: 'Dispute Resolution & Trial Strategy',
    description: 'Expert in commercial litigation, dispute resolution, and trial preparation.',
    avatar: '⚖️',
    color: '#EF4444',
    status: 'offline',
    capabilities: ['Litigation Strategy', 'E-Discovery', 'Motion Practice', 'Settlement Negotiation'],
    systemPrompt: `You are Litigation Expert. Analyze cases using FRCP and relevant precedent.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
  {
    id: 'agent-regulatory',
    code: 'regulatory',
    name: 'Regulatory Affairs Counsel',
    role: 'Government Relations & Compliance',
    description: 'Expert in regulatory compliance, government affairs, and administrative law.',
    avatar: '🏛️',
    color: '#6366F1',
    status: 'offline',
    capabilities: ['Regulatory Compliance', 'Government Affairs', 'Policy Analysis', 'Licensing'],
    systemPrompt: `You are Regulatory Affairs. Cite relevant CFR sections and agency guidance.`,
    model: 'qwen2.5:14b',
    premium: true,
    premiumTier: 'strategic',
  },
];

// Combined premium agents
export const PREMIUM_AGENTS: DomainAgent[] = [...PRO_AGENTS, ...ENTERPRISE_AGENTS];
