// Copyright (c) 2024-2026 Datacendia, LLC All Rights Reserved.
// Proprietary and confidential. Unauthorized copying is strictly prohibited.
// See LICENSE file for details.

// =============================================================================
// TECH TEAM PANEL
// UI for monitoring and controlling the AI Tech Team
// =============================================================================

import React, { useState, useEffect, useCallback } from 'react';
import {
  Users,
  AlertTriangle,
  CheckCircle,
  Clock,
  Zap,
  Settings,
  Play,
  Pause,
  RefreshCw,
  ChevronDown,
  ChevronRight,
  Code,
  Bug,
  Shield,
  Database,
  Cpu,
  FileText,
  Brain,
  Rocket,
  Eye,
  Terminal,
  Loader2,
} from 'lucide-react';
import {
  TECH_TEAM_AGENTS,
  TechTeamConfig,
  ErrorAnalysis,
  FixSuggestion,
} from '../../lib/agents/techTeam';
import { AutoHealService } from '../../services/AutoHealService';

// =============================================================================
// TECH TEAM DASHBOARD
// =============================================================================

export const TechTeamPanel: React.FC = () => {
  const [isExpanded, setIsExpanded] = useState(false);
  const [activeTab, setActiveTab] = useState<'team' | 'errors' | 'fixes' | 'settings'>('team');
  const [config, setConfig] = useState<TechTeamConfig>(AutoHealService.getConfig());
  const [errors, setErrors] = useState<ErrorAnalysis[]>([]);
  const [fixes, setFixes] = useState<FixSuggestion[]>([]);
  const [stats, setStats] = useState(AutoHealService.getStats());
  const [loadingFixes, setLoadingFixes] = useState<Set<string>>(new Set());
  const [notification, setNotification] = useState<string | null>(null);

  useEffect(() => {
    // Subscribe to errors
    const unsubscribe = AutoHealService.onError((error) => {
      setErrors(AutoHealService.getErrorQueue());
      setStats(AutoHealService.getStats());
    });

    // Listen for fix-generated events
    const handleFixGenerated = (event: CustomEvent<FixSuggestion>) => {
      setFixes(AutoHealService.getFixHistory());
      setStats(AutoHealService.getStats());
      setNotification(`Fix generated by ${event.detail.agentCode}`);
      setTimeout(() => setNotification(null), 3000);
      // Switch to fixes tab to show the new fix
      setActiveTab('fixes');
    };

    window.addEventListener('autoheal:fix-generated', handleFixGenerated as EventListener);

    // Initial load
    setErrors(AutoHealService.getErrorQueue());
    setFixes(AutoHealService.getFixHistory());

    // Poll for updates
    const interval = setInterval(() => {
      setErrors(AutoHealService.getErrorQueue());
      setFixes(AutoHealService.getFixHistory());
      setStats(AutoHealService.getStats());
    }, 2000);

    return () => {
      unsubscribe();
      clearInterval(interval);
      window.removeEventListener('autoheal:fix-generated', handleFixGenerated as EventListener);
    };
  }, []);

  const handleConfigChange = (updates: Partial<TechTeamConfig>) => {
    AutoHealService.updateConfig(updates);
    setConfig(AutoHealService.getConfig());
  };

  // Handle requesting a fix with loading state
  const handleRequestFix = useCallback(
    async (errorId: string) => {
      if (loadingFixes.has(errorId)) {return;} // Already loading

      setLoadingFixes((prev) => new Set(prev).add(errorId));
      setNotification('Generating fix...');

      try {
        const fix = await AutoHealService.requestFix(errorId);
        if (!fix) {
          const reason = AutoHealService.lastGenerateError || 'Unknown error';
          setNotification(`Failed to generate fix - ${reason}`);
          setTimeout(() => setNotification(null), 5000);
        }
        // Success notification is handled by the event listener
      } catch (e) {
        console.error('[TechTeamPanel] Fix request failed:', e);
        setNotification('Fix request failed');
        setTimeout(() => setNotification(null), 3000);
      } finally {
        setLoadingFixes((prev) => {
          const next = new Set(prev);
          next.delete(errorId);
          return next;
        });
      }
    },
    [loadingFixes]
  );

  const getAgentIcon = (code: string) => {
    const icons: Record<string, React.ReactNode> = {
      'dev-lead': <Users size={16} />,
      frontend: <Code size={16} />,
      backend: <Database size={16} />,
      fullstack: <RefreshCw size={16} />,
      devops: <Rocket size={16} />,
      sre: <AlertTriangle size={16} />,
      dba: <Database size={16} />,
      'qa-lead': <Eye size={16} />,
      'test-auto': <Bug size={16} />,
      'security-eng': <Shield size={16} />,
      'ai-ml-eng': <Brain size={16} />,
      'perf-eng': <Zap size={16} />,
      docs: <FileText size={16} />,
    };
    return icons[code] || <Cpu size={16} />;
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical':
        return 'bg-red-500';
      case 'high':
        return 'bg-orange-500';
      case 'medium':
        return 'bg-yellow-500';
      case 'low':
        return 'bg-blue-500';
      default:
        return 'bg-gray-500';
    }
  };

  if (!isExpanded) {
    return (
      <button
        onClick={() => setIsExpanded(true)}
        className="fixed bottom-4 left-4 z-50 flex items-center gap-2 px-4 py-2 bg-slate-800 text-white rounded-lg shadow-lg hover:bg-slate-700 transition-colors"
      >
        <Terminal size={18} />
        <span className="font-medium">Tech Team</span>
        {errors.length > 0 && (
          <span className="flex items-center justify-center w-5 h-5 bg-red-500 rounded-full text-xs font-bold">
            {errors.length}
          </span>
        )}
      </button>
    );
  }

  return (
    <div className="fixed bottom-4 left-4 z-50 w-[480px] max-h-[600px] bg-slate-900 rounded-xl shadow-2xl border border-slate-700 overflow-hidden flex flex-col">
      {/* Header */}
      <div className="px-4 py-3 bg-slate-800 border-b border-slate-700 flex items-center justify-between">
        <div className="flex items-center gap-3 group">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center">
            <Terminal size={18} className="text-white" />
          </div>
          <div>
            <h3 className="font-semibold text-white">AI Tech Team</h3>
            <p className="text-xs text-slate-400">
              {TECH_TEAM_AGENTS.length} agents • Auto-heal {config.autoHealEnabled ? 'ON' : 'OFF'}
            </p>
            <p className="text-[10px] text-slate-500 hidden group-hover:block max-w-[280px]">
              Engineering agents that monitor, diagnose, and propose fixes across the Datacendia
              stack.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => handleConfigChange({ autoHealEnabled: !config.autoHealEnabled })}
            className={`p-2 rounded-lg transition-colors ${config.autoHealEnabled ? 'bg-green-500/20 text-green-400' : 'bg-slate-700 text-slate-400'}`}
            title={config.autoHealEnabled ? 'Disable Auto-Heal' : 'Enable Auto-Heal'}
          >
            {config.autoHealEnabled ? <Play size={16} /> : <Pause size={16} />}
          </button>
          <button
            onClick={() => setIsExpanded(false)}
            className="p-2 rounded-lg bg-slate-700 text-slate-400 hover:text-white transition-colors"
          >
            <ChevronDown size={16} />
          </button>
        </div>
      </div>

      {/* Notification Toast */}
      {notification && (
        <div className="px-4 py-2 bg-cyan-500/20 border-b border-cyan-500/30 text-cyan-400 text-xs font-medium flex items-center gap-2">
          <Loader2
            size={12}
            className={notification.includes('Generating') ? 'animate-spin' : 'hidden'}
          />
          <CheckCircle size={12} className={notification.includes('generated') ? '' : 'hidden'} />
          <AlertTriangle
            size={12}
            className={
              notification.includes('Failed') || notification.includes('failed') ? '' : 'hidden'
            }
          />
          {notification}
        </div>
      )}

      {/* Stats Bar */}
      <div className="px-4 py-2 bg-slate-800/50 border-b border-slate-700/50 flex items-center gap-4 text-xs">
        <div className="flex items-center gap-1.5">
          <div
            className={`w-2 h-2 rounded-full ${stats.isProcessing || loadingFixes.size > 0 ? 'bg-green-500 animate-pulse' : 'bg-slate-500'}`}
          />
          <span className="text-slate-400">
            {stats.isProcessing || loadingFixes.size > 0 ? 'Processing' : 'Idle'}
          </span>
        </div>
        <div className="flex items-center gap-1.5 text-slate-400">
          <AlertTriangle size={12} />
          <span>{stats.errorsInQueue} in queue</span>
        </div>
        <div className="flex items-center gap-1.5 text-slate-400">
          <CheckCircle size={12} />
          <span>{stats.fixesApplied} fixed</span>
        </div>
        <div className="flex items-center gap-1.5 text-slate-400">
          <Clock size={12} />
          <span>{stats.fixesThisHour}/hr</span>
        </div>
      </div>

      {/* Tabs */}
      <div className="px-4 py-2 border-b border-slate-700/50 flex gap-1">
        {(['team', 'errors', 'fixes', 'settings'] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
              activeTab === tab
                ? 'bg-cyan-500/20 text-cyan-400'
                : 'text-slate-400 hover:text-white hover:bg-slate-700/50'
            }`}
          >
            {tab.charAt(0).toUpperCase() + tab.slice(1)}
            {tab === 'errors' && errors.length > 0 && (
              <span className="ml-1.5 px-1.5 py-0.5 bg-red-500 rounded text-xs text-white">
                {errors.length}
              </span>
            )}
          </button>
        ))}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4">
        {activeTab === 'team' && (
          <div className="space-y-2">
            {TECH_TEAM_AGENTS.map((agent) => (
              <div
                key={agent.id}
                className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div
                    className="w-8 h-8 rounded-lg flex items-center justify-center"
                    style={{ backgroundColor: `${agent.color}20`, color: agent.color }}
                  >
                    {getAgentIcon(agent.code)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-white text-sm">{agent.name}</span>
                      <span className="text-xs text-slate-500">{agent.code}</span>
                    </div>
                    <p className="text-xs text-slate-400 truncate">{agent.role}</p>
                  </div>
                  <div className="text-xs text-slate-500">{agent.model.split(':')[0]}</div>
                </div>
              </div>
            ))}
          </div>
        )}

        {activeTab === 'errors' && (
          <div className="space-y-2">
            {errors.length === 0 ? (
              <div className="text-center py-8 text-slate-400">
                <CheckCircle size={32} className="mx-auto mb-2 text-green-500" />
                <p>No errors in queue</p>
              </div>
            ) : (
              errors.map((error) => (
                <div
                  key={error.id}
                  className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50"
                >
                  <div className="flex items-start gap-3">
                    <div
                      className={`w-2 h-2 rounded-full mt-1.5 ${getSeverityColor(error.severity)}`}
                    />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm text-white font-medium truncate">
                        {error.message.substring(0, 80)}
                      </p>
                      <p className="text-xs text-slate-400 mt-1">
                        {error.file}:{error.line}
                      </p>
                      <div className="flex items-center gap-2 mt-2">
                        <span className="text-xs px-2 py-0.5 rounded bg-slate-700 text-slate-300">
                          {error.assignedAgent}
                        </span>
                        <span className="text-xs text-slate-500">
                          {new Date(error.timestamp).toLocaleTimeString()}
                        </span>
                      </div>
                    </div>
                    <button
                      onClick={() => handleRequestFix(error.id)}
                      disabled={loadingFixes.has(error.id)}
                      className={`px-3 py-1.5 rounded text-xs font-medium transition-colors flex items-center gap-1.5 ${
                        loadingFixes.has(error.id)
                          ? 'bg-cyan-500/10 text-cyan-400/50 cursor-wait'
                          : 'bg-cyan-500/20 text-cyan-400 hover:bg-cyan-500/30'
                      }`}
                    >
                      {loadingFixes.has(error.id) ? (
                        <>
                          <Loader2 size={12} className="animate-spin" />
                          Fixing...
                        </>
                      ) : (
                        'Fix'
                      )}
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        )}

        {activeTab === 'fixes' && (
          <div className="space-y-2">
            {fixes.length === 0 ? (
              <div className="text-center py-8 text-slate-400">
                <FileText size={32} className="mx-auto mb-2" />
                <p>No fixes generated yet</p>
              </div>
            ) : (
              fixes
                .slice()
                .reverse()
                .map((fix) => (
                  <div
                    key={fix.id}
                    className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50"
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <p className="text-sm text-white">{fix.description.substring(0, 100)}</p>
                        <div className="flex items-center gap-2 mt-2 flex-wrap">
                          <span className="text-xs px-2 py-0.5 rounded bg-slate-700 text-slate-300">
                            {fix.agentCode}
                          </span>
                          <span
                            className={`text-xs px-2 py-0.5 rounded ${
                              fix.riskLevel === 'safe'
                                ? 'bg-green-500/20 text-green-400'
                                : fix.riskLevel === 'moderate'
                                  ? 'bg-yellow-500/20 text-yellow-400'
                                  : 'bg-red-500/20 text-red-400'
                            }`}
                          >
                            {fix.riskLevel}
                          </span>
                          <span className="text-xs text-slate-500">
                            {Math.round(fix.confidence * 100)}% confidence
                          </span>
                          <button
                            onClick={() =>
                              window.open(
                                `/cortex/intelligence/chronos?timestamp=${new Date((fix as any).timestamp || Date.now()).toISOString()}`,
                                '_blank'
                              )
                            }
                            className="text-[10px] px-1.5 py-0.5 rounded bg-cyan-500/10 text-cyan-400 hover:bg-cyan-500/20 transition-colors"
                            title="View when this error occurred in Chronos"
                          >
                            ⏱️ View in Chronos
                          </button>
                        </div>
                      </div>
                      {fix.requiresReview && (
                        <button
                          onClick={() => AutoHealService.approveFix(fix.id)}
                          className="px-2 py-1 rounded bg-green-500/20 text-green-400 text-xs hover:bg-green-500/30 transition-colors"
                        >
                          Approve
                        </button>
                      )}
                    </div>
                  </div>
                ))
            )}
          </div>
        )}

        {activeTab === 'settings' && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-white">Auto-Heal Enabled</p>
                <p className="text-xs text-slate-400">Automatically process and fix errors</p>
                <p className="text-[10px] text-amber-400/70 mt-0.5">
                  ⚠️ In sovereign mode, auto-heal remains off unless explicitly enabled
                </p>
              </div>
              <button
                onClick={() => handleConfigChange({ autoHealEnabled: !config.autoHealEnabled })}
                className={`w-12 h-6 rounded-full transition-colors ${config.autoHealEnabled ? 'bg-cyan-500' : 'bg-slate-600'}`}
              >
                <div
                  className={`w-5 h-5 rounded-full bg-white shadow transition-transform ${config.autoHealEnabled ? 'translate-x-6' : 'translate-x-0.5'}`}
                />
              </button>
            </div>

            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-white">Require Approval</p>
                <p className="text-xs text-slate-400">Review fixes before applying</p>
              </div>
              <button
                onClick={() => handleConfigChange({ requireApproval: !config.requireApproval })}
                className={`w-12 h-6 rounded-full transition-colors ${config.requireApproval ? 'bg-cyan-500' : 'bg-slate-600'}`}
              >
                <div
                  className={`w-5 h-5 rounded-full bg-white shadow transition-transform ${config.requireApproval ? 'translate-x-6' : 'translate-x-0.5'}`}
                />
              </button>
            </div>

            <div>
              <p className="text-sm font-medium text-white mb-2">Auto-Fix Severity Threshold</p>
              <div className="flex gap-2">
                {(['critical', 'high', 'medium', 'all'] as const).map((level) => (
                  <button
                    key={level}
                    onClick={() => handleConfigChange({ autoFixSeverity: level })}
                    className={`px-3 py-1.5 rounded text-xs font-medium transition-colors ${
                      config.autoFixSeverity === level
                        ? 'bg-cyan-500 text-white'
                        : 'bg-slate-700 text-slate-300 hover:bg-slate-600'
                    }`}
                  >
                    {level}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <p className="text-sm font-medium text-white mb-2">Max Fixes Per Hour</p>
              <input
                type="range"
                min="1"
                max="50"
                value={config.maxAutoFixesPerHour}
                onChange={(e) =>
                  handleConfigChange({ maxAutoFixesPerHour: parseInt(e.target.value) })
                }
                className="w-full"
              />
              <p className="text-xs text-slate-400 mt-1">{config.maxAutoFixesPerHour} fixes/hour</p>
            </div>

            <button
              onClick={() => AutoHealService.clearQueue()}
              className="w-full py-2 rounded-lg bg-red-500/20 text-red-400 text-sm font-medium hover:bg-red-500/30 transition-colors"
            >
              Clear Error Queue
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default TechTeamPanel;
