/**
 * Club Alianza Lima — Spanish Scenarios
 * @module pages/sandbox/configs/alianza-lima-es
 */

// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.

import type { TemplateScenario } from '../SandboxTemplate';

export const ES_SCENARIOS: TemplateScenario[] = [
  // ESCENARIO 1 — ESCÁNDALO DE CONDUCTA
  {
    id: 'player-conduct',
    title: 'Escándalo de Conducta — Gobernanza Disciplinaria y Procedimientos Penales',
    subtitle: 'Zambrano, Trauco, Peña · Tribunal FPF · Ministerio Público · Ley 30364 · Debido proceso',
    banner: 'Simulando la gobernanza disciplinaria de la crisis de conducta 2024. Tres jugadores del primer equipo acusados de presunto abuso sexual — la IA gobierna decisiones de suspensión, investigación y reintegración con evidencia de debido proceso para el Tribunal FPF, Ministerio Público y rendición de cuentas ante socios.',
    risk: 'Crítico',
    scenarioNum: 'Conducta',
    icon: 'shield-alert',
    color: 'text-red-400',
    agents: [
      { id: 'disciplinary', name: 'Agente Disciplinario', role: 'Reglamento FPF y Proceso Interno', icon: '⚖️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'legal-criminal', name: 'Agente de Derecho Penal', role: 'Código Penal y Ministerio Público', icon: '🏛️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'safeguarding', name: 'Agente de Salvaguarda', role: 'Protección de Víctimas y Ley 30364', icon: '🛡️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'reputation', name: 'Agente de Integridad Institucional', role: 'Socios y Rendición de Cuentas', icon: '📋', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Tribunal FPF', status: 'connected', type: 'Disciplinario', icon: 'scale', detail: 'Reglamento Disciplinario — procedimientos activos para 3 jugadores' },
      { name: 'Ministerio Público', status: 'connected', type: 'Penal', icon: 'landmark', detail: 'Investigación de la Fiscalía — preservación de evidencia crítica' },
      { name: 'Registro Ley 30364', status: 'connected', type: 'Protección', icon: 'shield', detail: 'Violencia contra la mujer — medidas de protección vigentes' },
      { name: 'Portal de Socios', status: 'syncing', type: 'Gobernanza', icon: 'users', detail: 'Comunicación a socios — obligación de transparencia activa' },
    ],
    script: [
      { agentId: 'disciplinary', phase: 'phase1', type: 'warning', delay: 800, content: 'GOBERNANZA DISCIPLINARIA — CRISIS DE CONDUCTA. Tres jugadores suspendidos bajo el Reglamento Disciplinario FPF Art. 45-52 tras acusaciones de abuso sexual. Día 12 de investigación del plazo de 30 días FPF. Cada jugador ha contratado abogado separado. Cada decisión — suspensión, hallazgos, audiencias, reintegración — debe sellarse con evidencia criptográfica.' },
      { agentId: 'legal-criminal', phase: 'phase1', type: 'analysis', delay: 2500, content: 'DERECHO PENAL. La Fiscalía abrió investigación preliminar bajo Código Penal Art. 170-174 (penas de 6-12 años). Medidas de protección Ley 30364 emitidas. El club debe preservar TODA evidencia (CCTV, comunicaciones, registros de acceso) — destrucción = obstrucción (Art. 405). Los procedimientos FPF y penales corren en paralelo. Absolución penal NO impide sanción FPF.' },
      { agentId: 'safeguarding', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISIDENCIA — FALTA ENFOQUE CENTRADO EN LA VÍCTIMA. El proceso actual se centra en los jugadores. Pero la Ley 30364 requiere: (1) ¿El club contactó a la denunciante para ofrecer apoyo? No. (2) ¿Evaluación de riesgo de contacto indirecto a través de compañeros, agentes, hinchas? No. Mi disidencia: el club debe documentar apoyo a la denunciante — éticamente requerido y legalmente defendible.' },
      { agentId: 'reputation', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — RENDICIÓN DE CUENTAS. (1) Socios exigen transparencia — solo UN comunicado emitido. Insuficiente para un club de socios. (2) 3 patrocinadores solicitan reuniones — patrocinador de apuestas tiene cláusula de daño reputacional (PEN 1.8M/año en riesgo). (3) Equipo femenino planteó preocupación interna — Ley 30901 de igualdad de género. (4) Impacto comunitario en La Victoria. (5) No existía plan de comunicación de crisis.' },
      { agentId: 'disciplinary', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo de Gobernanza de Conducta: (1) DEBIDO PROCESO: Cronología día a día. Audiencias Días 20-25. Paquetes de evidencia por jugador. (2) APOYO A VÍCTIMA (aceptando disidencia): Oficial de bienestar independiente contacta a la denunciante. (3) EVIDENCIA: Todo sellado con marcas de tiempo. (4) SOCIOS: Actualizaciones semanales. Plan de comunicación de crisis. (5) PATROCINADORES: Reuniones documentadas. (6) TRIBUNAL FPF: Expediente completo. ML-DSA-65.' },
      { agentId: 'safeguarding', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISIDENCIA RETIRADA. El apoyo a la víctima mediante oficial de bienestar independiente aborda la brecha. Para la Fiscalía: el club preservó evidencia Y apoyó a la denunciante. La identidad de Alianza Lima como club de La Victoria significa que esta respuesta de gobernanza define a la institución.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:al10123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'al20123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (Disciplinario + Penal + Apoyo a víctima + Evidencia + Socios)',
      complianceLabel: 'Gobernanza de Conducta',
      complianceValue: 'INVESTIGACIÓN ACTIVA — DÍA 12',
      complianceThreshold: 'Plazo FPF 30 días · Protección Ley 30364',
      agents: ['Agente Disciplinario', 'Agente de Derecho Penal', 'Agente de Salvaguarda', 'Agente de Integridad Institucional'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Alianza Lima — Gobernanza de Conducta',
      guaranteeBody: 'Sella: proceso disciplinario de 3 jugadores, preservación de evidencia Fiscalía, apoyo a víctima Ley 30364, transparencia ante socios, gestión de patrocinadores, expediente Tribunal FPF.',
      evidenceChain: 'Incidente → Suspensión → Preservación de evidencia → Fiscalía → Apoyo a víctima → Audiencias → Tribunal FPF → Socios → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobernarán la crisis de conducta de Alianza Lima — debido proceso, respuesta centrada en la víctima, preservación de evidencia y rendición de cuentas institucional.',
    phaseLabels: ['Investigación y Coordinación Penal', 'Apoyo a Víctima y Rendición de Cuentas', 'Protocolo de Gobernanza'],
  },

  // ESCENARIO 2 — EL CLÁSICO
  {
    id: 'clasico-governance',
    title: 'El Clásico — Seguridad e Integridad del Mayor Partido del Perú',
    subtitle: 'Alianza vs Universitario · Matute 35.000 · Integridad de apuestas · Coordinación PNP',
    banner: 'Simulando la gobernanza del día de partido para El Clásico del fútbol peruano en Matute — el partido de mayor seguridad en Perú. La IA coordina monitoreo de apuestas Sportradar, despliegue policial PNP, gestión de multitudes y protocolos arbitrales.',
    risk: 'Alto',
    scenarioNum: 'Clásico',
    icon: 'shield',
    color: 'text-amber-400',
    agents: [
      { id: 'match-integrity', name: 'Agente de Integridad', role: 'Monitoreo de Apuestas y Sportradar', icon: '🎯', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'security-clasico', name: 'Agente de Seguridad', role: 'Coordinación PNP y Control de Multitudes', icon: '🔒', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'venue-matute', name: 'Agente de Recinto', role: 'Operaciones Matute e INDECI', icon: '🏟️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'referee-liaison', name: 'Agente de Enlace Arbitral', role: 'Árbitros FPF y VAR', icon: '📋', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Sportradar', status: 'connected', type: 'Integridad', icon: 'bar-chart', detail: 'El Clásico — $4.2M volumen estimado de apuestas global' },
      { name: 'Comando PNP', status: 'connected', type: 'Policía', icon: 'shield', detail: '800+ efectivos — coordinación Prefectura de Lima' },
      { name: 'Portal INDECI', status: 'connected', type: 'Seguridad', icon: 'check-circle', detail: 'Matute 35.000 — plan de evacuación certificado' },
      { name: 'Centro de Partido FPF', status: 'syncing', type: 'Árbitros', icon: 'users', detail: 'Designación arbitral — notificación 72h antes del partido' },
    ],
    script: [
      { agentId: 'match-integrity', phase: 'phase1', type: 'warning', delay: 800, content: 'ALERTA DE INTEGRIDAD. Monitoreo Sportradar: El Clásico genera ~$4.2M en apuestas globales. Alerta pre-partido: patrón inusual en hándicap asiático — dinero significativo en Alianza +1.5 desde cuentas del sudeste asiático. No confirma amaño pero activa notificación al oficial de integridad FPF y monitoreo reforzado.' },
      { agentId: 'security-clasico', phase: 'phase1', type: 'analysis', delay: 2500, content: 'EVALUACIÓN DE SEGURIDAD. PNP: 800 efectivos (mayor asignación doméstica). Externo 400, interno 200, escolta visitante 200. Hinchas de Universitario: Sector Norte (5.000), entrada segregada. Historial: 2023 — 12 arrestos, 3 heridos PNP, 2 pirotécnicos. 2024 — 8 arrestos. Barrio La Victoria genera desafíos pre/post-partido. Amenazas entre barras bravas detectadas en redes sociales.' },
      { agentId: 'venue-matute', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISIDENCIA — CAPACIDAD. Más de 50.000 solicitudes para 35.000 lugares. Último Clásico: 37.200 adentro (2.200 sobre capacidad) — INDECI registró violación. Torniquetes: 28 de 32 operativos. Médicos: 5 de 7 requeridos. Calles angostas de La Victoria limitan evacuación. Mi disidencia: operar a 30.000 de capacidad reducida. Impacto en ingresos ~PEN 200K pero corrige la brecha de seguridad.' },
      { agentId: 'referee-liaison', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — GOBERNANZA ARBITRAL. Árbitro designado: 3 Clásicos previos (2 rojas generaron debate mediático). Sala VAR: última inspección hace 6 meses — re-inspección recomendada. CRÍTICO: la alerta de apuestas NO debe compartirse con el árbitro — pero el oficial de integridad FPF debe estar en Matute con feed de Sportradar en vivo.' },
      { agentId: 'match-integrity', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo El Clásico: (1) INTEGRIDAD: Oficial FPF con Sportradar en vivo. Alerta documentada pero NO compartida con árbitro/equipos. (2) SEGURIDAD: PNP 800 confirmados. Monitoreo de redes. (3) CAPACIDAD (aceptando disidencia): 32.000 reducida. Detección de entradas falsas. 2 puntos médicos adicionales. (4) ÁRBITRO: VAR re-inspeccionado. Escolta PNP. (5) INDECI: Plan de evacuación actualizado. Todo sellado para FPF, PNP, INDECI, Sportradar.' },
      { agentId: 'venue-matute', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISIDENCIA RETIRADA. 32.000 de capacidad corrige las limitaciones de torniquetes y evacuación. Impacto en ingresos justificado por la gobernanza de seguridad. Para FPF: monitoreo de integridad como estándar de oro. Para socios: la seguridad prevalece sobre la presión comercial — incluso para el partido más grande del Perú.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:al30123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'al40123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (Integridad + PNP + Capacidad Matute + INDECI + Árbitro + VAR)',
      complianceLabel: 'Integridad del Partido',
      complianceValue: 'ALERTA DE APUESTAS — MONITOREO REFORZADO',
      complianceThreshold: 'Protocolo integridad FPF · Umbral Sportradar',
      agents: ['Agente de Integridad', 'Agente de Seguridad', 'Agente de Recinto', 'Agente de Enlace Arbitral'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Alianza Lima — Gobernanza del Clásico',
      guaranteeBody: 'Sella: alerta Sportradar, despliegue PNP 800 efectivos, Matute reducido a 32.000, escolta arbitral, re-inspección VAR, evacuación INDECI.',
      evidenceChain: 'Sportradar → Integridad FPF → Briefing PNP → Reducción capacidad → Médicos → Árbitro → Monitoreo → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobiernan El Clásico — coordinando integridad de apuestas, seguridad policial, seguridad del recinto y protocolos arbitrales.',
    phaseLabels: ['Integridad y Seguridad', 'Capacidad y Gobernanza Arbitral', 'Protocolo del Día de Partido'],
  },

  // ESCENARIO 3 — REMODELACIÓN DE MATUTE
  {
    id: 'matute-redevelopment',
    title: 'Remodelación de Matute — Modernización del Estadio Histórico',
    subtitle: 'Estadio Alejandro Villanueva · Brechas CONMEBOL · PEN 45M · Patrimonio · Votación socios',
    banner: 'Simulando la gobernanza de remodelación de Matute — el hogar histórico de Alianza Lima en La Victoria. Viabilidad asistida por IA, certificación CONMEBOL, financiación y aprobación de socios producen evidencia auditable.',
    risk: 'Alto',
    scenarioNum: 'Estadio',
    icon: 'building',
    color: 'text-blue-400',
    agents: [
      { id: 'venue-redev', name: 'Agente de Desarrollo', role: 'Estándares CONMEBOL y Viabilidad', icon: '🏟️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'financial-redev', name: 'Agente Financiero', role: 'Modelado de Costos y Financiación', icon: '💰', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'heritage-gov', name: 'Agente de Patrimonio', role: 'Identidad de La Victoria', icon: '🏛️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'socios-redev', name: 'Agente de Socios', role: 'Aprobación y Transparencia', icon: '📋', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'CONMEBOL Recintos', status: 'connected', type: 'Certificación', icon: 'check-circle', detail: '8 ítems bajo estándar Copa Libertadores' },
      { name: 'Municipalidad de Lima', status: 'connected', type: 'Planificación', icon: 'landmark', detail: 'Distrito La Victoria — zonificación y permisos' },
      { name: 'Modelo Financiero', status: 'connected', type: 'Viabilidad', icon: 'database', detail: 'Estimación PEN 45M — 3 escenarios modelados' },
      { name: 'Asamblea de Socios', status: 'syncing', type: 'Gobernanza', icon: 'users', detail: 'Asamblea extraordinaria — mayoría de 2/3 requerida' },
    ],
    script: [
      { agentId: 'venue-redev', phase: 'phase1', type: 'warning', delay: 800, content: 'ANÁLISIS DE BRECHAS MATUTE. 8 incumplimientos Copa Libertadores: (1) 4.000 espacios de pie→sentados. (2) Iluminación 1.200 vs 1.400 lux requeridos. (3) Prensa 120 vs 200 posiciones. (4) Hospitalidad bajo mínimo CONMEBOL. (5) Clima sala VAR insuficiente. (6) Drenaje de 25 años. (7) Vestuario visitante bajo estándar. (8) Discapacidad: 45 vs 100 sillas de ruedas (también CONADIS Ley 29973). Costo estimado: PEN 45M.' },
      { agentId: 'financial-redev', phase: 'phase1', type: 'analysis', delay: 2500, content: 'TRES ESCENARIOS. (1) Autofinanciado: PEN 45M de reservas + ingresos. 5 años. Recorta presupuesto de fichajes. (2) Banco: préstamo PEN 30M al ~12%, PEN 15M club. Deuda PEN 540K/mes por 7 años — excede superávit mensual de PEN 400K. (3) APP: Municipalidad + inversor privado. Club aporta derechos de uso. Inversor construye. Club retiene propiedad pero comparte ingresos comerciales 15 años. Todos requieren 2/3 de socios para gastos sobre PEN 5M.' },
      { agentId: 'heritage-gov', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISIDENCIA — PATRIMONIO. Matute es el corazón de La Victoria desde 1974. (1) Cambios de carácter externo arriesgan rechazo comunitario. (2) Consulta a La Victoria debería realizarse. (3) Riesgo APP: inversor privado controlando espacios comerciales 15 años puede diluir identidad obrera con hospitalidad corporativa que excluye a hinchas locales. Mi disidencia: Evaluación de Impacto Patrimonial, consulta comunitaria y garantías de acceso asequible al 30% de butacas.' },
      { agentId: 'socios-redev', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — REQUISITOS DE SOCIOS. Estatutos: mayoría de 2/3 requerida. ~40.000 socios, quórum 10% (4.000), necesitan 2.667 votos. Información 30 días antes. Votos previos: 2019 PEN 8M (78%), 2021 PEN 3M (85%). PEN 45M es sin precedentes — la mayor decisión de capital en la historia del club. Riesgo: si se rechaza, Matute queda bajo estándar CONMEBOL amenazando Copa.' },
      { agentId: 'venue-redev', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Matute: (1) POR FASES: Fase 1 (PEN 12M, Año 1) — iluminación, VAR, drenaje = certificación Copa básica. Fase 2 (PEN 18M, Año 2-3) — butacas, prensa, discapacidad. Fase 3 (PEN 15M, Año 3-5) — hospitalidad, exterior sensible al patrimonio. (2) PATRIMONIO (aceptando disidencia): Evaluación de impacto. Consulta La Victoria. Garantía 30% acceso asequible en resolución de socios. (3) Cada fase aprobada separadamente por socios. Todo sellado.' },
      { agentId: 'heritage-gov', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISIDENCIA RETIRADA. Evaluación patrimonial y acceso asequible al 30% aseguran que Matute siga accesible para la comunidad obrera de La Victoria. Enfoque por fases es prudente. Matute es la catedral de La Victoria — la renovación honra tanto estándares CONMEBOL como identidad comunitaria.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:al50123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'al60123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (Brechas CONMEBOL + Viabilidad + Patrimonio + Socios + Fases)',
      complianceLabel: 'Remodelación del Estadio',
      complianceValue: 'PLAN PEN 45M EN 3 FASES',
      complianceThreshold: 'Certificación CONMEBOL · Mayoría 2/3 socios',
      agents: ['Agente de Desarrollo', 'Agente Financiero', 'Agente de Patrimonio', 'Agente de Socios'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Alianza Lima — Remodelación de Matute',
      guaranteeBody: 'Sella: análisis de 8 brechas CONMEBOL, plan PEN 45M por fases, Evaluación de Impacto Patrimonial, consulta La Victoria, gobernanza de socios.',
      evidenceChain: 'Brechas CONMEBOL → Viabilidad → Patrimonio → Consulta comunitaria → Info socios → Asamblea → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobiernan la modernización de Matute — requisitos CONMEBOL, protección patrimonial, viabilidad financiera y democracia de socios.',
    phaseLabels: ['Brechas CONMEBOL y Viabilidad', 'Patrimonio y Socios', 'Protocolo de Renovación por Fases'],
  },

  // ESCENARIO 4 — SALVAGUARDA JUVENIL LA VICTORIA
  {
    id: 'youth-la-victoria',
    title: 'Academia Juvenil — Salvaguarda en el Barrio de La Victoria',
    subtitle: 'Comunidad obrera · Cumplimiento CNA · Seguridad de traslado · Escrutinio post-escándalo',
    banner: 'Simulando la salvaguarda juvenil en La Victoria — distrito obrero de Lima donde opera la academia de Alianza. Post-escándalo de conducta, cada decisión de salvaguarda lleva escrutinio institucional elevado.',
    risk: 'Alto',
    scenarioNum: 'Juvenil',
    icon: 'users',
    color: 'text-emerald-400',
    agents: [
      { id: 'youth-victoria', name: 'Agente de Salvaguarda Juvenil', role: 'Cumplimiento CNA y La Victoria', icon: '👦', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'community-safety', name: 'Agente de Seguridad Comunitaria', role: 'Riesgo del Barrio y Traslado', icon: '🛡️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'education-al', name: 'Agente de Educación', role: 'Coordinación Escolar', icon: '📚', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'welfare-al', name: 'Agente de Bienestar', role: 'Salud Física y Mental', icon: '💚', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'Registro Juvenil FPF', status: 'connected', type: 'Registro', icon: 'database', detail: '38 jugadores de academia de 12-17 años' },
      { name: 'Portal MINEDU', status: 'connected', type: 'Educación', icon: 'book-open', detail: 'Matrícula y seguimiento de asistencia' },
      { name: 'DEMUNA La Victoria', status: 'connected', type: 'Protección Infantil', icon: 'shield', detail: 'Protocolo de salvaguarda distrital' },
      { name: 'PNP La Victoria', status: 'syncing', type: 'Seguridad', icon: 'landmark', detail: 'Evaluación de riesgo de rutas juveniles' },
    ],
    script: [
      { agentId: 'youth-victoria', phase: 'phase1', type: 'warning', delay: 800, content: 'SALVAGUARDA JUVENIL — LA VICTORIA. 38 menores (12-17): (1) CNA: 36/38 con consentimiento verificado. 2 familias monoparentales (solo madre). (2) 22 de 38 viven en La Victoria o adyacentes — caminan/transporte público a Matute. (3) Post-escándalo 2024: escrutinio elevado — cualquier falla de salvaguarda se ve a través del lente del escándalo. (4) 2 certificados de personal de entrenamiento expirados hace 6 meses.' },
      { agentId: 'community-safety', phase: 'phase1', type: 'analysis', delay: 2500, content: 'RIESGO LA VICTORIA. (1) Tasas de criminalidad superiores al promedio de Lima — delitos callejeros afectan a jóvenes. (2) Entrenamiento 4-7pm: jugadores de 12-14 viajan a casa de noche en invierno. (3) SIN plan de traslado seguro documentado. (4) Datos PNP: 3 incidentes cerca de Matute con jóvenes en 12 meses. (5) Actividad de pandillas en bloques adyacentes documentada. El contexto del barrio que hace auténtico a Alianza crea obligaciones de salvaguarda específicas.' },
      { agentId: 'education-al', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISIDENCIA — BRECHAS EDUCATIVAS. (1) 5 de 38 jugadores bajo 65% de asistencia escolar. Horario de entrenamiento (4-7pm) conflicta con sesiones vespertinas de 3 colegios de La Victoria. (2) 2 jugadores de 14 años ofrecidos "trabajo" informal en mercados — preocupación de trabajo infantil bajo CNA Art. 22. (3) Mi disidencia: post-escándalo, Alianza debe demostrar salvaguarda PROACTIVA. Sin acuerdos formales con colegios, cualquier falla de asistencia se convierte en responsabilidad institucional.' },
      { agentId: 'welfare-al', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — BIENESTAR POST-ESCÁNDALO. (1) Impacto psicológico: jugadores de academia conscientes del escándalo por medios. Sin apoyo psicológico documentado. (2) Personal femenino reporta sentirse inseguro — preocupación de cultura institucional. (3) Capacitación en salvaguarda: última hace 2 años — debe ser anual post-escándalo. (4) Inspección DEMUNA: hace 14 meses — vencida. Re-inspección voluntaria demuestra gobernanza proactiva.' },
      { agentId: 'youth-victoria', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Juvenil La Victoria: (1) TRASLADO: Rutas seguras documentadas. Minibús del club para 12-14 años en invierno. Coordinación PNP. (2) PERSONAL: Certificados renovados. Capacitación anual. (3) EDUCACIÓN (aceptando disidencia): MOUs formales con 3 colegios. Horario ajustado. Intervención trabajo infantil documentada. (4) BIENESTAR: Apoyo psicológico post-escándalo. Evaluación de seguridad del personal femenino. (5) DEMUNA: Re-inspección voluntaria. Todo sellado para FPF, MIMP, MINEDU, DEMUNA.' },
      { agentId: 'education-al', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISIDENCIA RETIRADA. MOUs formales con colegios transforman el enfoque reactivo a proactivo. Intervención de trabajo infantil documentada. Post-escándalo, Alianza debe ser el modelo de salvaguarda — no a pesar de los desafíos de La Victoria, sino por ellos. 38 niños merecen protección que considere la realidad de su barrio.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:al70123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'al80123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (CNA + Seguridad de traslado + MOUs educativos + Bienestar post-escándalo + DEMUNA)',
      complianceLabel: 'Salvaguarda Juvenil',
      complianceValue: 'PROTOCOLO REFORZADO POST-ESCÁNDALO',
      complianceThreshold: 'CNA Ley 27337 · DEMUNA · Contexto Ley 30364',
      agents: ['Agente de Salvaguarda Juvenil', 'Agente de Seguridad Comunitaria', 'Agente de Educación', 'Agente de Bienestar'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Alianza Lima — Salvaguarda Juvenil La Victoria',
      guaranteeBody: 'Sella: auditoría de 38 menores, seguridad de traslado La Victoria, MOUs escolares, intervención trabajo infantil, bienestar post-escándalo, re-inspección DEMUNA.',
      evidenceChain: 'Auditoría academia → Riesgo La Victoria → Plan de traslado → MOUs escolares → Capacitación → Bienestar → DEMUNA → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA auditan la salvaguarda juvenil en La Victoria — riesgos del barrio, escrutinio post-escándalo y obligaciones educativas para 38 menores.',
    phaseLabels: ['Auditoría y Riesgo La Victoria', 'Educación y Bienestar Post-Escándalo', 'Protocolo de Salvaguarda Reforzado'],
  },

  // ESCENARIO 5 — CUMPLIMIENTO FINANCIERO
  {
    id: 'financial-compliance',
    title: 'SUNAT y Cumplimiento Financiero CONMEBOL',
    subtitle: 'Gobernanza tributaria · Estructuras de derechos de imagen · Partes relacionadas · Licencia de club',
    banner: 'Simulando la gobernanza financiera del complejo panorama de SUNAT de Alianza Lima — incluyendo estructuras de empresas de derechos de imagen, transacciones con partes relacionadas e indicadores financieros de Licencia de Club CONMEBOL.',
    risk: 'Alto',
    scenarioNum: 'Financiero',
    icon: 'landmark',
    color: 'text-cyan-400',
    agents: [
      { id: 'sunat-al', name: 'Agente SUNAT', role: 'Cumplimiento Tributario y Derechos de Imagen', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'conmebol-al', name: 'Agente Financiero CONMEBOL', role: 'Indicadores de Licencia de Club', icon: '🏆', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'legal-al', name: 'Agente Legal', role: 'Partes Relacionadas y Valor de Mercado', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'audit-al', name: 'Agente de Auditoría', role: 'Estados Financieros y Reporte a Socios', icon: '📊', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Portal SUNAT', status: 'connected', type: 'Autoridad Tributaria', icon: 'landmark', detail: 'Estado actual: CUMPLE — sin deudas pendientes' },
      { name: 'Licencia CONMEBOL', status: 'connected', type: 'Revisión Financiera', icon: 'check-circle', detail: 'Todos los indicadores: VERDE — elegible Copa Libertadores' },
      { name: 'Contratos de Jugadores', status: 'connected', type: 'Compensación', icon: 'database', detail: '28 contratos — 6 con estructuras de empresas de imagen' },
      { name: 'Finanzas Socios', status: 'syncing', type: 'Reporte', icon: 'users', detail: 'Publicación anual de estados financieros — revisión asamblea' },
    ],
    script: [
      { agentId: 'sunat-al', phase: 'phase1', type: 'warning', delay: 800, content: 'REVISIÓN SUNAT. (1) 6 jugadores con empresas SAC de derechos de imagen. Pagos deben ser a valor de mercado — SUNAT Precios de Transferencia (Art. 32-A, Ley IR). Si SUNAT determina sobreprecio: deducciones denegadas + 50% multa. (2) Pagos combinados: PEN 3.8M/año. Se necesita análisis de referencia. (3) 4 jugadores extranjeros en USD: retención 30% para no domiciliados. (4) AFP/ONP: 28 jugadores al día. Staff: 2 aportes atrasados (PEN 8K). (5) ESSALUD: al día.' },
      { agentId: 'conmebol-al', phase: 'phase1', type: 'analysis', delay: 2500, content: 'LICENCIA CONMEBOL — VERDE. Todos los indicadores cumplen. Pero las estructuras de imagen crean complejidad de REPORTE. CONMEBOL requiere divulgación de todas las transacciones con partes relacionadas. Si las SAC son propiedad de jugadores bajo contrato, cada pago es transacción con parte relacionada. 4 de 6 divulgadas. 2 empresas recientes no identificadas como partes relacionadas. Brecha de divulgación que podría ser señalada en la próxima revisión CONMEBOL.' },
      { agentId: 'legal-al', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISIDENCIA — RIESGO DE PARTES RELACIONADAS. Las 2 SAC no divulgadas crean doble riesgo: (1) SUNAT: si investiga y encuentra pagos no divulgados, activa auditoría completa de precios de transferencia de TODOS los pagos de imagen. Exposición: PEN 1.9M (50% de PEN 3.8M). (2) CONMEBOL: no divulgación es violación de licencia — podría resultar en licencia condicional o prohibición. Mi disidencia: propiedad de empresas debe verificarse ANTES del primer pago. La brecha sugiere KYC insuficiente.' },
      { agentId: 'audit-al', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — IMPLICACIONES DE AUDITORÍA. (1) Si las 2 transacciones no divulgadas son materiales (PEN 900K combinado), la opinión del auditor puede ser calificada. Opinión calificada debilita la posición de licencia CONMEBOL. (2) Los socios tienen derecho a estados financieros precisos. Partes relacionadas no divulgadas minan la confianza. (3) Las estructuras de imagen son LEGALES — muchos clubes las usan. El problema no es la estructura; es la falta de documentación.' },
      { agentId: 'sunat-al', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo de Cumplimiento Financiero: (1) INMEDIATO: Divulgar 2 SAC faltantes a CONMEBOL. Divulgación voluntaria previene sanción. (2) PRECIOS DE TRANSFERENCIA: Estudio independiente de referencia para los 6 pagos de imagen. (3) KYC: Verificación de propiedad de empresa antes de pago. Nueva política: sin pagos sin KYC completo. (4) AFP: PEN 8K resuelto esta semana. (5) CONMEBOL: Divulgación actualizada. (6) SOCIOS: Nota de derechos de imagen en estados anuales. Todo sellado.' },
      { agentId: 'legal-al', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISIDENCIA RETIRADA. Divulgación voluntaria a CONMEBOL previene que la brecha se convierta en violación. Estudio de referencia protege contra desafío de precios de transferencia SUNAT. Política KYC previene futuras fallas. La posición financiera de Alianza es sólida — este protocolo la mantiene así.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:al90123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'ala0123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (SUNAT + Derechos de imagen + Partes relacionadas + Licencia CONMEBOL + KYC)',
      complianceLabel: 'Cumplimiento Financiero',
      complianceValue: '2 DIVULGACIONES DE PARTES RELACIONADAS PENDIENTES',
      complianceThreshold: 'SUNAT Art. 32-A · Licencia CONMEBOL',
      agents: ['Agente SUNAT', 'Agente Financiero CONMEBOL', 'Agente Legal', 'Agente de Auditoría'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Alianza Lima — Gobernanza de Cumplimiento Financiero',
      guaranteeBody: 'Sella: referencia de derechos de imagen, divulgación de partes relacionadas, política KYC, indicadores de licencia CONMEBOL, defensa precios de transferencia SUNAT, transparencia financiera socios.',
      evidenceChain: 'Auditoría imagen → Propiedad SAC → Precios transferencia → Divulgación CONMEBOL → Política KYC → AFP → Reporte socios → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobiernan el cumplimiento financiero de Alianza Lima — estructuras de derechos de imagen, precios de transferencia SUNAT, licencia CONMEBOL y transparencia ante socios.',
    phaseLabels: ['Revisión Tributaria y Licencia', 'Riesgo de Partes Relacionadas y Auditoría', 'Protocolo de Cumplimiento'],
  
        complianceScore: 87,
        timelineEvents: [
      {
            "timestamp": "2026-04-01T12:18:01.116Z",
            "type": "analysis",
            "title": "System Assessment - Escándalo de Conducta — Gobernanza Disciplinaria y Procedimientos Penales",
            "description": "Data protection, cybersecurity, IP rights, platform governance: System Assessment analysis for Alianza Lima Es completed with industry-specific compliance checks",
            "agent": "Tech Agent",
            "impact": "high"
      },
      {
            "timestamp": "2026-04-01T12:19:01.116Z",
            "type": "warning",
            "title": "Privacy Compliance - Escándalo de Conducta — Gobernanza Disciplinaria y Procedimientos Penales",
            "description": "Data protection, cybersecurity, IP rights, platform governance: Privacy Compliance analysis for Alianza Lima Es completed with industry-specific compliance checks",
            "agent": "Privacy Agent",
            "impact": "high"
      },
      {
            "timestamp": "2026-04-01T12:20:01.116Z",
            "type": "dissent",
            "title": "Security Risk - Escándalo de Conducta — Gobernanza Disciplinaria y Procedimientos Penales",
            "description": "Data protection, cybersecurity, IP rights, platform governance: Security Risk analysis for Alianza Lima Es completed with industry-specific compliance checks",
            "agent": "Security Agent",
            "impact": "medium"
      },
      {
            "timestamp": "2026-04-01T12:21:01.116Z",
            "type": "proposal",
            "title": "Governance Framework - Escándalo de Conducta — Gobernanza Disciplinaria y Procedimientos Penales",
            "description": "Data protection, cybersecurity, IP rights, platform governance: Governance Framework analysis for Alianza Lima Es completed with industry-specific compliance checks",
            "agent": "Platform Agent",
            "impact": "high"
      },
      {
            "timestamp": "2026-04-01T12:22:01.116Z",
            "type": "resolution",
            "title": "Compliance Certified - Escándalo de Conducta — Gobernanza Disciplinaria y Procedimientos Penales",
            "description": "Data protection, cybersecurity, IP rights, platform governance: Compliance Certified analysis for Alianza Lima Es completed with industry-specific compliance checks",
            "agent": "Audit Agent",
            "impact": "high"
      }
]},
];
