/**
 * Cusco FC — Spanish (Español) Scenarios
 * @module pages/sandbox/configs/cusco-fc-es
 */

// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.

import type { TemplateScenario } from '../SandboxTemplate';

export const ES_SCENARIOS: TemplateScenario[] = [
  // ESCENARIO 1 — ALTITUD EXTREMA 3,400m
  {
    id: 'altitude-3400',
    title: 'Seguridad de Altitud Extrema — Gobernando el Fútbol a 3,400m',
    subtitle: 'Estadio Garcilaso · Monitoreo SpO2 · Riesgo cardíaco · Debate FIFA 2007 · Aclimatación',
    banner: 'Simulando el desafío de altitud más extremo del fútbol peruano. A 3,400m, el Estadio Garcilaso empuja a visitantes a territorio fisiológicamente peligroso — SpO2 cae a 89%, VO2 máx reducido 15-25%.',
    risk: 'Crítico',
    scenarioNum: 'Altitud',
    icon: 'mountain',
    color: 'text-red-400',
    agents: [
      { id: 'medical-extreme', name: 'Agente Médico', role: 'Fisiología de Alta Altitud y Riesgo Cardíaco', icon: '🏥', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'legal-altitude', name: 'Agente Legal', role: 'Regulaciones FIFA y Defensa de Responsabilidad', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'sporting-equity', name: 'Agente Deportivo', role: 'Balance Competitivo y Aclimatación', icon: '⚽', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'emergency-cusco', name: 'Agente de Emergencia', role: 'Evacuación Médica y Acceso Hospitalario', icon: '🚑', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'Monitor de Altitud', status: 'connected', type: 'Fisiología', icon: 'heart', detail: 'SpO2 visitante: 89% a 3,400m — 3 jugadores sintomáticos' },
      { name: 'Base FIFA', status: 'connected', type: 'Investigación', icon: 'database', detail: 'Prohibición 2007: coalición Bolivia/Perú/Ecuador revirtió 2008' },
      { name: 'Mapa Hospitalario', status: 'connected', type: 'Emergencia', icon: 'map-pin', detail: 'Cusco: 2 hospitales cardíacos a 15 min' },
      { name: 'Registro Aclimatación', status: 'syncing', type: 'Bienestar', icon: 'clock', detail: 'Visitante llegó 4h antes — mínimo: 24h' },
    ],
    script: [
      { agentId: 'medical-extreme', phase: 'phase1', type: 'warning', delay: 800, content: 'ALERTA MÉDICA — 3,400m. Partido en Garcilaso. Visitante: SpO2 promedio 89%, 3 jugadores bajo 87% (sintomáticos), frecuencia cardíaca +18%, 2 con cefalea/náuseas (MAM). Llegaron 4h antes vs 24h recomendadas. Presión atmosférica al 66% del nivel del mar — capacidad aeróbica reducida 15-25%. Histórico: 3 incidentes oxígeno en 2 temporadas, 1 hospitalizado.' },
      { agentId: 'sporting-equity', phase: 'phase1', type: 'analysis', delay: 2500, content: 'EQUIDAD COMPETITIVA — 5 temporadas. Cusco FC local: 68% victorias (liga: 48%). Visitante en Garcilaso: 18% (liga: 38%). Goles visitante: 0.6 (liga: 1.2). Caída 2do tiempo: 28%. Comparación: Juliaca (3,827m) 15%, Arequipa (2,335m) 24%. La prohibición FIFA 2007 apuntó exactamente a esto. Si ocurre evento cardíaco, el debate se reabre con Perú como ejemplo negativo.' },
      { agentId: 'emergency-cusco', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO. 2 hospitales cardíacos a 15 min — ADECUADO. Pero evacuación nocturna limitada. Los 3 bajo 87% SpO2 tienen riesgo de arritmia. Sin monitoreo SpO2 continuo durante juego. Mi disenso: los 3 sintomáticos deben ser EXCLUIDOS. Jugar con SpO2 bajo 87% a 3,400m es médicamente indefendible.' },
      { agentId: 'legal-altitude', phase: 'phase2', type: 'flag', delay: 2500, content: 'RESPONSABILIDAD: Si evento cardíaco: (1) ¿FPF aplicó aclimatación? 4h vs 24h = fallo documentado. (2) ¿"Recomendado" tiene fuerza legal? Si es solo consultivo, FPF no se absuelve. (3) FIFA examinará gobernanza. (4) Bolivia/Ecuador — socios de coalición — pierden credibilidad. La diferencia entre "incidente con gobernanza" e "incidente sin gobernanza" es defender el fútbol de altitud o perderlo.' },
      { agentId: 'medical-extreme', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Datacendia (3,400m+): (1) Aclimatación OBLIGATORIA 24h — forfeit 3-0. (2) SpO2 pre-partido — exclusión bajo 90%, OBLIGATORIO. (3) Monitoreo SpO2 en partido — sustitución bajo 85%. (4) Protocolo emergencia por sede sellado. Cusco: 2 ambulancias, helicóptero para nocturnos. (5) Cada partido produce paquete de seguridad sellado para FIFA. La gobernanza de altitud más rigurosa del mundo.' },
      { agentId: 'emergency-cusco', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Aclimatación obligatoria + barreras SpO2 abordan todo: 3 excluidos, problema de 4h eliminado, monitoreo en tiempo real. Para FIFA: gobernanza MÁS rigurosa que cualquier protocolo mundial. Los 3,400m de Cusco se convierten en ESCAPARATE — partidos seguros CON gobernanza adecuada.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:cf10123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'cf20123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (SpO2 + Aclimatación + Monitoreo + Emergencia + Defensa FIFA)',
      complianceLabel: 'Seguridad Altitud',
      complianceValue: '3 JUGADORES EXCLUIDOS — SpO2 < 90%',
      complianceThreshold: 'Aclimatación obligatoria 24h · Barrera SpO2 90%',
      agents: ['Agente Médico', 'Agente Legal', 'Agente Deportivo', 'Agente de Emergencia'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Cusco FC — Gobernanza Altitud Extrema 3,400m',
      guaranteeBody: 'SpO2 pre-partido (3 excluidos < 90%), aclimatación 24h obligatoria, monitoreo portátil, protocolo emergencia por sede, paquete evidencia FIFA.',
      evidenceChain: 'Partido (3,400m) → Aclimatación 24h → SpO2 → 3 excluidos → Monitor → Emergencia → FIFA → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes gobernarán fútbol a 3,400m — aclimatación obligatoria, exclusión de sintomáticos y evidencia para defender el derecho del Perú a jugar en altitud extrema.',
    phaseLabels: ['Evaluación Médica y Rendimiento', 'Emergencia y Responsabilidad', 'Protocolo Obligatorio de Altitud'],
  },

  // ESCENARIO 2 — RECINTO PATRIMONIO UNESCO
  {
    id: 'unesco-heritage',
    title: 'Recinto Patrimonio UNESCO — Fútbol en Ciudad Patrimonio Mundial',
    subtitle: 'Estadio Garcilaso · Zona buffer UNESCO · Ministerio de Cultura · Ruido · Turismo',
    banner: 'Simulando gobernanza de un recinto deportivo dentro de zona buffer Patrimonio Mundial UNESCO. Cusco impone restricciones de ruido, multitudes, infraestructura y actividad comercial únicas en Liga 1.',
    risk: 'Alto',
    scenarioNum: 'Patrimonio',
    icon: 'landmark',
    color: 'text-amber-400',
    agents: [
      { id: 'heritage-gov', name: 'Agente Patrimonio', role: 'UNESCO y Ministerio de Cultura', icon: '🏛️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'venue-ops', name: 'Agente Operaciones', role: 'Gestión Estadio e Infraestructura', icon: '🏟️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'tourism-agent', name: 'Agente Turismo', role: 'Economía Visitantes y Comunidad', icon: '🌍', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'legal-heritage', name: 'Agente Legal', role: 'Ley Patrimonio y Ordenanza Municipal', icon: '⚖️', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'Ministerio de Cultura', status: 'connected', type: 'Autoridad Patrimonial', icon: 'landmark', detail: 'Garcilaso en zona buffer UNESCO — modificación restringida' },
      { name: 'Monitoreo UNESCO', status: 'connected', type: 'Patrimonio Mundial', icon: 'globe', detail: 'Inscripción WHC 1983 — monitoreo periódico activo' },
      { name: 'Municipal Cusco', status: 'connected', type: 'Ruido', icon: 'volume-2', detail: 'Límite 85dB 22:00-07:00 — Copa termina ~23:00' },
      { name: 'Junta Turismo', status: 'syncing', type: 'Visitantes', icon: 'users', detail: '3.2M turistas/año — conflictos tráfico día de partido' },
    ],
    script: [
      { agentId: 'heritage-gov', phase: 'phase1', type: 'warning', delay: 800, content: 'ALERTA PATRIMONIAL. Garcilaso (42,000) en zona buffer UNESCO (WHC 1983). Restricciones: (1) ESTRUCTURAL: modificación requiere aprobación Ministerio (Ley 28296). Construcción prohibida en zona buffer. (2) RUIDO: 85dB después 22:00. Copa se extiende a 23:00. (3) VISUAL: sin señalización comercial visible desde miradores patrimoniales. LEDs perimetrales visibles desde Sacsayhuamán. (4) TRÁFICO: 42,000 fans en centro histórico diseñado para tráfico peatonal.' },
      { agentId: 'tourism-agent', phase: 'phase1', type: 'analysis', delay: 2500, content: 'IMPACTO TURÍSTICO. 3.2M turistas/año. (1) Tráfico bloquea Plaza de Armas, Qorikancha, San Blas. Quejas de hoteles. (2) 3 operadores presentaron quejas formales. (3) PERO: turismo futbolístico crece. 12% son turistas combinando fútbol + Machu Picchu. Copa atraería turismo internacional. (4) Infraestructura turística absorbe 42,000 mejor que otra ciudad provincial. La tensión patrimonio vs fútbol vs turismo no tiene que ser conflicto — pero sin gobernanza, lo será.' },
      { agentId: 'legal-heritage', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO. (1) Ley 28296: aprobación Ministerio para modificaciones — 90-180 días. CONMEBOL requiere mejoras en 3 semanas — IMPOSIBLE. (2) UNESCO: si estatus WHC amenazado, Perú pierde designación valorada en miles de millones. (3) Ordenanza ruido: multas PEN 10K-50K por evento. 6 partidos Copa = PEN 60K-300K. Mi disenso: Cusco FC NO PUEDE cumplir CONMEBOL Y patrimonio simultáneamente. La respuesta NO debe ser perder UNESCO.' },
      { agentId: 'venue-ops', phase: 'phase2', type: 'flag', delay: 2500, content: 'CONFLICTO CONMEBOL vs PATRIMONIO: (1) LEDs: CONMEBOL requiere, patrimonio prohíbe visibilidad. (2) Estructuras temporales: CONMEBOL requiere, patrimonio restringe. (3) Ruido: CONMEBOL espera ambiente, patrimonio limita 85dB. (4) Capacidad: 42,000 pero tráfico patrimonial limita a ~35,000 prácticos. Si Cusco no puede ser sede Copa en Garcilaso, juegan en Lima — perdiendo todo.' },
      { agentId: 'heritage-gov', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Patrimonio-Fútbol: (1) MINISTERIO: Copa como "instalaciones temporales reversibles" — aprobación 30 días vs 180. (2) LED: paneles direccionales lejos de miradores. Estudio visibilidad sellado. (3) RUIDO: ingeniería acústica para 85dB en perímetro. Medición sellada por partido. (4) TRÁFICO: ingreso escalonado 4h antes. Corredores turísticos mantenidos. (5) CAPACIDAD: tope 35,000 para Copa — compatible con patrimonio. (6) UNESCO: posicionar Cusco FC como "patrimonio cultural vivo" — fútbol andino ES cultura.' },
      { agentId: 'legal-heritage', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. "Instalaciones temporales reversibles" resuelve cronograma legal. LEDs direccionales y acústica resuelven conflictos. Tope 35,000 pragmático. La alianza UNESCO es inspiradora: fútbol y patrimonio COEXISTEN. Fútbol andino a 3,400m en ciudad UNESCO es único en el mundo. El Recibo sella cada partido: CONMEBOL + patrimonio + acústica + tráfico.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:cf30123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'cf40123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (UNESCO + Ministerio + Acústica + Tráfico + CONMEBOL)',
      complianceLabel: 'Gobernanza Patrimonial',
      complianceValue: 'TOPE 35,000 — COMPATIBLE PATRIMONIO',
      complianceThreshold: 'Ley 28296 + UNESCO WHC + CONMEBOL',
      agents: ['Agente Patrimonio', 'Agente Operaciones', 'Agente Turismo', 'Agente Legal'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Cusco FC — Gobernanza Recinto Patrimonio UNESCO',
      guaranteeBody: 'Instalaciones temporales, LED direccional, contención acústica 85dB, tope 35,000, ingreso escalonado, corredores turísticos, alianza UNESCO.',
      evidenceChain: 'Ministerio → Temporales → LED → Acústica → Tráfico → 35K → CONMEBOL → UNESCO → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes navegarán el desafío de gobernar fútbol profesional dentro de zona buffer Patrimonio Mundial UNESCO.',
    phaseLabels: ['Restricciones e Impacto Turístico', 'Conflictos CONMEBOL vs Patrimonio', 'Coexistencia Patrimonio-Fútbol'],
  },

  // ESCENARIO 3 — LICENCIAS COPA LIBERTADORES
  {
    id: 'copa-qualification',
    title: 'Licencias Copa Libertadores — CONMEBOL a 3,400m',
    subtitle: 'Indicadores financieros · Certificación recinto · Infraestructura médica · Logística',
    banner: 'Simulando licencias CONMEBOL para Copa Libertadores de Cusco FC. Requisitos financieros, infraestructura, deportivos y médicos complicados por altitud 3,400m, patrimonio UNESCO y recursos provinciales.',
    risk: 'Alto',
    scenarioNum: 'CONMEBOL',
    icon: 'trophy',
    color: 'text-blue-400',
    agents: [
      { id: 'licensing-agent', name: 'Agente Licencias', role: 'Licencias CONMEBOL y Documentación', icon: '🏆', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'financial-cusco', name: 'Agente Financiero', role: 'FFP y Cumplimiento SUNAT', icon: '💰', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'medical-copa', name: 'Agente Médico', role: 'Médico Altitud y Estándares CONMEBOL', icon: '🏥', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'operations-copa', name: 'Agente Operaciones', role: 'Logística Viajes y Día de Partido', icon: '✈️', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'Licencias CONMEBOL', status: 'connected', type: 'Licencias', icon: 'check-circle', detail: 'Solicitud presentada — 4 criterios bajo revisión' },
      { name: 'Portal SUNAT', status: 'connected', type: 'Fiscal', icon: 'landmark', detail: 'Obligaciones: PEN 3.8M — fraccionamiento activo' },
      { name: 'INDECI Cusco', status: 'connected', type: 'Seguridad', icon: 'shield', detail: 'Renovación certificación Garcilaso' },
      { name: 'Sistema Viajes', status: 'syncing', type: 'Logística', icon: 'plane', detail: 'Aeropuerto Cusco: conexiones internacionales limitadas' },
    ],
    script: [
      { agentId: 'licensing-agent', phase: 'phase1', type: 'warning', delay: 800, content: 'EVALUACIÓN LICENCIAS. 5 áreas: (1) DEPORTIVO: plantel 25, conforme. Juvenil debajo nivel 2. (2) INFRAESTRUCTURA: Garcilaso 42,000 conforme, pero patrimonio limita modificaciones. VAR y cancha conformes. (3) PERSONAL: DT y secretario conformes. Médico 4/6 posiciones. (4) LEGAL: conforme. (5) FINANCIERO: pagos vencidos PEN 620K (2 proveedores 45+ días + SUNAT), salarios-ingresos 69.5% (ÁMBAR 70%). Frágil pero recuperable.' },
      { agentId: 'financial-cusco', phase: 'phase1', type: 'analysis', delay: 2500, content: 'FINANZAS. Ingresos PEN 12.8M/año. Salarios PEN 8.9M (69.5%). Vencidos: PEN 620K. SUNAT total PEN 3.8M, 1 pago perdido. Cuenta por cobrar PEN 800K (60 días). UN fichaje empuja salarios a ROJO (70%+). Deuda-ingresos acercándose 0.78 (ROJO: 0.80). Recuperable SI vencidos se resuelven en 30 días.' },
      { agentId: 'medical-copa', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — BRECHA MÉDICA. CONMEBOL requiere 6 posiciones (2 médicos, 2 paramédicos, 1 fisio, 1 cardiólogo). Cusco tiene 4 — falta cardiólogo y 1 paramédico. A 3,400m, cardiólogo no es burocrático — es CRÍTICO. Hospital Regional tiene cardiólogos pero no contratados por el club. Mi disenso: sin cardiólogo contratado, licencia Copa no debería otorgarse. Altitud lo hace no negociable.' },
      { agentId: 'operations-copa', phase: 'phase2', type: 'flag', delay: 2500, content: 'LOGÍSTICA. Aeropuerto Cusco sin vuelos internacionales directos. Todo viaje Copa requiere conexión Lima (+3-6h). Costo: PEN 52K/viaje (vs 38K desde Lima). 3 partidos: PEN 156K. Equipos visitantes con slots limitados. CONMEBOL requiere planes documentados de viaje y aclimatación.' },
      { agentId: 'licensing-agent', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Licencias: (1) FINANCIERO: resolver proveedores (PEN 380K) en 15 días, regularizar SUNAT (PEN 240K), cobrar transferencia (PEN 800K). (2) MÉDICO: contratar cardiólogo Hospital Regional PEN 3,500/partido (PEN 63K/temp). Paramédico adicional. (3) JUVENIL: plan mejorado aprovechando altitud. (4) VIAJES: pre-reservar vía Lima. (5) PATRIMONIO: instalaciones temporales aprobadas. (6) Paquete sellado completo.' },
      { agentId: 'medical-copa', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Cardiólogo PEN 63K/temporada cierra brecha crítica. Con protocolo altitud, infraestructura médica de Cusco FC es la MÁS FUERTE de Liga 1 para altitud. Club provincial a 3,400m con cardiólogo, SpO2 y protocolos sellados excede la mayoría de participantes Copa. El paquete transforma debilidades en escaparates de gobernanza.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:cf50123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'cf60123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (CONMEBOL + Finanzas + Médico + Viajes + Patrimonio)',
      complianceLabel: 'Licencias Copa',
      complianceValue: 'REMEDIACIÓN FINANCIERA — 15 DÍAS',
      complianceThreshold: 'Manual Licencias CONMEBOL 2026',
      agents: ['Agente Licencias', 'Agente Financiero', 'Agente Médico', 'Agente Operaciones'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Cusco FC — Licencias Copa Libertadores',
      guaranteeBody: 'Remediación PEN 620K, contrato cardiólogo, plan juvenil, logística viajes, aprobaciones patrimonio, paquete completo.',
      evidenceChain: 'Licencias → Finanzas → SUNAT → Médico → Viajes → Patrimonio → Juvenil → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes gobernarán licencias Copa — brechas financieras, infraestructura médica y desafíos de recinto patrimonial.',
    phaseLabels: ['Evaluación y Brecha Financiera', 'Médico y Viajes', 'Remediación y Evidencia'],
  },

  // ESCENARIO 4 — PROTECCIÓN DE DATOS
  {
    id: 'fan-data-tourism',
    title: 'Protección de Datos — Ley 29733 en Capital Turística',
    subtitle: 'Turista-fan · ANPDP · Datos internacionales · Plataformas entradas · DS 115',
    banner: 'Simulando protección de datos donde la base de fans se superpone con turismo internacional. Cusco FC procesa datos de peruanos Y turistas — creando gobernanza transfronteriza única en Liga 1.',
    risk: 'Medio',
    scenarioNum: 'Datos',
    icon: 'shield',
    color: 'text-emerald-400',
    agents: [
      { id: 'data-protect', name: 'Agente Datos', role: 'Ley 29733 y ANPDP', icon: '🔒', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'commercial-data', name: 'Agente Comercial', role: 'Engagement y Plataforma Entradas', icon: '📊', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'legal-data', name: 'Agente Legal', role: 'Datos Transfronterizos y Privacidad', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'tourism-data', name: 'Agente Turismo', role: 'Datos Visitantes y MINCETUR', icon: '🌍', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'Registro ANPDP', status: 'connected', type: 'Autoridad', icon: 'shield', detail: '2 de 4 bases registradas — 2 faltantes' },
      { name: 'Teleticket', status: 'connected', type: 'Comercial', icon: 'ticket', detail: 'Procesa DNI + pasaporte para 42,000' },
      { name: 'MINCETUR', status: 'connected', type: 'Turismo', icon: 'globe', detail: '12% asistentes son turistas' },
      { name: 'DS 115-2025-PCM', status: 'syncing', type: 'IA', icon: 'cpu', detail: 'Analítica fan con IA — cumplimiento requerido' },
    ],
    script: [
      { agentId: 'data-protect', phase: 'phase1', type: 'warning', delay: 800, content: 'AUDITORÍA. 4 bases identificadas (abonos, día partido, redes, merchandising). Solo 2 en ANPDP = violación. Consentimiento Teleticket enterrado en T&Cs — no conforme Art. 13.5. Sin política retención (datos desde 2019). 12% asistentes con pasaporte = datos transfronterizos sin evaluación. Analítica IA sin cumplimiento DS 115.' },
      { agentId: 'tourism-data', phase: 'phase1', type: 'analysis', delay: 2500, content: 'SUPERPOSICIÓN TURISMO. Domésticos ~8%, internacionales ~4% (brasileños, argentinos, estadounidenses). 3 operadores turísticos empaquetan "Cusco FC + Machu Picchu" sin acuerdos de procesamiento. 4 hoteles comparten datos bidireccionalmente sin DPAs. Copa aumenta internacionales a ~15%. Complejidad única en Liga 1.' },
      { agentId: 'legal-data', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO. Pasaportes: Art. 15 requiere protección para transferencia exterior. Teleticket usa AWS EE.UU. para respaldo = transferencia transfronteriza. Turistas UE (~2%): exposición GDPR. DS 115: analítica IA DEBE tener transparencia y override humano — sistema actual no tiene. Mi disenso: DETENER analítica IA hasta cumplimiento. Multas ANPDP hasta 100 UIT (~PEN 515K).' },
      { agentId: 'commercial-data', phase: 'phase2', type: 'flag', delay: 2500, content: 'IMPACTO COMERCIAL. IA genera 22% merchandising (PEN 180K). Hoteles PEN 120K. Operadores PEN 112K. Total en riesgo: PEN 412K. PERO multa ANPDP: hasta PEN 1.03M. Costo cumplimiento << riesgo incumplimiento.' },
      { agentId: 'data-protect', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo: (1) Registrar 2 bases ANPDP (5 días). (2) Rediseñar consentimiento Teleticket — multilingüe. (3) Retención: 3 años partido, 5 abonos. (4) DPAs con Teleticket, hoteles, operadores. (5) DS 115: transparencia, override humano, evaluación algorítmica sellada. (6) Flujo separado para pasaportes. Todo sellado para auditoría ANPDP.' },
      { agentId: 'legal-data', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Registro + DS 115 aborda riesgo. IA reanuda en ~2 semanas con transparencia y override. Cusco FC: primer club Liga 1 con gobernanza transfronteriza integral. Pionero DS 115 en analítica fan. Turismo y datos PUEDEN coexistir con gobernanza.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:cf70123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'cf80123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (ANPDP + Consentimiento + DPAs + DS 115 + Retención)',
      complianceLabel: 'Protección Datos',
      complianceValue: '2 BASES REGISTRADAS — IA PAUSADA',
      complianceThreshold: 'Ley 29733 + DS N° 115-2025-PCM',
      agents: ['Agente Datos', 'Agente Comercial', 'Agente Legal', 'Agente Turismo'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Cusco FC — Protección Datos en Capital Turística',
      guaranteeBody: 'ANPDP (4 bases), consentimiento rediseñado, retención 3 años, DPAs transfronterizos, DS 115, consentimiento turístico multilingüe.',
      evidenceChain: 'Auditoría → ANPDP → Consentimiento → Retención → DPAs → DS 115 → IA → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes gobernarán protección de datos en el club más turístico del Perú — ANPDP, datos transfronterizos y analítica IA.',
    phaseLabels: ['Auditoría y Turismo', 'Riesgo Transfronterizo e IA', 'Protocolo Integral'],
  },

  // ESCENARIO 5 — GOBERNANZA POLÍTICA REGIONAL
  {
    id: 'regional-politics',
    title: 'Gobernanza Política — Fútbol en Fuego Cruzado Político',
    subtitle: 'Gobierno Regional · Financiamiento municipal · Elecciones · Independencia',
    banner: 'Simulando gobernanza política para un club en una de las regiones más activas políticamente. Gobierno regional, municipal y representantes nacionales reclaman influencia sobre Cusco FC — conflictos de financiamiento público, infraestructura e independencia.',
    risk: 'Alto',
    scenarioNum: 'Política',
    icon: 'building',
    color: 'text-purple-400',
    agents: [
      { id: 'governance-pol', name: 'Agente Gobernanza', role: 'Independencia Institucional', icon: '🏛️', color: 'text-purple-400', borderColor: 'border-purple-500/40', bgColor: 'bg-purple-500/10' },
      { id: 'legal-pol', name: 'Agente Legal', role: 'Financiamiento Público y Anti-Corrupción', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'financial-pol', name: 'Agente Financiero', role: 'Gobernanza Público-Privada y OSCE', icon: '💰', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'community-pol', name: 'Agente Comunitario', role: 'Identidad Cívica y Representación', icon: '🌍', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Gobierno Regional', status: 'connected', type: 'Regional', icon: 'landmark', detail: 'PEN 2.5M infraestructura — vinculado a elecciones' },
      { name: 'Municipal Cusco', status: 'connected', type: 'Local', icon: 'building', detail: 'Permisos políticamente condicionados' },
      { name: 'Portal OSCE', status: 'connected', type: 'Contratación', icon: 'file-text', detail: 'Fondos públicos requieren OSCE' },
      { name: 'Contraloría', status: 'syncing', type: 'Auditoría', icon: 'shield', detail: 'Supervisión activa' },
    ],
    script: [
      { agentId: 'governance-pol', phase: 'phase1', type: 'warning', delay: 800, content: 'ALERTA POLÍTICA. (1) Gobierno Regional: PEN 2.5M "infraestructura deportiva" — anunciado en mitin 4 meses antes de elecciones. Gobernador quiere branding en instalaciones. (2) Municipal: permisos retrasados tras declinar al Alcalde en ceremonia Copa. (3) Congresista propuso ley "patrimonio cultural" que traería financiamiento PERO supervisión y nombramientos gubernamentales en directorio. (4) 2 de 7 directores políticamente conectados — votos divididos en líneas políticas.' },
      { agentId: 'financial-pol', phase: 'phase1', type: 'analysis', delay: 2500, content: 'FINANCIAMIENTO PÚBLICO. PEN 2.5M: (1) Ley del Deporte permite inversión regional. (2) OSCE requiere licitación competitiva. (3) Contraloría audita >PEN 500K. (4) Propuesta actual: contrato directo que omite OSCE — potencial violación. Si auditado: devolución + responsabilidad penal (peculado). Precedente: 3 clubes investigados, 1 presidente procesado.' },
      { agentId: 'legal-pol', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — CAPTURA POLÍTICA. PEN 2.5M con branding = patrocinio político disfrazado. Retrasos permisos = coerción suave. Ley patrimonio crea mecanismo para nombramientos gubernamentales en directorio = fin de independencia. Mi disenso: RECHAZAR PEN 2.5M en forma actual. Proponer APP con OSCE y cero obligaciones de branding.' },
      { agentId: 'community-pol', phase: 'phase2', type: 'flag', delay: 2500, content: 'IDENTIDAD COMUNITARIA. Cusco FC es institución cívica. 68% comentarios negativos sobre PEN 2.5M: "quieren adueñarse." Ultras protestarán branding político. Referéndum: 73% opuestos a nombramientos gubernamentales. Independencia política es lo que hace a Cusco FC institución cívica. Perderla sería irreversible.' },
      { agentId: 'governance-pol', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Independencia: (1) PEN 2.5M: RECHAZAR directo. APP vía fondo regional con OSCE. Cusco FC aporta PEN 500K. Cero branding. Conforme Contraloría. (2) PERMISOS: documentar retrasos, recurso administrativo, evidencia sellada para Defensoría. (3) LEY: oponerse nombramientos, contra-proponer directorio elegido por fans. (4) DIRECTORIO: conflictos de interés declarados, recusal sellado. (5) COMUNIDAD: carta de independencia — "Cusco FC pertenece a Cusco, no a políticos."' },
      { agentId: 'legal-pol', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. APP preserva inversión sin captura. OSCE + Contraloría = cero exposición. Para FIFA: independencia política es requisito core de gobernanza. La carta de independencia sellada es exactamente lo que FIFA requiere. Para Cusco: los fans tienen razón. El club pertenece a la comunidad. El Recibo prueba que cada decisión es independiente, transparente y con evidencia.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:cf90123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'cfa0123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (Independencia + OSCE + Contraloría + Permisos + Recusal)',
      complianceLabel: 'Independencia Política',
      complianceValue: 'PEN 2.5M REESTRUCTURADO — OSCE',
      complianceThreshold: 'OSCE + Contraloría + FIFA independencia',
      agents: ['Agente Gobernanza', 'Agente Legal', 'Agente Financiero', 'Agente Comunitario'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Cusco FC — Independencia Política',
      guaranteeBody: 'PEN 2.5M reestructurado APP OSCE, documentación permisos, contra-propuesta ley, recusal directorio, carta independencia.',
      evidenceChain: 'Presión → PEN 2.5M → OSCE → Permisos → Ley → Recusal → Carta → Asamblea → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes defenderán independencia política de Cusco FC — reestructurando financiamiento, documentando presión y protegiendo identidad cívica.',
    phaseLabels: ['Presión Política y Financiamiento', 'Captura e Identidad Comunitaria', 'Independencia y OSCE'],
  },
];
