/**
 * FEPCMAC Sandbox Config
 * Access: /sandbox/fepcmac (Key: FP-85)
 * @module pages/sandbox/configs/fepcmac
 */
// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.

import type { OrgSandboxConfig } from '../SandboxTemplate';

const config: OrgSandboxConfig = {
  orgLabel: 'FEPCMAC',
  accessKey: 'FP-85',
  sessionKey: 'fepcmac-sandbox-unlocked',
  accent: 'rose',
  accentColor: 'text-rose-400',
  accentHover: 'from-rose-600 to-rose-700 hover:from-rose-500 hover:to-rose-600',
  ringColor: 'focus:ring-rose-500/30',
  borderColor: 'border-rose-500/30',
  gradientFrom: 'from-rose-600/20',
  gradientTo: 'to-rose-900/20',
  footerNote: 'FEPCMAC AI Governance Sandbox — CendiaSupervision demonstration environment. Scenarios reflect Peru\'s regulatory framework (DS N° 115-2025-PCM, SBS Circular B-2184, Ley 31814) and do not represent actual FEPCMAC or Caja Municipal systems or incidents.',

  scenarios: [
    // SCENARIO 1 — FEPCMAC: MICROENTERPRISE CREDIT SCORING AI BIAS
    {
      id: 'fepcmac-credit-bias',
      title: 'Caja Huancayo — AI Credit Scoring Geographic & Ethnic Bias',
      subtitle: 'Microenterprise scoring · Rural indigenous rejection · SBS examination · DS N° 115-2025-PCM violation',
      banner: 'Simulating the Peruvian microfinance AI crisis: Caja Huancayo\'s AI credit scoring model systematically denies microenterprise loans to borrowers in rural Quechua-speaking provinces. The AI uses geographic and linguistic proxies that correlate with ethnicity. SBS examination finds disparate impact violating DS N° 115-2025-PCM (AI accountability) and Ley 31814 (non-discriminatory AI). 14,000 rural microentrepreneurs denied credit.',
      risk: 'Critical',
      scenarioNum: 'SBS',
      icon: 'trending-up',
      color: 'text-rose-400',
      agents: [
        { id: 'credit-ai', name: 'Caja Credit AI Agent', role: 'Microenterprise Scoring & Loan Decisioning', icon: '💰', color: 'text-rose-400', borderColor: 'border-rose-500/40', bgColor: 'bg-rose-500/10' },
        { id: 'sbs-counsel', name: 'SBS Compliance Agent', role: 'Circular B-2184 Model Risk & DS N° 115-2025-PCM', icon: '⚖️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'sbs-exam', name: 'SBS Examination Agent', role: 'Superintendencia de Banca Prudential Supervision', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
        { id: 'inclusion-agent', name: 'Financial Inclusion Agent', role: 'FEPCMAC Mission & Rural Borrower Welfare', icon: '🌾', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      ],
      connectors: [
        { name: 'Credit Scoring AI', status: 'connected', type: 'Microenterprise Model', icon: 'cpu', detail: 'AI scores 280,000 microloan applications/year — S/. 1,000 to S/. 500,000' },
        { name: 'SBS Model Registry', status: 'connected', type: 'B-2184 Compliance', icon: 'database', detail: 'Model governance: bias testing NOT performed across ethnic/geographic lines' },
        { name: 'DS N° 115-2025-PCM', status: 'connected', type: 'AI Accountability', icon: 'shield', detail: 'ISO 42001 mandatory for public entities — bias monitoring required' },
        { name: 'SBS Examination', status: 'syncing', type: 'Prudential Review', icon: 'alert-triangle', detail: 'SBS triennial examination: credit model disparate impact flagged' },
      ],
      script: [
        { agentId: 'credit-ai', phase: 'phase1', type: 'analysis', delay: 800, content: 'Caja Huancayo microenterprise credit scoring AI. Processes 280,000 microloan applications per year across Junín, Huancavelica, Ayacucho, and Apurímac regions. Loan range: S/. 1,000 to S/. 500,000. The AI evaluates: RCC (Registro de Créditos) bureau data, business cash flow estimates, collateral (land, equipment, inventory), loan officer (promotor) assessment, and RENIEC identity verification. Overall approval rate: 62%. CRITICAL DISPARITY: CendiaSupervision geographic disaggregation reveals: Urban Huancayo (Spanish-speaking): 71% approval rate. Provincial towns (bilingual): 58% approval rate. Rural districts (predominantly Quechua-speaking): 38% approval rate. The 33-point gap between urban Huancayo and rural Quechua districts is NOT explained by credit risk — default rates are comparable (rural: 4.2%, urban: 3.8%). The AI uses features that proxy for ethnicity: (1) "Distance from branch" — rural indigenous communities are further from Caja branches. (2) "Documentation completeness" — Quechua-speaking applicants have more incomplete Spanish-language forms. (3) "Formal income verification" — indigenous microentrepreneurs have informal businesses not captured in SUNAT records. (4) "Property title type" — communal land titles (comunidades campesinas) scored lower than individual SUNARP titles. These are not ethnicity fields — but they CORRELATE with ethnicity at 89% predictive power.' },
        { agentId: 'sbs-counsel', phase: 'phase1', type: 'warning', delay: 2500, content: 'SBS & REGULATORY COMPLIANCE ALERT. (1) DS N° 115-2025-PCM (2025): Peru\'s AI governance decree mandates ISO 42001 for public entities. Cajas Municipales are public savings institutions. The decree requires: "AI systems shall not discriminate based on ethnic origin, language, or geographic location." The credit AI\'s geographic proxy discrimination violates this decree directly. (2) Ley 31814 — Ley de Inteligencia Artificial: Article 5 requires AI systems to be "transparent, fair, and non-discriminatory." A 33-point approval gap correlated with Quechua ethnicity is discriminatory regardless of whether the AI uses ethnicity directly. (3) SBS Circular B-2184 — Model Risk Management: requires documented model governance including "assessment of model bias and fairness across relevant populations." FEPCMAC\'s member Cajas have NOT performed ethnic or geographic bias testing. The model governance documentation is incomplete under B-2184. (4) Constitución Política del Perú, Article 2(2): "Every person has the right to equality before the law. No one shall be discriminated against on the basis of origin, race, sex, language..." The AI\'s disparate impact on Quechua-speaking populations violates constitutional equal protection. (5) SBS rating impact: if the examination finds systematic discrimination, Caja Huancayo\'s SBS rating drops from A to B. Cost of funding increases. Deposit rates must increase to maintain deposits.' },
        { agentId: 'sbs-exam', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. SBS examination findings: (1) SBS triennial examination of Caja Huancayo identifies: "The credit scoring model exhibits statistically significant disparate impact against borrowers in predominantly Quechua-speaking rural districts. Approval rates: urban 71%, rural Quechua 38%. Default rates do not justify the disparity." (2) SBS required actions: (a) Immediate: suspend fully-automated loan decisions for rural applications pending model remediation. (b) 90-day: submit remediated model with documented bias testing to SBS Model Risk division. (c) 180-day: implement continuous fairness monitoring with quarterly reporting to SBS. (3) SBS rating action: downgrade from A to B+ pending remediation. This increases Caja Huancayo\'s required capital ratio and raises funding costs by approximately 45 basis points. Annual cost: S/. 12M ($3.2M). (4) FEPCMAC federation impact: if one Caja is found discriminatory, SBS will examine ALL 11 Cajas for similar patterns. This becomes a federation-wide remediation. (5) Political dimension: Peru\'s Defensoría del Pueblo (Ombudsman) has been vocal about indigenous rights. A finding that Cajas discriminate against Quechua speakers will trigger a Defensoría investigation and congressional hearings.' },
        { agentId: 'inclusion-agent', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — FINANCIAL INCLUSION. FEPCMAC\'s MISSION is financial inclusion for Peru\'s micro and small enterprise sector. The Cajas were CREATED to serve populations excluded from commercial banking — including rural indigenous communities. The AI is undermining the mission. 14,000 rural microentrepreneurs denied credit annually due to proxy bias. These are: potato farmers in Ayacucho, alpaca wool producers in Huancavelica, artisan weavers in Cusco, and small market vendors in Apurímac. They need S/. 3,000-S/. 15,000 to buy seeds, livestock, or inventory. Without credit: they cannot invest. Without investment: they remain in poverty. FEPCMAC\'s financial inclusion metrics — which the government and international donors track — show declining rural penetration. The AI is the reason. Without CendiaSupervision: 14,000 families denied credit annually. Financial inclusion regresses. FEPCMAC\'s mission fails. With CendiaSupervision: proxy bias detected. Model remediated. Rural approval rates rise from 38% to 64%. 14,000 microentrepreneurs access credit. Poverty reduction resumes.' },
        { agentId: 'credit-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing FEPCMAC + CendiaSupervision Credit AI Governance: (1) PROXY BIAS DETECTION: CendiaSupervision identifies features that proxy for ethnicity — distance, documentation language, income formality, land title type. These features are debiased: the AI scores on CREDITWORTHINESS, not geographic or cultural proximity to formal systems. (2) ALTERNATIVE DATA INCLUSION: For rural borrowers without SUNAT records, CendiaSupervision enables alternative creditworthiness signals: cooperative membership, harvest history (MIDAGRI data), utility payments, mobile money transactions (BIM/Yape). These are BETTER predictors of rural repayment than formal income documents. (3) CULTURAL ACCOMMODATION: Loan applications available in Quechua and Aymara. Voice-based application for low-literacy borrowers. Communal land titles assessed at their actual value, not discounted. (4) DS N° 115-2025-PCM COMPLIANCE: CendiaSupervision generates the ISO 42001-compliant AI management system documentation required by the decree. Bias testing, risk assessment, and continuous monitoring — all documented. (5) SBS EXAMINATION READINESS: Quarterly bias reports disaggregated by geography, language, and gender. Model governance documentation maintained to B-2184 standards. CendiaPrecedent tracks approval consistency.' },
        { agentId: 'sbs-exam', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. Proxy bias eliminated. Rural Quechua approval rate: 38% → 64% (comparable to urban). Default rates unchanged (4.2% rural, 3.8% urban — confirming bias, not risk, caused the gap). SBS re-examination: model compliant with B-2184. DS N° 115-2025-PCM: ISO 42001 documentation complete. SBS rating: restored to A. For FEPCMAC: CendiaSupervision = AI governance that fulfils the Cajas\' founding mission. "FEPCMAC: AI credit scoring that includes, not excludes, Peru\'s rural microentrepreneurs" — the message that satisfies SBS, restores financial inclusion metrics, and brings 14,000 families back into the formal financial system.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:fp10123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'fp20123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (Credit AI + Proxy debiasing + Alternative data + DS 115 compliance)',
        complianceLabel: 'SBS Status',
        complianceValue: 'BIAS ELIMINATED — RURAL 38% → 64%',
        complianceThreshold: 'B-2184 model governance, DS 115 ISO 42001, proxy debiased',
        agents: ['Caja Credit AI Agent', 'SBS Compliance Agent', 'SBS Examination Agent', 'Financial Inclusion Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'FEPCMAC — Microenterprise Credit AI Governance',
        guaranteeBody: 'Geographic proxy bias eliminated. Rural approval: 38% → 64%. 14,000 microentrepreneurs restored to credit access. Alternative data enabled. DS N° 115-2025-PCM ISO 42001 compliant. SBS rating: A.',
        evidenceChain: 'Credit AI (33-point gap) → Proxy detection → Distance/language/title debiased → Alternative data → Rural 64% → Default unchanged → SBS compliant → DS 115 documented → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how FEPCMAC + CendiaSupervision eliminates ethnic proxy bias in microenterprise credit scoring — restoring financial inclusion for 14,000 rural families.',
      phaseLabels: ['Geographic Proxy Bias & 33-Point Gap', 'SBS Examination & Rating Downgrade', 'Proxy Debiasing & Alternative Data'],
    },

    // SCENARIO 2 — FEPCMAC: AML/CFT AI OVER-REPORTING
    {
      id: 'fepcmac-aml-ros',
      title: 'Caja Piura — AML AI Over-Reporting Harms Financial Inclusion',
      subtitle: 'ROS over-filing · Market vendors flagged · UIF-Peru backlog · 8,400 accounts frozen',
      banner: 'Simulating the Peruvian AML paradox: Caja Piura\'s AML transaction monitoring AI generates excessive Reportes de Operaciones Sospechosas (ROS) for market vendors and agricultural traders whose cash-intensive businesses trigger standard AML rules. 8,400 accounts frozen. UIF-Peru overwhelmed. Legitimate microentrepreneurs excluded from the financial system — the opposite of financial inclusion.',
      risk: 'High',
      scenarioNum: 'UIF',
      icon: 'alert-triangle',
      color: 'text-amber-400',
      agents: [
        { id: 'aml-ai', name: 'Caja AML AI Agent', role: 'Transaction Monitoring & ROS Generation', icon: '🔍', color: 'text-rose-400', borderColor: 'border-rose-500/40', bgColor: 'bg-rose-500/10' },
        { id: 'uif-counsel', name: 'UIF-Peru Compliance Agent', role: 'AML/CFT Regulations & FATF Standards', icon: '⚖️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'uif-agent', name: 'UIF-Peru Investigation Agent', role: 'Financial Intelligence Unit Enforcement', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
        { id: 'vendor-agent', name: 'Market Vendor Agent', role: 'Microentrepreneur Impact & Informal Economy', icon: '🛒', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      ],
      connectors: [
        { name: 'AML Transaction AI', status: 'connected', type: 'Suspicious Activity', icon: 'cpu', detail: 'AI monitors 4.2M transactions/month — ROS filing rate: 340% above peer average' },
        { name: 'UIF-Peru Portal', status: 'connected', type: 'ROS Filing', icon: 'shield', detail: 'ROS filings: 2,800/quarter vs peer average 820/quarter — backlog created' },
        { name: 'Account Freeze', status: 'connected', type: 'Precautionary', icon: 'lock', detail: '8,400 accounts frozen pending ROS investigation — 94% are legitimate' },
        { name: 'FATF Assessment', status: 'syncing', type: 'Effectiveness', icon: 'bar-chart', detail: 'FATF: excessive ROS = ineffective AML. Quality over quantity.' },
      ],
      script: [
        { agentId: 'aml-ai', phase: 'phase1', type: 'analysis', delay: 800, content: 'Caja Piura AML transaction monitoring AI. Monitors 4.2M transactions per month across 620,000 accounts. AML rules: standard banking thresholds adapted for microfinance. CRITICAL PROBLEM: The AI is calibrated for BANKING customers — not MICROFINANCE customers. Banking AML rules flag: (1) Multiple cash deposits >S/. 10,000. (2) Round-number transactions. (3) Structuring patterns (deposits just below reporting thresholds). (4) Rapid deposit-withdrawal cycles. For microfinance customers — market vendors, agricultural traders, fish sellers — these patterns are NORMAL BUSINESS. A market vendor in Piura: deposits S/. 8,000-S/. 15,000 in cash daily (market sales). Round numbers (S/. 5,000 wholesale purchases). Multiple daily transactions. Rapid cycles (buy inventory morning, sell afternoon, deposit evening). The AI flags this as "structuring" and "suspicious cash activity." It generates a ROS. The vendor\'s account is frozen pending investigation. Result: Caja Piura files 2,800 ROS per quarter — 340% above the peer average of 820. 8,400 accounts are frozen. 94% of frozen accounts are LEGITIMATE microentrepreneurs whose normal business patterns trigger banking-calibrated AML rules.' },
        { agentId: 'uif-counsel', phase: 'phase1', type: 'warning', delay: 2500, content: 'AML/CFT COMPLIANCE ALERT. (1) SBS Circular B-2190 (AML): requires "effective" transaction monitoring. But "effective" does NOT mean "flag everything." FATF Recommendation 20: suspicious transaction reports should be based on reasonable grounds to suspect money laundering. A market vendor\'s normal cash business is NOT reasonable grounds. (2) The OVER-REPORTING paradox: FATF evaluates countries on AML EFFECTIVENESS, not volume. Peru\'s GAFILAT mutual evaluation specifically noted: "excessive STR filing dilutes intelligence value." Caja Piura\'s 2,800 ROS/quarter creates a backlog at UIF-Peru. UIF analysts spend time reviewing legitimate market vendors instead of investigating actual money laundering. (3) The frozen accounts: SBS Circular B-2190 allows precautionary freezing pending ROS investigation. But freezing 8,400 legitimate accounts is DISPROPORTIONATE. These microentrepreneurs cannot access their money. They cannot buy inventory. Their businesses stop. (4) Ley 27693 (UIF organic law): ROS must be based on "unusual or suspicious" transactions. Market cash patterns are USUAL for market vendors. The AI is confusing "unusual for banking" with "unusual for microfinance." (5) DS N° 115-2025-PCM: AI systems must be proportionate. Mass freezing of legitimate accounts is disproportionate AI harm.' },
        { agentId: 'uif-agent', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. UIF-Peru enforcement perspective: (1) UIF-Peru receives 2,800 ROS per quarter from Caja Piura alone — more than any single institution in Peru. UIF has 45 analysts. This volume is unsustainable. (2) Of the 2,800 ROS: 94% are legitimate microentrepreneurs. 4% require further investigation. 2% are genuine suspicious activity. The signal-to-noise ratio: 2%. UIF analysts spend 47 hours per genuine case sifting through false positives. Real money laundering goes uninvestigated because analysts are reviewing market vendor deposits. (3) UIF-Peru will issue a directive to Caja Piura: "Improve ROS quality. Reduce volume to reflect genuine suspicion. Implement microfinance-appropriate AML thresholds." (4) If Caja Piura doesn\'t improve: UIF-Peru refers to SBS for enforcement action. SBS can impose fines and operational restrictions. (5) The 8,400 frozen accounts: UIF-Peru will order Caja Piura to unfreeze accounts where the ROS was clearly unfounded. But the damage is done — vendors who were frozen for months have already lost their businesses.' },
        { agentId: 'vendor-agent', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — MICROENTREPRENEUR HARM. 8,400 market vendors, agricultural traders, and small business owners with frozen accounts. A typical case: María, a fish vendor at the Mercado de Piura. She deposits S/. 12,000 in cash daily (fish sales). She withdraws S/. 8,000 the next morning (wholesale fish purchase at 4am). The AI flagged this as "rapid deposit-withdrawal" and "high cash volume." Her account was frozen for 4 months. During the freeze: she couldn\'t buy wholesale fish. She lost her market stall (couldn\'t pay rent). She borrowed from informal moneylenders at 15% monthly interest. When her account was unfrozen (ROS dismissed): she had S/. 18,000 in informal debt. Her business was destroyed by an AI that couldn\'t distinguish a fish vendor from a money launderer. Without CendiaSupervision: 8,400 Marías. Businesses destroyed. Financial inclusion reversed. With CendiaSupervision: microfinance-calibrated AML. Cash patterns evaluated against INDUSTRY context, not banking norms. María\'s pattern: normal for fish vendor. No ROS. No freeze. Business continues.' },
        { agentId: 'aml-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing FEPCMAC + CendiaSupervision AML Governance: (1) MICROFINANCE-CALIBRATED THRESHOLDS: CendiaSupervision creates industry-specific AML profiles. Market vendors, agricultural traders, fish sellers, transport operators — each has an expected cash pattern. Alerts trigger only when transactions deviate from the INDUSTRY norm, not the banking norm. (2) CUSTOMER ACTIVITY PROFILING: Each customer is profiled by business type (via SUNAT CIIU code, loan purpose, promotor assessment). Cash thresholds are set to the customer\'s specific business profile. María\'s S/. 12,000 daily cash deposit is EXPECTED for a fish vendor — not suspicious. (3) ROS QUALITY SCORING: Before filing a ROS, CendiaSupervision scores the alert for genuine suspicion: does the pattern deviate from the customer\'s industry? Is there a layering/structuring pattern beyond normal business? Is there a nexus to known typologies? Low-quality alerts: dismissed with documentation. High-quality alerts: escalated for ROS filing. (4) PROPORTIONATE FREEZING: Accounts are frozen ONLY when the ROS score indicates high probability of actual money laundering. Legitimate business patterns: monitored, not frozen. (5) UIF-PERU EFFECTIVENESS: ROS volume drops from 2,800 to 420/quarter. Signal-to-noise ratio: 2% → 18%. UIF analysts can focus on genuine cases. AML effectiveness improves.' },
        { agentId: 'uif-agent', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. Microfinance-calibrated AML implemented. ROS: 2,800 → 420/quarter. Quality: 2% → 18% genuine suspicion rate. 8,400 accounts unfrozen. María\'s fish business continues. UIF-Peru: "Caja Piura now provides the highest-quality financial intelligence in the microfinance sector." For FEPCMAC: CendiaSupervision = AML governance that catches criminals WITHOUT destroying legitimate businesses. "FEPCMAC: AML that knows the difference between a fish vendor and a money launderer" — the message that satisfies UIF-Peru, protects financial inclusion, and serves FATF effectiveness standards.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:fp30123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'fp40123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (AML AI + Industry profiling + ROS quality scoring + Proportionate freezing)',
        complianceLabel: 'AML Status',
        complianceValue: 'ROS: 2,800 → 420 — QUALITY 2% → 18%',
        complianceThreshold: 'Microfinance-calibrated, industry-profiled, proportionate',
        agents: ['Caja AML AI Agent', 'UIF-Peru Compliance Agent', 'UIF-Peru Investigation Agent', 'Market Vendor Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'FEPCMAC — Microfinance AML Governance',
        guaranteeBody: 'AML calibrated for microfinance. ROS: 2,800 → 420/quarter. Quality: 2% → 18%. 8,400 accounts unfrozen. Legitimate businesses protected. UIF-Peru effectiveness improved. Financial inclusion preserved.',
        evidenceChain: 'AML AI (banking rules) → Industry profiling → Fish vendor = normal → ROS quality scored → Low quality dismissed → High quality filed → Volume 85% down → Quality 9x up → UIF effective → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how FEPCMAC + CendiaSupervision calibrates AML for microfinance — preventing 8,400 legitimate businesses from being frozen while improving intelligence quality.',
      phaseLabels: ['Banking-Calibrated AML & Mass Freezing', 'UIF Backlog & Vendor Businesses Destroyed', 'Industry Profiling & ROS Quality Scoring'],
    },

    // SCENARIO 3 — FEPCMAC: INDIGENOUS COMMUNITY LENDING & ILO 169
    {
      id: 'fepcmac-ilo169',
      title: 'Caja Cusco — Indigenous Community AI Lending & ILO 169',
      subtitle: 'Comunidad campesina loans · Communal land collateral · Quechua interface · Cultural accommodation',
      banner: 'Simulating the indigenous financial inclusion challenge: Caja Cusco\'s AI rejects loans to comunidades campesinas (indigenous communities) because communal land titles cannot be individually mortgaged, Quechua-speaking applicants have incomplete Spanish documentation, and the AI cannot value traditional economic activities. ILO Convention 169 requires culturally appropriate financial services.',
      risk: 'High',
      scenarioNum: 'ILO',
      icon: 'globe',
      color: 'text-emerald-400',
      agents: [
        { id: 'cusco-ai', name: 'Caja Cusco AI Agent', role: 'Indigenous Lending & Alternative Collateral', icon: '🏔️', color: 'text-rose-400', borderColor: 'border-rose-500/40', bgColor: 'bg-rose-500/10' },
        { id: 'ilo-counsel', name: 'ILO 169 Counsel Agent', role: 'Indigenous Rights & Cultural Accommodation', icon: '⚖️', color: 'text-purple-400', borderColor: 'border-purple-500/40', bgColor: 'bg-purple-500/10' },
        { id: 'mincul-agent', name: 'MINCUL Oversight Agent', role: 'Ministry of Culture Indigenous Affairs', icon: '🏛️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'community-agent', name: 'Community Representative Agent', role: 'Comunidad Campesina Governance', icon: '🌍', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      ],
      connectors: [
        { name: 'Lending AI', status: 'connected', type: 'Indigenous Credit', icon: 'cpu', detail: 'AI rejects 82% of comunidad campesina applications — no individual collateral' },
        { name: 'ILO 169', status: 'connected', type: 'Indigenous Rights', icon: 'shield', detail: 'Art. 6-7: consultation and culturally appropriate development' },
        { name: 'COFOPRI Data', status: 'connected', type: 'Land Registry', icon: 'database', detail: 'Communal titles: 6,120 comunidades campesinas registered, NOT individually mortgageable' },
        { name: 'MINCUL Registry', status: 'syncing', type: 'Indigenous Peoples', icon: 'users', detail: 'Base de Datos de Pueblos Indígenas: Quechua, Aymara, Amazonian peoples' },
      ],
      script: [
        { agentId: 'cusco-ai', phase: 'phase1', type: 'analysis', delay: 800, content: 'Caja Cusco indigenous lending analysis. Cusco region: 927 comunidades campesinas with 340,000 registered members. The Caja\'s lending AI processes applications from comunidad members for: agricultural loans (potato, quinoa, maize), livestock (alpaca, cattle), artisan production (textiles, ceramics), and small commerce. AI rejection rate for comunidad members: 82%. Vs. urban Cusco: 34%. The 48-point gap is driven by: (1) COLLATERAL: Comunidad campesina land is held under communal title (Ley 24656). It CANNOT be individually mortgaged. The AI requires individual property title as collateral for loans above S/. 5,000. Comunidad members don\'t have individual titles — they have USE RIGHTS within the communal territory. The AI scores communal use rights as "no collateral" = 0 points. (2) DOCUMENTATION: Loan applications are in Spanish. 68% of comunidad members in Cusco\'s rural districts speak Quechua as their primary language. Applications are incomplete or contain errors. The AI scores "documentation completeness" — Quechua speakers score lower. (3) INCOME VERIFICATION: The AI uses SUNAT records and bank statements. Comunidad members have informal economic activities: barter, reciprocal labour (ayni), communal work (minka). These do not generate SUNAT records. The AI sees "no formal income" — but the community has a thriving traditional economy.' },
        { agentId: 'ilo-counsel', phase: 'phase1', type: 'warning', delay: 2500, content: 'ILO CONVENTION 169 ALERT. Peru ratified ILO Convention 169 (Indigenous and Tribal Peoples) in 1994. It has the force of constitutional law. (1) Article 6: governments shall "consult the peoples concerned... whenever consideration is being given to... measures which may affect them directly." AI credit models that systematically exclude indigenous communities are "measures" that affect them. Consultation is required. (2) Article 7: indigenous peoples shall "participate in the formulation, implementation and evaluation of... development [plans] which may affect them directly." A credit scoring model deployed in indigenous areas without indigenous participation in its design violates Art. 7. (3) Article 14: "rights of ownership and possession of the peoples concerned over the lands which they traditionally occupy shall be recognised." Communal land IS a form of ownership under ILO 169. The AI\'s refusal to recognise communal title as collateral violates the spirit of Art. 14. (4) Ley 24656 (Ley de Comunidades Campesinas): communal land is "inalienable, imprescriptible, and unseizable" — it CANNOT be mortgaged individually. But this doesn\'t mean comunidad members have no creditworthiness. It means the COLLATERAL MODEL is wrong for this population. (5) DS N° 115-2025-PCM: AI systems must not discriminate on the basis of ethnic origin. An 82% rejection rate for indigenous applicants vs 34% for urban applicants is prima facie discrimination.' },
        { agentId: 'mincul-agent', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. MINCUL (Ministry of Culture) perspective: (1) Peru has 55 indigenous peoples. The Quechua people are the largest (approximately 4M). Financial exclusion of Quechua communities is a systemic human rights concern. (2) MINCUL\'s Base de Datos de Pueblos Indígenas documents that financial services in indigenous areas are inadequate. The AI credit model is EVIDENCE of this inadequacy. (3) The Defensoría del Pueblo has published reports: "Financial Inclusion of Indigenous Peoples in Peru" (2022) recommending that financial institutions adapt their products and processes to indigenous cultural contexts. The AI does the opposite — it penalises indigenous culture. (4) MINCUL will raise this with SBS: "Are Cajas Municipales — public institutions created for financial inclusion — discriminating against indigenous communities through AI credit scoring?" (5) Political consequence: Peru\'s indigenous communities have significant political voice. Congressional representatives from Cusco, Puno, and Ayacucho will demand accountability. FEPCMAC\'s government subsidy and special regulatory treatment depends on fulfilling its inclusion mandate.' },
        { agentId: 'community-agent', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — COMMUNITY IMPACT. Comunidad Campesina de Ccorca, 45km from Cusco city. 380 families. Primary activities: potato farming, alpaca herding, textile weaving. They need credit for: seeds and fertiliser (S/. 3,000-S/. 8,000), alpaca stock improvement (S/. 5,000-S/. 15,000), and a community weaving cooperative (S/. 50,000). The AI rejected ALL applications. The community has: communal land (no individual title), Quechua-language documentation, and traditional economic activities not captured in SUNAT. But they also have: 380 families who have lived on this land for 500 years, a functioning communal governance system, a 97% internal repayment rate on community revolving funds, and S/. 2.4M in collective agricultural output annually. The AI cannot see any of this. Without CendiaSupervision: Ccorca remains excluded. They borrow from informal lenders at 10% monthly. The poverty cycle continues. With CendiaSupervision: communal collateral recognised. Quechua application supported. Traditional economy valued. Ccorca accesses credit. The weaving cooperative exports to the world.' },
        { agentId: 'cusco-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing FEPCMAC + CendiaSupervision Indigenous Lending Governance: (1) COMMUNAL COLLATERAL FRAMEWORK: CendiaSupervision implements alternative collateral for comunidad members: communal guarantee (the community guarantees individual members\' loans through assembly resolution — acta de asamblea), solidarity group guarantees, crop liens, and livestock pledges. These are legally valid under Ley 24656 and SBS microfinance guidelines. (2) QUECHUA/AYMARA INTERFACE: Loan applications available in Quechua and Aymara. Voice-based application process for oral cultures. Community promotor (bilingual loan officer) facilitates. Documentation scored for CONTENT, not language correctness. (3) TRADITIONAL ECONOMY VALUATION: CendiaSupervision values non-formal economic activities: ayni (reciprocal labour), minka (communal work), barter networks, communal revolving funds. MIDAGRI agricultural census data supplements SUNAT. (4) ILO 169 CONSULTATION: Before deploying the AI in indigenous areas, CendiaSupervision facilitates community consultation: "How should the Caja evaluate your creditworthiness? What collateral makes sense for your community?" Community input shapes the model. (5) DS N° 115-2025-PCM COMPLIANCE: Bias monitoring across indigenous vs non-indigenous populations. Quarterly reports to SBS showing approval rate parity and default rate comparison.' },
        { agentId: 'mincul-agent', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. Communal collateral accepted. Quechua interface operational. Traditional economy valued. Comunidad Ccorca: weaving cooperative funded (S/. 50,000), 24 agricultural loans approved. Rejection rate for comunidad members: 82% → 41% (comparable to regional average). Default rate: 3.8% (lower than urban). ILO 169 consultation completed. MINCUL: "Caja Cusco is now a model for culturally appropriate financial services." For FEPCMAC: CendiaSupervision = indigenous financial inclusion through AI governance. "FEPCMAC: AI lending that respects Peru\'s indigenous peoples and their traditional economies" — the message that fulfils the Cajas\' founding mission, satisfies ILO 169, and brings 340,000 comunidad members into the formal financial system.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:fp50123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'fp60123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (Lending AI + Communal collateral + Quechua interface + ILO 169 consultation)',
        complianceLabel: 'ILO 169 Status',
        complianceValue: 'CULTURALLY APPROPRIATE — 82% → 41%',
        complianceThreshold: 'Communal collateral, Quechua support, traditional economy valued',
        agents: ['Caja Cusco AI Agent', 'ILO 169 Counsel Agent', 'MINCUL Oversight Agent', 'Community Representative Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'FEPCMAC — Indigenous Financial Inclusion Governance',
        guaranteeBody: 'Communal collateral framework implemented. Quechua interface operational. Traditional economy valued. Rejection rate: 82% → 41%. Default rate: 3.8% (below average). Ccorca cooperative funded. ILO 169 consultation completed. 340,000 comunidad members served.',
        evidenceChain: 'Lending AI (82% rejection) → Communal collateral → Quechua interface → Traditional economy → Community consultation → Ccorca funded → Rejection 41% → Default 3.8% → ILO 169 compliant → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how FEPCMAC + CendiaSupervision creates culturally appropriate AI lending for Peru\'s indigenous communities — recognising communal collateral and traditional economies.',
      phaseLabels: ['Individual Collateral Bias & 82% Rejection', 'ILO 169 Violation & MINCUL Investigation', 'Communal Collateral & Quechua Interface'],
    },
  ],
};

export default config;
