/**
 * FPF Peru Sandbox — Spanish (Español) Scenarios
 * @module pages/sandbox/configs/fpf-peru-es
 */

// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.

import type { TemplateScenario } from '../SandboxTemplate';

export const ES_SCENARIOS: TemplateScenario[] = [
  // ESCENARIO 1
  {
    id: 'corruption-rebuild',
    title: 'Post-Lozano — Reconstrucción Institucional Bajo Escrutinio de FIFA',
    subtitle: 'Organización criminal · Normalización FIFA · Cooperación Fiscalía · Reforma de gobernanza',
    banner: 'Simulando la crisis de gobernanza institucional tras el arresto del presidente de la FPF Agustín Lozano por cargos de organización criminal, lavado de activos y soborno. La amenaza del Comité de Normalización de FIFA requiere reforma demostrable — o Perú pierde la autogobernanza de su fútbol.',
    risk: 'Critical',
    scenarioNum: 'Reforma',
    icon: 'shield-check',
    color: 'text-red-400',
    agents: [
      { id: 'governance', name: 'Agente de Gobernanza', role: 'Reforma Institucional y Cumplimiento FIFA', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'legal-fpf', name: 'Agente Legal', role: 'Cooperación con Fiscalía y Defensa Penal', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'fifa-rel', name: 'Agente Relaciones FIFA', role: 'Prevención del Comité de Normalización', icon: '🌐', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'finance-fpf', name: 'Agente Financiero', role: 'Anti-Lavado de Activos y Rastreo de Fondos', icon: '📊', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Portal de Fiscalía', status: 'connected', type: 'Investigación Penal', icon: 'shield', detail: 'Lozano + 6 funcionarios: organización criminal, lavado de activos, soborno' },
      { name: 'Dashboard FIFA', status: 'connected', type: 'Riesgo de Normalización', icon: 'globe', detail: 'Artículo 8: "preocupación seria" — ventana de 90 días' },
      { name: 'Auditoría Financiera FPF', status: 'connected', type: 'Contabilidad Forense', icon: 'database', detail: 'Registros 2019-2024 bajo revisión forense — $12M sin justificar' },
      { name: 'Cumplimiento CONMEBOL', status: 'syncing', type: 'Estándares Confederación', icon: 'check-circle', detail: 'Hitos de reforma requeridos para Q2' },
    ],
    script: [
      { agentId: 'governance', phase: 'phase1', type: 'warning', delay: 800, content: 'CRISIS INSTITUCIONAL — RIESGO DE NORMALIZACIÓN FIFA. Tras el arresto del presidente Lozano en noviembre de 2024, la FPF enfrenta la crisis de gobernanza más grave en sus 102 años. Los cargos: (1) Organización criminal (Código Penal Art. 317), (2) Lavado de activos (Ley 27765) — derechos de transmisión desviados a empresas fantasma, (3) Soborno (Código Penal Art. 393). FIFA ha colocado a la FPF en revisión de 90 días bajo el Artículo 8. Si FIFA determina que la FPF no puede autogobernarse, se nombrará un Comité de Normalización. Esto ha sucedido con CONCACAF (2015), AIFF India (2022), y AFF Afganistán (2023). Perú debe demostrar reforma en 90 días o perder el control.' },
      { agentId: 'finance-fpf', phase: 'phase1', type: 'analysis', delay: 2500, content: 'Análisis financiero forense 2019-2024: (1) $12M en gastos injustificados en 47 transacciones — pagos a intermediarios y "honorarios de consultoría" a entidades sin operaciones verificables. (2) Fondos FIFA Forward ($6M/año): 3 proyectos declarados completados pero 2 nunca construidos. Fondos mal asignados: $4.2M. (3) Derechos de transmisión Liga 1 de $28M/año licitados a un único postor — ex socio de Lozano. Valor justo: $35-40M/año. La FPF perdió $7-12M/año en ingresos. (4) Comisiones de agentes del 18-25% vs estándar de 5-10%. Daño total al fútbol peruano: estimado $40-60M en 5 años.' },
      { agentId: 'fifa-rel', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO REGISTRADO. La revisión de 90 días crea una paradoja: (1) FIFA requiere EVIDENCIA de reforma implementada. (2) La Fiscalía requiere preservación de evidencia sin cambios que puedan interpretarse como destrucción. (3) Reforma agresiva puede parecer destrucción de evidencia ante la Fiscalía. (4) Reforma lenta convencerá a FIFA de que no es genuina. El desafío: reformar VISIBLEMENTE para FIFA mientras se preserva COMPLETAMENTE para la Fiscalía. Estos objetivos parecen contradictorios — pero el enfoque de evidencia sellada de Datacendia resuelve la paradoja.' },
      { agentId: 'legal-fpf', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — Marco legal excepcionalmente complejo: (1) Derecho penal peruano: cooperar con Fiscalía, no obstruir. (2) Estatutos FIFA Art. 8: demostrar reforma o normalización. (3) CONMEBOL: cumplir hitos o perder elegibilidad en Copa Libertadores/Sudamericana. (4) Ley de asociaciones peruanas: elecciones y gobernanza deben cumplir regulaciones nacionales. La intersección de derecho penal, gobernanza FIFA, cumplimiento CONMEBOL y ley de asociaciones crea un desafío tetradimensional sin precedentes.' },
      { agentId: 'governance', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proponiendo Protocolo Post-Corrupción Datacendia: (1) PRESERVACIÓN + REFORMA SIMULTÁNEA: Cada documento de la era Lozano se sella con ML-DSA-65 ANTES de reforma. La evidencia no puede alterarse — satisface a Fiscalía. La reforma procede con documentación completa — satisface a FIFA. (2) DASHBOARD DE REFORMA FIFA: Evidencia en tiempo real de 12 hitos. (3) COOPERACIÓN FISCALÍA: Documentos sellados con marca de tiempo. (4) CUMPLIMIENTO CONMEBOL: Licencia de clubes y monitoreo financiero automáticos. (5) RECUPERACIÓN FONDOS FORWARD: $4.2M documentados para proceso de recuperación FIFA.' },
      { agentId: 'fifa-rel', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. "Preservar y luego reformar" resuelve la paradoja. La evidencia sellada da confianza a FIFA de reforma genuina, mientras da confianza a la Fiscalía de que nada se destruyó. El Dashboard de Reforma proporciona evidencia en tiempo real de 12 hitos — FIFA nunca ha visto este nivel de transparencia. Si la FPF demuestra que Datacendia puede reconstruir una institución después de la corrupción, FIFA puede recomendar la plataforma a otras federaciones en crisis.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:fp10123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'fp20123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (Auditoría forense + Cooperación Fiscalía + Hitos FIFA + CONMEBOL)',
      complianceLabel: 'Estado de Gobernanza',
      complianceValue: 'REFORMA EN PROGRESO',
      complianceThreshold: 'Artículo 8 FIFA — revisión 90 días',
      agents: ['Agente de Gobernanza', 'Agente Legal', 'Agente Relaciones FIFA', 'Agente Financiero'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'FPF Perú — Reconstrucción Post-Corrupción',
      guaranteeBody: 'Paquete criptográfico: auditoría forense ($12M, $4.2M Forward), cooperación Fiscalía, 12 hitos de reforma FIFA, cumplimiento CONMEBOL, protocolo "preservar y reformar."',
      evidenceChain: 'Arresto Lozano → Auditoría forense → Preservación (ML-DSA-65) → Hitos 1-12 → Dashboard FIFA → Fiscalía → CONMEBOL → Fondos Forward → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA navegarán la crisis post-corrupción — demostrando que reforma y preservación de evidencia pueden ocurrir simultáneamente.',
    phaseLabels: ['Crisis y Auditoría Forense', 'Paradoja FIFA/Fiscalía', 'Preservar-Luego-Reformar'],
  },

  // ESCENARIO 2
  {
    id: 'match-fixing',
    title: 'Amaño de Partidos Liga 1 — El Campeonato del Riesgo de Corrupción',
    subtitle: 'Salarios bajos · Alto volumen apuestas · Precedente Alianza · Alerta Sportradar',
    banner: 'Simulando investigación de amaño en Liga 1 — donde salarios bajos, mercados de apuestas crecientes y débil aplicación crean uno de los perfiles de riesgo más altos del fútbol mundial. La IA detecta patrones sospechosos en 3 partidos consecutivos de un club provincial.',
    risk: 'Critical',
    scenarioNum: 'Integridad',
    icon: 'alert-triangle',
    color: 'text-amber-400',
    agents: [
      { id: 'integrity-fpf', name: 'Agente de Integridad', role: 'Análisis de Patrones e Inteligencia de Apuestas', icon: '🛡️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'legal-fix', name: 'Agente Legal', role: 'Derecho Penal Peruano y Disciplina FIFA', icon: '⚖️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'betting', name: 'Agente de Apuestas', role: 'Comisión de Juego e Inteligencia de Operadores', icon: '📊', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'player-welfare', name: 'Agente de Bienestar', role: 'Condiciones Salariales y Vulnerabilidad', icon: '💚', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'Sportradar Integridad', status: 'connected', type: 'Inteligencia Apuestas', icon: 'activity', detail: 'Alerta: 3 resultados sospechosos consecutivos — Club X' },
      { name: 'Mercados Asiáticos', status: 'connected', type: 'Monitoreo Offshore', icon: 'globe', detail: '$340K en marcadores exactos en 3 partidos' },
      { name: 'Disciplinario FPF', status: 'connected', type: 'Aplicación', icon: 'shield', detail: 'Precedente 2019: investigación Alianza Lima' },
      { name: 'Fiscalía Deportiva', status: 'syncing', type: 'Investigación', icon: 'database', detail: 'Jurisdicción fraude deportivo' },
    ],
    script: [
      { agentId: 'integrity-fpf', phase: 'phase1', type: 'warning', delay: 800, content: 'ALERTA — 3 PARTIDOS SOSPECHOSOS. Sportradar señaló al Club X en 3 partidos de visitante: (1) Perdió 0-3 tras empatar al medio tiempo. $95K en "más de 2.5 goles 2do tiempo" a 4.1. (2) Perdió 1-4 ganando 1-0 al 38\'. $120K en marcador exacto 1-4 a 28:1 desde Manila. (3) Empató 2-2 ganando 2-0 al 70\'. $125K en "empate" — cuotas de 15:1 a 4:1 en 10 minutos. Confianza: 94.7%. Los mismos 3 defensores en errores críticos. Beneficio estimado: $1.2M.' },
      { agentId: 'player-welfare', phase: 'phase1', type: 'analysis', delay: 2500, content: 'VULNERABILIDAD — POR QUÉ LIGA 1 ES ALTO RIESGO. Club X: salario promedio $1,800/mes. Los 3 defensores ganan $1,200-$2,000/mes. 4 meses de atraso salarial. Auto-certificó "pagos al día" pero registros bancarios no muestran pagos. Un pago de amaño de $5,000-$10,000 = 3-8 meses de salario. Esto no es crimen sofisticado — es explotación de trabajadores vulnerables.' },
      { agentId: 'legal-fix', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO. Conflicto de jurisdicción: (1) FPF: sanciones deportivas, estándar de probabilidades. (2) Código Penal Art. 196 (fraude) o Art. 317 (crimen organizado): más allá de duda razonable. (3) MINCETUR: ley de juego subdesarrollada, apuestas offshore fuera de jurisdicción. (4) FIFA: prohibiciones globales si red internacional. Mi disenso: NO procesar jugadores sin abordar atrasos salariales. Procesar explotados ignorando violaciones laborales del club es injusto.' },
      { agentId: 'betting', phase: 'phase2', type: 'flag', delay: 2500, content: 'RED OFFSHORE: 12 cuentas en 4 plataformas (Manila, Curaçao, Malta, Isla de Man). Creadas en ventana de 3 semanas. Depósitos en cripto (Bitcoin, USDT). Retiros peer-to-peer en Perú, Colombia, Ecuador. Los defensores son el nivel más bajo de red regional que ataca ligas sudamericanas con débil aplicación.' },
      { agentId: 'integrity-fpf', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Datacendia Liga 1: (1) DOBLE VÍA: Aplicación (datos sellados para FPF y Fiscalía, 3 partidos como patrón) + Prevención (atrasos documentados, verificación bancaria obligatoria). (2) PROTECCIÓN: Defensores como sospechosos Y víctimas, sanciones reducidas por cooperación. (3) COORDINACIÓN: Evidencia para Interpol, CONMEBOL, FIFA. (4) REFORMA: Verificación salarial bancaria mensual obligatoria.' },
      { agentId: 'legal-fix', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. La doble vía aborda la justicia: el crimen se castiga, la causa se aborda, la red es objetivo. El Recibo transforma escándalo en catalizador de reforma. La FPF post-Lozano demuestra que puede investigar amaño mientras reforma las condiciones que lo habilitan.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:fp30123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'fp40123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (3 partidos + Apuestas + Salarios + Red offshore + Interpol)',
      complianceLabel: 'Integridad',
      complianceValue: 'RED IDENTIFICADA',
      complianceThreshold: '94.7% confianza — 3 partidos',
      agents: ['Agente de Integridad', 'Agente Legal', 'Agente de Apuestas', 'Agente de Bienestar'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Amaño Liga 1 — Aplicación + Prevención',
      guaranteeBody: 'Patrón 3 partidos (94.7%), red $340K (12 cuentas, 4 plataformas), atrasos Club X (4 meses), doble vía aplicación + reforma.',
      evidenceChain: 'Sportradar → Patrón → Red offshore → Salarios → Vulnerabilidad → FPF → Fiscalía → Interpol → Reforma → ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes investigarán amaño en Liga 1 — equilibrando aplicación contra jugadores vulnerables con reforma de condiciones salariales.',
    phaseLabels: ['Detección y Vulnerabilidad', 'Jurisdicción y Justicia', 'Doble Vía'],
  },

  // ESCENARIO 3
  {
    id: 'altitude-safety',
    title: 'Gobernanza de Altitud — Seguridad del Jugador a 3,400m+',
    subtitle: 'Cusco/Juliaca · Prohibición FIFA 2007 · Riesgo cardíaco · Aclimatación',
    banner: 'Simulando el desafío de seguridad único del fútbol peruano: partidos a altitud extrema (Cusco 3,400m, Juliaca 3,827m). La IA debe gobernar aclimatación, emergencias médicas y la evidencia para defender partidos en altitud si FIFA revisa la prohibición.',
    risk: 'High',
    scenarioNum: 'Altitud',
    icon: 'mountain',
    color: 'text-cyan-400',
    agents: [
      { id: 'medical-alt', name: 'Agente Médico', role: 'Fisiología de Altitud y Riesgo Cardíaco', icon: '🏥', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
      { id: 'legal-alt', name: 'Agente Legal', role: 'Regulaciones FIFA y Responsabilidad', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'sporting-alt', name: 'Agente Deportivo', role: 'Equidad Competitiva y Aclimatación', icon: '⚽', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'emergency', name: 'Agente de Emergencia', role: 'Evacuación Médica y Acceso Hospitalario', icon: '🚑', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
    ],
    connectors: [
      { name: 'Monitor de Altitud', status: 'connected', type: 'Fisiología', icon: 'heart', detail: 'SpO2 visitante: 89% a 3,400m (normal: 96-99%)' },
      { name: 'Base FIFA', status: 'connected', type: 'Investigación', icon: 'database', detail: 'Prohibición 2007 — coalición Bolivia/Perú/Ecuador' },
      { name: 'Mapa Hospitalario', status: 'connected', type: 'Emergencia', icon: 'map-pin', detail: 'Cusco: 2 hospitales cardíacos a 15 min del estadio' },
      { name: 'Protocolo Aclimatación', status: 'syncing', type: 'Bienestar', icon: 'clock', detail: 'Visitante llegó 4h antes — mínimo: 24h' },
    ],
    script: [
      { agentId: 'medical-alt', phase: 'phase1', type: 'warning', delay: 800, content: 'ALERTA MÉDICA. Partido en Estadio Garcilaso, Cusco (3,400m). Equipo visitante: SpO2 promedio 89%, 3 jugadores bajo 87% (sintomáticos), frecuencia cardíaca +18%, 2 con cefalea y náuseas (MAM). Llegaron 4h antes vs 24h recomendadas. A 3,400m la presión es 66% del nivel del mar — capacidad aeróbica reducida 15-25%.' },
      { agentId: 'sporting-alt', phase: 'phase1', type: 'analysis', delay: 2500, content: 'Equidad competitiva: locales aclimatados, visitantes con VO2max reducido 15-25%. Visitantes ganan 18% en Cusco vs 38% promedio liga. FIFA prohibió partidos sobre 2,500m en 2007 — Bolivia/Perú/Ecuador lograron reversión en 2008. Si ocurre evento cardíaco, el debate se reabre. Posición FPF: partidos en altitud son integrales al fútbol peruano SOLO si protocolos son robustos y documentados.' },
      { agentId: 'emergency', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO. Emergencia Cusco: 2 hospitales cardíacos a 15 min (ADECUADO). 1 ambulancia en estadio + 1 en hospital. Pero evacuación nocturna limitada, Lima a 1h por aire. Los 3 jugadores bajo 87% están en rango sintomático. Protocolos actuales no incluyen monitoreo SpO2 continuo durante juego. Mi disenso: 2 de 3 sintomáticos deben ser EXCLUIDOS como precaución.' },
      { agentId: 'legal-alt', phase: 'phase2', type: 'flag', delay: 2500, content: 'RESPONSABILIDAD: Si evento cardíaco: (1) ¿FPF aplicó protocolos? Llegada 4h vs 24h = fallo documentado. (2) ¿Club siguió guía? Si FPF recomendó 24h y club llegó en 4h, club es responsable primario. (3) ¿Recomendación tiene fuerza ejecutiva? Si es "recomendación" no "requisito," FPF no se absuelve. (4) FIFA examinará si gobernanza fue adecuada. Debate 2007 se reabre con Perú como ejemplo negativo.' },
      { agentId: 'medical-alt', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Datacendia: (1) Aclimatación OBLIGATORIA 24h sobre 2,500m — forfeit 3-0 por llegada tarde. (2) Evaluación SpO2 pre-partido — exclusión bajo 90% sin anulación. (3) Monitoreo SpO2 portátil durante partido — sustitución obligatoria bajo 85%. (4) Protocolo emergencia por sede sellado. (5) Evidencia FIFA: cada partido produce paquete de seguridad sellado.' },
      { agentId: 'emergency', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Aclimatación obligatoria + barreras SpO2 abordan todo: 3 sintomáticos EXCLUIDOS, problema de 4h eliminado, monitoreo en tiempo real, emergencia planificada. Para FIFA: gobernanza MÁS rigurosa que cualquier protocolo mundial. Transforma el "problema" de altitud en "escaparate" — partidos a 3,400m seguros con gobernanza adecuada.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:fp50123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'fp60123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (SpO2 + Aclimatación + Monitoreo + Emergencia)',
      complianceLabel: 'Seguridad Altitud',
      complianceValue: '3 JUGADORES EXCLUIDOS',
      complianceThreshold: 'SpO2 < 90% barrera estricta',
      agents: ['Agente Médico', 'Agente Legal', 'Agente Deportivo', 'Agente de Emergencia'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Gobernanza Altitud FPF — Seguridad a 3,400m',
      guaranteeBody: 'SpO2 pre-partido (3 excluidos < 90%), aclimatación 24h obligatoria, monitoreo portátil, protocolo emergencia por sede, defensa FIFA.',
      evidenceChain: 'Partido (3,400m) → Aclimatación 24h → SpO2 → 3 excluidos → Monitoreo → Emergencia → Revisión → ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes gobernarán seguridad a 3,400m — aclimatación obligatoria, exclusión de sintomáticos y evidencia para defender el derecho de Perú a jugar en altitud.',
    phaseLabels: ['Evaluación Médica', 'Responsabilidad y Emergencia', 'Protocolo Obligatorio'],
  },

  // ESCENARIO 4
  {
    id: 'youth-trafficking',
    title: 'Academia Juvenil — IA Detecta Trata de Menores por Redes de Agentes Falsos',
    subtitle: 'Artículo 19 FIFA · Menores de 18 · Academias falsas · 47 niños · Referencia Fiscalía',
    banner: 'Simulando la crisis de protección juvenil: análisis de IA de registros juveniles de Liga 1 revela una red de intermediarios falsos canalizando menores de provincias andinas a Lima a través de "academias" no registradas. 47 menores de 12-16 años en condiciones de explotación — sin educación, sin consentimiento parental, sin registro federativo.',
    risk: 'Critical',
    scenarioNum: 'Juvenil',
    icon: 'users',
    color: 'text-orange-400',
    agents: [
      { id: 'youth-protect', name: 'Agente de Protección Juvenil', role: 'Artículo 19 FIFA y Protección de Menores', icon: '👦', color: 'text-orange-400', borderColor: 'border-orange-500/40', bgColor: 'bg-orange-500/10' },
      { id: 'legal-youth', name: 'Agente Legal', role: 'Ley de Protección al Menor y Coordinación Fiscalía', icon: '⚖️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'registry-ai', name: 'Agente de Registro', role: 'Análisis de Base de Datos y Detección de Redes', icon: '🔍', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'welfare-youth', name: 'Agente de Bienestar Infantil', role: 'Coordinación MIMP y Reunificación Familiar', icon: '🏠', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Registro Juvenil FPF', status: 'connected', type: 'Registro Jugadores', icon: 'database', detail: '47 menores: sin consentimiento parental, sin certificados educativos' },
      { name: 'Registro de Agentes', status: 'connected', type: 'Base FIFA', icon: 'users', detail: '5 "agentes" — sin licencia FIFA, 3 con condenas por fraude' },
      { name: 'Portal MIMP', status: 'connected', type: 'Protección Infantil', icon: 'shield', detail: 'Ministerio de la Mujer — unidad contra trata' },
      { name: 'Fiscalía Especializada', status: 'syncing', type: 'Investigación', icon: 'alert-triangle', detail: 'Trata de personas (Ley 28950) — agravante por menores' },
    ],
    script: [
      { agentId: 'registry-ai', phase: 'phase1', type: 'warning', delay: 800, content: 'ANOMALÍA EN REGISTRO JUVENIL. La IA señaló un patrón en 47 menores de 12-16 años: (1) Los 47 registrados en 8 meses en 4 "academias" de Lima — Academia Futuro Dorado, Escuela de Talentos Perú, Centro de Formación Nacional, Academia Estrellas del Sur. Ninguna registrada en FPF. (2) Los 47 de Cusco, Puno y Huancavelica — las regiones más pobres. (3) 47/47 sin consentimiento parental válido (firmas fotocopiadas, direcciones no coinciden). (4) 0/47 con matrícula escolar (Ley 28044). (5) 5 "representantes" para los 47 — ninguno con licencia FIFA, 3 con condenas por estafa. (6) Los 5 reclutaron a los 47 de comunidades rurales prometiendo carreras futbolísticas y educación en Lima. Las familias no recibieron contratos escritos ni comunicación posterior.' },
      { agentId: 'welfare-youth', phase: 'phase1', type: 'analysis', delay: 2500, content: 'EVALUACIÓN DE BIENESTAR. Investigación de campo: (1) Futuro Dorado (SJL): 14 menores en una casa. Sin instalaciones. Niños venden caramelos en buses para "contribuir." (2) Talentos Perú (VES): 12 menores. 2 con desnutrición. Ninguno en escuela. (3) Formación Nacional (Ate): 11 menores. "Entrenador" sin credenciales. 6h/día en cancha de tierra. Sin exámenes médicos. (4) Estrellas del Sur (Chorrillos): 10 menores. 3 menores de 13 años. Las "academias" son operaciones de retención — muestran niños a clubes. Si fichan: el "agente" toma 40-60%. Si no: los niños permanecen en explotación. 8 llevan más de 6 meses sin colocación ni educación.' },
      { agentId: 'legal-youth', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO. Se requiere acción INMEDIATA: (1) Ley 28950 (Trata): reclutar menores con falsas promesas, transportarlos y explotar su trabajo = trata. Agravante por menores: 12-20 años de pena. (2) Artículo 19 FIFA: protección de menores aplica — FPF debe aplicar protecciones equivalentes domésticamente. (3) Ley 28044: matrícula obligatoria. 0/47 = violación masiva que activa MINEDU. (4) Ley 27337: derecho a vivir con la familia. Separación sin autorización judicial. Mi disenso: la FPF debe referir a la Fiscalía Especializada contra Trata de Personas INMEDIATAMENTE y coordinar con MIMP. Cada día de demora es un día más de explotación.' },
      { agentId: 'youth-protect', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — FALLO SISTÉMICO. No es incidente aislado: (1) FPF sin verificación obligatoria para academias. Cualquiera puede crear una "academia" y registrar niños. (2) Sin referencia cruzada registro-matrícula escolar. (3) Sin verificación de agentes para transacciones juveniles. (4) Los 47 son fracción del total. El modelo: reclutar talento de familias pobres, traer a Lima, mostrar a clubes, tomar el fee o abandonar. Esto es trata futbolística — la falta de infraestructura de gobernanza juvenil de la FPF lo habilitó.' },
      { agentId: 'registry-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Datacendia de Protección Juvenil: (1) INMEDIATO: Referencia Fiscalía 24h. MIMP emergencia para 47 menores. Reunificación familiar con DEMUNA de Cusco, Puno, Huancavelica. (2) REFORMA REGISTRO: Consentimiento biométrico/notarizado, matrícula escolar, examen médico, agente con licencia o familia directa. CendiaSupervision verifica antes de aceptar. (3) ACREDITACIÓN: Academias registradas con estándares mínimos — entrenadores, educación, instalaciones, inspecciones. (4) DETECCIÓN DE REDES: Análisis continuo de patrones de registro. (5) COMUNICACIÓN FAMILIAR: Padres notificados automáticamente de cada registro/transferencia.' },
      { agentId: 'legal-youth', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Referencia inmediata + MIMP aborda la urgencia. Los 47 protegidos HOY. Evidencia sellada (anomalías, campo, antecedentes, bienestar) proporcionada a Fiscalía con cadena de custodia. Para FIFA: la FPF descubrió red de trata por IA, refirió inmediatamente, protegió niños e implementó reformas. Los niños de Perú merecen oportunidades sin explotación. CendiaSupervision asegura que el sistema los proteja.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:fp70123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'fp80123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (Anomalía registro + Investigación campo + Fiscalía + MIMP)',
      complianceLabel: 'Protección Juvenil',
      complianceValue: '47 MENORES PROTEGIDOS',
      complianceThreshold: 'Artículo 19 FIFA + Ley 28950',
      agents: ['Agente Protección Juvenil', 'Agente Legal', 'Agente de Registro', 'Agente Bienestar Infantil'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Protección Juvenil FPF — Anti-Trata',
      guaranteeBody: 'IA detectó 47 menores en academias falsas. 5 agentes sin licencia (3 con condenas). Fiscalía 24h. MIMP activado. Reunificación iniciada. Reforma registro implementada.',
      evidenceChain: 'Anomalía (47) → Agentes (5) → Campo (4 academias) → Bienestar → Fiscalía → MIMP → Reunificación → Reforma → ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes expondrán una red de trata juvenil operando a través de academias falsas — protegiendo a 47 niños y reformando el registro juvenil.',
    phaseLabels: ['Anomalía y Detección de Red', 'Protección Infantil y Acción Inmediata', 'Reforma y Protocolo Anti-Trata'],
  },

  // ESCENARIO 5
  {
    id: 'broadcast-transparency',
    title: 'Derechos de Transmisión — Auditoría Revela $7M/Año de Pago Insuficiente a Clubes',
    subtitle: 'Derechos TV · Postor único · Bajo mercado · Crisis de clubes · SBS',
    banner: 'Simulando la crisis de derechos de transmisión: análisis financiero compara el contrato de Liga 1 ($28M/año) contra mercados comparables y descubre $7-12M/año bajo valor justo. La licitación de postor único — conectada al arrestado presidente — costó millones a los clubes peruanos.',
    risk: 'Critical',
    scenarioNum: 'Derechos TV',
    icon: 'tv',
    color: 'text-blue-400',
    agents: [
      { id: 'broadcast-ai', name: 'Agente de Ingresos', role: 'Valuación de Mercado y Análisis Comparable', icon: '📺', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'legal-broadcast', name: 'Agente Legal', role: 'Forensia Contractual y Anti-Corrupción', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'club-finance', name: 'Agente Financiero Clubes', role: 'Viabilidad de Clubes y Distribución', icon: '💰', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'fifa-broadcast', name: 'Agente Relaciones FIFA', role: 'Gobernanza y Mejores Prácticas Comerciales', icon: '🌐', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'Contrato Transmisión', status: 'connected', type: 'Análisis Contractual', icon: 'file-text', detail: 'Liga 1 TV: $28M/año — postor único, sin licitación competitiva' },
      { name: 'Datos CONMEBOL', status: 'connected', type: 'Comparables', icon: 'bar-chart', detail: 'Chile $38M, Colombia $42M, Ecuador $22M' },
      { name: 'Finanzas Clubes', status: 'connected', type: 'Distribución', icon: 'database', detail: '18 clubes: 6 en crisis, 3 con atrasos salariales' },
      { name: 'Evidencia Fiscalía', status: 'syncing', type: 'Corrupción', icon: 'shield', detail: 'Licitación era Lozano: intermediario bajo investigación' },
    ],
    script: [
      { agentId: 'broadcast-ai', phase: 'phase1', type: 'warning', delay: 800, content: 'ALERTA DE INGRESOS. Análisis comparable Liga 1: (1) Contrato actual: $28M/año con GolPerú (Movistar), 2019, 5 años con auto-renovación. Postor único. (2) Comparables: Chile $38M (19M hab.), Colombia $42M (52M), Ecuador $22M (18M), Paraguay $12M (7M). (3) Perú: 34M hab., clase media creciente, cultura futbolística, selección en Mundial 2018. Valor justo: $35-40M — $7-12M/año MÁS que el contrato actual. (4) Brecha en 5 años: $35-60M total. Por club: $1.9-3.3M perdidos. Para clubes provinciales con presupuesto de $2-4M: diferencia entre viabilidad e insolvencia. (5) Auto-renovación permite que el contrato bajo mercado continúe indefinidamente.' },
      { agentId: 'legal-broadcast', phase: 'phase1', type: 'analysis', delay: 2500, content: 'FORENSIA CONTRACTUAL. La licitación revela fallos: (1) Ventana de 14 días — broadcasters internacionales (ESPN, DAZN) necesitan 60-90 días. Excluyó competencia. (2) Requisitos técnicos que solo el incumbente cumplía ("infraestructura terrestre 85% territorio"). (3) Intermediario Mediapro Perú SAC recibió 12% comisión ($3.36M/año). Beneficiario final: socio comercial de Lozano, bajo investigación de Fiscalía. (4) Comisión estándar: 3-5%. El 12% en contrato bajo mercado sugiere facilitación de resultado predeterminado. (5) Pagos intermediario en 5 años: $16.8M. Combinado con subvaluación: el fútbol peruano perdió $52-77M en 5 años por esta transacción.' },
      { agentId: 'club-finance', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO. Impacto devastador: (1) 6 de 18 clubes en dificultades financieras. 3 con atrasos de 2-4 meses. 2 en riesgo de descenso por incumplimiento. (2) Transmisión = 35-45% ingresos de clubes provinciales. Subpago de $7-12M = $389K-$667K MENOS por club/año. Para club con $2.5M: 15-27% perdido. (3) Atrasos salariales habilitan amaño (Escenario 2). Jugadores de $1,200/mes sin pagar por 4 meses son vulnerables. La cadena: subpago transmisión → atrasos → amaño. (4) Mi disenso: FPF debe terminar el contrato INMEDIATAMENTE y relicitar competitivamente. Cada mes cuesta $583K-$1M. La auto-renovación debe bloquearse. La investigación penal del intermediario no debe demorar la relicitación.' },
      { agentId: 'fifa-broadcast', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA FIFA. Licenciamiento de clubes y sostenibilidad financiera requieren gobernanza comercial transparente: (1) Derechos de transmisión = activo comercial más grande. Contrato bajo mercado con postor único e intermediario conectado políticamente = fallo de gobernanza textual. (2) Revisión de 90 días incluye transparencia de contratos comerciales. Si FIFA descubre que el contrato benefició a insiders: fortalece caso de Normalización. (3) CONMEBOL: si 6 clubes fallan viabilidad financiera por ingresos artificialmente suprimidos, podrían ser excluidos de competiciones continentales. (4) La oportunidad: relicitación transparente y documentada demuestra a FIFA que la FPF post-Lozano prioriza clubes sobre enriquecimiento de insiders.' },
      { agentId: 'broadcast-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Datacendia de Gobernanza de Transmisión: (1) INMEDIATO: Bloquear auto-renovación con notificación sellada con marca de tiempo. (2) RELICITACIÓN COMPETITIVA: 90 días, ventana internacional. Requisitos en inglés, español, portugués. CendiaSupervision sella cada etapa. (3) VALUACIÓN INDEPENDIENTE: Consultora deportiva independiente — metodología y hallazgos sellados. Meta: $35-40M. (4) PROHIBICIÓN INTERMEDIARIOS: Sin comisiones. Negociaciones directas. CendiaSupervision monitorea intermediarios no declarados. (5) DISTRIBUCIÓN TRANSPARENTE: Fórmula publicada y sellada. Informes mensuales auditables. (6) EVIDENCIA FISCALÍA: Análisis de mercado, comisiones y forensia proporcionados como evidencia para procesamiento Lozano.' },
      { agentId: 'club-finance', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Bloqueo de auto-renovación + relicitación aborda la crisis. Estimación conservadora: $35-38M/año — $7-10M más. Por club: $389-556K adicionales. Los 6 en crisis resuelven atrasos en 3 meses y viabilidad en 12. La vulnerabilidad de amaño (Escenario 2) se reduce porque se paga a tiempo. Para FIFA: la relicitación sellada es la evidencia más fuerte de reforma comercial. Cada paso transparente e inmutable. La FPF post-Lozano demuestra que los derechos de transmisión sirven a CLUBES Y AFICIONADOS, no a insiders. CendiaSupervision transforma la transacción más corrupta de Perú en la más transparente.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:fp90123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'fpa0123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (Valuación + Forensia licitación + Relicitación + Distribución + Fiscalía)',
      complianceLabel: 'Gobernanza Comercial',
      complianceValue: '$7-12M/AÑO SUBPAGO PROBADO',
      complianceThreshold: 'Valor justo: $35-40M. Actual: $28M. Relicitación iniciada.',
      agents: ['Agente de Ingresos', 'Agente Legal', 'Agente Financiero Clubes', 'Agente Relaciones FIFA'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'FPF Transmisión — Gobernanza Comercial Transparente',
      guaranteeBody: 'Análisis probó subpago $7-12M/año ($52-77M en 5 años). Licitación postor único con comisión 12% documentada. Auto-renovación bloqueada. Relicitación competitiva iniciada. Distribución a clubes publicada. Evidencia Fiscalía proporcionada.',
      evidenceChain: 'Contrato ($28M) → Comparables ($35-40M) → Subpago ($7-12M) → Forensia intermediario (12%, $16.8M) → Auto-renovación bloqueada → Relicitación → Valuación → Distribución → Fiscalía → ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes auditarán el contrato de transmisión de Liga 1 — probando subpago de $7-12M/año causado por corrupción interna e iniciando relicitación transparente.',
    phaseLabels: ['Valuación y Forensia de Corrupción', 'Crisis Financiera de Clubes', 'Relicitación Competitiva y Distribución Transparente'],
  
        complianceScore: 88,
        timelineEvents: [
      {
            "timestamp": "2026-04-01T12:18:01.147Z",
            "type": "analysis",
            "title": "System Assessment - Post-Lozano — Reconstrucción Institucional Bajo Escrutinio de FIFA",
            "description": "Data protection, cybersecurity, IP rights, platform governance: System Assessment analysis for Fpf Peru Es completed with industry-specific compliance checks",
            "agent": "Tech Agent",
            "impact": "high"
      },
      {
            "timestamp": "2026-04-01T12:19:01.147Z",
            "type": "warning",
            "title": "Privacy Compliance - Post-Lozano — Reconstrucción Institucional Bajo Escrutinio de FIFA",
            "description": "Data protection, cybersecurity, IP rights, platform governance: Privacy Compliance analysis for Fpf Peru Es completed with industry-specific compliance checks",
            "agent": "Privacy Agent",
            "impact": "high"
      },
      {
            "timestamp": "2026-04-01T12:20:01.147Z",
            "type": "dissent",
            "title": "Security Risk - Post-Lozano — Reconstrucción Institucional Bajo Escrutinio de FIFA",
            "description": "Data protection, cybersecurity, IP rights, platform governance: Security Risk analysis for Fpf Peru Es completed with industry-specific compliance checks",
            "agent": "Security Agent",
            "impact": "medium"
      },
      {
            "timestamp": "2026-04-01T12:21:01.147Z",
            "type": "proposal",
            "title": "Governance Framework - Post-Lozano — Reconstrucción Institucional Bajo Escrutinio de FIFA",
            "description": "Data protection, cybersecurity, IP rights, platform governance: Governance Framework analysis for Fpf Peru Es completed with industry-specific compliance checks",
            "agent": "Platform Agent",
            "impact": "high"
      },
      {
            "timestamp": "2026-04-01T12:22:01.147Z",
            "type": "resolution",
            "title": "Compliance Certified - Post-Lozano — Reconstrucción Institucional Bajo Escrutinio de FIFA",
            "description": "Data protection, cybersecurity, IP rights, platform governance: Compliance Certified analysis for Fpf Peru Es completed with industry-specific compliance checks",
            "agent": "Audit Agent",
            "impact": "high"
      }
]},
];
