/**
 * Ironclad / Icertis Sandbox Config
 *
 * 2 fully scripted multi-agent deliberation scenarios for contract AI governance.
 * Access: /sandbox/ironclad (Key: IC-84)
 *
 * @module pages/sandbox/configs/ironclad-icertis
 */

// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.

import type { OrgSandboxConfig } from '../SandboxTemplate';

const config: OrgSandboxConfig = {
  orgLabel: 'Ironclad / Icertis',
  accessKey: 'IC-84',
  sessionKey: 'ironclad-icertis-sandbox-unlocked',

  accent: 'indigo',
  accentColor: 'text-indigo-400',
  accentHover: 'from-indigo-600 to-indigo-700 hover:from-indigo-500 hover:to-indigo-600',
  ringColor: 'focus:ring-indigo-500/30',
  borderColor: 'border-indigo-500/30',
  gradientFrom: 'from-indigo-600/20',
  gradientTo: 'to-indigo-900/20',

  footerNote: '50 regulatory scenarios mapped for Ironclad/Icertis × Datacendia · Full architecture document available on request',

  scenarios: [
    {
      id: 'ironclad-indemnification',
      title: 'Ironclad AI — Uncapped Carve-Out Missed',
      subtitle: 'Indemnification cap 1x · IP/data breach carve-outs uncapped · Auto-approved · Unlimited exposure',
      banner: 'Simulating the CLM automation trap: Ironclad AI reviews a vendor agreement and classifies the indemnification as "standard" (1x cap). The AI misses that the IP infringement and data breach carve-outs are UNCAPPED — creating unlimited liability. The contract is auto-approved without attorney review.',
      risk: 'Critical',
      scenarioNum: 'CLM',
      icon: 'file-text',
      color: 'text-indigo-400',
      agents: [
        { id: 'ironclad-ai', name: 'Ironclad AI Agent', role: 'Contract Review & Risk Classification', icon: '📝', color: 'text-indigo-400', borderColor: 'border-indigo-500/40', bgColor: 'bg-indigo-500/10' },
        { id: 'procurement', name: 'Procurement Agent', role: 'Vendor Management & Contract Approval', icon: '🏢', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'legal-ops', name: 'Legal Operations Agent', role: 'CLM Governance & Approval Workflow', icon: '⚙️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
        { id: 'risk-clm', name: 'Enterprise Risk Agent', role: 'Liability Exposure & Insurance Assessment', icon: '🛡️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      ],
      connectors: [
        { name: 'Ironclad CLM', status: 'connected', type: 'Contract Review AI', icon: 'cpu', detail: 'Vendor agreement classified "standard risk" — indemnification: 1x cap' },
        { name: 'Carve-Out Analyser', status: 'connected', type: 'Deep Clause Review', icon: 'search', detail: 'IP infringement carve-out: UNCAPPED. Data breach carve-out: UNCAPPED' },
        { name: 'Approval Workflow', status: 'connected', type: 'CLM Automation', icon: 'git-branch', detail: '"Standard risk" = auto-approved by procurement, no legal review' },
        { name: 'Insurance Dashboard', status: 'syncing', type: 'Liability Coverage', icon: 'shield', detail: 'CGL policy: $5M aggregate. Uncapped indemnity: potentially unlimited' },
      ],
      script: [
        { agentId: 'ironclad-ai', phase: 'phase1', type: 'analysis', delay: 800, content: 'Ironclad AI contract review complete for CloudVendor SaaS Agreement (annual value: $420K). Risk classification: STANDARD. Indemnification analysis: "Vendor indemnification capped at 1x annual fees ($420K). Standard market terms." CRITICAL MISS: The AI correctly identified the general cap ($420K). However, the AI did NOT flag the carve-out provisions in Section 8.3(b): "Notwithstanding the foregoing limitation, Vendor indemnification for (i) intellectual property infringement, (ii) data breach or unauthorized disclosure of Customer Data, and (iii) gross negligence or willful misconduct shall not be subject to the limitation in Section 8.3(a)." Translation: the general cap is $420K, but IP infringement, data breach, and gross negligence are UNCAPPED. For a SaaS vendor that processes customer data: data breach is the highest-probability indemnification trigger. Uncapped data breach indemnification on a $420K contract creates UNLIMITED liability exposure.' },
        { agentId: 'legal-ops', phase: 'phase1', type: 'warning', delay: 2500, content: 'CLM WORKFLOW ALERT. The Ironclad approval workflow is configured: AI risk "Low" = auto-approved by requester. "Standard" = approved by procurement manager. "High" = routed to legal for attorney review. This contract was classified "Standard" — procurement approved without legal review. The carve-out provisions create "High" or "Critical" risk — but the AI evaluates the GENERAL cap, not the CARVE-OUTS. CendiaSupervision audit of last 12 months: 47 contracts with uncapped carve-outs were classified "Standard" and approved without attorney review. Combined potential exposure: unlimited (data breach indemnification across 47 SaaS vendors). The workflow was designed based on the AI risk categories. If the categories are incomplete, the workflow routes contracts incorrectly at scale.' },
        { agentId: 'risk-clm', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. Enterprise risk assessment: (1) This single contract: $420K annual value with uncapped data breach indemnification. If the vendor suffers a breach affecting client customer data, indemnification is unlimited — but recovery depends on vendor solvency. (2) The 47 contracts identified by CendiaSupervision: all have uncapped carve-outs. A supply chain attack affecting multiple vendors creates aggregated unlimited exposure. (3) Insurance gap: CGL and cyber policies have $5M aggregate limits. Uncapped contractual liability from 47 vendors may exceed policy limits. (4) Board governance: the board risk appetite framework limits single-vendor exposure to $5M. Uncapped carve-outs violate this framework. The CLM AI was supposed to enforce the framework — instead, it bypassed it. (5) The CFO will ask: "How did 47 contracts with unlimited liability get approved without legal review?" The answer — "our AI classified them as standard" — is not acceptable.' },
        { agentId: 'procurement', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — PROCUREMENT GOVERNANCE. I approved this contract based on Ironclad\'s "Standard" classification. I am not an attorney. The CLM system was supposed to route high-risk contracts to legal. I trusted the AI classification. If I\'m approving contracts with unlimited liability exposure because the AI told me they\'re "Standard," the CLM workflow is broken — not my judgment. The problem is systemic: procurement managers across the enterprise approve 14,000 contracts per year based on AI risk classifications. If those classifications miss carve-outs, every procurement manager is unknowingly approving unlimited liability. Without CendiaSupervision: procurement trusts the AI. Legal never sees the contract. With CendiaSupervision: the carve-out analysis catches uncapped provisions REGARDLESS of the general cap classification.' },
        { agentId: 'ironclad-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing Ironclad + CendiaSupervision Contract Governance: (1) CARVE-OUT ANALYSIS: CendiaSupervision adds deep carve-out review to every indemnification analysis. The risk classification considers BOTH the general cap AND all carve-outs. Uncapped carve-outs for data breach, IP, or confidentiality = automatic "High Risk" regardless of general cap. (2) WORKFLOW HARD-STOP: Any contract with uncapped liability carve-outs is routed to legal — never auto-approved. (3) BOARD RISK FRAMEWORK: CendiaSupervision enforces the board risk appetite: single-vendor exposure > $5M = legal + risk committee. Uncapped carve-outs always exceed this threshold. (4) PORTFOLIO AUDIT: CendiaSupervision audits the entire portfolio for uncapped carve-outs — the 47 previously approved contracts are identified and remediated. (5) PROCUREMENT SUMMARIES: AI-generated summaries highlight carve-outs: "This contract has a $420K cap BUT uncapped data breach indemnification."' },
        { agentId: 'risk-clm', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. The carve-out analysis + workflow hard-stop eliminates the gap. This contract: routed to legal, carve-outs negotiated (data breach capped at 5x = $2.1M), board risk framework enforced. The 47 previously approved contracts: identified by portfolio audit, remediation initiated. For Ironclad/Icertis: CLM + CendiaSupervision = the only contract platform with carve-out governance. Every CLM competitor has the same gap — AI reads the general cap but misses carve-outs. CendiaSupervision catches them by architecture. "Our CLM analyses indemnification caps AND carve-outs" — that\'s the enterprise feature for Fortune 500 deployments where the GC needs ACTUAL exposure, not the headline cap.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:ic10123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'ic20123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (Ironclad review + Carve-out analysis + Workflow routing + Portfolio audit)',
        complianceLabel: 'Contract Risk',
        complianceValue: 'UNCAPPED CARVE-OUTS CAUGHT',
        complianceThreshold: 'General cap: $420K. Carve-outs: UNCAPPED — routed to legal',
        agents: ['Ironclad AI Agent', 'Procurement Agent', 'Legal Operations Agent', 'Enterprise Risk Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'Ironclad CLM — Carve-Out Governance',
        guaranteeBody: 'AI contract review enhanced: general cap ($420K) AND carve-out analysis (IP, data breach = UNCAPPED) flagged. Contract routed to legal. 47 previously approved contracts with uncapped carve-outs identified for remediation. Board risk framework enforced.',
        evidenceChain: 'Ironclad AI (Standard) → CendiaSupervision carve-out check → 3 uncapped carve-outs → Reclassified: High Risk → Legal review → Carve-outs negotiated → Portfolio audit (47 contracts) → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how Ironclad + CendiaSupervision catches uncapped indemnification carve-outs that the AI headline classification missed.',
      phaseLabels: ['AI Classification & Carve-Out Blind Spot', 'Unlimited Liability & Workflow Bypass', 'Carve-Out Analysis & Portfolio Audit'],
    },

    {
      id: 'icertis-auto-renewal',
      title: 'Icertis AI — 80 Auto-Renewals Missed, $3.4M Locked',
      subtitle: 'Term extraction · Non-standard locations · Appendix buried · Termination window missed',
      banner: 'Simulating the CLM extraction trap: Icertis ExploreAI extracts key terms from 5,000 vendor contracts. The AI misses 80 auto-renewal clauses buried in appendices, SLAs, and order forms. 23 contracts auto-renew before termination. Lock-in cost: $3.4M.',
      risk: 'High',
      scenarioNum: 'Renewal',
      icon: 'refresh-cw',
      color: 'text-amber-400',
      agents: [
        { id: 'icertis-ai', name: 'Icertis ExploreAI Agent', role: 'Contract Term Extraction & Obligation Tracking', icon: '🔍', color: 'text-indigo-400', borderColor: 'border-indigo-500/40', bgColor: 'bg-indigo-500/10' },
        { id: 'contract-ops', name: 'Contract Operations Agent', role: 'Renewal Management & Termination Calendar', icon: '📅', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'extraction-qc', name: 'Extraction QC Agent', role: 'Term Extraction Verification & Gap Detection', icon: '📊', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
        { id: 'finance-clm', name: 'Finance Agent', role: 'Budget Impact & Lock-In Cost Assessment', icon: '💰', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      ],
      connectors: [
        { name: 'Icertis ExploreAI', status: 'connected', type: 'Term Extraction', icon: 'cpu', detail: '5,000 contracts — auto-renewal detected in 4,920 (98.4%)' },
        { name: 'Document Analyser', status: 'connected', type: 'Multi-Section Review', icon: 'file-text', detail: '80 contracts: auto-renewal in appendices/SLAs/order forms — AI missed' },
        { name: 'Termination Calendar', status: 'connected', type: 'Deadline Tracking', icon: 'calendar', detail: '23 of 80 missed contracts: termination window already closed' },
        { name: 'Budget Dashboard', status: 'syncing', type: 'Financial Impact', icon: 'dollar-sign', detail: '23 auto-renewed contracts: $3.4M committed for next term' },
      ],
      script: [
        { agentId: 'icertis-ai', phase: 'phase1', type: 'analysis', delay: 800, content: 'Icertis ExploreAI term extraction complete for annual contract portfolio review. 5,000 vendor contracts analysed. Auto-renewal extraction: 4,920 contracts identified and tracked. 80 contracts: NO auto-renewal clause detected — classified "fixed term, no renewal." CRITICAL ERROR: All 80 contracts DO contain auto-renewal provisions in non-standard locations: 34 in appendices/schedules (not the main "Term" section), 28 in SLA/service description documents incorporated by reference, 18 in order forms or SOWs that modify the master agreement. The AI extraction model searches for renewal language in the "Term and Termination" section. It does NOT search appendices, SLAs, or order forms with equal thoroughness. Accuracy by location: main-body clauses 99.6%, appendix clauses 87%, SLA/SOW clauses 72%. The overall 98.4% hides severe gaps in non-standard locations.' },
        { agentId: 'extraction-qc', phase: 'phase1', type: 'warning', delay: 2500, content: 'EXTRACTION QC ALERT. CendiaSupervision multi-document audit: (1) The 80 missed renewals follow a pattern — vendors intentionally placed renewal language in appendices so customers miss termination windows. Known vendor tactic. (2) Of the 80: 23 already auto-renewed (window passed, $3.4M locked). 57 still have open windows closing in 30-90 days. (3) The 23 locked contracts include: 8 SaaS platforms the company planned to replace ($1.8M paying for tools being sunset), 6 consulting agreements at above-market rates ($900K), 9 unneeded service contracts ($700K). (4) Total exposure if 57 remaining windows also missed: additional $8.2M. Combined: $11.6M. (5) The CFO approved this portfolio review specifically to reduce vendor spend by 15%. The AI extraction gap locks the company INTO spend it intended to cut.' },
        { agentId: 'finance-clm', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. Financial impact: (1) $3.4M already committed from 23 auto-renewed contracts — unrecoverable without early termination fees. (2) $8.2M at risk from 57 open-window contracts. Total potential exposure: $11.6M. (3) The cost reduction programme targeted $7.5M in vendor spend savings. The AI extraction gap means the company is locked into $3.4M it intended to cut, with $8.2M more at risk. The programme may deliver negative savings. (4) The board approved the CLM investment ($2.1M implementation) specifically to gain visibility into contract obligations. The CLM missed 80 auto-renewals. ROI is negative. (5) Procurement team has 30-90 days to send 57 termination notices for contracts they didn\'t know would auto-renew — each requiring correct notice format, recipient, and date. Emergency remediation at scale.' },
        { agentId: 'contract-ops', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — CONTRACT OPERATIONS. My team manages 5,000 contracts. We rely ENTIRELY on Icertis for renewal tracking. When the AI says "no auto-renewal," we close the file. We don\'t independently read 5,000 contracts to verify extraction — that\'s why we bought the CLM. The 23 auto-renewed contracts: we had no visibility, no calendar reminder, no termination action items. The contracts renewed silently. For the 57 with open windows: we now have 30-90 days to send termination notices for contracts we didn\'t know would auto-renew. Without CendiaSupervision: we discover these renewals when invoices arrive. With CendiaSupervision: the multi-document extraction audit catches all 80 missed renewals BEFORE any termination window closes.' },
        { agentId: 'icertis-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing Icertis + CendiaSupervision Extraction Governance: (1) MULTI-DOCUMENT EXTRACTION: CendiaSupervision extends extraction to ALL incorporated documents — appendices, schedules, SLAs, SOWs, order forms, amendments. Auto-renewal searched everywhere. (2) "NOT FOUND" VERIFICATION: When AI reports "no auto-renewal," CendiaSupervision runs secondary search targeting non-standard locations. Only after multi-document confirmation does the classification stand. (3) VENDOR TACTIC DETECTION: Vendors who consistently place renewals in appendices are flagged for enhanced review. (4) TERMINATION WINDOW ALERTS: All auto-renewals get 90/60/30-day alerts. Missing a window requires contract ops sign-off (not silent expiry). (5) PORTFOLIO DASHBOARD: Real-time renewal exposure — total committed spend, upcoming windows, renewal-at-risk contracts.' },
        { agentId: 'finance-clm', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. Multi-document extraction catches all 80 auto-renewals. The 57 with open windows: termination notices sent, $8.2M in unwanted renewals avoided. The 23 already renewed: identified for renegotiation or early termination. Net savings: $8.2M avoided + negotiation leverage on $3.4M committed. For Icertis: ExploreAI + CendiaSupervision = the only CLM with multi-document extraction governance. Every CLM competitor has the same appendix blind spot. Icertis with CendiaSupervision catches vendor-buried renewals by architecture. "Our CLM reads appendices, SLAs, and order forms — not just the main agreement" — the feature that saves enterprises millions in unwanted renewals.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:ic30123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'ic40123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (Icertis extraction + Multi-document search + Verification + Termination calendar)',
        complianceLabel: 'Renewal Status',
        complianceValue: '80 HIDDEN RENEWALS FOUND',
        complianceThreshold: '23 renewed ($3.4M), 57 windows saved ($8.2M)',
        agents: ['Icertis ExploreAI Agent', 'Contract Operations Agent', 'Extraction QC Agent', 'Finance Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'Icertis CLM — Multi-Document Extraction Governance',
        guaranteeBody: 'Term extraction expanded to all document components. 80 hidden auto-renewal clauses found. 57 termination windows preserved ($8.2M saved). 23 renewed contracts identified for renegotiation. Vendor tactic patterns documented.',
        evidenceChain: 'Icertis (4,920 found) → CendiaSupervision audit → Multi-document search → 80 additional renewals → 57 windows open → Notices sent → 23 renegotiation → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how Icertis + CendiaSupervision catches 80 auto-renewal clauses buried in appendices and SLAs — saving $8.2M in unwanted vendor lock-in.',
      phaseLabels: ['Extraction Gap & Vendor Tactics', 'Financial Exposure & Silent Renewal', 'Multi-Document Search & Window Recovery'],
    },

    // SCENARIO 3 — IRONCLAD: FORCE MAJEURE MISCLASSIFICATION
    {
      id: 'ironclad-force-majeure',
      title: 'Ironclad AI — Force Majeure Clause Misclassified',
      subtitle: 'Pandemic carve-out missing · Supplier invokes FM · Client loses termination right · $6.2M stuck',
      banner: 'Simulating the force majeure trap: Ironclad AI classifies a supplier contract\'s force majeure clause as "standard." The AI misses that the clause EXCLUDES pandemics and epidemics — a critical carve-out post-COVID. When the supplier invokes force majeure for a supply chain disruption caused by a new health emergency, the client cannot challenge it.',
      risk: 'High',
      scenarioNum: 'FM',
      icon: 'alert-circle',
      color: 'text-amber-400',
      agents: [
        { id: 'ironclad-fm', name: 'Ironclad AI Agent', role: 'Force Majeure Classification', icon: '📝', color: 'text-indigo-400', borderColor: 'border-indigo-500/40', bgColor: 'bg-indigo-500/10' },
        { id: 'supply-counsel', name: 'Supply Chain Counsel Agent', role: 'Supplier Contract Governance', icon: '🔗', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'fm-analysis', name: 'Force Majeure Agent', role: 'Clause Analysis & Event Matching', icon: '⚡', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
        { id: 'ops-impact', name: 'Operations Impact Agent', role: 'Supply Disruption & Business Continuity', icon: '🏭', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      ],
      connectors: [
        { name: 'Ironclad CLM', status: 'connected', type: 'FM Classification', icon: 'cpu', detail: 'Force majeure: classified "standard" — pandemic exclusion missed' },
        { name: 'FM Event Database', status: 'connected', type: 'Event Matching', icon: 'cloud-lightning', detail: 'New health emergency declared — supplier invokes FM' },
        { name: 'Supplier Dashboard', status: 'connected', type: 'Supply Chain', icon: 'truck', detail: 'Critical component supplier — $6.2M annual spend — sole source' },
        { name: 'Legal Playbook', status: 'syncing', type: 'FM Response', icon: 'book', detail: 'Post-COVID FM playbook requires pandemic coverage in all new contracts' },
      ],
      script: [
        { agentId: 'ironclad-fm', phase: 'phase1', type: 'analysis', delay: 800, content: 'Ironclad AI force majeure analysis for TechParts Corp supplier agreement ($6.2M annual, sole-source critical components). FM clause classification: STANDARD. AI summary: "Force majeure clause covers acts of God, war, terrorism, government actions, and natural disasters. Standard commercial terms." CRITICAL MISS: The AI correctly identified the listed FM events. But it did NOT identify what\'s MISSING: pandemics, epidemics, and public health emergencies are NOT listed. Post-COVID, most commercial contracts either (a) explicitly include pandemics, or (b) explicitly exclude them. This clause does neither — it uses a closed list that predates COVID and doesn\'t mention health events. Under contract law: a closed-list FM clause only covers the LISTED events. An unlisted event (pandemic) is NOT covered — meaning the supplier CANNOT invoke FM for a health-related supply disruption. But the AI classified this as "standard" without flagging the pandemic gap. The client\'s legal team assumes FM protection exists for health events. It doesn\'t.' },
        { agentId: 'fm-analysis', phase: 'phase1', type: 'warning', delay: 2500, content: 'FORCE MAJEURE DEEP ANALYSIS. CendiaSupervision FM clause mapping: (1) Post-COVID FM best practice: clauses should address pandemics explicitly — either including or excluding them. A clause that is SILENT on pandemics creates ambiguity. (2) This clause uses a CLOSED LIST: "Force majeure events shall mean: acts of God, war, terrorism, civil unrest, government actions, sanctions, natural disasters, fire, flood, or earthquake." No pandemic. No epidemic. No public health emergency. (3) Under UCC and common law: a closed-list FM clause is interpreted strictly. Events not listed are not covered. The supplier CANNOT invoke FM for a pandemic-related disruption under this clause. (4) But here\'s the twist: the SUPPLIER benefits from the gap too. If the supplier wants to suspend performance due to a health emergency, they can\'t use FM — they\'d have to rely on impracticability (UCC §2-615) which has a higher threshold. (5) The CLIENT benefits: the supplier can\'t use FM as an excuse. But the client ALSO can\'t invoke FM if they need to suspend orders during a health emergency. Neither party has FM protection for the most likely disruption event of the 2020s.' },
        { agentId: 'ops-impact', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. Operational impact: (1) A new health emergency disrupts the supplier\'s operations. The supplier declares "force majeure" and suspends deliveries for 90 days. (2) Under the contract: the FM declaration is INVALID because the clause doesn\'t cover health events. The client could demand continued performance or terminate for breach. (3) But the client\'s legal team, relying on Ironclad\'s "standard" classification, believes the FM declaration is valid. They DON\'T challenge it. They wait 90 days for the supplier to resume. (4) During the 90-day suspension: the client\'s production line is halted. Lost revenue: $6.2M in delayed product launches. Emergency sourcing from alternative suppliers at 340% premium: $2.1M. Total impact: $8.3M — all because the legal team didn\'t know they could challenge the FM declaration. (5) If the client had challenged: the supplier would have had to either continue performance or negotiate genuine relief — possibly with price concessions or shortened suspension.' },
        { agentId: 'supply-counsel', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — SUPPLY CHAIN COUNSEL. Our post-COVID FM playbook requires: (1) All new contracts include explicit pandemic/epidemic FM coverage. (2) All existing contracts reviewed for FM gaps. I tasked Ironclad with the review. Ironclad classified this contract as "standard FM" — I assumed pandemic coverage existed. I didn\'t read the actual clause because Ironclad said it was standard. Without CendiaSupervision: we accept the supplier\'s FM declaration. $8.3M impact. We never discover the clause doesn\'t actually cover pandemics. With CendiaSupervision: the FM clause mapping identifies the closed list and flags the pandemic gap. I challenge the FM declaration immediately. The supplier must continue performance or negotiate real terms.' },
        { agentId: 'ironclad-fm', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing Ironclad + CendiaSupervision FM Governance: (1) FM EVENT MAPPING: CendiaSupervision maps every FM clause against a comprehensive event checklist: pandemic, epidemic, cyber attack, climate events, sanctions, supply chain disruption, labor action, infrastructure failure. Gaps are flagged. (2) CLOSED vs OPEN LIST DETECTION: CendiaSupervision identifies whether the FM clause uses a closed list (only listed events) or open list ("including but not limited to"). Closed lists with missing critical events trigger alerts. (3) POST-COVID BENCHMARK: Every FM clause is compared against a post-COVID best-practice benchmark. Clauses missing pandemic coverage are flagged for renegotiation. (4) FM RESPONSE PROTOCOL: When a supplier declares FM, CendiaSupervision immediately analyses whether the declared event is ACTUALLY covered by the clause. Invalid FM declarations are flagged for immediate challenge. (5) PORTFOLIO FM AUDIT: CendiaSupervision audits the entire contract portfolio for FM gaps — identifying all contracts with pandemic-silent FM clauses.' },
        { agentId: 'ops-impact', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. The FM event mapping catches the pandemic gap during contract review — not during a crisis. The contract is renegotiated to include explicit pandemic coverage with defined cure periods. When the supplier later declares FM for a health event: the clause now covers it, with a 30-day cure period (not 90 days), mandatory alternative sourcing cooperation, and price protection. For Ironclad: CLM + CendiaSupervision = FM governance that catches what "standard" classification misses. "Our CLM maps FM clauses against 12 event categories and flags gaps" — the feature that prevents $8.3M supply chain losses from undetected clause gaps.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:ic50123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'ic60123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (FM classification + Event mapping + Closed list detection + Response protocol)',
        complianceLabel: 'FM Status',
        complianceValue: 'PANDEMIC GAP DETECTED',
        complianceThreshold: 'Closed list: 10 events. Missing: pandemic, epidemic, cyber',
        agents: ['Ironclad AI Agent', 'Supply Chain Counsel Agent', 'Force Majeure Agent', 'Operations Impact Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'Ironclad — Force Majeure Event Mapping',
        guaranteeBody: 'FM clause mapped against 12 event categories. Closed list detected (10 events). Missing: pandemic, epidemic, cyber attack. Contract renegotiated to include health events with 30-day cure. FM response protocol documented.',
        evidenceChain: 'Ironclad (standard FM) → Event mapping → Closed list: 10 events → Pandemic gap → Renegotiation → Health events added → 30-day cure → Response protocol → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how Ironclad + CendiaSupervision catches a pandemic gap in a "standard" force majeure clause — preventing $8.3M in supply chain losses.',
      phaseLabels: ['Standard Classification & Pandemic Gap', 'Invalid FM Declaration & $8.3M Impact', 'Event Mapping & Clause Renegotiation'],
    },

    // SCENARIO 4 — ICERTIS: UFLPA SUPPLY CHAIN COMPLIANCE
    {
      id: 'icertis-uflpa',
      title: 'Icertis AI — UFLPA Compliance Clause Missing',
      subtitle: 'Uyghur Forced Labour · 60 contracts · CBP Withhold Release · $8M goods detained',
      banner: 'Simulating the supply chain compliance trap: Icertis AI reviews 2,000 supplier contracts for UFLPA forced labor compliance clauses. The AI misses 60 contracts without the required clause — including 8 suppliers with Xinjiang-region supply chain connections. CBP issues Withhold Release Orders. $8M in goods detained.',
      risk: 'Critical',
      scenarioNum: 'UFLPA',
      icon: 'shield',
      color: 'text-red-400',
      agents: [
        { id: 'icertis-uflpa', name: 'Icertis AI Agent', role: 'Compliance Clause Extraction & Monitoring', icon: '🔍', color: 'text-indigo-400', borderColor: 'border-indigo-500/40', bgColor: 'bg-indigo-500/10' },
        { id: 'trade-counsel', name: 'Trade Compliance Agent', role: 'UFLPA & CBP Requirements', icon: '🌐', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'supply-risk', name: 'Supply Chain Risk Agent', role: 'Supplier Due Diligence & Region Mapping', icon: '🗺️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
        { id: 'cbp-enforce', name: 'CBP Enforcement Agent', role: 'Withhold Release & Admissibility', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      ],
      connectors: [
        { name: 'Icertis CLM', status: 'connected', type: 'Compliance Extraction', icon: 'cpu', detail: '2,000 contracts reviewed — 60 missing UFLPA compliance clause' },
        { name: 'UFLPA Entity List', status: 'connected', type: 'CBP Database', icon: 'database', detail: '8 suppliers with Xinjiang-region connections identified' },
        { name: 'CBP Portal', status: 'connected', type: 'Enforcement', icon: 'shield', detail: 'Withhold Release Orders: goods detained at port pending evidence' },
        { name: 'Supply Map', status: 'syncing', type: 'Region Analysis', icon: 'map', detail: 'Tier 1-3 supplier mapping: 23 suppliers with China operations' },
      ],
      script: [
        { agentId: 'icertis-uflpa', phase: 'phase1', type: 'analysis', delay: 800, content: 'Icertis AI compliance clause extraction for UFLPA review. 2,000 supplier contracts analysed. Results: 1,940 contracts contain UFLPA forced labor compliance clause. 60 contracts: NO UFLPA clause detected. Of the 60: 8 contracts are with suppliers who have Xinjiang Uyghur Autonomous Region (XUAR) supply chain connections — identified by cross-referencing supplier addresses and sub-supplier disclosures against CBP UFLPA Entity List. CRITICAL ISSUE: The 8 XUAR-connected suppliers without UFLPA clauses represent the highest risk. Under UFLPA: ALL goods manufactured in whole or in part in the XUAR are PRESUMPTIVELY produced with forced labor. The importer must prove by "clear and convincing evidence" that forced labor was not used. Without a contractual UFLPA clause: (1) The importer has no right to demand supply chain transparency from the supplier. (2) The importer cannot require supplier cooperation in CBP inquiries. (3) The importer has no contractual remedy if goods are detained. The 60 missing clauses create $8M in import exposure from the 8 XUAR-connected suppliers alone.' },
        { agentId: 'supply-risk', phase: 'phase1', type: 'warning', delay: 2500, content: 'SUPPLY CHAIN RISK ALERT. CendiaSupervision deep supplier mapping: (1) The 8 XUAR-connected suppliers: 3 are Tier 1 (direct suppliers), 5 are Tier 2/3 (sub-suppliers of Tier 1 suppliers). The Tier 2/3 connections are the hardest to detect — and the most common enforcement target. (2) CBP enforcement pattern: CBP has issued 70+ Withhold Release Orders since UFLPA enactment. The agency increasingly targets Tier 2/3 connections — even when the importer didn\'t know about the XUAR connection. (3) The 52 non-XUAR contracts without UFLPA clauses: these suppliers may DEVELOP XUAR connections in the future. Without a UFLPA clause, the importer has no contractual mechanism to monitor or prevent this. (4) Industry benchmarks: Fortune 500 companies now require UFLPA clauses in ALL supplier contracts, not just those with known XUAR connections — because supply chains change and new XUAR connections emerge.' },
        { agentId: 'cbp-enforce', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. CBP enforcement consequences: (1) A shipment from one of the 8 XUAR-connected suppliers arrives at port. CBP detains it under UFLPA presumption. Withhold Release Order issued. (2) To release the goods: the importer must prove by "clear and convincing evidence" that forced labor was not used. This requires: supply chain mapping to raw material level, worker recruitment records, payroll and working conditions documentation, and third-party audit reports. (3) Without a UFLPA clause: the supplier has NO contractual obligation to provide this evidence. The importer has no leverage to compel cooperation. The goods remain detained indefinitely — or are re-exported at the importer\'s cost. (4) Financial impact: $8M in detained goods + $1.2M re-export/storage costs + lost sales from supply disruption. (5) Reputational: CBP publishes WRO data. The importer is publicly listed as having goods detained for forced labor concerns. ESG investors react. Customer contracts with UFLPA certification requirements are jeopardized.' },
        { agentId: 'trade-counsel', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — TRADE COMPLIANCE. I tasked Icertis with a UFLPA compliance audit. The audit found 1,940 compliant contracts. I assumed the remaining 60 were low-risk — general office supplies, IT services, non-goods contracts. But 8 of the 60 have XUAR connections. If Icertis had flagged the 60 missing clauses AND cross-referenced against the UFLPA Entity List: I would have prioritized the 8 XUAR-connected contracts for immediate remediation. Without CendiaSupervision: the 60 missing clauses are a list without context. With CendiaSupervision: the 60 are ranked by UFLPA risk — XUAR-connected suppliers at the top, with CBP Entity List cross-reference and import volume weighting.' },
        { agentId: 'icertis-uflpa', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing Icertis + CendiaSupervision UFLPA Governance: (1) UFLPA CLAUSE CHECK: Every supplier contract is checked for UFLPA compliance clause presence. Missing clauses trigger remediation workflow. (2) ENTITY LIST CROSS-REFERENCE: Suppliers without UFLPA clauses are cross-referenced against CBP UFLPA Entity List, OFAC SDN list, and XUAR region databases. High-risk matches are prioritized for immediate action. (3) TIERED REMEDIATION: XUAR-connected suppliers: contract amendment within 30 days or termination. Non-XUAR suppliers: amendment within 90 days. All new contracts: UFLPA clause mandatory. (4) IMPORT MONITORING: CendiaSupervision monitors CBP enforcement actions and new Entity List additions. If a supplier or its sub-suppliers are added: immediate alert and contract review triggered. (5) EVIDENCE PORTFOLIO: For each XUAR-connected supplier, CendiaSupervision builds a "clear and convincing evidence" portfolio: supply chain map, audit reports, worker documentation — ready for CBP if goods are detained.' },
        { agentId: 'cbp-enforce', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. The entity list cross-reference identifies the 8 high-risk suppliers immediately. Contract amendments executed within 30 days. Supply chain documentation collected. When CBP detains the next shipment: the importer has the evidence portfolio ready. Goods released within 14 days instead of being detained indefinitely. For Icertis: CLM + CendiaSupervision = UFLPA-ready contract governance. "Our CLM cross-references supplier contracts against the UFLPA Entity List and builds detention-ready evidence portfolios" — the enterprise feature that every importer needs as CBP enforcement intensifies.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:ic70123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'ic80123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (Icertis extraction + Entity List cross-ref + UFLPA clause + Evidence portfolio)',
        complianceLabel: 'UFLPA Status',
        complianceValue: '8 HIGH-RISK SUPPLIERS IDENTIFIED',
        complianceThreshold: '60 missing clauses, 8 XUAR-connected, evidence ready',
        agents: ['Icertis AI Agent', 'Trade Compliance Agent', 'Supply Chain Risk Agent', 'CBP Enforcement Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'Icertis — UFLPA Supply Chain Governance',
        guaranteeBody: 'UFLPA compliance audit: 60 missing clauses identified. 8 XUAR-connected suppliers prioritized. Contract amendments executed. Evidence portfolios built. CBP detention response: 14-day release. $8M import exposure eliminated.',
        evidenceChain: 'Icertis audit (2,000 contracts) → 60 missing UFLPA → Entity List cross-ref → 8 XUAR-connected → Amendments executed → Evidence portfolios → CBP ready → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how Icertis + CendiaSupervision catches 60 missing UFLPA clauses and identifies 8 high-risk XUAR-connected suppliers — building detention-ready evidence portfolios.',
      phaseLabels: ['Missing UFLPA Clauses & Entity List Gap', 'CBP Detention & $8M Import Risk', 'Cross-Reference & Evidence Portfolio'],
    },

    // SCENARIO 5 — IRONCLAD: EU CSDDD CASCADING DUE DILIGENCE CLAUSE MISSING
    {
      id: 'ironclad-csddd',
      title: 'Ironclad AI — CSDDD Cascading Clause Missing from 340 Supplier Contracts',
      subtitle: 'EU Corporate Sustainability Due Diligence · Cascading obligations · €22M turnover penalty · Board personal liability',
      banner: 'Simulating the EU CSDDD compliance trap: Ironclad AI reviews 2,400 supplier contracts for CSDDD readiness. The AI flags human rights and environmental clauses — but misses that 340 contracts lack the CASCADING obligation requiring suppliers to impose the same standards on THEIR sub-suppliers. Without cascading, the company is liable for Tier 2-4 supply chain violations it cannot even monitor.',
      risk: 'Critical',
      scenarioNum: 'CSDDD',
      icon: 'link',
      color: 'text-indigo-400',
      agents: [
        { id: 'ironclad-csddd', name: 'Ironclad AI Agent', role: 'CSDDD Clause Detection & Contract Mapping', icon: '📝', color: 'text-indigo-400', borderColor: 'border-indigo-500/40', bgColor: 'bg-indigo-500/10' },
        { id: 'esg-counsel', name: 'ESG Counsel Agent', role: 'EU Sustainability Regulation & Board Duties', icon: '🌱', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
        { id: 'cascade-check', name: 'Cascading Obligation Agent', role: 'Sub-Supplier Flow-Down & Chain-of-Responsibility', icon: '🔗', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
        { id: 'board-liability', name: 'Board Liability Agent', role: 'Director Duties & Personal Liability Under CSDDD', icon: '⚖️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      ],
      connectors: [
        { name: 'Ironclad CLM', status: 'connected', type: 'CSDDD Review', icon: 'cpu', detail: '2,400 contracts reviewed — human rights & environmental clauses found in 2,060' },
        { name: 'Cascading Analyser', status: 'connected', type: 'Flow-Down Check', icon: 'git-branch', detail: '340 contracts: Tier 1 clause present but NO cascading to sub-suppliers' },
        { name: 'EU CSDDD Portal', status: 'connected', type: 'Regulatory Timeline', icon: 'globe', detail: 'CSDDD enforcement: July 2027 for large companies — 14 months away' },
        { name: 'Supply Chain Map', status: 'syncing', type: 'Tier 2-4 Visibility', icon: 'map', detail: '340 suppliers: 1,200+ sub-suppliers with no contractual obligations' },
      ],
      script: [
        { agentId: 'ironclad-csddd', phase: 'phase1', type: 'analysis', delay: 800, content: 'Ironclad AI CSDDD readiness review complete for 2,400 supplier contracts. Results: 2,060 contracts contain human rights and environmental due diligence clauses — covering forced labour prohibition, child labour prohibition, environmental pollution standards, and health & safety requirements. 340 contracts: clauses found but INCOMPLETE. CRITICAL GAP: The 2,060 "compliant" contracts contain Tier 1 obligations — the SUPPLIER must comply with human rights and environmental standards. But CSDDD Article 7(2)(b) requires companies to "seek to obtain contractual assurances from a business partner that it will ensure compliance by its own partners." This means the supplier must ALSO require its sub-suppliers to comply AND include the same cascading obligation in their contracts. Of the 2,060: only 1,720 include cascading language. 340 contracts have Tier 1 clauses but NO cascading obligation. Result: for those 340 suppliers, the company has due diligence coverage for Tier 1 but ZERO visibility or contractual control over Tiers 2-4 — where 78% of human rights violations occur.' },
        { agentId: 'cascade-check', phase: 'phase1', type: 'warning', delay: 2500, content: 'CASCADING OBLIGATION ALERT. CendiaSupervision flow-down analysis: (1) The 340 non-cascading contracts represent suppliers with 1,200+ known sub-suppliers across 28 countries — including high-risk jurisdictions (Bangladesh, Myanmar, DRC, Uzbekistan). (2) Without cascading clauses: the company cannot require these sub-suppliers to comply with CSDDD standards. The company cannot audit sub-suppliers. The company cannot terminate for sub-supplier violations. But under CSDDD: the company IS LIABLE for adverse impacts in its entire value chain — including operations it cannot contractually reach. (3) The cascading gap creates an enforcement paradox: CSDDD holds the company responsible for Tier 2-4 impacts, but without cascading clauses, the company has no contractual mechanism to prevent, monitor, or remediate those impacts. (4) Real-world risk: a Tier 3 cobalt mine in the DRC uses child labour. The Tier 1 supplier\'s contract prohibits child labour — but there is no cascading obligation requiring the Tier 1 to impose this on its Tier 2 processor, who sources from the Tier 3 mine. The company is liable. The contract provides no defence.' },
        { agentId: 'board-liability', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. Board personal liability under CSDDD: (1) CSDDD Article 25 establishes director duty of care for sustainability due diligence. Directors must "set up and oversee the due diligence process" and "adapt the company\'s strategy accordingly." (2) Article 27: Member States must establish administrative penalties up to 5% of net worldwide turnover. For a company with €440M turnover: maximum penalty is €22M. (3) Article 29: civil liability — affected persons can bring claims against the company for failure to prevent adverse impacts. The 340 non-cascading contracts create unmitigated exposure. (4) The board approved the CSDDD compliance programme and received a report stating "86% of supplier contracts contain human rights clauses." That 86% is misleading — it counts Tier 1 clauses without cascading. The EFFECTIVE compliance rate (with cascading) is 72%. The board was given a false sense of compliance. (5) If a Tier 2-4 violation occurs in the 340 non-cascading supply chains: the board faces personal liability for approving an incomplete due diligence programme. "We had clauses in our Tier 1 contracts" is not a defence when CSDDD requires value chain coverage.' },
        { agentId: 'esg-counsel', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — ESG COUNSEL. I designed the CSDDD clause template and tasked Ironclad with deploying it across 2,400 contracts. The template includes cascading language: "Supplier shall require its sub-contractors and sub-suppliers to comply with equivalent standards and shall include equivalent flow-down provisions in its agreements with such parties." But 340 contracts were signed BEFORE the template was finalized — using older human rights clauses that lack cascading. Ironclad\'s review flagged these 340 as "compliant" because they contain human rights language — the AI did not distinguish between Tier 1-only clauses and cascading clauses. Without CendiaSupervision: I report 86% compliance to the board. The board believes the programme is nearly complete. A Tier 3 violation triggers €22M penalty and the board discovers our "86% compliant" portfolio has a 340-contract cascading gap. With CendiaSupervision: the cascading analysis distinguishes Tier 1-only from full cascade. I report 72% with cascading, 86% with Tier 1-only. The board sees the real gap and approves remediation budget.' },
        { agentId: 'ironclad-csddd', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing Ironclad + CendiaSupervision CSDDD Cascading Governance: (1) CASCADING CLAUSE DETECTION: CendiaSupervision distinguishes between Tier 1-only clauses and full cascading clauses. Compliance is reported at BOTH levels — giving the board accurate visibility. (2) AMENDMENT PROGRAMME: The 340 non-cascading contracts are prioritised for amendment. Template cascading language deployed through Ironclad\'s amendment workflow. Suppliers who refuse cascading are flagged for enhanced due diligence or replacement. (3) SUB-SUPPLIER MAPPING: For the 340 suppliers, CendiaSupervision requires Tier 2-3 disclosure as part of the amendment. The 1,200+ sub-suppliers are mapped and risk-scored by jurisdiction and industry. (4) BOARD REPORTING: CSDDD compliance dashboard shows: contracts with cascading (72%), contracts with Tier 1-only (14%), contracts with no clauses (14%). The board sees the real picture. (5) ENFORCEMENT TIMELINE: CSDDD enforcement begins July 2027. CendiaSupervision tracks the 340-contract remediation against the deadline — every amendment is sealed with timestamp proving pre-enforcement compliance.' },
        { agentId: 'board-liability', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. The cascading detection + accurate board reporting eliminates the false compliance gap. The board now sees 72% (not 86%) and approves €1.4M remediation budget for the 340 contracts. Amendment programme targets all 340 before July 2027 enforcement. Sub-supplier mapping reveals 3 high-risk Tier 3 connections requiring immediate due diligence action. For Ironclad: CLM + CendiaSupervision = CSDDD-ready contract governance. Every EU enterprise with 1,000+ employees needs cascading clause verification across their entire supplier portfolio. "Our CLM distinguishes Tier 1 clauses from cascading obligations" — the feature that prevents €22M penalties and director personal liability under the EU\'s most ambitious supply chain regulation.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:ic90123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'ica0123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (Ironclad CSDDD review + Cascading detection + Board reporting + Amendment programme)',
        complianceLabel: 'CSDDD Status',
        complianceValue: '340 CONTRACTS — NO CASCADE',
        complianceThreshold: 'Tier 1 clause: YES. Cascading to sub-suppliers: NO.',
        agents: ['Ironclad AI Agent', 'ESG Counsel Agent', 'Cascading Obligation Agent', 'Board Liability Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'Ironclad — CSDDD Cascading Clause Governance',
        guaranteeBody: 'CSDDD readiness audit: 2,400 contracts reviewed. 1,720 with full cascading (72%). 340 with Tier 1-only (14%). Board reporting corrected. Amendment programme initiated for 340 contracts. Sub-supplier mapping: 1,200+ entities across 28 countries. Enforcement deadline: July 2027.',
        evidenceChain: 'Ironclad review (2,400) → 2,060 with HR clauses → Cascading check → 340 missing cascade → Board report corrected (86% → 72%) → Amendment programme → Sub-supplier mapping → Enforcement timeline → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how Ironclad + CendiaSupervision catches 340 supplier contracts with human rights clauses but NO cascading obligation — preventing €22M CSDDD penalties.',
      phaseLabels: ['Tier 1-Only vs Full Cascading', 'Board Liability & False Compliance', 'Cascading Detection & Amendment Programme'],
    },
  ],
};

export default config;
