/**
 * FBC Melgar — Spanish (Español) Scenarios
 * @module pages/sandbox/configs/melgar-es
 */

// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.

import type { TemplateScenario } from '../SandboxTemplate';

export const ES_SCENARIOS: TemplateScenario[] = [
  // ESCENARIO 1 — DISPUTA L1 MAX
  {
    id: 'l1max-broadcast',
    title: 'Disputa de Transmisión L1 Max — Ingresos Regionales vs Contrato Nacional',
    subtitle: 'Exclusividad · Caída de asistencia provincial · Competencia INDECOPI · Coalición de clubes · €9.29M plantel',
    banner: 'Simulando la crisis de gobernanza de transmisión que afecta al fútbol peruano. El acuerdo exclusivo OTT de L1 Max ha desplazado aficionados de los estadios a las pantallas — la hinchada arequipeña de Melgar reporta 22% de caída en asistencia. La IA debe gobernar la posición de Melgar en la coalición de clubes que desafía el acuerdo mientras protege los ingresos.',
    risk: 'Crítico',
    scenarioNum: 'Transmisión',
    icon: 'tv',
    color: 'text-red-400',
    agents: [
      { id: 'broadcast-gov', name: 'Agente de Transmisión', role: 'Análisis de Ingresos y Gobernanza Contractual', icon: '📺', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'legal-broadcast', name: 'Agente Legal', role: 'Ley de Competencia INDECOPI y Análisis Contractual', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'commercial-melgar', name: 'Agente Comercial', role: 'Impacto en Asistencia y Modelado de Patrocinios', icon: '📊', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'fan-engagement', name: 'Agente de Hinchada', role: 'Hinchada Arequipeña e Identidad Regional', icon: '🏟️', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Dashboard L1 Max', status: 'connected', type: 'Datos de Transmisión', icon: 'tv', detail: 'Audiencia Melgar: 185K promedio — 3ro en Liga 1' },
      { name: 'Portal INDECOPI', status: 'connected', type: 'Autoridad de Competencia', icon: 'scale', detail: 'Acuerdo OTT exclusivo bajo revisión preliminar' },
      { name: 'Sistema de Asistencia', status: 'connected', type: 'Ingresos de Taquilla', icon: 'users', detail: 'UNSA 45,000 cap — asistencia promedio bajó 22% interanual' },
      { name: 'Comercial FPF', status: 'syncing', type: 'Distribución de Ingresos', icon: 'database', detail: 'Coalición de clubes: 8 clubes desafían fórmula de distribución' },
    ],
    script: [
      { agentId: 'broadcast-gov', phase: 'phase1', type: 'warning', delay: 800, content: 'CRISIS DE GOBERNANZA DE TRANSMISIÓN. Análisis del acuerdo exclusivo OTT L1 Max para Melgar: (1) Participación anual en transmisión: PEN 4.8M — 28% de ingresos totales. (2) Pre-L1 Max (división TV abierta): PEN 3.2M pero la asistencia generaba PEN 2.4M más en taquilla/F&B. Posición neta PEOR bajo L1 Max por ~PEN 800K/año. (3) Mercado Arequipa: 1.1M metro, hinchada apasionada, UNSA tiene 45,000. Asistencia promedio cayó de 28,000 a 21,800 (-22%). (4) Suscripción L1 Max: PEN 25/mes — en una ciudad donde el salario mínimo es PEN 1,025. La barrera de precio excluye porción significativa de la hinchada obrera de Melgar. (5) Coalición de 8 clubes formándose para desafiar la distribución — Melgar es el club provincial más grande de la coalición.' },
      { agentId: 'commercial-melgar', phase: 'phase1', type: 'analysis', delay: 2500, content: 'Análisis profundo de impacto comercial: (1) Ingresos de taquilla: PEN 2.4M perdidos anualmente (6,200 menos aficionados × PEN 25 entrada promedio × 15 partidos locales). (2) F&B de día de partido: PEN 480K perdidos (concesiones proporcionales a asistencia). (3) Patrocinio: Patrocinadores locales (Cervecería del Sur, Socosani) vinculados a asistencia — 2 patrocinadores redujeron 15% citando "menos ojos en el estadio." (4) Merchandising: 18% de caída en ventas de día de partido. (5) Pérdida total de ingresos atribuible a L1 Max: PEN 3.6M. Contra aumento de PEN 1.6M en transmisión = PÉRDIDA NETA de PEN 2.0M anuales. (6) Para clubes limeños con estadios más pequeños, L1 Max es neto positivo. Para la UNSA de 45,000 asientos de Arequipa, la matemática es devastadoramente negativa.' },
      { agentId: 'legal-broadcast', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — RIESGO DE ESTRATEGIA DE COALICIÓN. Análisis INDECOPI: (1) Ley de Libre Competencia (DL 1034): acuerdo OTT exclusivo puede constituir abuso de posición dominante SI no existen alternativas razonables. (2) Sin embargo: FPF negoció colectivamente — clubes consintieron. Romper acuerdo colectivo arriesga sanciones FPF. (3) Coalición de 8 clubes carece de personería jurídica como entidad separada — debe actuar a través de gobernanza FPF. (4) Precedente: clubes colombianos desafiaron transmisión de Dimayor — resultó en batalla legal de 18 meses SIN partidos transmitidos. Mi disenso: Melgar NO debería liderar confrontación pública. En cambio, proponer reforma de gobernanza DENTRO de FPF — fórmula de distribución variable que considere tamaño de estadio e impacto de mercado regional.' },
      { agentId: 'fan-engagement', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — IDENTIDAD AREQUIPEÑA EN RIESGO. (1) Melgar es el ÚNICO club de Liga 1 de Arequipa — institución cívica, no solo fútbol. (2) 68% de aficionados encuestados dicen que asisten menos porque "ya pagué L1 Max." (3) Grupos ultra organizando protestas "No a L1 Max" — riesgo de incidentes en estadio. (4) Orgullo regional: arequipeños ven transmisión centralista como otro ejemplo de centralismo limeño. Las oficinas en Lima y marketing enfocado en Lima de L1 Max refuerza esto. (5) Juventud: grupo 14-22 años migró a streams piratas — L1 Max los pierde, Melgar pierde conexión. (6) El acuerdo de transmisión está erosionando el vínculo club-comunidad que hace valioso a Melgar.' },
      { agentId: 'broadcast-gov', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Datacendia de Gobernanza de Transmisión: (1) PAQUETE DE EVIDENCIA: Documentar PEN 2.0M de pérdida neta anual con análisis financiero sellado — presentar al directorio FPF. (2) PROPUESTA DE REFORMA: Fórmula de distribución variable — participación base + multiplicador de asistencia + factor de mercado regional. La UNSA de 45,000 de Melgar genera más valor comunitario que recintos limeños de 10,000. (3) MODELO HÍBRIDO: Negociar transmisión diferida gratuita en TV abierta (24h) para mercado arequipeño para reconstruir asistencia. L1 Max retiene exclusividad en vivo. (4) INDECOPI: Presentar análisis formal de competencia (no denuncia) — crea presión regulatoria sin confrontación. (5) PATROCINIO: Presentar datos de asistencia sellados a patrocinadores mostrando trayectoria de recuperación bajo modelo híbrido.' },
      { agentId: 'legal-broadcast', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Reforma interna + modelo híbrido evita catástrofe estilo colombiano. Enfoque basado en evidencia a través de gobernanza FPF es legalmente sólido. Análisis INDECOPI (no denuncia) crea presión sin riesgo de litigio. Para CONMEBOL: demuestra que Melgar gobierna decisiones comerciales con datos. Para Arequipa: el modelo híbrido reconecta suscriptores de L1 Max Y aficionados del estadio. El Recibo del Regulador sella la posición de Melgar: no anti-transmisión, sino pro-distribución justa. Los 1.1M de arequipeños merecen acceso equitativo a su club.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:mg10123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'mg20123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (Análisis de ingresos + Impacto asistencia + INDECOPI + Coalición + Modelo híbrido)',
      complianceLabel: 'Gobernanza de Transmisión',
      complianceValue: 'PEN 2.0M PÉRDIDA NETA ANUAL DOCUMENTADA',
      complianceThreshold: 'Reforma gobernanza FPF + análisis INDECOPI presentado',
      agents: ['Agente de Transmisión', 'Agente Legal', 'Agente Comercial', 'Agente de Hinchada'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'FBC Melgar — Gobernanza de Transmisión L1 Max',
      guaranteeBody: 'Paquete criptográfico sella: documentación de pérdida neta PEN 2.0M, análisis de caída de asistencia 22%, presentación INDECOPI, propuesta de reforma FPF, modelo híbrido para mercado arequipeño, trayectoria de recuperación de patrocinios.',
      evidenceChain: 'Datos L1 Max → Análisis ingresos → Asistencia (-22%) → Impacto patrocinios → INDECOPI → Reforma FPF → Modelo híbrido → Mercado Arequipa → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobernarán la respuesta de Melgar a la crisis de transmisión L1 Max — equilibrando ingresos, ley de competencia, participación de hinchada e identidad regional arequipeña.',
    phaseLabels: ['Impacto en Ingresos y Asistencia', 'Estrategia Legal e Identidad Regional', 'Modelo Híbrido y Reforma FPF'],
  },

  // ESCENARIO 2 — SEGURIDAD ESTADIO UNSA
  {
    id: 'unsa-safety',
    title: 'Estadio Monumental UNSA — Gobernanza de Seguridad para Recinto de 45,000',
    subtitle: 'Certificación INDECI · Inspección CONMEBOL · Zona sísmica Arequipa · Convenio universitario',
    banner: 'Simulando gobernanza de seguridad del recinto para el estadio universitario compartido de Melgar. La UNSA se ubica en una de las zonas más sísmicamente activas del Perú — INDECI y CONMEBOL requieren protocolos de emergencia resistentes a terremotos que la gobernanza estándar no puede abordar.',
    risk: 'Alto',
    scenarioNum: 'Seguridad',
    icon: 'shield',
    color: 'text-amber-400',
    agents: [
      { id: 'venue-safety', name: 'Agente de Seguridad', role: 'Certificación INDECI y Protocolos de Emergencia', icon: '🏟️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'seismic-agent', name: 'Agente de Riesgo Sísmico', role: 'Monitoreo de Terremotos y Volcanes de Arequipa', icon: '🌋', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'conmebol-venue', name: 'Agente CONMEBOL', role: 'Estándares Continentales de Recintos', icon: '🏆', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'university-rel', name: 'Agente Relaciones Universitarias', role: 'Convenio UNSA y Gobernanza de Doble Uso', icon: '🎓', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Portal INDECI', status: 'connected', type: 'Defensa Civil', icon: 'shield', detail: 'Arequipa Zona IV (máximo riesgo sísmico) — certificación pendiente' },
      { name: 'IGP Sísmico', status: 'connected', type: 'Monitor Terremotos', icon: 'activity', detail: 'Arequipa: 3 eventos >4.0 en últimos 90 días — Misti activo' },
      { name: 'Recintos CONMEBOL', status: 'connected', type: 'Inspección', icon: 'check-circle', detail: 'Inspección recinto Copa Libertadores — Semana 4' },
      { name: 'Admin UNSA', status: 'syncing', type: 'Universidad', icon: 'building', detail: 'Convenio doble uso: 18 días de partido + eventos universitarios' },
    ],
    script: [
      { agentId: 'venue-safety', phase: 'phase1', type: 'warning', delay: 800, content: 'AUDITORÍA DE SEGURIDAD — ESTADIO UNSA (45,000). Evaluación INDECI: (1) Evacuación: 14 minutos por 36 puertas — INDECI requiere 8 minutos para zona sísmica IV. BRECHA CRÍTICA. (2) Estructural: Última evaluación sísmica 2019 — 6 años. Refuerzo post-terremoto de Arequipa 2001 (magnitud 8.4) fue parcial. (3) Incendios: 298 de 320 extintores vigentes. Tribuna B sin cobertura de rociadores. (4) Iluminación de emergencia: 4 generadores — 1 falló última prueba. (5) Médico: 4 de 6 estaciones requeridas operativas. (6) Señalización: 40% solo en español — CONMEBOL requiere bilingüe (español/inglés) para partidos continentales.' },
      { agentId: 'seismic-agent', phase: 'phase1', type: 'analysis', delay: 2500, content: 'RIESGO SÍSMICO AREQUIPA — ELEVADO. (1) Zona IV: máxima clasificación sísmica en Perú. 3 eventos significativos (>4.0) en 90 días. (2) Volcán Misti: 17km del estadio — monitoreo activo. Última erupción 1985. Clasificación IGP: "potencialmente activo." (3) Histórico: terremoto 2001 (8.4) causó daño parcial al estadio. Enjambre 2024: 47 micro-eventos en cuenca de Arequipa. (4) UNSA sobre suelo aluvial — factor de amplificación 1.4x. (5) Durante partido con 45,000: evento 6.0+ durante evacuación de tribunas superiores crea riesgo de aplastamiento. Evacuación actual de 14 minutos es INACEPTABLE para zona sísmica IV. (6) No existe protocolo de evacuación específico para terremotos — solo plantilla genérica INDECI.' },
      { agentId: 'university-rel', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — CONFLICTO DE GOBERNANZA DE DOBLE USO. UNSA es dueña del estadio. Melgar alquila 18 días de partido. (1) Mejoras de capital requieren aprobación del consejo UNSA — proceso burocrático (60-90 días). (2) Prioridad de UNSA: eventos académicos, ceremonias de graduación. El fútbol es secundario. (3) Melgar ha invertido PEN 2.8M en mejoras pero UNSA controla la programación. (4) Refuerzo sísmico: estimado PEN 4.5M. ¿Quién paga? El contrato de alquiler de Melgar no incluye obligaciones estructurales. (5) Mi disenso: Melgar no puede garantizar cumplimiento de seguridad en un recinto que no es de su propiedad. O UNSA acepta gobernanza de seguridad compartida con Melgar o Melgar debe planificar contingencia de recinto alternativo.' },
      { agentId: 'conmebol-venue', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — INSPECCIÓN CONMEBOL SEMANA 4. Requisitos: (1) Certificado sísmico vigente (el de Melgar tiene 6 años — FALLA). (2) Evacuación menor a 10 minutos (14 — FALLA). (3) Todas las estaciones médicas operativas (4/6 — FALLA). (4) Señalización bilingüe (40% no conforme — FALLA). (5) Sala VAR climatizada (conforme). (6) Cancha: conforme. 4 de 6 requisitos CONMEBOL FALLAN. Si el recinto Copa Libertadores es rechazado, Melgar debe jugar en sede neutral — probablemente Lima. Jugar partidos "locales" de Copa en Lima destruye la identidad arequipeña y los ingresos de día de partido.' },
      { agentId: 'venue-safety', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Datacendia de Seguridad UNSA: (1) GOBERNANZA CONJUNTA: Proponer Comité de Seguridad Melgar-UNSA con revisiones trimestrales — Melgar financia mejoras relacionadas con fútbol, UNSA financia estructurales. Evidencia del acuerdo sellada. (2) SÍSMICO: Encargar evaluación independiente (2 semanas, PEN 85K). Protocolo de evacuación específico para terremotos para 45,000 — no genérico INDECI. (3) EVACUACIÓN: Despejar obstrucciones Tribuna B + agregar 4 salidas de emergencia = objetivo 9 minutos. (4) MÉDICO: Desplegar 2 estaciones temporales para partidos Copa. (5) SEÑALIZACIÓN: Kit bilingüe instalado Semana 2. (6) PAQUETE CONMEBOL: Presentar gobernanza conjunta + evaluación sísmica + mejoras como evidencia de gestión sistemática de seguridad.' },
      { agentId: 'university-rel', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Comité de Seguridad Conjunto resuelve la brecha de gobernanza de doble uso. UNSA se beneficia: infraestructura de seguridad moderna sirve también para eventos universitarios. Modelo de costo compartido es justo — estructural (UNSA), operacional (Melgar). Para CONMEBOL: el modelo de gobernanza conjunta puede ser la primera alianza de seguridad universidad-fútbol en el fútbol sudamericano. Para Arequipa: mantener la Copa Libertadores en la UNSA significa todo. 45,000 arequipeños en su estadio, gobernados por el protocolo de seguridad más riguroso del Perú provincial.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:mg30123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'mg40123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (INDECI + Evaluación sísmica + Recinto CONMEBOL + Gobernanza conjunta UNSA + Evacuación)',
      complianceLabel: 'Seguridad del Recinto',
      complianceValue: '4 BRECHAS CONMEBOL — GOBERNANZA CONJUNTA',
      complianceThreshold: 'INDECI Zona IV · Inspección CONMEBOL Semana 4',
      agents: ['Agente de Seguridad', 'Agente de Riesgo Sísmico', 'Agente CONMEBOL', 'Agente Relaciones Universitarias'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'FBC Melgar — Gobernanza de Seguridad Sísmica UNSA',
      guaranteeBody: 'Sella: auditoría UNSA 45,000, 4 brechas CONMEBOL, evaluación sísmica Zona IV, Comité Melgar-UNSA, protocolo de evacuación para terremotos, señalización bilingüe, defensa de sede Copa.',
      evidenceChain: 'Auditoría INDECI → Riesgo sísmico → Doble uso UNSA → Brechas CONMEBOL → Comité conjunto → Evacuación (9 min) → Médico → Señalización → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobernarán la seguridad del recinto en el estadio más expuesto sísmicamente del Perú — resolviendo gobernanza de doble uso y defendiendo la sede Copa Libertadores.',
    phaseLabels: ['Auditoría de Seguridad y Riesgo Sísmico', 'Gobernanza de Doble Uso y CONMEBOL', 'Protocolo de Seguridad Conjunto'],
  },

  // ESCENARIO 3 — GOBERNANZA DE ALTITUD AREQUIPA (2,335m)
  {
    id: 'altitude-arequipa',
    title: 'Gobernanza de Altitud Arequipa — Protocolos Médicos y Competitivos a 2,335m',
    subtitle: 'Altitud moderada · Aclimatación · Monitoreo SpO2 · Debate FIFA 2007 · Bienestar visitante',
    banner: 'Simulando gobernanza de altitud a 2,335m de Arequipa — altitud moderada justo debajo del umbral histórico de 2,500m de FIFA. Aunque menos extrema que Cusco (3,400m), equipos visitantes del nivel del mar experimentan impacto fisiológico medible que requiere gobernanza.',
    risk: 'Medio',
    scenarioNum: 'Altitud',
    icon: 'mountain',
    color: 'text-cyan-400',
    agents: [
      { id: 'medical-alt', name: 'Agente Médico', role: 'Fisiología de Altitud y Bienestar del Jugador', icon: '🏥', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
      { id: 'sporting-alt', name: 'Agente Deportivo', role: 'Equidad Competitiva y Aclimatación', icon: '⚽', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'legal-alt', name: 'Agente Legal', role: 'Regulaciones FIFA y Marco de Responsabilidad', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'data-alt', name: 'Agente de Analítica', role: 'Rendimiento Histórico y Modelado Fisiológico', icon: '📊', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
    ],
    connectors: [
      { name: 'Monitor de Altitud', status: 'connected', type: 'Fisiología', icon: 'heart', detail: 'SpO2 visitante: 93% promedio a 2,335m (normal: 96-99%)' },
      { name: 'Investigación FIFA', status: 'connected', type: 'Estudios de Altitud', icon: 'database', detail: 'Umbral prohibición 2007: 2,500m — Arequipa está 165m debajo' },
      { name: 'Datos de Rendimiento', status: 'connected', type: 'Analítica de Partidos', icon: 'bar-chart', detail: 'Tasa de victoria visitante en UNSA: 24% vs 38% promedio liga' },
      { name: 'Protocolo Médico', status: 'syncing', type: 'Salud del Jugador', icon: 'activity', detail: 'Marco de evaluación SpO2 pre-partido en desarrollo' },
    ],
    script: [
      { agentId: 'medical-alt', phase: 'phase1', type: 'warning', delay: 800, content: 'EVALUACIÓN DE ALTITUD — 2,335m AREQUIPA. Impacto fisiológico en equipos visitantes: (1) SpO2: promedio 93% vs 96-99% a nivel del mar — medible pero no sintomático para la mayoría. (2) Reducción VO2 máx: 8-12% (vs 15-25% a 3,400m Cusco). (3) Frecuencia cardíaca: +10-12% elevación. (4) Recuperación: más lenta entre esfuerzos de alta intensidad. (5) Incidentes históricos: 2 visitantes requirieron oxígeno en últimas 3 temporadas (condiciones preexistentes). (6) Diferencia clave con altitud extrema: 2,335m raramente causa MAM (mal agudo de montaña). Cefalea/náuseas en <5% de visitantes. Sin embargo, el rendimiento atlético SÍ se ve afectado de manera medible — la cuestión es gobernanza, no emergencia.' },
      { agentId: 'data-alt', phase: 'phase1', type: 'analysis', delay: 2500, content: 'DATOS DE RENDIMIENTO — 5 TEMPORADAS. (1) Tasa de victoria local de Melgar: 62% (promedio liga local: 48%). (2) Tasa de victoria visitante en UNSA: 24% (promedio liga visitante: 38%). (3) Goles visitantes por partido: 0.8 (promedio liga: 1.2). (4) Rendimiento visitante en 2do tiempo cae 18% (fatiga amplificada por altitud). (5) Patrones de sustitución: visitantes promedian 0.4 más cambios por partido en UNSA vs recintos a nivel del mar. (6) Comparación: Cusco (3,400m) tasa visitante 18%, Juliaca (3,827m) 15%. El 24% de Arequipa muestra ventaja moderada pero significativa. (7) Patrón: equipos visitantes que llegan 12+ horas antes rinden 15% mejor que los que llegan el mismo día.' },
      { agentId: 'legal-alt', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — GOBERNANZA VOLUNTARIA vs OBLIGATORIA. (1) La prohibición FIFA 2007 fue a 2,500m — Arequipa a 2,335m NUNCA fue restringida. (2) Ninguna regulación FPF requiere protocolos de altitud debajo de 2,500m. (3) CONMEBOL: sin requisitos específicos a esta elevación. (4) Mi disenso: implementar gobernanza formal de altitud a 2,335m crea un PRECEDENTE que podría usarse contra el fútbol peruano de altitud. Si Melgar voluntariamente dice "nuestra altitud necesita gobernanza," FIFA podría extender restricciones. La coalición de 2007 (Bolivia/Perú/Ecuador) luchó para REMOVER restricciones. Agregarlas voluntariamente socava esa lucha.' },
      { agentId: 'sporting-alt', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — CONTEXTO COMPETITIVO. (1) La ventaja local de Melgar ES su ventaja competitiva — un plantel de €9.29M no puede competir con clubes limeños (€11-14.7M) solo en talento. (2) La altitud de Arequipa es parte del panorama competitivo, no un peligro. (3) Sin embargo: 2 incidentes de oxígeno crean exposición de responsabilidad. (4) Si Melgar documenta que PROACTIVAMENTE gestiona el bienestar visitante a altitud moderada, fortalece el argumento de que el fútbol peruano gobierna la altitud responsablemente — lo que ayuda a Cusco (3,400m) y Juliaca (3,827m) a mantener sus partidos.' },
      { agentId: 'medical-alt', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Datacendia de Altitud Moderada (2,335m): (1) MEJOR PRÁCTICA VOLUNTARIA — no requisito regulatorio. Enmarcado como "bienestar del visitante" no "restricción de altitud." (2) PRE-PARTIDO: Verificación SpO2 ofrecida (no obligatoria). Resultados sellados pero no publicados. (3) RECOMENDACIÓN: Llegada 12h para equipos visitantes (recomendación, no requisito). Datos muestran 15% de mejora en rendimiento. (4) MÉDICO: Estaciones de oxígeno al borde de cancha + 2 posiciones en tribunas. Ya buena práctica — ahora documentada. (5) CONTRIBUCIÓN DE DATOS: Datos fisiológicos anonimizados contribuidos a investigación de altitud FPF/FIFA — posiciona a Melgar como líder de gobernanza. (6) MARCO: "Melgar demuestra que la altitud SE gobierna responsablemente en cada elevación del Perú."' },
      { agentId: 'legal-alt', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. El marco de "mejor práctica voluntaria" resuelve la preocupación de precedente. Al posicionar esto como bienestar del visitante (no restricción de altitud), Melgar contribuye a la defensa de altitud del Perú. Los datos sellados crean base de evidencia: "A 2,335m, los incidentes son raros y gestionados — esto apoya, no socava, el fútbol de altitud." Para FIFA: si el debate de 2007 resurge, Perú puede mostrar gobernanza en CADA elevación — desde Lima a nivel del mar hasta Juliaca a 3,827m. Melgar llena el vacío de altitud moderada en esa cadena de evidencia.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:mg50123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'mg60123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (Datos SpO2 + Analítica de rendimiento + Protocolo voluntario + Defensa altitud FIFA)',
      complianceLabel: 'Gobernanza de Altitud',
      complianceValue: 'MEJOR PRÁCTICA VOLUNTARIA — 2,335m',
      complianceThreshold: 'Debajo del umbral FIFA 2,500m — gobernanza proactiva',
      agents: ['Agente Médico', 'Agente Deportivo', 'Agente Legal', 'Agente de Analítica'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'FBC Melgar — Gobernanza de Altitud Moderada',
      guaranteeBody: 'Sella: protocolo voluntario 2,335m, evaluación SpO2 visitante, análisis de rendimiento 5 temporadas, recomendación de llegada 12h, contribución a defensa de altitud FIFA, documentación de preparación médica.',
      evidenceChain: 'Datos altitud → SpO2 (93%) → Rendimiento (5 años) → Protocolo voluntario → Defensa FIFA → Médico → Contribución datos → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA desarrollarán gobernanza voluntaria de altitud — posicionando a Melgar como administrador responsable del fútbol de altitud moderada mientras defiende el derecho del Perú a jugar en elevación.',
    phaseLabels: ['Datos Fisiológicos y de Rendimiento', 'Riesgo de Precedente y Contexto Competitivo', 'Protocolo de Mejor Práctica Voluntaria'],
  },

  // ESCENARIO 4 — ACADEMIA JUVENIL REGIONAL
  {
    id: 'youth-arequipa',
    title: 'Academia Juvenil — Cantera de Desarrollo Regional de Arequipa',
    subtitle: 'Talento del sur peruano · Cumplimiento CNA · FIFA Artículo 19 · Integración educativa · Orgullo provincial',
    banner: 'Simulando gobernanza del desarrollo juvenil para la cantera principal del sur del Perú. La academia de Melgar recluta de Arequipa, Tacna, Moquegua y Puno — gobernando educación, salvaguarda y separación familiar para menores de las regiones más pobres del Perú.',
    risk: 'Alto',
    scenarioNum: 'Juvenil',
    icon: 'users',
    color: 'text-emerald-400',
    agents: [
      { id: 'youth-safeguard', name: 'Agente de Salvaguarda', role: 'Cumplimiento CNA y Protección de Menores', icon: '👦', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'education-agent', name: 'Agente Educativo', role: 'Ley General de Educación y Verificación Escolar', icon: '📚', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'regional-dev', name: 'Agente de Desarrollo Regional', role: 'Talento del Sur Peruano e Impacto Comunitario', icon: '🌍', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'welfare-youth', name: 'Agente de Bienestar', role: 'Salud, Nutrición y Conexión Familiar', icon: '💚', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'Registro Juvenil FPF', status: 'connected', type: 'Registro de Jugadores', icon: 'database', detail: '38 jugadores de academia 12-18 — 14 de fuera de Arequipa' },
      { name: 'Portal MINEDU', status: 'connected', type: 'Verificación Educativa', icon: 'book-open', detail: 'Verificación de matrícula para los 38 menores' },
      { name: 'Coordinación MIMP', status: 'connected', type: 'Protección Infantil', icon: 'shield', detail: 'Registro DEMUNA para 14 menores no locales' },
      { name: 'Sistema de Contacto Familiar', status: 'syncing', type: 'Comunicación', icon: 'phone', detail: 'Informes familiares mensuales — 3 familias no localizables' },
    ],
    script: [
      { agentId: 'youth-safeguard', phase: 'phase1', type: 'warning', delay: 800, content: 'AUDITORÍA DE SALVAGUARDA — 38 MENORES DE ACADEMIA. (1) Consentimiento parental: 36/38 verificados. 2 jugadores de Puno (13, 14 años) tienen consentimiento de "amigo de la familia" — legalmente insuficiente bajo CNA Ley 27337. (2) Registro DEMUNA: 14 menores no locales — 11 registrados en DEMUNA Arequipa, 3 NO registrados. (3) Educación: 35/38 matriculados. 3 con asistencia debajo del 55% (conflictos con entrenamientos). (4) Médico: 38 certificados anuales. 2 menores de Tacna sin revisión dental. (5) Residencia: 14 en alojamiento de academia — última inspección independiente hace 20 meses. (6) Contacto familiar: 11 familias en contacto regular. 3 familias de pueblos remotos de Puno — sin teléfono, sin internet. Cartas enviadas pero recepción no confirmada.' },
      { agentId: 'education-agent', phase: 'phase1', type: 'analysis', delay: 2500, content: 'ANÁLISIS EDUCATIVO. 3 jugadores debajo del 55% de asistencia: (1) Jugador A (15, Moquegua): 52% — entrenamientos vespertinos se superponen mar/jue con escuela. (2) Jugador B (14, Puno): 48% — barrera lingüística. Quechua como primera lengua, dificultades en escuela de medio español. Sin apoyo académico del club. (3) Jugador C (16, Arequipa): 54% — convocatorias FPF U-17 contadas como inasistencias. Bajo Ley 28044 y CNA Art. 14: la educación es un derecho fundamental que prevalece sobre compromisos deportivos. La situación del Jugador B es particularmente preocupante — un quechuahablante de 14 años reubicado 400km de casa sin apoyo lingüístico no es solo un fallo educativo, es un fallo de bienestar.' },
      { agentId: 'regional-dev', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — TENSIÓN DEL DESARROLLO REGIONAL. (1) Melgar es la ÚNICA academia de élite del sur peruano. Sin ella, el talento de Tacna, Moquegua, Puno no tiene camino excepto Lima (1,000km). (2) Cerrar brechas es esencial, pero protocolos excesivamente restrictivos podrían reducir captación regional — empujando familias hacia "academias" no registradas (Escenario 4 FPF Perú documentó esto). (3) Mi disenso: las 3 familias no localizables de Puno remoto no pueden contactarse por métodos estándar. Enviar personal de Melgar a pueblos cuesta PEN 3,500 por viaje. Con el presupuesto de Melgar, esto es significativo. (4) LA SOLUCIÓN DEBE SER: proporcional a los recursos de un club provincial. Estándares limeños aplicados rígidamente a realidades arequipeñas fracasarán.' },
      { agentId: 'welfare-youth', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — PREOCUPACIONES DE BIENESTAR INMEDIATAS. (1) Jugador B (14, quechuahablante): aislado, fracaso académico, 400km de familia, sin apoyo lingüístico = alta vulnerabilidad. Riesgo de deserción y explotación. (2) 3 familias no localizables: si las familias no saben dónde están sus hijos, CNA Art. 8 (derecho a vivir con la familia) está comprometido. (3) Alojamiento de academia: brecha de inspección de 20 meses. (4) Nutrición: 2 jugadores de Puno mostrando signos de deficiencia proteica — ajuste de altitud de 3,827m a 2,335m afecta el apetito. (5) Apoyo psicológico: cero. Niños de 14 años separados de familias en cultura diferente necesitan apoyo estructurado de bienestar.' },
      { agentId: 'youth-safeguard', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Datacendia de Juventud Regional: (1) INMEDIATO: Jugador B — tutor de quechua + apoyo académico. 2 jugadores de Puno — suspender hasta obtener consentimiento de tutor legal. Registro DEMUNA para 3 no registrados. Inspección de alojamiento en 10 días. (2) CONTACTO FAMILIAR: Asociarse con DEMUNA Puno para visitas familiares presenciales. Costo compartido con fondo de desarrollo regional FPF. (3) EDUCACIÓN: Cero conflictos con horario escolar. Convocatorias FPF coordinadas con MINEDU. Debajo del 65% activa suspensión. (4) NUTRICIÓN: Programa dietético de transición de altitud. (5) BIENESTAR: Evaluaciones psicológicas trimestrales. Consejero quechuahablante para menores de Puno/Cusco. (6) PROPORCIONAL: Protocolo escalado a recursos de club provincial — co-financiamiento FPF para bienestar regional.' },
      { agentId: 'regional-dev', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Co-financiamiento FPF hace el bienestar regional proporcional. Alianzas con DEMUNA aprovechan infraestructura existente. El protocolo no restringe captación regional — la hace MÁS SEGURA. Para CONMEBOL: la academia regional de Melgar se convierte en modelo de desarrollo juvenil provincial en toda Sudamérica. Para el sur peruano: 14 menores no locales merecen la misma salvaguarda que jugadores de academia limeños. La misión de Melgar — desarrollar el talento arequipeño — solo es legítima si cada niño está protegido. El Recibo del Regulador prueba que lo están.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:mg70123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'mg80123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (Auditoría CNA + Educación + DEMUNA + Contacto familiar + Bienestar regional)',
      complianceLabel: 'Salvaguarda Juvenil',
      complianceValue: '2 SUSPENSIONES + APOYO QUECHUA',
      complianceThreshold: 'CNA Ley 27337 + Ley 28044 + FPF Regional',
      agents: ['Agente de Salvaguarda', 'Agente Educativo', 'Agente de Desarrollo Regional', 'Agente de Bienestar'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'FBC Melgar — Gobernanza de Academia Juvenil Regional',
      guaranteeBody: 'Sella: auditoría de 38 menores, 2 suspensiones de consentimiento, 3 intervenciones educativas, apoyo lingüístico quechua, alianzas DEMUNA, protocolo de contacto familiar, bienestar regional co-financiado FPF.',
      evidenceChain: 'Auditoría (38) → Consentimiento (2 brechas) → Educación (3 debajo 55%) → Jugador B (quechua) → DEMUNA → Visitas familiares → Nutrición → Alojamiento → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobernarán la cantera principal del sur peruano — asegurando salvaguarda, educación y conexión familiar para menores de las regiones más pobres del país.',
    phaseLabels: ['Auditoría de Salvaguarda y Educación', 'Desafíos Regionales y Bienestar', 'Protocolo Regional Proporcional'],
  },

  // ESCENARIO 5 — SOSTENIBILIDAD FINANCIERA COPA LIBERTADORES
  {
    id: 'copa-finance',
    title: 'Sostenibilidad Financiera Copa Libertadores — Club Provincial en Competición Continental',
    subtitle: '€9.29M plantel · Licencias CONMEBOL · Cumplimiento SUNAT · Costos de viaje · Profundidad del plantel',
    banner: 'Simulando gobernanza financiera para un club provincial compitiendo en la Copa Libertadores. El plantel de €9.29M de Melgar debe navegar costos de viaje continental, asignación de premios, obligaciones SUNAT sobre ingresos internacionales y fair play financiero CONMEBOL — todo con un presupuesto 37% menor que Universitario.',
    risk: 'Alto',
    scenarioNum: 'Finanzas',
    icon: 'landmark',
    color: 'text-blue-400',
    agents: [
      { id: 'financial-copa', name: 'Agente Financiero', role: 'Presupuesto Copa y Gestión de Flujo de Caja', icon: '💰', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'conmebol-fin', name: 'Agente Licencias CONMEBOL', role: 'Fair Play Financiero e Indicadores', icon: '🏆', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'sunat-intl', name: 'Agente SUNAT', role: 'Ingresos Internacionales y Tratados Fiscales', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'sporting-depth', name: 'Agente Deportivo', role: 'Gestión de Plantel y Rotación Continental', icon: '⚽', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Finanzas CONMEBOL', status: 'connected', type: 'Licencias de Clubes', icon: 'check-circle', detail: 'Indicadores financieros: ÁMBAR — umbral de pagos vencidos' },
      { name: 'SUNAT Internacional', status: 'connected', type: 'Cumplimiento Fiscal', icon: 'landmark', detail: 'Premios Copa: retención sobre ingresos de fuente extranjera' },
      { name: 'Presupuesto de Viaje', status: 'connected', type: 'Gestión de Costos', icon: 'plane', detail: 'Fase de grupos: 3 partidos fuera — prom. $45K por viaje desde Arequipa' },
      { name: 'Modelo de Flujo de Caja', status: 'syncing', type: 'Planificación Financiera', icon: 'bar-chart', detail: 'Superávit mensual: PEN 180K — Costos Copa: PEN 540K/viaje' },
    ],
    script: [
      { agentId: 'financial-copa', phase: 'phase1', type: 'warning', delay: 800, content: 'ANÁLISIS FINANCIERO COPA LIBERTADORES. Presupuesto fase de grupos de Melgar: (1) Premios: $1.0M garantizados (fase de grupos). Si avanza: $1.5M (octavos). (2) Viajes: 3 partidos fuera desde Arequipa. Buenos Aires: $48K. São Paulo: $52K. Bogotá: $38K. Total viajes: $138K (~PEN 540K). (3) Refuerzos para profundidad continental: PEN 2.1M (3 jugadores). (4) Personal adicional de día de partido, seguridad, médico para estándares CONMEBOL: PEN 320K. (5) Inversión total Copa: ~PEN 3.5M. (6) Superávit mensual: PEN 180K. Costos Copa EXCEDEN 19 meses de superávit. (7) Timing: costos son anticipados (viajes, refuerzos) pero premios llegan después de completar fase de grupos. Brecha de flujo de caja: PEN 2.8M por 4 meses.' },
      { agentId: 'conmebol-fin', phase: 'phase1', type: 'analysis', delay: 2500, content: 'Evaluación de Fair Play Financiero CONMEBOL: (1) Indicadores actuales: ÁMBAR. Pagos vencidos: PEN 420K (2 proveedores, 1 cuota SUNAT). (2) Inversión Copa empuja ratio deuda-ingresos de 0.62 a 0.78 — aún debajo del umbral ROJO de 0.80, pero el margen es mínimo. (3) Salarios-ingresos: actualmente 68%. Agregar 3 refuerzos empuja a 74% — ÁMBAR se mantiene pero se acerca a ROJO (75%). (4) Empresa en marcha: si Melgar es eliminado en fase de grupos Y no vende jugadores, hay déficit de caja de 4 meses post-Copa. (5) CONMEBOL requiere "expectativa razonable de continuidad financiera." La trayectoria actual requiere premios O ingresos por transferencias para mantener continuidad.' },
      { agentId: 'sunat-intl', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — INGRESOS INTERNACIONALES SUNAT. (1) Premios Copa ($1.0M = ~PEN 3.9M): ingreso de fuente extranjera, totalmente gravable. Impuesto a la Renta: 29.5% = PEN 1.15M. (2) CONMEBOL paga en USD — riesgo cambiario durante fase de grupos de 4 meses. (3) Plan de fraccionamiento SUNAT existente de Melgar: faltar UN pago = aceleración de toda la deuda. Brecha de flujo Copa hace esto probable en Mes 2. (4) Comisiones de agentes por 3 refuerzos: deducibilidad requiere documentación de cumplimiento FIFA FFAR. (5) Mi disenso: Melgar NO debería fichar 3 refuerzos antes de asegurar financiamiento puente. Si la brecha de flujo Copa fuerza un pago SUNAT perdido, todo el plan de fraccionamiento colapsa — la Copa se vuelve financieramente destructiva.' },
      { agentId: 'sporting-depth', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — REALIDAD DE PROFUNDIDAD DE PLANTEL. (1) Liga 1 + Copa requiere 40+ partidos competitivos. Plantel actual: 26. Mínimo industria para doble competición: 28-30. (2) 3 refuerzos es mínimo, no lujo. Sin profundidad: brechas por lesión/suspensión fuerzan a jugadores juveniles a competición continental prematuramente. (3) Alternativa: 2 refuerzos (PEN 1.4M vs 2.1M) + promover 2 graduados de cantera. Ahorra PEN 700K pero aumenta riesgo deportivo. (4) Rotación continental: primer equipo de Melgar juega jueves (Copa) luego domingo (Liga 1) — recuperación a 2,335m de altitud es 15% más lenta que a nivel del mar. La profundidad de plantel es tema de bienestar, no solo deportivo.' },
      { agentId: 'financial-copa', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Financiero Datacendia Copa: (1) FINANCIAMIENTO PUENTE: Facilidad de crédito a corto plazo PEN 2.8M contra premios Copa como garantía. Negociar con banco local usando cronograma de pagos CONMEBOL como colateral. (2) REFUERZOS ESCALONADOS: Fichar 2 inmediatamente (PEN 1.4M) + 1 a préstamo con opción (difiere PEN 700K). (3) PROTECCIÓN SUNAT: Reservar 2 cuotas SUNAT (PEN 360K) antes de cualquier gasto Copa. Nunca faltar un pago. (4) CONMEBOL: Reportes financieros mensuales con evidencia sellada — cumplimiento proactivo. (5) CONTINGENCIA: Si eliminados en fase de grupos, venta de jugador (1 titular) cubre déficit. Objetivo identificado, valoración sellada, no activado salvo necesidad. (6) PREMIOS: 40% reducción deuda, 30% plantel, 20% infraestructura, 10% cantera.' },
      { agentId: 'sunat-intl', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Reserva SUNAT + financiamiento puente resuelve la brecha de flujo sin arriesgar el plan de fraccionamiento. Préstamo con opción reduce costo anticipado. Para CONMEBOL: Melgar demuestra que un club provincial con PEN 180K de superávit mensual puede competir continentalmente CON gobernanza — no irresponsablemente. El plan de contingencia (venta de jugador si eliminados) muestra madurez financiera. Para Arequipa: la Copa Libertadores es el momento deportivo más grande de la ciudad. Gobernada correctamente, fortalece al club. Gobernada irresponsablemente, podría destruirlo. El Recibo del Regulador asegura lo primero.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:mg90123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'mga0123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz Merkle (Presupuesto Copa + Financiamiento puente + Reserva SUNAT + FFP CONMEBOL + Contingencia)',
      complianceLabel: 'Sostenibilidad Financiera',
      complianceValue: 'FINANCIAMIENTO PUENTE + RESERVA SUNAT',
      complianceThreshold: 'CONMEBOL deuda-ingresos < 0.80 · Cuotas SUNAT protegidas',
      agents: ['Agente Financiero', 'Agente Licencias CONMEBOL', 'Agente SUNAT', 'Agente Deportivo'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'FBC Melgar — Gobernanza Financiera Copa Libertadores',
      guaranteeBody: 'Sella: presupuesto Copa PEN 3.5M, financiamiento puente contra premios, reserva SUNAT (PEN 360K), refuerzos escalonados, cumplimiento FFP CONMEBOL, contingencia venta jugador, asignación de premios.',
      evidenceChain: 'Sorteo Copa → Presupuesto (PEN 3.5M) → Brecha caja (PEN 2.8M) → Financiamiento puente → Reserva SUNAT → Refuerzos → CONMEBOL → Contingencia → Asignación premios → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobernarán las finanzas Copa Libertadores de un club provincial — asegurando que la ambición continental no destruya la estabilidad financiera.',
    phaseLabels: ['Presupuesto Copa y Brecha de Flujo', 'Riesgo SUNAT y CONMEBOL', 'Financiamiento Puente y Contingencia'],
  },
];
