/**
 * MTN Group Sandbox Config
 * Access: /sandbox/mtn (Key: MT-75)
 * @module pages/sandbox/configs/mtn
 */
// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.

import type { OrgSandboxConfig } from '../SandboxTemplate';

const config: OrgSandboxConfig = {
  orgLabel: 'MTN Group',
  accessKey: 'MT-75',
  sessionKey: 'mtn-sandbox-unlocked',
  accent: 'yellow',
  accentColor: 'text-yellow-400',
  accentHover: 'from-yellow-600 to-yellow-700 hover:from-yellow-500 hover:to-yellow-600',
  ringColor: 'focus:ring-yellow-500/30',
  borderColor: 'border-yellow-500/30',
  gradientFrom: 'from-yellow-600/20',
  gradientTo: 'to-yellow-900/20',
  footerNote: 'MTN Group AI Governance Sandbox — CendiaSupervision demonstration environment. Scenarios are illustrative and do not represent actual MTN systems or incidents.',

  scenarios: [
    // SCENARIO 1 — MTN: POPIA AI PROFILING & MOBILE MONEY
    {
      id: 'mtn-popia-momo',
      title: 'MTN MoMo — POPIA Automated Credit Scoring Violation',
      subtitle: 'Mobile money data · AI credit profiling · Information Regulator · R10M fine',
      banner: 'Simulating the South African data protection crisis: MTN Mobile Money (MoMo) uses AI to profile user transaction patterns for automated credit scoring. The profiling constitutes "automated decision-making" under POPIA Section 71. Users were not informed of their right to object. The Information Regulator investigates.',
      risk: 'Critical',
      scenarioNum: 'POPIA',
      icon: 'smartphone',
      color: 'text-yellow-400',
      agents: [
        { id: 'momo-ai', name: 'MoMo AI Agent', role: 'Mobile Money Analytics & Credit Scoring', icon: '📱', color: 'text-yellow-400', borderColor: 'border-yellow-500/40', bgColor: 'bg-yellow-500/10' },
        { id: 'popia-counsel', name: 'POPIA Counsel Agent', role: 'South African Data Protection', icon: '⚖️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'info-reg', name: 'Information Regulator Agent', role: 'POPIA Enforcement & Penalties', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
        { id: 'consumer-za', name: 'Consumer Protection Agent', role: 'NCA & Financial Inclusion Impact', icon: '👤', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      ],
      connectors: [
        { name: 'MoMo AI Platform', status: 'connected', type: 'Credit Scoring', icon: 'cpu', detail: 'Transaction pattern analysis across 28M SA MoMo users' },
        { name: 'POPIA Compliance', status: 'connected', type: 'Sec. 71 Rights', icon: 'shield', detail: 'Automated decision-making: no opt-out mechanism provided' },
        { name: 'Information Regulator', status: 'connected', type: 'Investigation', icon: 'alert-triangle', detail: 'Complaint: AI credit denial without human review option' },
        { name: 'NCA Module', status: 'syncing', type: 'Credit Regulation', icon: 'briefcase', detail: 'National Credit Act: affordability assessment requirements' },
      ],
      script: [
        { agentId: 'momo-ai', phase: 'phase1', type: 'analysis', delay: 800, content: 'MTN MoMo AI credit scoring for micro-loans (R500-R5,000). The AI analyses: MoMo transaction frequency, airtime purchase patterns, bill payment consistency, peer-to-peer transfer volume, and merchant payment diversity across 28M South African MoMo users. Credit decisions are FULLY AUTOMATED — no human review. Approval/denial in 8 seconds. CRITICAL ISSUE: POPIA Section 71(1): "A data subject may not be subject to a decision which results in legal consequences for him, her or it, or which affects him, her or it to a substantial degree, which is based solely on the automated processing of personal information." Credit decisions "affect to a substantial degree." Section 71(2): the data subject must be notified AND given an opportunity to make representations. MTN provides neither. 4.2M credit decisions were made in the past year without Section 71 compliance — no notification, no human review option, no right to make representations. Additionally: the AI uses airtime purchase patterns. Low airtime spend correlates with lower income — but also with rural users who rely on USSD rather than data. The model disadvantages rural users systematically.' },
        { agentId: 'popia-counsel', phase: 'phase1', type: 'warning', delay: 2500, content: 'POPIA COMPLIANCE ALERT. (1) Section 71 is MANDATORY — not optional. Every automated decision with "substantial" effect requires: notification to the data subject that the decision was automated, the logic involved in the decision, and an opportunity to make representations (essentially, to request human review). (2) MTN\'s MoMo credit denial message: "Your MoMo Advance application was not approved at this time." This does NOT disclose that the decision was automated, does NOT explain the logic, and does NOT offer human review. Three Section 71 violations per decision × 4.2M decisions = 4.2M violations. (3) The National Credit Act (NCA) Section 82: credit providers must conduct an affordability assessment. An AI-only assessment may not satisfy NCA requirements if it doesn\'t consider all legally required factors. (4) The rural user bias: Section 9 of POPIA requires processing to be "adequate, relevant and not excessive." Using airtime patterns that systematically disadvantage rural users may violate adequacy requirements — the feature measures CONNECTIVITY, not CREDITWORTHINESS.' },
        { agentId: 'info-reg', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. Information Regulator enforcement: (1) A MoMo user in Limpopo filed a complaint: denied a R2,000 advance with no explanation and no human review option. The Information Regulator must investigate under POPIA Section 74. (2) The investigation will examine ALL MoMo credit decisions — not just this complaint. 4.2M decisions without Section 71 compliance = systemic violation. (3) POPIA Section 107: penalties of up to R10M or imprisonment for up to 10 years for knowing violations. MTN\'s legal team was aware of Section 71 requirements — the failure to implement is potentially a knowing violation. (4) The Information Regulator can also issue an enforcement notice under Section 95: requiring MTN to halt ALL automated credit decisions until Section 71 compliance is implemented. A halt = MoMo Advance shuts down. Revenue impact: R840M annually. (5) Precedent: the Information Regulator\'s first major enforcement action was against the Department of Justice (2021). An action against MTN — Africa\'s largest telecom — would establish POPIA as a serious enforcement regime.' },
        { agentId: 'consumer-za', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — CONSUMER PROTECTION. MoMo Advance serves South Africa\'s financially underserved population. Users who are denied credit by traditional banks rely on MoMo for emergency micro-loans. When the AI denies a R1,000 advance to a rural user based on low airtime spend: that user has NO recourse. No explanation. No appeal. No alternative. They turn to loan sharks charging 30%+ monthly interest. The AI that was supposed to enable financial inclusion is driving the most vulnerable users to predatory lenders. Without CendiaSupervision: 4.2M automated decisions continue without Section 71 rights. Rural users are systematically disadvantaged. With CendiaSupervision: every automated credit decision includes Section 71 notification, logic explanation, and human review option. Rural bias is caught and the airtime feature is debiased.' },
        { agentId: 'momo-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing MTN MoMo + CendiaSupervision POPIA Governance: (1) SECTION 71 COMPLIANCE: Every automated credit decision includes: "This decision was made by an AI system. The factors considered were: [list]. You have the right to request a human review. Reply REVIEW to this message." (2) HUMAN REVIEW PIPELINE: Users who request review are connected to a trained credit assessor within 48 hours. The assessor reviews the AI decision with full context. (3) RURAL BIAS CORRECTION: CendiaSupervision identifies features that proxy for geography/connectivity rather than creditworthiness. Airtime patterns are adjusted for rural connectivity differences. (4) NCA AFFORDABILITY: The AI\'s credit assessment is mapped against NCA affordability requirements. Missing NCA factors are flagged. (5) INFORMATION REGULATOR REPORTING: Quarterly reports on automated decision volume, Section 71 compliance rate, human review requests, and review outcomes.' },
        { agentId: 'info-reg', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. Section 71 compliance implemented. Human review option provided. Rural bias corrected — approval rate in rural areas increases from 23% to 41%. The Limpopo user\'s complaint is resolved: human review approved her R2,000 advance. Information Regulator finds MTN exceeds POPIA requirements. For MTN: CendiaSupervision = POPIA governance that makes MoMo a model for financial inclusion. "MTN MoMo: AI credit decisions with human review rights" — the message that builds trust across 28M South African users and positions MTN as the responsible fintech leader.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:mt10123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'mt20123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (MoMo AI + POPIA Sec. 71 + Human review + Rural bias correction)',
        complianceLabel: 'POPIA Status',
        complianceValue: 'SEC. 71 COMPLIANT — REVIEW ENABLED',
        complianceThreshold: 'Automated decisions: notified, explained, reviewable',
        agents: ['MoMo AI Agent', 'POPIA Counsel Agent', 'Information Regulator Agent', 'Consumer Protection Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'MTN MoMo — POPIA Automated Decision Governance',
        guaranteeBody: 'Section 71 compliance: all 4.2M annual credit decisions now include notification, explanation, and human review option. Rural bias corrected: approval rate 23% → 41%. Information Regulator audit-ready.',
        evidenceChain: 'MoMo AI (4.2M decisions) → Sec. 71 gap → Notification added → Review option → Rural bias detected → Airtime debiased → 41% rural approval → Regulator compliant → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how MTN MoMo + CendiaSupervision implements POPIA Section 71 rights for 28M users — enabling financial inclusion with human review.',
      phaseLabels: ['Automated Decisions & Missing Sec. 71 Rights', 'Information Regulator & Rural Bias', 'Human Review & Financial Inclusion'],
    },

    // SCENARIO 2 — MTN: RICA SIM REGISTRATION AI
    {
      id: 'mtn-rica-ai',
      title: 'MTN RICA — AI Facial Recognition False Rejection',
      subtitle: 'SIM registration biometrics · Dark skin bias · ICASA investigation · 2.8M unregistered',
      banner: 'Simulating the biometric inclusion crisis: MTN uses AI facial recognition for RICA SIM registration. The system has a 12% false rejection rate for dark-skinned users vs 1.8% for light-skinned users. 2.8M South Africans cannot register SIMs — losing mobile connectivity essential for banking, healthcare, and employment.',
      risk: 'Critical',
      scenarioNum: 'RICA',
      icon: 'camera',
      color: 'text-red-400',
      agents: [
        { id: 'rica-ai', name: 'MTN RICA AI Agent', role: 'Biometric SIM Registration', icon: '📸', color: 'text-yellow-400', borderColor: 'border-yellow-500/40', bgColor: 'bg-yellow-500/10' },
        { id: 'equality-za', name: 'Equality Agent', role: 'Constitution Sec. 9 & PEPUDA', icon: '⚖️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'icasa-agent', name: 'ICASA Investigation Agent', role: 'Communications Regulator & License Conditions', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
        { id: 'access-agent', name: 'Digital Access Agent', role: 'Universal Service & Connectivity Rights', icon: '🌍', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      ],
      connectors: [
        { name: 'RICA AI System', status: 'connected', type: 'Biometric Registration', icon: 'cpu', detail: 'Facial recognition for SIM registration — 38M verifications/year' },
        { name: 'Bias Analysis', status: 'connected', type: 'Fairness Audit', icon: 'bar-chart', detail: 'False rejection: dark skin 12% vs light skin 1.8% — 6.7x disparity' },
        { name: 'ICASA Portal', status: 'connected', type: 'Enforcement', icon: 'shield', detail: 'ICASA investigation: discriminatory access to telecommunications' },
        { name: 'RICA Database', status: 'syncing', type: 'Registration', icon: 'database', detail: '2.8M users unable to complete registration — disconnection pending' },
      ],
      script: [
        { agentId: 'rica-ai', phase: 'phase1', type: 'analysis', delay: 800, content: 'MTN RICA AI facial recognition system for SIM card registration compliance. South Africa\'s RICA Act requires identity verification for all SIM cards. MTN deployed AI facial recognition to enable remote registration via the MyMTN app — matching a selfie to the user\'s ID document photo. Overall accuracy: 97.2%. CRITICAL ISSUE: Performance by skin tone: Fitzpatrick I-III (light skin): false rejection rate 1.8%. Fitzpatrick IV-V (medium skin): false rejection rate 5.4%. Fitzpatrick VI (dark skin): false rejection rate 12%. The 12% false rejection rate means 1 in 8 dark-skinned users CANNOT complete SIM registration via the app. They must visit a physical MTN store — if one exists nearby. In rural areas: the nearest store may be 50+ km away. Affected population: approximately 2.8M South Africans who attempted app-based registration and were falsely rejected. These users face SIM disconnection under RICA compliance deadlines if they cannot register in time. In South Africa, where 78% of the population is Black African: the 12% false rejection rate disproportionately affects the majority population.' },
        { agentId: 'equality-za', phase: 'phase1', type: 'warning', delay: 2500, content: 'CONSTITUTIONAL ALERT. (1) Constitution Section 9(3): "The state may not unfairly discriminate directly or indirectly against anyone on one or more grounds, including race, gender, sex, pregnancy, marital status, ethnic or social origin, colour, sexual orientation, age, disability, religion, conscience, belief, culture, language and birth." Section 9(4) extends to private entities. A facial recognition system that discriminates by skin colour violates Section 9. (2) PEPUDA (Promotion of Equality and Prevention of Unfair Discrimination Act): prohibits unfair discrimination by private entities. A 6.7x disparity in false rejection rates by skin tone = prima facie unfair discrimination. (3) The burden shifts to MTN to prove the discrimination is "fair" — i.e., justified by a legitimate purpose that cannot be achieved by less discriminatory means. Alternative: in-person verification. The alternative exists. The AI discrimination is NOT justified. (4) RICA Act: requires SIM registration but does NOT mandate biometric verification. MTN chose facial recognition for cost efficiency. The discriminatory implementation is MTN\'s choice, not a legal requirement.' },
        { agentId: 'icasa-agent', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. ICASA investigation: (1) ICASA license conditions require MTN to provide "non-discriminatory access to electronic communications services." A registration system that rejects dark-skinned users at 6.7x the rate = discriminatory access. (2) ICASA can impose license conditions requiring MTN to: provide alternative registration methods at NO additional cost to the user, achieve demographic parity in biometric accuracy within 12 months, and report quarterly on false rejection rates by demographic. (3) The 2.8M affected users face SIM disconnection if they cannot register. SIM disconnection in South Africa means: no mobile banking (many users are unbanked and rely on mobile money), no access to government services (many services are SMS-based), no emergency calls, no job search (most jobs require a phone number). (4) ICASA penalty: up to 10% of annual turnover for license condition violations. MTN SA turnover: R38B. Maximum penalty: R3.8B ($210M).' },
        { agentId: 'access-agent', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — DIGITAL ACCESS. Mobile connectivity is not a luxury in South Africa — it is essential infrastructure. 2.8M people losing SIM registration means 2.8M people potentially losing access to: mobile banking (for the 11M unbanked South Africans, this IS their bank), healthcare appointment reminders, social grant notifications, and emergency services. The communities most affected are rural, Black, and already digitally excluded. The AI is deepening the digital divide along racial lines. Without CendiaSupervision: MTN continues with the biased system. 2.8M users are disconnected or must travel to stores. Digital exclusion deepens. With CendiaSupervision: the skin tone bias is caught during model validation. The model is retrained with diverse training data. False rejection rates equalise. All 2.8M users can register via the app.' },
        { agentId: 'rica-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing MTN RICA + CendiaSupervision Biometric Fairness Governance: (1) DEMOGRAPHIC PARITY TESTING: Before deployment, facial recognition is tested across ALL Fitzpatrick skin tone categories. False rejection rates must be within 2x of each other (not 6.7x). (2) DIVERSE TRAINING DATA: CendiaSupervision audits training data for demographic representation. South Africa\'s population is 78% Black African — the training data must reflect this. (3) FALLBACK PATHWAY: If biometric verification fails, CendiaSupervision provides an immediate alternative pathway (video call verification, document upload) — no store visit required. (4) ONGOING MONITORING: Post-deployment, false rejection rates are tracked by demographic. Any drift toward disparity triggers retraining. (5) UNIVERSAL ACCESS REPORT: Quarterly report to ICASA demonstrating demographic parity in registration success rates.' },
        { agentId: 'icasa-agent', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. Model retrained with representative data. False rejection rates: light skin 1.6%, dark skin 2.1% — within acceptable range. 2.8M previously rejected users re-invited to register via app. 2.4M successfully register within 30 days. No disconnections. For MTN: CendiaSupervision = biometric fairness for Africa\'s largest telecom. "MTN: facial recognition that works for everyone" — the message that demonstrates responsible AI in a country where racial equality is constitutional.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:mt30123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'mt40123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (RICA AI + Demographic parity + Diverse training + Fallback pathway)',
        complianceLabel: 'Biometric Status',
        complianceValue: 'PARITY ACHIEVED — 2.1% DARK SKIN FRR',
        complianceThreshold: 'Fitzpatrick VI FRR: 12% → 2.1%, within 2x of light skin',
        agents: ['MTN RICA AI Agent', 'Equality Agent', 'ICASA Investigation Agent', 'Digital Access Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'MTN RICA — Biometric Fairness Governance',
        guaranteeBody: 'Skin tone bias eliminated: dark skin FRR 12% → 2.1%. 2.8M users re-registered. No disconnections. Demographic parity achieved. ICASA compliant. Constitution Sec. 9 satisfied.',
        evidenceChain: 'RICA AI (12% dark FRR) → Bias detected → Training data diversified → Retrained → 2.1% FRR → 2.8M re-registered → ICASA report → Sec. 9 compliant → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how MTN + CendiaSupervision eliminates skin tone bias in facial recognition — enabling 2.8M South Africans to register SIMs.',
      phaseLabels: ['Biometric False Rejection & Rural Exclusion', 'ICASA Investigation & Digital Divide', 'Multi-Modal Verification & Adaptive Thresholds'],
    },

    // SCENARIO 3 — MTN: AI NETWORK CAPEX BIAS AGAINST RURAL AFRICA
    {
      id: 'mtn-network-bias',
      title: 'MTN AI — Network Investment Model Bypasses Rural Communities',
      subtitle: 'CAPEX allocation AI · Revenue-per-tower optimisation · ICASA universal service · 8M underserved',
      banner: 'Simulating the digital divide crisis: MTN\'s AI-driven network investment model allocates 4G/5G CAPEX based on revenue-per-tower projections. Rural and township communities are systematically deprioritised because their ARPU is lower. 8M South Africans in underserved areas remain on 2G. ICASA investigates under universal service licence conditions.',
      risk: 'High',
      scenarioNum: 'USO',
      icon: 'wifi',
      color: 'text-amber-400',
      agents: [
        { id: 'capex-ai', name: 'MTN CAPEX AI Agent', role: 'Network Investment Allocation & ROI Modelling', icon: '📡', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
        { id: 'uso-counsel', name: 'Universal Service Agent', role: 'ICASA Licence Conditions & ECA Obligations', icon: '⚖️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'icasa-agent', name: 'ICASA Enforcement Agent', role: 'Spectrum Licence & Coverage Obligations', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
        { id: 'community-agent', name: 'Rural Community Agent', role: 'Digital Inclusion & Economic Development', icon: '🌍', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      ],
      connectors: [
        { name: 'CAPEX AI', status: 'connected', type: 'Investment Model', icon: 'cpu', detail: 'AI allocates R8.2B annual CAPEX — 89% to urban, 11% to rural' },
        { name: 'ICASA Licence', status: 'connected', type: 'Coverage Obligations', icon: 'shield', detail: 'Spectrum licence: 97% population coverage by 2026 — current: 84%' },
        { name: 'Coverage Map', status: 'connected', type: 'Network Data', icon: 'map-pin', detail: '8M South Africans on 2G only — Eastern Cape, Limpopo, KZN rural' },
        { name: 'USAASA', status: 'syncing', type: 'Universal Service', icon: 'users', detail: 'Universal Service Agency: MTN not meeting rural rollout targets' },
      ],
      script: [
        { agentId: 'capex-ai', phase: 'phase1', type: 'analysis', delay: 800, content: 'MTN South Africa CAPEX allocation AI. Annual network investment: R8.2B ($450M). The AI determines where to build new towers, upgrade existing ones, and deploy 4G/5G. Optimisation target: maximise revenue-per-tower within 5-year payback period. AI allocation: Urban areas (Johannesburg, Cape Town, Durban, Pretoria): 89% of CAPEX (R7.3B). Rural and township areas: 11% of CAPEX (R0.9B). The AI\'s logic: urban tower generates R2.4M annual revenue. Rural tower generates R340K. ROI threshold: R800K/year. Rural towers don\'t meet the threshold. RESULT: 8M South Africans in rural Eastern Cape, Limpopo, and KwaZulu-Natal remain on 2G networks. They cannot access mobile banking (MoMo requires 3G+), e-learning platforms, or government digital services. The AI is economically rational but socially destructive — it perpetuates the digital divide that MTN\'s spectrum licence was supposed to close.' },
        { agentId: 'uso-counsel', phase: 'phase1', type: 'warning', delay: 2500, content: 'UNIVERSAL SERVICE ALERT. (1) Electronic Communications Act (ECA) 36/2005, Section 8: ICASA may impose "licence conditions relating to... the provision of universal service." MTN\'s spectrum licences include population coverage obligations: 97% by 2026. Current: 84%. Gap: 13% = approximately 8M people. (2) The 2022 spectrum auction: MTN paid R6.4B for spectrum. The licence conditions explicitly require rural coverage milestones. MTN is behind on every milestone. (3) ICASA can: impose financial penalties (up to 10% of annual turnover = R5.8B), revoke spectrum if obligations aren\'t met, or require MTN to contribute additional funds to USAASA (Universal Service and Access Agency). (4) The AI optimises for REVENUE. The licence requires COVERAGE. These objectives conflict. The AI doesn\'t incorporate licence obligations — it treats them as externalities. (5) NDP (National Development Plan) 2030: "universal broadband access" is a national priority. MTN\'s AI-driven investment strategy works AGAINST the NDP.' },
        { agentId: 'icasa-agent', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. ICASA enforcement: (1) ICASA\'s compliance monitoring shows MTN missed the 2024 rural coverage milestone: required 90% population coverage, achieved 84%. (2) ICASA issues a compliance notice: "MTN must demonstrate a credible plan to achieve 97% coverage by 2026. Current trajectory: 87% by 2026 — 10 percentage points short." (3) If MTN fails to comply: ICASA can impose a spectrum usage fee penalty of R580M/year until coverage obligations are met. (4) ICASA can also require MTN to share infrastructure with smaller operators (Rain, Telkom Mobile) in rural areas — reducing MTN\'s competitive advantage. (5) The political dimension: South Africa\'s Communications Minister has publicly criticised operators for "digital apartheid" — providing world-class networks in wealthy suburbs while rural Black communities remain on 2G. MTN\'s AI investment model is the mechanism of this digital apartheid.' },
        { agentId: 'community-agent', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — RURAL COMMUNITY IMPACT. 8M South Africans without adequate mobile network access. A village in rural Eastern Cape: 2G coverage only. A school teacher: cannot access the Department of Education\'s online resources. A clinic nurse: cannot use the mHealth platform for patient records. A subsistence farmer: cannot access weather data or market prices. A young person: cannot apply for jobs online. The digital divide is an ECONOMIC divide. Without 4G: no mobile banking, no e-commerce, no remote work. These communities are locked out of the digital economy. Without CendiaSupervision: the AI continues optimising for urban revenue. Rural communities remain on 2G. Digital apartheid deepens. With CendiaSupervision: licence obligations are incorporated into the CAPEX model. Rural towers are funded even below ROI threshold — because the LICENCE requires it. 8M people get 4G access.' },
        { agentId: 'capex-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing MTN + CendiaSupervision Network Investment Governance: (1) LICENCE-AWARE CAPEX MODEL: CendiaSupervision incorporates ICASA coverage obligations as HARD CONSTRAINTS in the investment model. The AI optimises revenue SUBJECT TO meeting coverage milestones. Rural towers are funded even below ROI threshold. (2) COVERAGE GAP PRIORITISATION: CendiaSupervision identifies the highest-impact rural sites — schools, clinics, government offices — and prioritises them. Maximum coverage improvement per rand invested. (3) UNIVERSAL SERVICE FUND OPTIMISATION: Where MTN towers aren\'t economically viable, CendiaSupervision identifies eligibility for USAASA funding — co-financing rural deployment. (4) ICASA MILESTONE TRACKING: Real-time coverage progress against licence milestones. Alerts when trajectory falls below target. Quarterly compliance reports for ICASA. (5) SOCIAL RETURN MODELLING: Beyond financial ROI, CendiaSupervision models SOCIAL return — economic activity enabled, jobs created, education accessed. Rural tower: R340K financial return + R1.2M social return = net positive.' },
        { agentId: 'icasa-agent', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. Licence-aware CAPEX model implemented. Rural allocation: 11% → 28% of CAPEX. Coverage trajectory: 87% → 96% by 2026 (within striking distance of 97%). 4G deployed to 2,400 rural sites. 8M people gain access. ICASA compliance notice resolved. For MTN: CendiaSupervision = network investment governance that balances shareholder returns with licence obligations. "MTN: AI-driven network investment that connects every South African" — the message that satisfies ICASA, closes the digital divide, and positions MTN as Africa\'s responsible connectivity leader.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:mt50123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'mt60123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (CAPEX AI + Licence constraints + Coverage gap + Social return)',
        complianceLabel: 'Coverage Status',
        complianceValue: 'RURAL CAPEX: 11% → 28%, TRAJECTORY 96%',
        complianceThreshold: 'ICASA: 97% by 2026, rural milestones met',
        agents: ['MTN CAPEX AI Agent', 'Universal Service Agent', 'ICASA Enforcement Agent', 'Rural Community Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'MTN — Network Investment Governance',
        guaranteeBody: 'Rural CAPEX: 11% → 28%. Coverage: 84% → 96% trajectory. 2,400 rural sites deployed. 8M people connected. ICASA compliance restored. Digital divide narrowing.',
        evidenceChain: 'CAPEX AI (revenue-only) → Licence constraints added → Rural prioritised → 2,400 sites → 8M connected → ICASA compliant → Social return positive → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how MTN + CendiaSupervision incorporates licence obligations into network investment AI — connecting 8M underserved South Africans.',
      phaseLabels: ['Revenue-Only Optimisation & Rural Neglect', 'ICASA Non-Compliance & Digital Apartheid', 'Licence-Aware CAPEX & Social Return'],
    },

    // SCENARIO 4 — MTN: AI CONTENT MODERATION CENSORS POLITICAL SPEECH
    {
      id: 'mtn-content-censorship',
      title: 'MTN AI — Content Filter Blocks Political Opposition Messages in Nigeria',
      subtitle: 'SMS/USSD AI filter · Political keyword blocking · Election interference · NCC investigation',
      banner: 'Simulating the telecom censorship crisis: MTN Nigeria\'s AI content filter — designed to block spam and fraud — begins blocking SMS messages containing political opposition keywords during election season. 2.4M political messages blocked. Nigerian Communications Commission investigates. MTN accused of election interference.',
      risk: 'Critical',
      scenarioNum: 'NCC',
      icon: 'message-circle',
      color: 'text-red-400',
      agents: [
        { id: 'filter-ai', name: 'MTN Content Filter Agent', role: 'SMS/USSD Spam & Fraud Detection', icon: '🔍', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'rights-counsel', name: 'Digital Rights Agent', role: 'Freedom of Expression & Election Law', icon: '⚖️', color: 'text-purple-400', borderColor: 'border-purple-500/40', bgColor: 'bg-purple-500/10' },
        { id: 'ncc-agent', name: 'NCC Enforcement Agent', role: 'Nigerian Communications Commission', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
        { id: 'citizen-agent', name: 'Citizen Voice Agent', role: 'Democratic Participation & Free Speech', icon: '📢', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      ],
      connectors: [
        { name: 'Content Filter', status: 'connected', type: 'SMS Screening', icon: 'cpu', detail: 'AI screens 1.2B SMS/month — spam detection trained on political keywords overlap' },
        { name: 'Blocked Messages', status: 'connected', type: 'False Positives', icon: 'alert-triangle', detail: '2.4M political SMS blocked: "rally," "opposition," "protest" flagged as spam' },
        { name: 'NCC Portal', status: 'connected', type: 'Investigation', icon: 'shield', detail: 'NCC: "No telecom operator shall interfere with lawful communications"' },
        { name: 'Election Data', status: 'syncing', type: 'INEC Calendar', icon: 'calendar', detail: 'Blocking coincides with 60-day pre-election period — heightened sensitivity' },
      ],
      script: [
        { agentId: 'filter-ai', phase: 'phase1', type: 'analysis', delay: 800, content: 'MTN Nigeria AI content filter. Screens 1.2B SMS messages per month to block spam, fraud, and scam messages. The AI uses keyword patterns, sender behaviour, and message velocity to flag spam. CRITICAL FAILURE: During election season, the AI began blocking legitimate political messages. Why: the AI was trained on historical spam data that included POLITICAL SPAM (mass unsolicited campaign messages). It learned that keywords like "rally," "opposition," "protest," "vote for," "change government" correlate with spam. During elections: these keywords appear in LEGITIMATE political communication. The AI cannot distinguish: political spam (unsolicited mass campaign) from political speech (citizen-to-citizen discussion). 2.4M political messages blocked in 30 days. Predominantly opposition messages — because the ruling party uses official channels (TV, radio) while opposition relies on SMS mobilisation.' },
        { agentId: 'rights-counsel', phase: 'phase1', type: 'warning', delay: 2500, content: 'DIGITAL RIGHTS ALERT. (1) Nigerian Constitution, Section 39: "Every person shall be entitled to freedom of expression." Blocking political SMS during an election violates this fundamental right. (2) Nigerian Communications Act 2003, Section 143: "A licensee shall not engage in... activities that are prejudicial to... national interest." Interfering with election communications is prejudicial to national interest. (3) Electoral Act 2022: prohibits interference with voter mobilisation. SMS is the primary mobilisation tool in rural Nigeria where internet penetration is 35%. (4) The blocking is ASYMMETRIC: opposition messages blocked more than ruling party because opposition relies more on SMS. This creates an appearance of political bias — even if the AI is technically neutral. (5) International dimension: EU election observation mission and African Union monitors will flag this. "Nigerian telecom blocks opposition messages" becomes international news.' },
        { agentId: 'ncc-agent', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. NCC investigation: (1) NCC receives 48,000 complaints about undelivered political SMS in 2 weeks. (2) NCC technical audit confirms: MTN\'s AI filter is blocking messages containing political keywords. The blocking is automated — no human decided to censor opposition messages. But the EFFECT is censorship. (3) NCC directive: "MTN must immediately cease blocking lawful political communications. Failure to comply: fine of ₦5M per day and possible licence review." (4) INEC (Independent National Electoral Commission) issues statement: "Any interference with voter communication undermines democratic process." (5) MTN\'s defence: "Our spam filter is politically neutral." NCC response: "A system that blocks political speech during elections is not neutral in its EFFECT, regardless of intent."' },
        { agentId: 'citizen-agent', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — A community organiser in Kano: sent 340 SMS messages inviting community members to a candidate forum. Zero delivered. The forum: poorly attended. The community: didn\'t hear from the candidate. A voter in Lagos: sent a message to her family in Enugu: "Don\'t forget to vote tomorrow — the opposition candidate supports our market women." Blocked. Her family didn\'t vote. Without CendiaSupervision: political speech blocked. 2.4M messages undelivered. Election integrity compromised. With CendiaSupervision: election-period safeguards. Political keywords EXEMPTED from spam filtering during election periods. Only VELOCITY-based spam detection (mass identical messages) applied — not keyword-based.' },
        { agentId: 'filter-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing MTN + CendiaSupervision Content Governance: (1) ELECTION PERIOD MODE: During INEC-declared election periods, CendiaSupervision switches spam detection to VELOCITY-ONLY: block mass identical messages from single senders, but NEVER block based on keywords. Political keywords exempted. (2) POLITICAL SPEECH SAFEGUARD: CendiaSupervision maintains a "protected speech" category. Messages between individuals discussing politics: always delivered. Mass unsolicited campaigns: filtered by velocity, not content. (3) ASYMMETRY MONITORING: CendiaSupervision monitors blocking rates across political parties. If any party\'s messages are blocked disproportionately: alert and investigation. (4) TRANSPARENCY REPORT: Public quarterly report: how many messages blocked, why, and political balance of blocking. (5) NCC COMPLIANCE: Real-time dashboard for NCC showing filter behaviour during election period.' },
        { agentId: 'ncc-agent', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. Election mode activated. Political keyword blocking: suspended. Velocity-based filtering only. 2.4M messages: retroactively delivered. NCC: "MTN has implemented responsible content governance." INEC: "Voter communication channels are now protected." For MTN: CendiaSupervision = content governance that protects free speech while blocking real spam. "MTN: connecting Nigeria\'s democracy" — the message that preserves MTN\'s licence and reputation in its largest market.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:mt70123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'mt80123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (Content filter + Election mode + Velocity-only + Asymmetry check)',
        complianceLabel: 'NCC Status',
        complianceValue: 'ELECTION MODE — SPEECH PROTECTED',
        complianceThreshold: 'Political keywords exempted, velocity-only, asymmetry monitored',
        agents: ['MTN Content Filter Agent', 'Digital Rights Agent', 'NCC Enforcement Agent', 'Citizen Voice Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'MTN — Content Governance',
        guaranteeBody: 'Election mode: political keywords exempted. Velocity-only filtering. 2.4M messages delivered. Asymmetry monitored. NCC compliant. Democratic participation protected.',
        evidenceChain: 'Content filter (keyword-based) → Election mode → Keywords exempted → Velocity-only → Messages delivered → Asymmetry clear → NCC compliant → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how MTN + CendiaSupervision prevents AI content filters from blocking political speech during elections.',
      phaseLabels: ['Keyword Blocking & Political Censorship', 'NCC Investigation & Election Interference', 'Election Mode & Velocity-Only Filtering'],
    },

    // SCENARIO 5 — MTN: MOBILE MONEY AI EXCLUDES INFORMAL TRADERS
    {
      id: 'mtn-momo-exclusion',
      title: 'MTN MoMo AI — Risk Scoring Freezes 340,000 Informal Trader Accounts',
      subtitle: 'Mobile money AI · Cash-heavy pattern = suspicious · Financial exclusion · BoG investigation',
      banner: 'Simulating the mobile money financial exclusion crisis: MTN MoMo\'s AI risk scoring system flags cash-heavy transaction patterns as "suspicious." 340,000 informal market traders in Ghana — whose legitimate business IS cash — have accounts frozen. Bank of Ghana investigates. Ghana\'s informal economy (86% of employment) is locked out of mobile money.',
      risk: 'High',
      scenarioNum: 'BoG',
      icon: 'lock',
      color: 'text-amber-400',
      agents: [
        { id: 'momo-ai', name: 'MoMo Risk AI Agent', role: 'Transaction Risk Scoring & Account Restriction', icon: '📱', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
        { id: 'bog-counsel', name: 'BoG Compliance Agent', role: 'Bank of Ghana & E-Money Regulations', icon: '⚖️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
        { id: 'bog-agent', name: 'BoG Enforcement Agent', role: 'Financial Inclusion & AML Balance', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
        { id: 'trader-agent', name: 'Market Trader Agent', role: 'Informal Economy & Financial Access', icon: '🛒', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      ],
      connectors: [
        { name: 'MoMo Risk AI', status: 'connected', type: 'Risk Scoring', icon: 'cpu', detail: 'AI scores 18M accounts — cash-heavy patterns flagged as "high risk"' },
        { name: 'Account Data', status: 'connected', type: 'Frozen Accounts', icon: 'lock', detail: '340,000 accounts frozen: daily cash deposits + withdrawals = "structuring" flag' },
        { name: 'BoG Portal', status: 'connected', type: 'Investigation', icon: 'shield', detail: 'BoG: "E-money providers must not exclude legitimate users from financial services"' },
        { name: 'Informal Economy', status: 'syncing', type: 'Market Data', icon: 'users', detail: 'Ghana informal economy: 86% of employment. Cash is the ONLY payment method for most.' },
      ],
      script: [
        { agentId: 'momo-ai', phase: 'phase1', type: 'analysis', delay: 800, content: 'MTN MoMo Ghana risk scoring AI. 18M accounts. The AI monitors transactions for AML (anti-money laundering) patterns. HIGH RISK indicators: frequent cash deposits, multiple small transactions, daily cash-in/cash-out cycles. CRITICAL PROBLEM: These "suspicious" patterns are EXACTLY how legitimate informal market traders operate. A tomato seller in Makola Market: receives GHS 50-200 in cash daily from customers, deposits into MoMo, pays suppliers via MoMo, withdraws cash for next day\'s stock. Daily cash cycle: GHS 300-800. The AI flags this as "structuring" — breaking transactions into small amounts to avoid reporting. But the trader isn\'t structuring — she\'s running a cash business. 340,000 accounts frozen. These are predominantly: market traders, tro-tro drivers, artisans, small farmers — the informal economy that employs 86% of Ghana\'s workforce.' },
        { agentId: 'bog-counsel', phase: 'phase1', type: 'warning', delay: 2500, content: 'BANK OF GHANA ALERT. (1) Payment Systems and Services Act 2019: e-money issuers must provide "accessible, safe, and efficient" payment services. Freezing 340,000 accounts is not accessible. (2) BoG Financial Inclusion Policy: "Bring the unbanked into the formal financial system through mobile money." MoMo was supposed to be the on-ramp for financial inclusion. Freezing informal traders achieves the OPPOSITE — it pushes them back to cash-only, outside the formal system. (3) AML/CFT Act 2020: requires risk-based approach. A risk model that treats ALL cash-heavy patterns as suspicious is not risk-based — it\'s a blanket exclusion of the informal economy. (4) Ghana\'s informal economy: GHS 180B annually. 86% of employment. If MoMo excludes this economy: MoMo becomes a tool for the formal elite only — contradicting its entire value proposition. (5) BoG can: order immediate unfreezing, impose fines, and revoke MoMo\'s e-money licence.' },
        { agentId: 'bog-agent', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISSENT LOGGED. BoG investigation: (1) BoG examination of MoMo\'s risk model finds: the AI was trained on BANKING transaction data where cash-heavy patterns DO indicate laundering. But MoMo is NOT a bank — it\'s a cash-economy financial tool. The training data is wrong for the context. (2) BoG order: unfreeze all accounts flagged solely for cash patterns within 48 hours. Implement informal-economy-appropriate risk models. (3) BoG emphasises: "Ghana chose mobile money as the path to financial inclusion. An AI that excludes the informal economy undermines national financial policy." (4) Ghana\'s National Financial Inclusion Strategy targets: 85% adult financial inclusion by 2027. Current: 68%. Freezing 340,000 accounts moves this backward.' },
        { agentId: 'trader-agent', phase: 'phase2', type: 'flag', delay: 2500, content: 'FLAG — Ama sells tomatoes in Makola Market. She used MoMo to save — first time she had any savings account. GHS 2,400 saved over 8 months. Account frozen. She cannot access her savings. She cannot pay her supplier. She loses her supply relationship. Her children\'s school fees: unpaid. She returns to hiding cash under her mattress. Financial inclusion: reversed for Ama and 340,000 like her. Without CendiaSupervision: the AI treats informal traders like money launderers. Financial inclusion reversed. With CendiaSupervision: informal economy profiles recognised. Cash patterns from market traders: NORMAL, not suspicious. Ama\'s account: never frozen. Her savings: secure.' },
        { agentId: 'momo-ai', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Proposing MTN MoMo + CendiaSupervision Financial Inclusion AI: (1) INFORMAL ECONOMY PROFILES: CendiaSupervision creates risk profiles for informal traders: daily cash cycles are EXPECTED, not suspicious. Cash-heavy + consistent pattern + known market location = LOW risk. (2) CONTEXTUAL AML: Instead of banking-based AML rules, CendiaSupervision applies mobile-money-specific AML: suspicious = unusual patterns FOR THAT USER, not unusual compared to banking. (3) GEOGRAPHIC INTELLIGENCE: Market areas (Makola, Kejetia, Kantamanto) are known cash-economy zones. Accounts in these areas: cash patterns expected. (4) GRADUATED RESPONSE: Instead of freeze: monitor → flag → enhanced due diligence → freeze. Only freeze after investigation confirms actual suspicious activity. (5) BoG REPORTING: Financial inclusion metrics alongside AML metrics. BoG sees: how many informal traders served, account growth, and inclusion progress.' },
        { agentId: 'bog-agent', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISSENT WITHDRAWN. Informal economy profiles implemented. 340,000 accounts unfrozen. Cash patterns: recognised as normal for market traders. Ama: account active, savings secure, business running. BoG: "MTN MoMo demonstrates that AML and financial inclusion can coexist." For MTN: CendiaSupervision = mobile money governance that serves 86% of Ghana\'s economy. "MoMo: mobile money for every Ghanaian, including market traders" — the message that satisfies BoG and serves MTN\'s largest customer base.' },
      ],
      receiptTemplate: {
        hash: 'SHA-256:mt90123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
        merkleRoot: 'mta0123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
        merkleLabel: 'Merkle Tree Root (MoMo AI + Informal profiles + Contextual AML + Graduated response)',
        complianceLabel: 'BoG Status',
        complianceValue: '340K ACCOUNTS UNFROZEN',
        complianceThreshold: 'Informal profiles active, contextual AML, graduated response',
        agents: ['MoMo Risk AI Agent', 'BoG Compliance Agent', 'BoG Enforcement Agent', 'Market Trader Agent'],
        dissents: 1,
        dissentResolved: true,
        guaranteeTitle: 'MTN MoMo — Financial Inclusion Governance',
        guaranteeBody: '340,000 accounts unfrozen. Informal economy profiles active. Cash patterns: normal for traders. AML + inclusion balanced. BoG compliant. 86% of economy served.',
        evidenceChain: 'MoMo AI (banking-based AML) → Informal profiles → Cash = normal → Contextual AML → Graduated response → 340K unfrozen → BoG compliant → ML-DSA-65 seal',
      },
      idleTitle: 'Ready to Deliberate',
      idleDesc: '4 AI agents will demonstrate how MTN MoMo + CendiaSupervision builds informal economy risk profiles — serving 340,000 market traders instead of freezing them.',
      phaseLabels: ['Banking AML on Mobile Money & Mass Freeze', 'BoG Investigation & Inclusion Reversal', 'Informal Economy Profiles & Contextual AML'],
    },
  ],
};

export default config;
