/**
 * Club Sporting Cristal — Spanish Scenarios
 * @module pages/sandbox/configs/sporting-cristal-es
 */

// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.

import type { TemplateScenario } from '../SandboxTemplate';

export const ES_SCENARIOS: TemplateScenario[] = [
  // ESCENARIO 1 — GOBERNANZA CORPORATIVA GRUPO ROMERO
  {
    id: 'grupo-romero-governance',
    title: 'Gobernanza Corporativa Grupo Romero — Obligaciones Equivalentes a SOX',
    subtitle: 'BCP · Alicorp · Ransa · Informes SMV · Umbrales de materialidad · Partes relacionadas',
    banner: 'Simulando la gobernanza corporativa del club de fútbol más corporativo del Perú. El Grupo Romero requiere estándares de gobernanza equivalentes a SOX para las decisiones materiales asistidas por IA de Sporting Cristal.',
    risk: 'Alto',
    scenarioNum: 'Corporativo',
    icon: 'building',
    color: 'text-sky-400',
    agents: [
      { id: 'corporate-gov', name: 'Agente de Gobernanza Corporativa', role: 'Estándares Grupo Romero y SMV', icon: '🏢', color: 'text-sky-400', borderColor: 'border-sky-500/40', bgColor: 'bg-sky-500/10' },
      { id: 'financial-cristal', name: 'Agente Financiero', role: 'Materialidad y Monitoreo de Umbrales', icon: '💰', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'related-party', name: 'Agente de Partes Relacionadas', role: 'Gobernanza de Transacciones BCP/Alicorp', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'audit-cristal', name: 'Agente de Auditoría', role: 'Responsabilidad de Anulación y Rastro', icon: '📊', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
    ],
    connectors: [
      { name: 'Cumplimiento Grupo Romero', status: 'connected', type: 'Corporativo', icon: 'building', detail: 'Estándares de gobernanza interna — umbral de materialidad PEN 2M' },
      { name: 'Portal SMV', status: 'connected', type: 'Regulador', icon: 'landmark', detail: 'Superintendencia del Mercado de Valores — requisitos de entidad cotizada' },
      { name: 'SUNAT', status: 'connected', type: 'Tributario', icon: 'database', detail: 'Consolidación tributaria del grupo corporativo activa' },
      { name: 'Licencia CONMEBOL', status: 'syncing', type: 'Fútbol', icon: 'check-circle', detail: 'Licencia de club — todos los indicadores financieros VERDE' },
    ],
    script: [
      { agentId: 'corporate-gov', phase: 'phase1', type: 'warning', delay: 800, content: 'GOBERNANZA CORPORATIVA — ESTÁNDARES GRUPO ROMERO. Cristal opera bajo gobernanza dual: (1) Regulaciones del fútbol (FPF, CONMEBOL, FIFA) y (2) Estándares corporativos del Grupo Romero equivalentes a SOX. Cada decisión asistida por IA por encima del umbral de materialidad PEN 2M requiere: documentación a nivel de directorio, responsabilidad de anulación y rastro de auditoría accesible para cumplimiento del Grupo Romero. Decisiones pendientes: (a) Fichaje €1.2M. (b) Renovación Gallardo Fase 2 — PEN 8M. (c) Renovación patrocinio Alicorp — transacción con parte relacionada.' },
      { agentId: 'financial-cristal', phase: 'phase1', type: 'analysis', delay: 2500, content: 'ANÁLISIS DE MATERIALIDAD. (1) Fichaje (€1.2M / ~PEN 5.4M): Sobre umbral PEN 2M. Grupo Romero requiere: valoración independiente, acta de aprobación del directorio, registro de responsabilidad de anulación. (2) Gallardo Fase 2 (PEN 8M): Requiere aprobación del comité de inversiones. Caso de negocio con proyección ROI a 5 años. (3) Patrocinio Alicorp (PEN 4.5M/año): Transacción con parte relacionada — SUNAT y SMV requieren evidencia de precios de mercado.' },
      { agentId: 'related-party', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISIDENCIA — CONCENTRACIÓN DE PARTES RELACIONADAS. (1) Patrocinio Alicorp PEN 4.5M — 35% de ingresos comerciales totales. (2) Servicios bancarios BCP — banco principal de Cristal (Grupo Romero). (3) Logística Ransa — contrato de viaje del equipo. (4) Exposición combinada: ~55% de ingresos comerciales de entidades Grupo Romero. Excede guías SMV (máximo recomendado 40%). Mi disidencia: revisión INDEPENDIENTE de todas las relaciones comerciales del Grupo Romero para demostrar precios de mercado.' },
      { agentId: 'audit-cristal', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — BRECHA DE RESPONSABILIDAD DE ANULACIÓN. 3 decisiones asistidas por IA en el último trimestre excedieron el umbral de materialidad pero NO se documentaron con responsabilidad de anulación. La auditoría del Grupo Romero encontró estas brechas — puntaje de cumplimiento bajó de 94% a 87%. Si baja de 85%, se activa supervisión mejorada — revisiones mensuales en vez de trimestrales.' },
      { agentId: 'corporate-gov', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Grupo Romero: (1) AUTOMATIZACIÓN DE UMBRAL: Todas las decisiones de IA señaladas automáticamente al acercarse a PEN 2M. (2) PARTES RELACIONADAS (aceptando disidencia): Revisión independiente de todas las relaciones comerciales. Evidencia de precios de mercado para Alicorp, BCP y Ransa. (3) RETROACTIVO: 3 decisiones no documentadas reciben documentación retroactiva con ratificación del directorio. (4) Todo sellado con ML-DSA-65 — accesible para Grupo Romero, SMV, SUNAT y CONMEBOL.' },
      { agentId: 'related-party', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISIDENCIA RETIRADA. La revisión independiente aborda el riesgo de concentración. Cristal es único en el fútbol peruano — el único club con obligaciones de gobernanza corporativa de esta sofisticación. Este protocolo hace de la gobernanza de Cristal el referente para clubes de fútbol de propiedad corporativa en Sudamérica.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:sc10123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'sc20123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (Gobernanza corporativa + Materialidad + Partes relacionadas + Anulación + SMV)',
      complianceLabel: 'Gobernanza Corporativa',
      complianceValue: 'CUMPLIMIENTO GRUPO ROMERO 87%',
      complianceThreshold: 'Materialidad PEN 2M · SMV 40% partes relacionadas',
      agents: ['Agente de Gobernanza Corporativa', 'Agente Financiero', 'Agente de Partes Relacionadas', 'Agente de Auditoría'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Sporting Cristal — Gobernanza Corporativa Grupo Romero',
      guaranteeBody: 'Sella: responsabilidad de anulación equivalente a SOX, revisión independiente de partes relacionadas, automatización de umbrales, divulgación SMV, defensa precios SUNAT.',
      evidenceChain: 'Señalización materialidad → Responsabilidad de anulación → Revisión partes relacionadas → Evidencia precios → Aprobación directorio → Divulgación SMV → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobiernan Sporting Cristal bajo estándares corporativos Grupo Romero — cumplimiento equivalente a SOX, gobernanza de partes relacionadas y obligaciones regulatorias duales.',
    phaseLabels: ['Estándares Corporativos y Materialidad', 'Partes Relacionadas y Anulación', 'Protocolo de Gobernanza'],
  },

  // ESCENARIO 2 — ACADEMIA JUVENIL
  {
    id: 'youth-academy-pipeline',
    title: 'Academia Juvenil — Gobernanza de Desarrollo con Estándares Corporativos',
    subtitle: 'Mayor pipeline del Perú · Estándares Grupo Romero · Cumplimiento CNA · Fichajes europeos',
    banner: 'Simulando la gobernanza juvenil de la academia del Cristal — una de las más productivas del Perú. Los estándares corporativos del Grupo Romero requieren documentación sistemática de salvaguarda, educación, identificación de talentos y gobernanza del pipeline de fichajes.',
    risk: 'Alto',
    scenarioNum: 'Juvenil',
    icon: 'users',
    color: 'text-emerald-400',
    agents: [
      { id: 'youth-cristal', name: 'Agente de Desarrollo Juvenil', role: 'Pipeline de Academia y FIFA Art. 19', icon: '👦', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'corporate-youth', name: 'Agente de Estándares Corporativos', role: 'Gobernanza Juvenil Grupo Romero', icon: '🏢', color: 'text-sky-400', borderColor: 'border-sky-500/40', bgColor: 'bg-sky-500/10' },
      { id: 'safeguarding-cristal', name: 'Agente de Salvaguarda', role: 'CNA y Protección Infantil', icon: '🛡️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'education-cristal', name: 'Agente de Educación', role: 'Coordinación Escolar y MINEDU', icon: '📚', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
    ],
    connectors: [
      { name: 'Registro Juvenil FPF', status: 'connected', type: 'Registro', icon: 'database', detail: '52 jugadores de academia de 12-18 años — top 3 del Perú' },
      { name: 'FIFA TMS', status: 'connected', type: 'Internacional', icon: 'globe', detail: 'Cumplimiento Art. 19 — 4 fichajes juveniles internacionales pendientes' },
      { name: 'RRHH Grupo Romero', status: 'connected', type: 'Corporativo', icon: 'building', detail: 'Estándares corporativos de empleo juvenil aplican a la academia' },
      { name: 'Portal MINEDU', status: 'syncing', type: 'Educación', icon: 'book-open', detail: 'Alianza escolar — 3 MOUs formales activos' },
    ],
    script: [
      { agentId: 'youth-cristal', phase: 'phase1', type: 'warning', delay: 800, content: 'PIPELINE JUVENIL — ESTÁNDARES CORPORATIVOS. 52 menores (12-18): (1) 4 jugadores de 16-17 con interés de clubes europeos — sujetos a FIFA Art. 19. (2) 8 graduados de academia en primer equipo (más alto de Liga 1). Ingresos por ventas: $4.2M en 3 años. (3) Estándar Grupo Romero: desarrollo juvenil debe seguir marcos corporativos de RRHH. (4) FIFA Art. 19: 3 de 4 fichajes con documentación completa. 1 (jugador de 16, argentino) requiere verificación adicional de empleo de padres en Perú.' },
      { agentId: 'corporate-youth', phase: 'phase1', type: 'analysis', delay: 2500, content: 'GOBERNANZA JUVENIL GRUPO ROMERO. (1) Plan de desarrollo documentado: 48/52 completos. 4 faltan (ingresos recientes). (2) Informes trimestrales de bienestar a RRHH Grupo Romero: cumple. (3) Auditoría anual de salvaguarda por evaluador independiente: en 6 semanas. (4) Presupuesto academia PEN 3.2M/año. (5) Reporte ESG corporativo: la academia se presenta como impacto social — documentación adicional requerida para auditoría ESG.' },
      { agentId: 'safeguarding-cristal', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISIDENCIA — INDEPENDENCIA DE SALVAGUARDA. (1) Marcos corporativos de RRHH diseñados para adultos, no niños. No pueden reemplazar salvaguarda específica infantil. (2) Auditoría anual insuficiente — CNA y mejores prácticas recomiendan monitoreo continuo. (3) 4 jugadores con interés europeo enfrentan vulnerabilidad única — agentes y familias pueden presionarlos. Mi disidencia: nombrar oficial de salvaguarda INDEPENDIENTE (no empleado de RRHH Grupo Romero) con mandato exclusivo de bienestar infantil, reportando al comité del directorio.' },
      { agentId: 'education-cristal', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — MÉTRICAS EDUCATIVAS. (1) 7 de 52 jugadores bajo 70% de asistencia. (2) 2 jugadores de 16 consideran abandono escolar — CNA requiere educación hasta los 16, Grupo Romero hasta los 18. (3) Reporte ESG afirma "100% cumplimiento educativo" — dato real: 87%. Riesgo para reporte ESG. (4) Fichaje FIFA Art. 19 del jugador argentino de 16 requiere documentación de matrícula escolar en Perú.' },
      { agentId: 'youth-cristal', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo de Academia: (1) FIFA ART. 19: Verificación independiente de empleo de padres del jugador argentino. Matrícula escolar confirmada. (2) SALVAGUARDA (aceptando disidencia): Oficial de salvaguarda independiente. Monitoreo continuo. (3) PLANES: 4 planes faltantes completados en 2 semanas. (4) EDUCACIÓN: 7 jugadores de baja asistencia con planes de intervención. ESG corregido a 87%. (5) PIPELINE: Apoyo de bienestar independiente para 4 jugadores con interés europeo. Todo sellado para FIFA, FPF, Grupo Romero, MINEDU y auditoría ESG.' },
      { agentId: 'safeguarding-cristal', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISIDENCIA RETIRADA. Oficial de salvaguarda independiente con reporte al directorio aborda la brecha estructural. Monitoreo continuo es el estándar correcto para 52 niños. La academia del Cristal es la mejor del Perú — la gobernanza debe estar a la altura. Los recursos corporativos del Grupo Romero lo hacen posible.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:sc30123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'sc40123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (FIFA Art. 19 + Salvaguarda + RRHH Corporativo + Educación + ESG)',
      complianceLabel: 'Desarrollo Juvenil',
      complianceValue: '4 FICHAJES INTERNACIONALES PENDIENTES',
      complianceThreshold: 'FIFA Art. 19 · CNA Ley 27337 · ESG Grupo Romero',
      agents: ['Agente de Desarrollo Juvenil', 'Agente de Estándares Corporativos', 'Agente de Salvaguarda', 'Agente de Educación'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Sporting Cristal — Gobernanza de Academia Juvenil',
      guaranteeBody: 'Sella: fichajes FIFA Art. 19, oficial de salvaguarda independiente, cumplimiento RRHH Grupo Romero, MOUs educativos, precisión de reporte ESG.',
      evidenceChain: 'Auditoría academia → FIFA Art. 19 → Oficial salvaguarda → Planes desarrollo → Intervención educativa → Corrección ESG → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobiernan la academia del Cristal — el mayor pipeline del Perú — bajo estándares duales FIFA y corporativos Grupo Romero.',
    phaseLabels: ['Pipeline y Estándares Corporativos', 'Salvaguarda y Educación', 'Protocolo de Academia'],
  },

  // ESCENARIO 3 — PARTES RELACIONADAS BCP/ALICORP
  {
    id: 'related-party-transactions',
    title: 'BCP y Alicorp — Gobernanza de Transacciones con Partes Relacionadas',
    subtitle: 'Entidades Grupo Romero · Precios de transferencia SUNAT · Divulgación SMV · Precios de mercado',
    banner: 'Simulando la gobernanza de partes relacionadas única de Sporting Cristal — el único club de Liga 1 donde las filiales del propietario son también socios comerciales. Cada transacción requiere evidencia documentada de precios de mercado.',
    risk: 'Alto',
    scenarioNum: 'Partes Relacionadas',
    icon: 'landmark',
    color: 'text-amber-400',
    agents: [
      { id: 'sunat-cristal', name: 'Agente SUNAT', role: 'Precios de Transferencia e Impuestos', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'smv-agent', name: 'Agente SMV', role: 'Divulgación del Mercado de Valores', icon: '📊', color: 'text-sky-400', borderColor: 'border-sky-500/40', bgColor: 'bg-sky-500/10' },
      { id: 'commercial-cristal', name: 'Agente Comercial', role: 'Gobernanza de Patrocinios y Banca', icon: '💼', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'conmebol-cristal', name: 'Agente CONMEBOL', role: 'Partes Relacionadas en Licencia de Club', icon: '🏆', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Precios Transferencia SUNAT', status: 'connected', type: 'Tributario', icon: 'landmark', detail: 'Art. 32-A — todas las transacciones Grupo Romero auditables' },
      { name: 'Divulgación SMV', status: 'connected', type: 'Valores', icon: 'bar-chart', detail: 'Informes de partes relacionadas de entidad cotizada activos' },
      { name: 'Contrato Alicorp', status: 'connected', type: 'Patrocinio', icon: 'building', detail: 'PEN 4.5M/año — valoración independiente requerida' },
      { name: 'Servicios BCP', status: 'syncing', type: 'Banca', icon: 'database', detail: 'Banca principal — comisiones y facilidades de crédito bajo revisión' },
    ],
    script: [
      { agentId: 'sunat-cristal', phase: 'phase1', type: 'warning', delay: 800, content: 'REVISIÓN DE PRECIOS DE TRANSFERENCIA. Transacciones con partes relacionadas Grupo Romero: (1) Patrocinio Alicorp: PEN 4.5M/año. Referencia de la industria: PEN 3.0-4.0M. En el extremo ALTO — defendible pero requiere estudio independiente. (2) Banca BCP: tasa de crédito por debajo del mercado. Beneficio para Cristal: ~PEN 280K/año. SUNAT puede considerar beneficio indirecto. (3) Logística Ransa: PEN 1.2M/año. (4) Total: PEN 5.98M anuales en partes relacionadas. SUNAT requiere evidencia de precios de mercado para CADA transacción.' },
      { agentId: 'smv-agent', phase: 'phase1', type: 'analysis', delay: 2500, content: 'DIVULGACIÓN SMV. Entidades cotizadas del Grupo Romero deben divulgar transacciones con partes relacionadas. (1) Patrocinio Alicorp: divulgado en estados de Alicorp. Pero el tratamiento de Cristal no ha sido verificado para consistencia. (2) Crédito BCP: NO divulgado separadamente — clasificado como inmaterial. Pero el agregado de transacciones cruzadas puede ser material. (3) CONMEBOL usa umbrales de materialidad diferentes a SMV. Cristal debe mantener documentación de doble cumplimiento.' },
      { agentId: 'commercial-cristal', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISIDENCIA — INDEPENDENCIA COMERCIAL. (1) Alicorp a PEN 4.5M está sobre el rango superior del mercado. Si SUNAT cuestiona, Cristal necesita demostrar que la PRIMA está justificada por entregables específicos. El acuerdo actual tiene cláusulas genéricas — insuficiente para defensa SUNAT. (2) El crédito BCP bajo mercado puede ser el mayor riesgo tributario. Mi disidencia: Cristal debe renegociar TODOS los contratos Grupo Romero con entregables específicos DOCUMENTADOS que justifiquen cada precio.' },
      { agentId: 'conmebol-cristal', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — PARTES RELACIONADAS CONMEBOL. La presentación actual de Cristal lista solo Alicorp. BCP y Ransa NO figuran. Brecha de divulgación. Revisión financiera CONMEBOL en 8 semanas. Divulgación voluntaria antes de la revisión previene sanción y demuestra madurez de gobernanza.' },
      { agentId: 'sunat-cristal', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo de Partes Relacionadas: (1) ESTUDIO INDEPENDIENTE: Big 4 para todas las transacciones — Alicorp, BCP, Ransa. Precios de mercado documentados. (2) ALICORP (aceptando disidencia): Renegociar con entregables de activación específicos. (3) BCP: Crédito bajo mercado documentado como beneficio de parte relacionada. (4) CONMEBOL: Divulgación voluntaria de BCP y Ransa antes de revisión Copa Libertadores. (5) SMV: Nota actualizada para próximo informe trimestral. (6) Todo sellado para SUNAT, SMV, CONMEBOL simultáneamente.' },
      { agentId: 'commercial-cristal', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISIDENCIA RETIRADA. Estudio independiente de precios y renegociación de entregables abordan el riesgo SUNAT. La propiedad corporativa de Cristal es una FORTALEZA — trae recursos y capacidad que ningún otro club de Liga 1 tiene. Pero la propiedad corporativa también crea obligaciones regulatorias únicas. Este protocolo asegura transparencia y cumplimiento.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:sc50123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'sc60123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (Precios SUNAT + Divulgación SMV + Partes CONMEBOL + Precios mercado)',
      complianceLabel: 'Gobernanza Partes Relacionadas',
      complianceValue: 'PEN 5.98M ANUAL — 3 ENTIDADES',
      complianceThreshold: 'SUNAT Art. 32-A · Materialidad SMV · CONMEBOL',
      agents: ['Agente SUNAT', 'Agente SMV', 'Agente Comercial', 'Agente CONMEBOL'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Sporting Cristal — Gobernanza de Partes Relacionadas',
      guaranteeBody: 'Sella: evidencia precios Alicorp/BCP/Ransa, estudio de precios de transferencia, divulgación trimestral SMV, divulgación voluntaria CONMEBOL, renegociación de contratos.',
      evidenceChain: 'Auditoría transacciones → Estudio precios → Evidencia mercado → Renegociación → Divulgación CONMEBOL → Informe SMV → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobiernan las transacciones con partes relacionadas entre Sporting Cristal y entidades del Grupo Romero — cumplimiento SUNAT, SMV y CONMEBOL simultáneo.',
    phaseLabels: ['Precios de Transferencia y Divulgación', 'Independencia Comercial', 'Protocolo de Partes Relacionadas'],
  },

  // ESCENARIO 4 — RENOVACIÓN ESTADIO GALLARDO
  {
    id: 'gallardo-renovation',
    title: 'Estadio Gallardo — Certificación de Recinto Copa Libertadores',
    subtitle: '18.076 capacidad · Brechas CONMEBOL · Aprobación de capital corporativo · Distrito Rímac',
    banner: 'Simulando la gobernanza de recintos para el Estadio Alberto Gallardo — el hogar compacto de Cristal en el Rímac que requiere mejoras de certificación Copa Libertadores CONMEBOL bajo la gobernanza de gastos de capital del Grupo Romero.',
    risk: 'Medio',
    scenarioNum: 'Estadio',
    icon: 'building',
    color: 'text-blue-400',
    agents: [
      { id: 'venue-gallardo', name: 'Agente de Recinto', role: 'Estándares CONMEBOL y Certificación', icon: '🏟️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'capex-agent', name: 'Agente de Gasto de Capital', role: 'Comité de Inversiones Grupo Romero', icon: '💰', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'safety-gallardo', name: 'Agente de Seguridad', role: 'INDECI y Municipalidad del Rímac', icon: '🛡️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'planning-gallardo', name: 'Agente de Planificación', role: 'Distrito del Rímac y Permisos', icon: '📋', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
    ],
    connectors: [
      { name: 'Recinto CONMEBOL', status: 'connected', type: 'Certificación', icon: 'check-circle', detail: '6 ítems bajo estándar Copa Libertadores' },
      { name: 'CapEx Grupo Romero', status: 'connected', type: 'Inversión', icon: 'building', detail: 'Comité de inversiones — propuesta de renovación PEN 12M' },
      { name: 'INDECI', status: 'connected', type: 'Seguridad', icon: 'shield', detail: '18.076 capacidad — plan de evacuación bajo revisión' },
      { name: 'Municipalidad Rímac', status: 'syncing', type: 'Planificación', icon: 'landmark', detail: 'Permisos de planificación distrital — restricciones de zonificación' },
    ],
    script: [
      { agentId: 'venue-gallardo', phase: 'phase1', type: 'warning', delay: 800, content: 'ANÁLISIS DE BRECHAS GALLARDO. 6 incumplimientos Copa Libertadores: (1) Iluminación: 1.100 vs 1.400 lux requeridos. (2) Prensa: 80 vs 200 posiciones. (3) Hospitalidad bajo mínimo CONMEBOL. (4) Clima sala VAR insuficiente. (5) Zona mixta insuficiente. (6) Discapacidad: 30 vs 75 sillas de ruedas. Espacio reducido (18.076) limita opciones de expansión. Costo estimado: PEN 12M.' },
      { agentId: 'capex-agent', phase: 'phase1', type: 'analysis', delay: 2500, content: 'GOBERNANZA DE CAPEX GRUPO ROMERO. PEN 12M requiere aprobación del comité de inversiones: (1) Caso de negocio con proyección ROI. (2) Alternativa: alquilar Estadio Nacional para partidos de Copa (~PEN 500K por partido). (3) Análisis VPN: al 12% de descuento y horizonte de 10 años, Gallardo es VPN positivo solo si Cristal clasifica 6+ veces en 10 años. Tasa histórica: 70%. (4) Comité en 4 semanas. Documentación en 2.' },
      { agentId: 'safety-gallardo', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISIDENCIA — SEGURIDAD ANTES QUE COMERCIAL. (1) Ubicación en el Rímac limita evacuación — calles estrechas, barrio residencial denso. INDECI señaló "capacidad de salida limitada" en 2 inspecciones. (2) Aumentar hospitalidad sin mejorar salidas EMPEORA la evacuación. (3) Discapacidad 30 vs 75 no es solo CONMEBOL — es incumplimiento de CONADIS Ley 29973. Violación legal actual. Mi disidencia: priorizar seguridad (evacuación, discapacidad) ANTES de mejoras comerciales.' },
      { agentId: 'planning-gallardo', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — PLANIFICACIÓN RÍMAC. (1) Gallardo en zona residencial densa — la construcción impacta a vecinos. Evaluación de impacto, mitigación de ruido y plan de tráfico requeridos. (2) Expansión de hospitalidad puede activar revisión de zonificación comercial. (3) Aprobación de planificación: típicamente 3-4 meses. (4) Vecinos del Rímac han protestado antes por estacionamiento y ruido del día de partido. La renovación ofrece oportunidad de documentar participación comunitaria.' },
      { agentId: 'venue-gallardo', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo Gallardo: (1) SEGURIDAD PRIMERO (aceptando disidencia): Fase 1 (PEN 5M) — mejoras de evacuación, discapacidad (30→75), resolución INDECI. Fase 2 (PEN 7M) — iluminación, VAR, prensa, hospitalidad. (2) CAPEX: Caso de negocio con fases de seguridad primero. Alquiler Nacional como interino. (3) PLANIFICACIÓN: Compromiso temprano con Municipalidad Rímac. (4) Todo sellado para Grupo Romero, CONMEBOL, INDECI, CONADIS y Rímac.' },
      { agentId: 'safety-gallardo', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISIDENCIA RETIRADA. Las fases de seguridad primero aseguran que evacuación y discapacidad se resuelvan antes de mejoras comerciales. Cumplimiento CONADIS es legalmente requerido. Gallardo es una joya compacta — la renovación lo convierte en el mejor recinto de Copa de pequeña capacidad de Sudamérica.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:sc70123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'sc80123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (Brechas CONMEBOL + Aprobación CapEx + INDECI + CONADIS + Planificación Rímac)',
      complianceLabel: 'Certificación de Recinto',
      complianceValue: 'PEN 12M EN 2 FASES — SEGURIDAD PRIMERO',
      complianceThreshold: 'Recinto CONMEBOL · CONADIS Ley 29973 · INDECI',
      agents: ['Agente de Recinto', 'Agente de Gasto de Capital', 'Agente de Seguridad', 'Agente de Planificación'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Sporting Cristal — Renovación Gallardo',
      guaranteeBody: 'Sella: análisis 6 brechas CONMEBOL, caso de negocio CapEx Grupo Romero, fases seguridad primero, cumplimiento CONADIS, consulta comunitaria Rímac.',
      evidenceChain: 'Brechas CONMEBOL → Análisis VPN → Fases seguridad → Comité inversiones → Planificación Rímac → Comunidad → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobiernan la renovación de Gallardo — certificación CONMEBOL bajo gobernanza de inversiones Grupo Romero con enfoque de seguridad primero.',
    phaseLabels: ['Brechas CONMEBOL y CapEx', 'Seguridad y Planificación', 'Protocolo de Renovación por Fases'],
  },

  // ESCENARIO 5 — REPORTE ESG
  {
    id: 'esg-reporting',
    title: 'ESG Grupo Romero — Reporte de Impacto Social del Club de Fútbol',
    subtitle: 'ESG Corporativo · Métricas de academia · RSC comunitaria · Cumplimiento ambiental',
    banner: 'Simulando la gobernanza de reporte ESG única de Cristal — el único club de Liga 1 cuyo impacto social debe documentarse para las divulgaciones ESG de un grupo corporativo cotizado. Resultados de academia, programas comunitarios y cumplimiento ambiental requieren evidencia verificada.',
    risk: 'Medio',
    scenarioNum: 'ESG',
    icon: 'bar-chart',
    color: 'text-emerald-400',
    agents: [
      { id: 'esg-agent', name: 'Agente de Reporte ESG', role: 'Sostenibilidad Grupo Romero', icon: '🌱', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'social-impact', name: 'Agente de Impacto Social', role: 'Comunidad y Métricas de Academia', icon: '👥', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'environmental', name: 'Agente Ambiental', role: 'Estadio y Cumplimiento Operacional', icon: '🌍', color: 'text-sky-400', borderColor: 'border-sky-500/40', bgColor: 'bg-sky-500/10' },
      { id: 'verification', name: 'Agente de Verificación', role: 'Precisión de Datos y Auditoría', icon: '✅', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
    ],
    connectors: [
      { name: 'ESG Grupo Romero', status: 'connected', type: 'Corporativo', icon: 'building', detail: 'Informe anual de sostenibilidad — sección Cristal en 8 semanas' },
      { name: 'Métricas Academia', status: 'connected', type: 'Social', icon: 'users', detail: '52 jóvenes, 8 graduados, seguimiento educativo' },
      { name: 'Programas Comunitarios', status: 'connected', type: 'Impacto', icon: 'globe', detail: '4 programas RSC — 12.000 beneficiarios declarados' },
      { name: 'Datos Ambientales', status: 'syncing', type: 'Ambiente', icon: 'check-circle', detail: 'Gallardo energía, agua, residuos — recolección activa' },
    ],
    script: [
      { agentId: 'esg-agent', phase: 'phase1', type: 'warning', delay: 800, content: 'REPORTE ESG — PLAZO GRUPO ROMERO. Informe anual de sostenibilidad en 8 semanas. Sección Cristal: (1) SOCIAL: Academia (52 jugadores, resultados educativos, salvaguarda). RSC (4 programas, 12.000 beneficiarios). Empleo (120 personal, diversidad). (2) AMBIENTAL: Consumo energético Gallardo, agua, residuos. Impacto ambiental de día de partido. (3) GOBERNANZA: Composición directorio, anticorrupción, conducta ética. (4) Este año Grupo Romero adoptó Estándares GRI — requiere métricas verificables, no narrativas.' },
      { agentId: 'social-impact', phase: 'phase1', type: 'analysis', delay: 2500, content: 'VERIFICACIÓN DE MÉTRICAS SOCIALES. (1) Academia: "52 jóvenes en desarrollo" — verificado. "8 graduados en primer equipo" — verificado. "100% cumplimiento educativo" — INCORRECTO (real: 87%). (2) RSC: "12.000 beneficiarios" — metodología poco clara. Documentados: 7.200. Los 5.000 de día de partido son estimación. (3) Diversidad: 22% personal femenino vs 30% objetivo Grupo Romero. (4) Bajo estándares GRI, las afirmaciones no verificadas deben excluirse o etiquetarse como estimaciones.' },
      { agentId: 'environmental', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISIDENCIA — BRECHAS DE DATOS AMBIENTALES. (1) Energía Gallardo: medidores inteligentes de solo 6 meses — GRI requiere 12 meses. (2) Agua: sin sub-medición separada riego de cancha vs edificio. (3) Residuos: datos de solo 4 partidos. (4) Huella de carbono: viajes del equipo nunca calculados. Copa Libertadores genera emisiones significativas. Mi disidencia: declarar "año base — recolección de datos en progreso" en vez de publicar cifras imprecisas.' },
      { agentId: 'verification', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — RIESGO DE AUDITORÍA. El reporte ESG del Grupo Romero tiene aseguramiento limitado por auditor externo. Si las métricas de Cristal no son verificables, refleja mal en todo el reporte. La afirmación de 12.000 beneficiarios y 100% cumplimiento educativo son los ítems de mayor riesgo. Plazo: datos finalizados en Semana 4 de 8.' },
      { agentId: 'esg-agent', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo ESG: (1) CORRECCIÓN SOCIAL: Educación revisada a 87% con plan de mejora. Beneficiarios revisados a 7.200 documentados + 5.000 estimados (etiquetados). Diversidad: brecha reconocida con cronograma hacia 30%. (2) AMBIENTAL (aceptando disidencia): Declaración "año base". Datos de 6 meses publicados con metodología de anualización. Sub-medición de agua instalada. Cálculo de carbono de viajes comisionado. (3) Todo sellado para Grupo Romero, auditoría GRI y aseguramiento externo.' },
      { agentId: 'environmental', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISIDENCIA RETIRADA. El enfoque de "año base" es honesto y conforme a GRI. Cristal es el primer club de fútbol peruano produciendo reporte ESG estándar GRI — no hay precedente. Para Grupo Romero: el reporte preciso protege la reputación corporativa. Para el fútbol: esto establece el estándar de cómo los clubes deben reportar impacto.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:sc90123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'sca0123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (Métricas GRI + Corrección social + Base ambiental + Evidencia auditoría)',
      complianceLabel: 'Reporte ESG',
      complianceValue: 'AÑO BASE GRI — VERIFICADO',
      complianceThreshold: 'Estándares GRI · Sostenibilidad Grupo Romero',
      agents: ['Agente de Reporte ESG', 'Agente de Impacto Social', 'Agente Ambiental', 'Agente de Verificación'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Sporting Cristal — Gobernanza ESG',
      guaranteeBody: 'Sella: métricas sociales GRI (corregidas), declaración base ambiental, metodología de beneficiarios, precisión educativa, evidencia de aseguramiento externo.',
      evidenceChain: 'Recolección métricas → Verificación social → Base ambiental → Corrección → Evidencia auditoría → Cumplimiento GRI → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobiernan el reporte ESG de Cristal — la primera divulgación de sostenibilidad estándar GRI para un club de fútbol peruano.',
    phaseLabels: ['Métricas Sociales y Verificación', 'Base Ambiental', 'Protocolo ESG'],
  },
];
