/**
 * Universitario de Deportes — Spanish Scenarios
 * @module pages/sandbox/configs/universitario-es
 */

// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.

import type { TemplateScenario } from '../SandboxTemplate';

export const ES_SCENARIOS: TemplateScenario[] = [
  // ESCENARIO 1 — VENTAS COPA LIBERTADORES
  {
    id: 'libertadores-transfers',
    title: 'Ventas Copa Libertadores — Evidencia para CONMEBOL y FIFA TMS',
    subtitle: 'Tricampeón 2023-25 · €14.70M valor del plantel · Scouts europeos · Transparencia para 80,000 socios',
    banner: 'Simulando gobernanza de transferencias para el plantel más valioso del Perú. Tres títulos consecutivos de la Liga 1 elevaron el valor de La U a €14.70M. Clubes europeos pujan simultáneamente por dos titulares. Las valoraciones de IA deben ser auditables para CONMEBOL, FIFA TMS, FPF y los 80,000+ socios.',
    risk: 'Alto',
    scenarioNum: 'Transferencia',
    icon: 'arrow-right-left',
    color: 'text-amber-400',
    agents: [
      { id: 'transfer-val', name: 'Agente de Valoración', role: 'Análisis de Mercado y Valor Justo', icon: '📊', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'conmebol-lic', name: 'Agente CONMEBOL', role: 'Licencias de Clubes y Competición', icon: '🏆', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'fifa-tms', name: 'Agente FIFA TMS', role: 'Sistema de Correspondencia y RSTP', icon: '🌐', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'financial-sust', name: 'Agente de Sostenibilidad', role: 'Cumplimiento SUNAT e Impacto', icon: '💰', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'FIFA TMS', status: 'connected', type: 'Correspondencia', icon: 'globe', detail: '2 negociaciones activas — clubes de Bélgica y Portugal' },
      { name: 'Licencias CONMEBOL', status: 'connected', type: 'Licencias', icon: 'check-circle', detail: 'Copa Libertadores 2026 fase de grupos — umbral monitoreado' },
      { name: 'Portal SUNAT', status: 'connected', type: 'Cumplimiento Fiscal', icon: 'database', detail: 'Cálculos de retención del Impuesto a la Renta' },
      { name: 'Datos Transfermarkt', status: 'syncing', type: 'Inteligencia de Mercado', icon: 'bar-chart', detail: 'Valoración en tiempo real: €14.70M — la más alta del Perú' },
    ],
    script: [
      { agentId: 'transfer-val', phase: 'phase1', type: 'warning', delay: 800, content: 'ALERTA DE GOBERNANZA DE TRANSFERENCIAS — OFERTAS SIMULTÁNEAS. Dos clubes europeos presentaron ofertas formales: (1) Liga Pro de Bélgica: €2.8M por mediocampista (Transfermarkt €1.5M, prima del 86%). (2) Primeira Liga de Portugal: €1.9M por lateral derecho (Transfermarkt €1.2M, prima del 58%). Combinado: €4.7M — 32% del valor total del plantel. Como tricampeón, perder dos titulares arriesga la Copa Libertadores 2026. Sin embargo, las primas representan valor significativo para un club de socios con obligaciones ante SUNAT.' },
      { agentId: 'conmebol-lic', phase: 'phase1', type: 'analysis', delay: 2500, content: 'Análisis de Licencias CONMEBOL: (1) Plantel: 28 registrados, perder 2 requiere reemplazos (máx 30). (2) Cuota de extranjeros: 7 de 8 — ambos son peruanos, sin impacto. (3) Indicadores financieros: €4.7M fortalece la posición — salarios al día (12 meses). (4) Impacto competitivo: vender antes del sorteo (marzo) permite integración; después es más riesgoso. (5) Desde la perspectiva de licencias, ambas ventas son permisibles. Pero el impacto deportivo debe evaluarse independientemente.' },
      { agentId: 'financial-sust', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — IMPLICACIONES SUNAT. €4.7M combinados (~PEN 18.5M). Impuesto a la Renta: 29.5% sobre ganancia neta. Jugadores formados en cantera = costo cero = monto total gravable. Obligación SUNAT: ~€1.39M. La deuda histórica de La U significa que ingresos grandes activan auditoría reforzada. Honorarios de agentes: ambos intermediarios reclaman 8% — por encima del tope FIFA FFAR (3-6%). Mi disenso: aceptar AMBAS simultáneamente crea un evento fiscal concentrado. Recomiendo escalonar: vender uno ahora, otro en la ventana de medio año.' },
      { agentId: 'fifa-tms', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — CUMPLIMIENTO FIFA TMS. Ambas transferencias vía TMS: (1) CTIs — FPF debe emitir, 5-10 días hábiles. (2) Compensación por formación: Jugador A formado desde los 14 — derechos de solidaridad deben registrarse. (3) TPO: ningún jugador tiene propiedad de terceros — VERIFICADO. (4) Verificación de agentes: Agente 1 tiene licencia FIFA (cumple). Licencia del Agente 2 venció hace 3 meses — PARADA OBLIGATORIA. CRÍTICO: la operación con Portugal no puede proceder con agente sin licencia.' },
      { agentId: 'transfer-val', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo de Gobernanza de Transferencias: (1) PARADA OBLIGATORIA: Jugador B pausado hasta que Agente 2 renueve licencia. (2) VENTAS ESCALONADAS: Jugador A (Bélgica) procede ahora — €2.8M. Jugador B diferido a medio año. (3) ASIGNACIÓN SUNAT: 40% de los ingresos del Jugador A para reducción de deuda histórica. (4) REEMPLAZO: €1.2M reservados para refuerzo Copa Libertadores. (5) SOLIDARIDAD: Derechos registrados en TMS antes de completar. (6) TRANSPARENCIA: Informe completo publicado para los socios — 80,000 dueños merecen evidencia, no promesas.' },
      { agentId: 'financial-sust', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. La estructura escalonada aborda el riesgo de concentración SUNAT. La parada obligatoria del agente proporciona escalonamiento natural. Para CONMEBOL: posición financiera fortalecida. Para los socios: el Recibo del Regulador proporciona prueba criptográfica de que cada decisión de transferencia fue deliberada con consideraciones deportivas, financieras, regulatorias y de gobernanza.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:ud10123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'ud20123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (Valoraciones + FIFA TMS + Licencias CONMEBOL + Asignación SUNAT + Verificación de agentes)',
      complianceLabel: 'Gobernanza de Transferencias',
      complianceValue: 'PARADA OBLIGATORIA ACTIVA',
      complianceThreshold: 'FIFA FFAR — agente sin licencia bloqueado',
      agents: ['Agente de Valoración', 'Agente CONMEBOL', 'Agente FIFA TMS', 'Agente de Sostenibilidad'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Universitario — Gobernanza de Transferencias Copa Libertadores',
      guaranteeBody: 'Este paquete criptográfico sella la deliberación completa: ofertas europeas duales (€4.7M), estructura escalonada, parada obligatoria de agente, cumplimiento CONMEBOL, registro de solidaridad FIFA TMS y transparencia para socios.',
      evidenceChain: 'Ofertas europeas → Valoración → CONMEBOL → SUNAT → Verificación de agentes → Parada obligatoria → Escalonamiento → Transparencia → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobernarán ofertas europeas simultáneas — equilibrando competitividad Copa Libertadores, obligaciones SUNAT, cumplimiento de agentes FIFA y transparencia para 80,000 socios.',
    phaseLabels: ['Análisis y Impacto CONMEBOL', 'SUNAT y Cumplimiento de Agentes', 'Protocolo de Venta Escalonada'],
  },

  // ESCENARIO 2 — DEUDA TRIBUTARIA SUNAT
  {
    id: 'sunat-debt',
    title: 'Deuda Tributaria SUNAT — Fair Play Financiero Bajo Presión Fiscal',
    subtitle: 'Obligaciones históricas · Riesgo de licencias CONMEBOL · Fraccionamiento · Amnistía',
    banner: 'Simulando gobernanza financiera para el desafío estructural de Universitario con SUNAT. Cada decisión financiera debe documentar su postura de cumplimiento tributario.',
    risk: 'Crítico',
    scenarioNum: 'SUNAT',
    icon: 'landmark',
    color: 'text-red-400',
    agents: [
      { id: 'sunat-compliance', name: 'Agente SUNAT', role: 'Seguimiento de Obligaciones y Defensa ante Auditoría', icon: '🏛️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'conmebol-fin', name: 'Agente Financiero CONMEBOL', role: 'Indicadores Financieros de Licencias', icon: '🏆', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'legal-tax', name: 'Agente Legal', role: 'Código Tributario y Estrategia de Amnistía', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'financial-ops', name: 'Agente de Operaciones', role: 'Flujo de Caja y Cronograma de Pagos', icon: '📊', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Portal SUNAT', status: 'connected', type: 'Autoridad Tributaria', icon: 'landmark', detail: 'Deuda activa: PEN 8.2M — fraccionamiento vigente' },
      { name: 'Licencias CONMEBOL', status: 'connected', type: 'Revisión Financiera', icon: 'check-circle', detail: 'Indicador de pagos vencidos: ÁMBAR' },
      { name: 'Sistema Financiero', status: 'connected', type: 'Flujo de Caja', icon: 'database', detail: 'Flujo mensual: PEN 3.1M ingresos vs PEN 2.8M obligaciones' },
      { name: 'Programa de Amnistía', status: 'syncing', type: 'Reestructuración', icon: 'file-text', detail: 'Amnistía SUNAT — ventana de aplicación abierta' },
    ],
    script: [
      { agentId: 'sunat-compliance', phase: 'phase1', type: 'warning', delay: 800, content: 'ALERTA SUNAT. Posición actual: (1) Deuda histórica: PEN 8.2M — Impuesto a la Renta y EsSalud impagos. (2) Fraccionamiento activo: PEN 180K/mes x 48 meses. 14 pagados, 34 restantes. (3) Premios Copa Libertadores (~$400K) crean nuevo ingreso gravable. (4) Clubes con deuda histórica e ingresos grandes son marcados para auditoría reforzada. (5) AFP/ONP: 3 empleados con contribuciones atrasadas — PEN 12K. Regularizar para evitar intervención SUNAFIL.' },
      { agentId: 'conmebol-fin', phase: 'phase1', type: 'analysis', delay: 2500, content: 'Indicadores financieros CONMEBOL: (1) PAGOS VENCIDOS: el fraccionamiento satisface CONMEBOL SI los pagos se mantienen al día. Faltar UN pago cambia ÁMBAR a ROJO — revisión de elegibilidad Copa. (2) SALARIOS: 12 meses al corriente — cumple. (3) ESTADOS FINANCIEROS: deuda SUNAT aparece como pasivo contingente. (4) Situación manejable pero frágil — un pago perdido, una disputa de auditoría o evento fiscal imprevisto lleva el indicador a ROJO.' },
      { agentId: 'legal-tax', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — OPORTUNIDAD DE AMNISTÍA. Decreto Legislativo: exoneración del 90% de intereses/multas si el principal se paga en 90 días. PEN 8.2M incluye ~PEN 3.1M en intereses. Con amnistía: PEN 5.41M total (ahorro PEN 2.79M). Pero requiere pago único en 90 días. Superávit mensual: solo PEN 300K. Fraccionamiento actual (PEN 180K x 34 = PEN 6.12M) cuesta MÁS pero distribuye en 34 meses. Mi disenso: la ruta óptima depende del timing de transferencias. Debemos MODELAR ambas rutas.' },
      { agentId: 'financial-ops', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — MODELOS DE FLUJO. RUTA A (fraccionamiento): PEN 6.12M en 34 meses. Predecible, CONMEBOL ÁMBAR. RUTA B (amnistía): PEN 5.41M. Si la transferencia del Jugador A (€2.8M = ~PEN 11M) se completa en 60 días: asignar PEN 5.41M a amnistía. Ahorro vs A: PEN 710K. CONMEBOL pasa de ÁMBAR a VERDE. RIESGO: Ruta B depende del timing de transferencia. AFP (PEN 12K) debe resolverse inmediatamente.' },
      { agentId: 'sunat-compliance', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo de Gobernanza SUNAT: (1) INMEDIATO: AFP/ONP resuelto esta semana, sellado para SUNAFIL. (2) AMNISTÍA CONDICIONAL: Preparar solicitud ahora. Si transferencia completa en 60 días: EJECUTAR amnistía. Si se retrasa: CONTINUAR fraccionamiento. Punto de decisión sellado. (3) CONMEBOL: paquete mensual de cumplimiento. (4) DEFENSA: cada decisión financiera produce memorando de cumplimiento tributario. (5) SOCIOS: informe trimestral de progreso SUNAT.' },
      { agentId: 'legal-tax', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. La ruta condicional preserva ambas opciones. Preparar la amnistía no cuesta nada pero proporciona opcionalidad de PEN 710K. Pasar de ÁMBAR a VERDE sería la señal más fuerte para las licencias Copa Libertadores. Para los socios: 80,000 dueños ven la estrategia SUNAT gobernada por datos, no por esperanza.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:ud30123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'ud40123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (Deuda SUNAT + Fraccionamiento + Amnistía + AFP/ONP + Indicadores CONMEBOL)',
      complianceLabel: 'Cumplimiento SUNAT',
      complianceValue: 'AMNISTÍA CONDICIONAL PREPARADA',
      complianceThreshold: 'Fraccionamiento al día — amnistía condicional',
      agents: ['Agente SUNAT', 'Agente Financiero CONMEBOL', 'Agente Legal', 'Agente de Operaciones'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Universitario — Gobernanza Tributaria SUNAT',
      guaranteeBody: 'Sella: gestión de deuda PEN 8.2M, cumplimiento del fraccionamiento, amnistía condicional, resolución AFP/ONP, indicadores CONMEBOL, transparencia para socios.',
      evidenceChain: 'Auditoría SUNAT → Fraccionamiento → Modelo amnistía → Timing transferencia → AFP → CONMEBOL → Informe socios → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobernarán la estrategia tributaria SUNAT — equilibrando deuda histórica, oportunidad de amnistía, requisitos Copa Libertadores y transparencia.',
    phaseLabels: ['Posición Fiscal e Impacto CONMEBOL', 'Amnistía vs Fraccionamiento', 'Ruta Condicional y Transparencia'],
  },

  // ESCENARIO 3 — SEGURIDAD DEL ESTADIO MONUMENTAL
  {
    id: 'monumental-safety',
    title: 'Estadio Monumental — Gobernanza del Estadio Más Grande de Sudamérica',
    subtitle: '80,093 de capacidad · Noches de Copa Libertadores · Cumplimiento INDECI · Protocolos de emergencia',
    banner: 'Simulando gobernanza del recinto en el estadio más grande de Sudamérica. La fase de grupos de la Copa Libertadores requiere planificación de seguridad, control de multitudes, protocolos médicos y certificación CONMEBOL.',
    risk: 'Alto',
    scenarioNum: 'Estadio',
    icon: 'building',
    color: 'text-blue-400',
    agents: [
      { id: 'venue-gov', name: 'Agente de Recinto', role: 'Certificación CONMEBOL y Gestión de Capacidad', icon: '🏟️', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'safety-indeci', name: 'Agente INDECI', role: 'Defensa Civil y Protocolos de Emergencia', icon: '🛡️', color: 'text-red-400', borderColor: 'border-red-500/40', bgColor: 'bg-red-500/10' },
      { id: 'medical-stadium', name: 'Agente Médico', role: 'Servicios Médicos de Emergencia', icon: '🏥', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'security-ops', name: 'Agente de Seguridad', role: 'Control de Multitudes y Orden Público', icon: '🔒', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
    ],
    connectors: [
      { name: 'Portal INDECI', status: 'connected', type: 'Defensa Civil', icon: 'shield', detail: 'Cumplimiento Ley 29664 — certificación vence en 30 días' },
      { name: 'Sistema CONMEBOL', status: 'connected', type: 'Certificación', icon: 'check-circle', detail: 'Inspección Copa Libertadores programada — Semana 3' },
      { name: 'Municipalidad de Lima', status: 'connected', type: 'Permisos', icon: 'landmark', detail: 'Permiso para 80,093 — aprobación distrito de Ate' },
      { name: 'Servicios de Emergencia', status: 'syncing', type: 'Médico y Bomberos', icon: 'heart', detail: '12 posiciones de ambulancia + coordinación bomberos' },
    ],
    script: [
      { agentId: 'venue-gov', phase: 'phase1', type: 'warning', delay: 800, content: 'GOBERNANZA DEL RECINTO — CERTIFICACIÓN COPA LIBERTADORES. El Monumental (80,093) debe pasar inspección CONMEBOL: (1) Asientos: 76,000 conformes, 4,093 en Sector Sur requieren numeración. (2) Iluminación: 1,380 lux esquina NO — debajo del mínimo de 1,400. (3) Medios: 180 de 200 posiciones requeridas. (4) Sala VAR: conforme pero aire acondicionado tiene 8 años. (5) Cancha: aprobó FPF pero estándares CONMEBOL son más altos. Los 5 puntos deben resolverse en 3 semanas.' },
      { agentId: 'safety-indeci', phase: 'phase1', type: 'analysis', delay: 2500, content: 'Evaluación INDECI para 80,093: (1) Evacuación: actual 12 min por 48 puertas — INDECI requiere 8 min. Puertas Sector Norte obstruidas. (2) Incendios: 312 de 340 extintores. Déficit 28. (3) Iluminación de emergencia: generadores Sector Este — 2 fallaron prueba de arranque. (4) Certificación vence en 30 días — si caduca, no hay permiso municipal, no hay partido Copa. (5) Último simulacro: hace 14 meses — INDECI requiere cada 12.' },
      { agentId: 'security-ops', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — DÉFICIT DE SEGURIDAD. Copa Libertadores requiere 1:250 = 321 oficiales mínimo. Contratados (licencia SUCAMEC): 280. Perímetros dedicados CONMEBOL absorben 60 — quedan 220 para público general (1:364, debajo del mínimo). Segregación de visitantes necesita 30 más. Mi disenso: 280 es INSUFICIENTE. Se necesitan mínimo 380. El contratista actual no puede escalar en 3 semanas.' },
      { agentId: 'medical-stadium', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — CAPACIDAD MÉDICA. (1) Al borde de cancha: CONFORME. (2) Público: 6 de 8 puntos médicos — faltan 2 temporales (Sector Sur, Norte). (3) Aplastamiento: el Monumental ha tenido incidentes de presión en la Noche Crema — CONMEBOL requiere plan de monitoreo de densidad (NO implementado). (4) Hospital: Level III más cercano a 8km — CONMEBOL recomienda transporte cardíaco preposicionado. (5) Calor: partidos feb-marzo pueden llegar a 30°C — plan de distribución de agua requerido.' },
      { agentId: 'venue-gov', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo del Monumental: (1) SEMANA 1: Despejar obstrucciones → evacuación 8 min. Pedir extintores. Programar simulacro. (2) SEMANA 2: Simulacro con observadores INDECI. Desplegar 2 puntos médicos. Instalar monitoreo de densidad. (3) SEGURIDAD: Contratar segundo proveedor para 100 oficiales. Total 380. Coordinación PNP documentada. (4) SEMANA 3: Numeración, iluminación, medios, VAR, cancha — todo completo. (5) Presentación INDECI con evidencia sellada. Delegado CONMEBOL recibe paquete completo.' },
      { agentId: 'security-ops', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Segundo contratista resuelve déficit — 380 oficiales supera mínimo en 18%. Acuerdo PNP documentado. Cada tarea tiene responsable, plazo y evidencia sellada. Para CONMEBOL: el paquete de inspección más completo que ha producido un club peruano. 80,093 espectadores merecen gobernanza a la escala del recinto.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:ud50123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'ud60123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (INDECI + Recinto CONMEBOL + Seguridad + Médico + Evacuación + Simulacro)',
      complianceLabel: 'Seguridad del Recinto',
      complianceValue: '5 BRECHAS — RESOLUCIÓN 3 SEMANAS',
      complianceThreshold: 'Inspección CONMEBOL Sem 3 · Renovación INDECI 30 días',
      agents: ['Agente de Recinto', 'Agente INDECI', 'Agente Médico', 'Agente de Seguridad'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Estadio Monumental — Gobernanza Copa Libertadores',
      guaranteeBody: 'Sella: resolución de seguridad 80,093, renovación INDECI, preparación CONMEBOL, escalamiento a 380 oficiales, monitoreo de densidad.',
      evidenceChain: 'Auditoría → 5 brechas → Simulacro INDECI (Sem2) → Escalamiento seguridad → Médico → Inspección CONMEBOL (Sem3) → Cert INDECI → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobernarán la seguridad del estadio más grande de Sudamérica — resolviendo brechas INDECI, escalando seguridad y produciendo evidencia completa.',
    phaseLabels: ['Auditoría y Brechas de Seguridad', 'Seguridad y Capacidad Médica', 'Resolución y Certificación'],
  },

  // ESCENARIO 4 — ACADEMIA JUVENIL
  {
    id: 'youth-academy',
    title: 'Academia Juvenil — Cumplimiento del Código de los Niños y Adolescentes',
    subtitle: 'Cantera de selección · FIFA Artículo 19 · Requisitos educativos · Salvaguarda',
    banner: 'Simulando gobernanza del desarrollo juvenil de La U. IA gobierna cumplimiento del CNA, FIFA Artículo 19, requisitos educativos y documentación de salvaguarda.',
    risk: 'Alto',
    scenarioNum: 'Juvenil',
    icon: 'users',
    color: 'text-emerald-400',
    agents: [
      { id: 'youth-safeguard', name: 'Agente de Salvaguarda', role: 'Cumplimiento CNA y Protección Infantil', icon: '👦', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
      { id: 'education-track', name: 'Agente Educativo', role: 'Ley General de Educación y Verificación', icon: '📚', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'fifa-youth', name: 'Agente FIFA Art. 19', role: 'Parada Obligatoria para Menores Internacionales', icon: '🌐', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'welfare-monitor', name: 'Agente de Bienestar', role: 'Supervisión de Salud Física y Mental', icon: '💚', color: 'text-cyan-400', borderColor: 'border-cyan-500/40', bgColor: 'bg-cyan-500/10' },
    ],
    connectors: [
      { name: 'Registro Juvenil FPF', status: 'connected', type: 'Registro', icon: 'database', detail: '42 jugadores de academia 12-18 años — cumplimiento monitoreado' },
      { name: 'Portal MINEDU', status: 'connected', type: 'Verificación Educativa', icon: 'book-open', detail: 'Verificación de matrícula para los 42 menores' },
      { name: 'FIFA TMS (Menores)', status: 'connected', type: 'Artículo 19', icon: 'globe', detail: '2 consultas internacionales — parada obligatoria activa' },
      { name: 'Coordinación MIMP', status: 'syncing', type: 'Protección Infantil', icon: 'shield', detail: 'Ministerio de la Mujer — protocolo registrado' },
    ],
    script: [
      { agentId: 'youth-safeguard', phase: 'phase1', type: 'warning', delay: 800, content: 'AUDITORÍA DE SALVAGUARDA — 42 menores: (1) Consentimiento parental: 40/42 verificados. 2 jugadores (Cusco, 13-14 años) tienen consentimiento de "tío" — legalmente insuficiente bajo CNA Ley 27337. (2) Educación: 39/42 con matrícula MINEDU. 3 con asistencia debajo del 60% (conflictos con entrenamientos). (3) Médico: 42 con certificados anuales. 4 de 12-13 años sin exámenes dentales. (4) Residencia juvenil: 8 jugadores de provincia — sin inspección independiente en 18 meses.' },
      { agentId: 'education-track', phase: 'phase1', type: 'analysis', delay: 2500, content: 'ANÁLISIS EDUCATIVO. 3 jugadores con baja asistencia: Jugador X (15): 52%, entrenamientos vespertinos se superponen mar/jue. Jugador Y (16): 58%, convocatorias U-17 FPF contadas como inasistencias. Jugador Z (14): 47% — superposición de entrenamientos MÁS presión económica familiar. Bajo Ley 28044 y CNA Art. 14: la educación es un derecho fundamental que prevalece sobre compromisos deportivos. Si el horario de la academia impide la asistencia, el horario debe cambiar.' },
      { agentId: 'fifa-youth', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — FIFA ARTÍCULO 19. Dos consultas internacionales: (1) Club argentino por jugador de 16 años. Excepciones Art. 19: padres reubicándose (no), UE/EEE (no), 50km frontera (Lima-Buenos Aires 3,500km — no). PARADA OBLIGATORIA. (2) Club colombiano por préstamo de jugador de 17. Mismo análisis — ninguna excepción aplica. PARADA OBLIGATORIA. Mi disenso: el director de cantera ha comunicado "informalmente" con ambos clubes. Cualquier arreglo que resulte en un menor cruzando fronteras para fútbol viola Art. 19. Las comunicaciones deben documentarse y CESAR.' },
      { agentId: 'welfare-monitor', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — BIENESTAR INMEDIATO. (1) Jugador Z (14, 47%): situación económica familiar requiere intervención. La U no puede beneficiarse del desarrollo de un menor mientras sus derechos fundamentales están comprometidos. Opciones: beca cubriendo educación + apoyo familiar, o liberación. (2) Residencia juvenil: inspección DEMUNA vencida por 6 meses. (3) Jugadores con consentimiento de "tío": si viven lejos de padres sin tutela legal, puede ser violación del CNA. (4) Sin programa de bienestar psicológico para 12-13 años.' },
      { agentId: 'youth-safeguard', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo de Gobernanza Juvenil: (1) INMEDIATO: Jugadores con consentimiento de "tío" suspendidos hasta obtener consentimiento de tutor legal. Jugador Z — beca + evaluación familiar + modificación de horario. Inspección DEMUNA solicitada en 5 días. (2) EDUCACIÓN: Cero conflictos en horario escolar. Convocatorias FPF coordinadas con MINEDU. Debajo del 70% activa suspensión. (3) ARTÍCULO 19: Ambas consultas BLOQUEADAS formalmente. Director instruido — comunicaciones con clubes extranjeros preaprobadas. (4) BIENESTAR: Evaluaciones psicológicas anuales. Residencia inspeccionada anualmente. (5) Acciones selladas para FPF, MIMP, MINEDU, FIFA.' },
      { agentId: 'fifa-youth', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Paradas obligatorias del Art. 19 confirmadas por escrito. Comunicaciones informales abordadas. La academia de La U produce talento de selección — pero la producción nunca debe costar los derechos de los niños. CNA, Ley de Educación y Art. 19 existen porque los niños en el fútbol son vulnerables. 42 niños bajo el cuidado de La U merecen el mismo rigor de gobernanza que los 80,093 espectadores del Monumental.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:ud70123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'ud80123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (CNA + Educación + FIFA Art. 19 + Bienestar + DEMUNA)',
      complianceLabel: 'Salvaguarda Juvenil',
      complianceValue: '2 PARADAS OBLIGATORIAS ART. 19',
      complianceThreshold: 'CNA Ley 27337 + FIFA RSTP Art. 19',
      agents: ['Agente de Salvaguarda', 'Agente Educativo', 'Agente FIFA Art. 19', 'Agente de Bienestar'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Universitario — Salvaguarda de la Academia Juvenil',
      guaranteeBody: 'Sella: auditoría de 42 menores, 2 deficiencias de consentimiento, 3 brechas educativas, 2 paradas obligatorias Art. 19, intervención de bienestar, inspección DEMUNA.',
      evidenceChain: 'Auditoría → Consentimiento → Educación → Art. 19 → Paradas obligatorias → Bienestar → Jugador Z → DEMUNA → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA auditarán la academia juvenil — cumplimiento CNA, bloqueo de violaciones Art. 19 y protección para 42 niños.',
    phaseLabels: ['Auditoría y Brechas', 'Artículo 19 y Bienestar', 'Protocolo de Gobernanza Juvenil'],
  },

  // ESCENARIO 5 — LA NOCHE CREMA COMERCIAL
  {
    id: 'noche-crema',
    title: 'La Noche Crema — Gobernanza de Evento Comercial',
    subtitle: '80,000+ asistentes · Precios dinámicos · INDECOPI · Publicidad de apuestas · Transparencia',
    banner: 'Simulando gobernanza comercial del evento pretemporada más grande del Perú. Precios de entradas, activación de patrocinios y términos de transmisión deben demostrar prácticas justas ante INDECOPI, MINCETUR y 80,000 socios.',
    risk: 'Medio',
    scenarioNum: 'Comercial',
    icon: 'ticket',
    color: 'text-purple-400',
    agents: [
      { id: 'commercial-gov', name: 'Agente Comercial', role: 'Estrategia de Precios y Comercio Justo', icon: '🎫', color: 'text-purple-400', borderColor: 'border-purple-500/40', bgColor: 'bg-purple-500/10' },
      { id: 'indecopi-agent', name: 'Agente INDECOPI', role: 'Competencia y Protección al Consumidor', icon: '⚖️', color: 'text-amber-400', borderColor: 'border-amber-500/40', bgColor: 'bg-amber-500/10' },
      { id: 'sponsor-brand', name: 'Agente de Patrocinios', role: 'Seguridad de Marca y Publicidad de Apuestas', icon: '📢', color: 'text-blue-400', borderColor: 'border-blue-500/40', bgColor: 'bg-blue-500/10' },
      { id: 'socios-gov', name: 'Agente de Socios', role: 'Transparencia y Rendición de Cuentas', icon: '🏛️', color: 'text-emerald-400', borderColor: 'border-emerald-500/40', bgColor: 'bg-emerald-500/10' },
    ],
    connectors: [
      { name: 'Plataforma de Entradas', status: 'connected', type: 'Datos de Ventas', icon: 'ticket', detail: '65,000 vendidas — 15,093 restantes. Precios dinámicos activos.' },
      { name: 'Registro INDECOPI', status: 'connected', type: 'Comercio Justo', icon: 'scale', detail: '2 quejas previas de precios (resueltas)' },
      { name: 'Portal MINCETUR', status: 'connected', type: 'Publicidad de Apuestas', icon: 'shield', detail: 'Verificación de cumplimiento del patrocinador de apuestas' },
      { name: 'Portal de Socios', status: 'syncing', type: 'Miembros', icon: 'users', detail: '80,000+ socios — transparencia de precios pendiente' },
    ],
    script: [
      { agentId: 'commercial-gov', phase: 'phase1', type: 'warning', delay: 800, content: 'ALERTA COMERCIAL NOCHE CREMA 2026. (1) 65,000 de 80,093 vendidas. Precios dinámicos en las restantes: PEN 80-250 (original PEN 35-120, aumento hasta 108%). (2) Descuento socios 20%: 35,000 compraron. (3) 14 patrocinadores — el principal es empresa de apuestas (Apuesta Total) en evento familiar con menores. (4) Transmisión exclusiva L1 Max — PEN 800K mínimo. Transmisión no autorizada el año pasado causó amenaza legal. (5) Proyección de ingresos: PEN 4.2M.' },
      { agentId: 'indecopi-agent', phase: 'phase1', type: 'analysis', delay: 2500, content: 'Análisis INDECOPI: Ley 29571 permite precios dinámicos SI: (a) se divulga que los precios cambian, (b) sin publicidad engañosa de "precio inicial", (c) consistencia dentro de categorías. El sitio web de La U muestra divulgación mínima. 2 quejas previas. Aumento del 108% es legal pero riesgo reputacional. Reventa de socios creando mercado gris — si se detecta, INDECOPI podría investigar.' },
      { agentId: 'sponsor-brand', phase: 'phase2', type: 'dissent', delay: 2000, content: 'DISENSO — PUBLICIDAD DE APUESTAS. Apuesta Total tiene: LED perimetral, logo en camiseta, naming de sector ("Sector Apuesta Total Norte"), stand en concurso con incentivos de descarga "apuesta gratis". MINCETUR DS 006-2023: no puede dirigirse a menores, debe incluir mensaje de juego responsable. Stand ofreciendo apuestas gratis en evento familiar = problema de targeting. Mi disenso: stand debe reubicarse a zona verificada de edad (18+). Promociones no visibles desde áreas generales.' },
      { agentId: 'socios-gov', phase: 'phase2', type: 'flag', delay: 2500, content: 'ALERTA — GOBERNANZA DE SOCIOS. (1) Asignación de ingresos: PEN 4.2M proyectados sin plan publicado. (2) Redes sociales: socios quejándose del aumento 108% — "SOMOS DUEÑOS del club y nos excluyen." Desafío legítimo en próxima asamblea. (3) Patrocinador de apuestas (PEN 2.5M/año) nunca fue votado por socios. (4) Socios de provincia sin L1 Max no pueden ver — inequidad. (5) Nunca se ha producido informe de transparencia comercial de la Noche Crema.' },
      { agentId: 'commercial-gov', phase: 'phase3', type: 'proposal', delay: 2000, content: 'Protocolo de Noche Crema: (1) PRECIOS: Página mejorada de divulgación de precios dinámicos. Documentación lista para INDECOPI. Monitoreo de reventa. (2) APUESTAS: Stand reubicado a zona 18+. Sector mantiene nombre con señalización de juego responsable. Paquete MINCETUR sellado. (3) SOCIOS: Primer Informe Comercial en 30 días — ingresos, asignación, patrocinios, metodología. (4) TRANSMISIÓN: Negociar retransmisión gratuita diferida 24h para socios de provincia. Política de redes sociales. (5) ASIGNACIÓN: 40% plantel, 30% deuda SUNAT, 20% instalaciones, 10% cantera.' },
      { agentId: 'sponsor-brand', phase: 'phase3', type: 'resolution', delay: 2500, content: 'DISENSO RETIRADO. Reubicación del stand resuelve MINCETUR. Zona verificada protege menores. Para INDECOPI: divulgación mejorada transforma riesgo de queja en demostración de transparencia. Para socios: primer informe comercial sienta precedente — 80,000 dueños ven cómo su club genera y asigna ingresos. La Noche Crema es la vitrina de gobernanza de la democracia de socios en el fútbol.' },
    ],
    receiptTemplate: {
      hash: 'SHA-256:ud90123456789abcdef0123456789abcdef0123456789abcdef012345678abcde',
      merkleRoot: 'uda0123456789abcdef0123456789abcdef0123456789abcdef012345678abcdef',
      merkleLabel: 'Raíz del Árbol Merkle (Precios dinámicos + INDECOPI + MINCETUR apuestas + Transparencia socios + Transmisión)',
      complianceLabel: 'Gobernanza Comercial',
      complianceValue: 'PUBLICIDAD DE APUESTAS REUBICADA',
      complianceThreshold: 'MINCETUR DS 006-2023 · INDECOPI Ley 29571',
      agents: ['Agente Comercial', 'Agente INDECOPI', 'Agente de Patrocinios', 'Agente de Socios'],
      dissents: 1,
      dissentResolved: true,
      guaranteeTitle: 'Universitario — Gobernanza Comercial Noche Crema',
      guaranteeBody: 'Sella: gobernanza de precios dinámicos, comercio justo INDECOPI, cumplimiento de apuestas MINCETUR, informe de transparencia para socios, exclusividad de transmisión, plan de asignación.',
      evidenceChain: 'Análisis de ingresos → Precios dinámicos → INDECOPI → Publicidad de apuestas → MINCETUR → Informe socios → Plan de asignación → Sello ML-DSA-65',
    },
    idleTitle: 'Listo para Deliberar',
    idleDesc: '4 agentes de IA gobernarán La Noche Crema — equilibrando precios dinámicos, cumplimiento de publicidad de apuestas y transparencia para 80,000 socios.',
    phaseLabels: ['Análisis Comercial y Precios', 'Apuestas y Gobernanza de Socios', 'Protocolo Comercial'],
  },
];
