/**
 * Connector — Index
 *
 * External system connector for third-party integrations.
 *
 * @exports AvionicsConnectorFactory, AVIONICS_CONNECTORS
 * @module connectors/avionics/index
 */

﻿// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.
// See LICENSE file for details.

/**
 * =============================================================================
 * AVIONICS CONNECTORS
 * =============================================================================
 * Aircraft Systems, Flight Data, Maintenance, Safety, Air Traffic Control
 */

import { ConnectorMetadata } from '../BaseConnector.js';

export const AVIONICS_CONNECTORS: ConnectorMetadata[] = [
  // Flight Data & Recording
  {
    id: 'arinc-429',
    name: 'ARINC 429',
    description: 'Primary avionics data bus standard',
    vertical: 'avionics',
    category: 'data-bus',
    provider: 'ARINC (Collins Aerospace)',
    region: 'Global',
    dataTypes: ['navigation', 'flight-controls', 'engine-data', 'sensors'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.arinc.com/',
    requiredCredentials: ['equipment_id', 'certificate'],
    complianceFrameworks: ['DO-178C', 'DO-254', 'AS9100'],
    compatibilityLabel: 'file_ingestion',
    integrationNotes: 'Physical data bus; ingestion via File Watcher from export hardware',
  },
  {
    id: 'arinc-664',
    name: 'ARINC 664 (AFDX)',
    description: 'Avionics Full-Duplex Switched Ethernet',
    vertical: 'avionics',
    category: 'data-bus',
    provider: 'ARINC (Collins Aerospace)',
    region: 'Global',
    dataTypes: ['high-bandwidth', 'redundant-comms', 'flight-critical'],
    updateFrequency: 'real-time',
    requiredCredentials: ['network_id', 'certificate'],
    complianceFrameworks: ['DO-178C', 'DO-254'],
    compatibilityLabel: 'file_ingestion',
    integrationNotes: 'Physical data bus; ingestion via File Watcher from export hardware',
  },
  {
    id: 'mil-std-1553',
    name: 'MIL-STD-1553',
    description: 'Military avionics data bus standard',
    vertical: 'avionics',
    category: 'data-bus',
    provider: 'US DoD',
    region: 'Global',
    dataTypes: ['weapons-systems', 'sensors', 'navigation', 'flight-controls'],
    updateFrequency: 'real-time',
    requiredCredentials: ['security_clearance', 'equipment_cert'],
    complianceFrameworks: ['DO-178C', 'MIL-HDBK-516C'],
    compatibilityLabel: 'file_ingestion',
    integrationNotes: 'Military data bus; requires clearance; file export ingestion only',
  },
  {
    id: 'acars',
    name: 'ACARS',
    description: 'Aircraft Communications Addressing and Reporting System',
    vertical: 'avionics',
    category: 'communications',
    provider: 'SITA/ARINC',
    region: 'Global',
    dataTypes: ['position-reports', 'oooi-events', 'free-text', 'weather'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.sita.aero/',
    requiredCredentials: ['airline_code', 'aircraft_id', 'subscription'],
    complianceFrameworks: ['EUROCAE ED-85'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO SITA/ARINC subscription; Webhook or File Watcher ingestion',
  },
  {
    id: 'ads-b',
    name: 'ADS-B',
    description: 'Automatic Dependent Surveillance-Broadcast',
    vertical: 'avionics',
    category: 'surveillance',
    provider: 'FAA/ICAO',
    region: 'Global',
    dataTypes: ['position', 'velocity', 'altitude', 'identification'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.faa.gov/air_traffic/technology/adsb',
    requiredCredentials: ['receiver_id'],
    complianceFrameworks: ['DO-260B', 'TSO-C166b'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public broadcast standard; various aggregator APIs available',
  },
  {
    id: 'fdr-qar',
    name: 'Flight Data Recorder / QAR',
    description: 'Flight Data Recorder and Quick Access Recorder',
    vertical: 'avionics',
    category: 'recording',
    provider: 'L3Harris/Honeywell/Safran',
    region: 'Global',
    dataTypes: ['flight-parameters', 'engine-data', 'control-inputs', 'warnings'],
    updateFrequency: 'batch',
    requiredCredentials: ['airline_id', 'aircraft_registration'],
    complianceFrameworks: ['ED-112A', 'TSO-C124b'],
    compatibilityLabel: 'file_ingestion',
    integrationNotes: 'Requires physical QAR retrieval; File Watcher ingestion',
  },

  // Avionics OEMs
  {
    id: 'honeywell-forge',
    name: 'Honeywell Forge',
    description: 'Honeywell connected aircraft platform',
    vertical: 'avionics',
    category: 'oem-platform',
    provider: 'Honeywell Aerospace',
    region: 'Global',
    dataTypes: ['engine-health', 'apu-monitoring', 'predictive-maintenance', 'flight-ops'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://aerospace.honeywell.com/us/en/products-and-services/product/forge',
    requiredCredentials: ['api_key', 'org_id'],
    complianceFrameworks: ['SOC2', 'ISO27001'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Honeywell Forge subscription; Webhook Adapter integration',
  },
  {
    id: 'ge-digital-fleet',
    name: 'GE Digital Fleet',
    description: 'GE Aviation engine monitoring and analytics',
    vertical: 'avionics',
    category: 'oem-platform',
    provider: 'GE Aerospace',
    region: 'Global',
    dataTypes: ['engine-performance', 'fuel-efficiency', 'maintenance-alerts', 'trend-monitoring'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.geaviation.com/digital',
    requiredCredentials: ['api_key', 'fleet_id'],
    complianceFrameworks: ['SOC2'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO GE Digital subscription; Webhook Adapter integration',
  },
  {
    id: 'rolls-royce-intelliengine',
    name: 'Rolls-Royce IntelliEngine',
    description: 'Engine health management system',
    vertical: 'avionics',
    category: 'oem-platform',
    provider: 'Rolls-Royce',
    region: 'Global',
    dataTypes: ['engine-health', 'on-wing-time', 'maintenance-forecasts'],
    updateFrequency: 'real-time',
    requiredCredentials: ['customer_id', 'api_key'],
    complianceFrameworks: ['ISO27001'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Rolls-Royce TotalCare subscription; Webhook Adapter integration',
  },
  {
    id: 'collins-arincconnect',
    name: 'Collins ARINCConnect',
    description: 'Connected aircraft services',
    vertical: 'avionics',
    category: 'oem-platform',
    provider: 'Collins Aerospace',
    region: 'Global',
    dataTypes: ['connectivity', 'flight-ops', 'cabin-systems', 'maintenance'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.collinsaerospace.com/',
    requiredCredentials: ['api_key', 'airline_code'],
    complianceFrameworks: ['SOC2', 'DO-178C'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Collins subscription; Webhook Adapter integration',
  },
  {
    id: 'thales-flytlink',
    name: 'Thales FlytLINK',
    description: 'Aircraft connectivity and data services',
    vertical: 'avionics',
    category: 'oem-platform',
    provider: 'Thales',
    region: 'Global',
    dataTypes: ['connectivity', 'streaming-data', 'cabin-wifi'],
    updateFrequency: 'real-time',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['DO-178C'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Thales subscription; Webhook Adapter integration',
  },

  // Maintenance & Safety
  {
    id: 'spec2000',
    name: 'ATA Spec 2000',
    description: 'E-business standards for aviation industry',
    vertical: 'avionics',
    category: 'maintenance',
    provider: 'ATA/A4A',
    region: 'Global',
    dataTypes: ['parts-data', 'inventory', 'procurement', 'repair-orders'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.a4a.org/spec-2000',
    requiredCredentials: ['trading_partner_id'],
    complianceFrameworks: ['AS9100'],
    compatibilityLabel: 'native_protocol',
    integrationNotes: 'Native Spec 2000 XML format support via File Watcher',
  },
  {
    id: 'amos-mro',
    name: 'AMOS MRO',
    description: 'Aviation maintenance management system',
    vertical: 'avionics',
    category: 'maintenance',
    provider: 'Swiss-AS',
    region: 'Global',
    dataTypes: ['work-orders', 'parts-inventory', 'compliance-tracking', 'fleet-status'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.swiss-as.com/',
    requiredCredentials: ['api_key', 'org_id'],
    complianceFrameworks: ['EASA Part-145', 'FAA Part-145'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO AMOS license; Database Adapter for direct integration',
  },
  {
    id: 'trax-mro',
    name: 'TRAX eMRO',
    description: 'Enterprise MRO software platform',
    vertical: 'avionics',
    category: 'maintenance',
    provider: 'TRAX',
    region: 'Global',
    dataTypes: ['maintenance-planning', 'logistics', 'engineering', 'compliance'],
    updateFrequency: 'real-time',
    requiredCredentials: ['api_key'],
    complianceFrameworks: ['EASA Part-M', 'FAA Part-121'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO TRAX license; Database Adapter for direct integration',
  },
  {
    id: 'asias-safety',
    name: 'FAA ASIAS',
    description: 'Aviation Safety Information Analysis and Sharing',
    vertical: 'avionics',
    category: 'safety',
    provider: 'FAA',
    region: 'US',
    dataTypes: ['safety-reports', 'incidents', 'risk-assessments', 'trends'],
    updateFrequency: 'daily',
    documentationUrl: 'https://www.asias.faa.gov/',
    requiredCredentials: ['organization_id', 'certificate'],
    complianceFrameworks: ['FedRAMP', 'SMS'],
    compatibilityLabel: 'client_gateway',
    integrationNotes: 'FAA partnership required; File export ingestion',
  },
  {
    id: 'eccairs',
    name: 'ECCAIRS',
    description: 'European Co-ordination Centre for Accident Reporting',
    vertical: 'avionics',
    category: 'safety',
    provider: 'EASA',
    region: 'EU',
    dataTypes: ['occurrences', 'incidents', 'accidents', 'safety-recommendations'],
    updateFrequency: 'daily',
    documentationUrl: 'https://www.easa.europa.eu/',
    requiredCredentials: ['organization_id'],
    complianceFrameworks: ['GDPR', 'EASA SMS'],
    compatibilityLabel: 'client_gateway',
    integrationNotes: 'EASA membership required; File export ingestion',
  },

  // Air Traffic Control
  {
    id: 'eurocontrol-nm',
    name: 'EUROCONTROL Network Manager',
    description: 'European ATM network operations',
    vertical: 'avionics',
    category: 'atc',
    provider: 'EUROCONTROL',
    region: 'EU',
    dataTypes: ['atfm-slots', 'flight-plans', 'delays', 'capacity'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.eurocontrol.int/network-manager',
    requiredCredentials: ['b2b_certificate', 'org_id'],
    complianceFrameworks: ['GDPR'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO EUROCONTROL B2B subscription; Webhook Adapter',
  },
  {
    id: 'sesar-swim',
    name: 'SESAR SWIM',
    description: 'System Wide Information Management (Europe)',
    vertical: 'avionics',
    category: 'atc',
    provider: 'SESAR JU',
    region: 'EU',
    dataTypes: ['aeronautical-info', 'meteorological', 'flight-data', 'surveillance'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.sesarju.eu/',
    requiredCredentials: ['certificate', 'subscription'],
    complianceFrameworks: ['GDPR', 'ED-133'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO SESAR subscription; Webhook Adapter',
  },
  {
    id: 'iata-aidx',
    name: 'IATA AIDX',
    description: 'Aviation Information Data Exchange',
    vertical: 'avionics',
    category: 'operations',
    provider: 'IATA',
    region: 'Global',
    dataTypes: ['flight-schedules', 'movements', 'delays', 'gates'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.iata.org/',
    requiredCredentials: ['iata_code', 'certificate'],
    complianceFrameworks: [],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO IATA membership; Webhook Adapter',
  },

  // Weather for Aviation
  {
    id: 'metar-taf',
    name: 'METAR/TAF Weather',
    description: 'Aviation weather observations and forecasts',
    vertical: 'avionics',
    category: 'weather',
    provider: 'NOAA AWC',
    region: 'Global',
    dataTypes: ['metar', 'taf', 'sigmet', 'airmet', 'pirep'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://aviationweather.gov/',
    requiredCredentials: [],
    complianceFrameworks: ['FedRAMP'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API, no licensing required',
  },
  {
    id: 'jeppesen-wx',
    name: 'Jeppesen Weather',
    description: 'Premium aviation weather services',
    vertical: 'avionics',
    category: 'weather',
    provider: 'Jeppesen (Boeing)',
    region: 'Global',
    dataTypes: ['turbulence', 'icing', 'convective', 'winds-aloft'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://ww2.jeppesen.com/',
    requiredCredentials: ['api_key', 'subscription'],
    complianceFrameworks: [],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO Jeppesen subscription; Webhook Adapter',
  },

  // UAS/Drones
  {
    id: 'faa-laanc',
    name: 'FAA LAANC',
    description: 'Low Altitude Authorization and Notification Capability',
    vertical: 'avionics',
    category: 'uas',
    provider: 'FAA',
    region: 'US',
    dataTypes: ['airspace-authorization', 'uas-facility-maps', 'waivers'],
    updateFrequency: 'real-time',
    documentationUrl: 'https://www.faa.gov/uas/programs_partnerships/data_exchange',
    requiredCredentials: ['operator_id', 'api_key'],
    complianceFrameworks: ['FedRAMP', 'Part-107'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public API with free registration',
  },
  {
    id: 'remote-id',
    name: 'Remote ID',
    description: 'UAS Remote Identification broadcast',
    vertical: 'avionics',
    category: 'uas',
    provider: 'FAA/EASA',
    region: 'Global',
    dataTypes: ['uas-position', 'operator-location', 'serial-number'],
    updateFrequency: 'real-time',
    requiredCredentials: ['receiver_id'],
    complianceFrameworks: ['Part-89', 'EU 2019/947'],
    compatibilityLabel: 'public_api',
    integrationNotes: 'Public broadcast standard; receiver hardware required',
  },
  {
    id: 'utm-uss',
    name: 'UTM USS',
    description: 'UAS Traffic Management Service Supplier',
    vertical: 'avionics',
    category: 'uas',
    provider: 'Various',
    region: 'Global',
    dataTypes: ['flight-plans', 'deconfliction', 'airspace-status', 'alerts'],
    updateFrequency: 'real-time',
    requiredCredentials: ['api_key', 'operator_certificate'],
    complianceFrameworks: ['Part-107', 'U-space'],
    compatibilityLabel: 'license_required',
    integrationNotes: 'BYO USS provider subscription; Webhook Adapter',
  },
];

export class AvionicsConnectorFactory {
  static getAvailableConnectors(): ConnectorMetadata[] {
    return AVIONICS_CONNECTORS;
  }

  static getByCategory(category: string): ConnectorMetadata[] {
    return AVIONICS_CONNECTORS.filter(c => c.category === category);
  }
}
